### ISSUE TITLE
URL inside WebHook request

### ISSUE THREAD

**Issue by otsuka** [gitbucket/gitbucket#1000]
When GitBucket runs behind a reverse proxy, the proxied backend URL is used in a payload of WebHook requests as follows:

```
"pusher": { "html_url":"http://www.example.com:8080/gitbucket/username" ... }
```

It would be nice if Base URL specified in System Settings is used here.

**Comment by McFoggy** [comment]
@otsuka congrats you have opened #1000 !!! ;-)

**Comment by takezoe** [comment]
@otsuka GitBucket uses the base url for repository urls in the webhook payload if it has been configured.

**Comment by otsuka** [comment]
:+1: :+1: :+1:

**Comment by takezoe** [comment]
@otsuka Oh, maybe my word wasn't enough. It's current behavior. I couldn't find a problem you said.

**Comment by otsuka** [comment]
I could not reproduce the behavior, too, though I use the latest version now.
Sorry for creating an issue based on my mistake.
