### ISSUE TITLE
Request: Ability to have issues and wiki public/private

### ISSUE THREAD

**Issue by Shojy** [gitbucket/gitbucket#1003]
While it's not featured on GitHub, the ability to set the issues or wiki parts as public or private independently of the repository would be extremely useful.

Eg. A private repo with a public issue tracker and public wiki would be useful for a project where source is not available to the public, but releases are, where public users can report bugs.

Perhaps by way of a config in the repository settings where each can be declared public private, and a default feature for public landings. Eg, if repository is private, display the wiki by default instead.

**Comment by McFoggy** [comment]
@Shojy can't you split in 2 projects? 
- one public with releases, wiki & public issues
- one private with sources a other private stuff

Also you can have a look at a previous issue #985 that discuss rights & permissions.

**Comment by Shojy** [comment]
@McFoggy That issue certainly covers it, sorry I missed it when I took a look through!

Splitting it into two projects is one workaround, but then splits what could otherwise be a self-contained unit, and would lose inner-project referencing. Eg, issues from commits. I do agree though that it does provide a workable method, and that this is more a "Wouldn't it be nice if" rather than a "This must have".

**Comment by eprozium** [comment]
> but then splits what could otherwise be a self-contained unit,

What about "organization"? For each pair (public/private) make a new organization with the same name as the public repo.

**Comment by takezoe** [comment]
It became possible to configure detailed access right since GitBucket 4.7. Even read-only users can register issues or edit wiki pages if they being gave write right for issues or wiki.
