### ISSUE TITLE
Editing a web hook that contains the protocol fails

### ISSUE THREAD

**Issue by conet** [gitbucket/gitbucket#1004]
In 3.9 editing a webhook that contains https:// fails with 404.

**Comment by takezoe** [comment]
@conet Could you show the generated url and JDK version?

**Comment by conet** [comment]
java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
I can't post the complete URL here is the sanitised version:
https://git_hostname/git_project/settings/hooks/edit/https%3A%2F%2Ftarget_hostname%2Fapi%2F1%2Fjob...

**Comment by takezoe** [comment]
@conet Thanks. Fixed in 3.10.
