### ISSUE TITLE
404 on deleted repository

### ISSUE THREAD

**Issue by simmyg89** [gitbucket/gitbucket#1012]
Deleting a forked repository will not remove the entries in the activity list.
If i click on the link in the activity list this will redirect me in an 404 page.

Steps:
Create Group1/Repo1
Fork Group1/Repo1 in simone/Repo1
Delete simone/Repo1

Activity logs continue to show me:
simone forked Group1/Repo1 to simone/Repo1 30 minutes ago

open the simone/Repo1 link, load a 404 page

**Comment by simmyg89** [comment]
Reproduced even in http://gitbucket.herokuapp.com/

**Comment by aadrian** [comment]
> Deleting a forked repository will not remove the entries in the activity list.

This is not a bug, but in fact a **feature** :) . "Activity log" is an important part of auditing systems.
