### ISSUE TITLE
Where can find a complete installation documentation ?

### ISSUE THREAD

**Issue by sekaijin** [gitbucket/gitbucket#1014]
I read the page
https://github.com/gitbucket/gitbucket
but the deployment in ServiceMix (Jetty web pax) causes a NullPointerException
and manual start
java -jar gitbucket.war --port = 8080 = gitbucket --gitbucket.home
displays a page containing only / tmp

C:\gitbucket> sbt

unresolved dependency: org.fusesource.jansi#jansi;1.11: not found
Error during sbt execution: Error retrieving required libraries
  (see D:\Users\4004012\.sbt\boot\update.log for complete log)
Error: Could not retrieve jansi 1.11

howto configure the build to use th dévolopper maven settings ?
the maven repositories aren't accessed directly but through the internal nexus server.
all devolopers have, in their .m2 folder, a settings.xml that defines this nexus server

I'm just looking to test the solution.
but I can not execute it.

A+JYT

**Comment by GoForce5500** [comment]
把你的Maven设置为从官方库或是oschina的镜像站下载依赖项目,

**Comment by takezoe** [comment]
@sekaijin Here is not the support forum. I reply to your post at the gitter room.
