### ISSUE TITLE
i upgrade new gitbucket,but  *.md file cannot render to html

### ISSUE THREAD

**Issue by yuweitaocn** [gitbucket/gitbucket#1015]
how to setting ?

**Comment by yuweitaocn** [comment]
when i rollback 3.4 version.it' can be work render to  html.
now i use 3.9

**Comment by nazoking** [comment]
it seems working on demo site (version 3.9)

https://gitbucket.herokuapp.com/root/test/blob/master/README.md

**Comment by yuweitaocn** [comment]
when use ###title   it cannot render to html  ,use ## and space ,it can be render to html .

**Comment by yuweitaocn** [comment]
i use markdown  editor to create md file,copy markdown code to gitbucket,sometimes will lose some breakline,and it cannot render to html

**Comment by takezoe** [comment]
@yuweitaocn GitBucket switched markdown parser to [markedj](https://github.com/gitbucket/markedj) from pegdown since 3.9 to reproduce GitHub behavior as much as possible.

> when use ###title it cannot render to html ,use ## and space ,it can be render to html .

This behavior is same as GitHub, so we wouldn't fix this issue.

**Comment by takezoe** [comment]
@yuweitaocn 
> i use markdown editor to create md file,copy markdown code to gitbucket,sometimes will lose some breakline,and it cannot render to html

Please raise a new issue with specific examples.
