### ISSUE TITLE
View repository from smartphone is not responsive

### ISSUE THREAD

**Issue by jesusvpct** [gitbucket/gitbucket#1023]
When i go to the repository from my smartphone, is not showing responsive, the messages are too large and i have to zoom out, the right sidebar menu is over the code. It seems that CSS is not well defined for smartphones.
![screenshot_20151230-120042](https://cloud.githubusercontent.com/assets/5315258/12049879/87be6c38-aeed-11e5-9071-2245d1425a27.png)
![screenshot_20151230-120103](https://cloud.githubusercontent.com/assets/5315258/12049878/87bd5384-aeed-11e5-9f30-a46a3b14e9aa.png)

**Comment by takezoe** [comment]
Upgrading to Bootstrap3 in GitBucket 3.10 broke mobile view. We will recover this in 3.11 or future versions.

**Comment by jesusvpct** [comment]
Good!! Thanks!!

**Comment by takezoe** [comment]
Fixed in #1108.
