### ISSUE TITLE
h2 database trouble

### ISSUE THREAD

**Issue by siyiys** [gitbucket/gitbucket#1034]
the data.mv.db   is increasing, write some useless information into 
 Within two hours from the 100M has increased to 7-8G
 how to fix this? thx

**Comment by aadrian** [comment]
If the DB is stopped from the console manually before stopping Gitbucket (see http://h2database.com/html/grammar.html#shutdown ), it should compact the DB. After restart it will grow again.

**Comment by takezoe** [comment]
GitBucket 4.0 has been released with external database support. If you have any trouble with H2 database we recommend upgrading GitBucket and moving to MySQL or PostgreSQL.
