### ISSUE TITLE
How to configure the log directory

### ISSUE THREAD

**Issue by liuyufang** [gitbucket/gitbucket#1037]
hello,
 For example ,
 " java -jar  gitbucket.war --port=8001 --gitbucket.home=gitbucketWork  " ,

but, How to configure the log directory?

**Comment by takezoe** [comment]
Simplest way is `java -jar gitbucket.war  > /var/log/gitbucket.log`

**Comment by liuyufang** [comment]
thanks .   but,  I   can't    found  the ldap error  log,  and  the  access logs ,etc .
Are  them  output  to  the  console  ?
