### ISSUE TITLE
ACL for Repository

### ISSUE THREAD

**Issue by adnae** [gitbucket/gitbucket#1044]
First of all: I compare in this request gitbucket with redmine and not with github.

Currently Gitbucket support only public and private as "ACL". My favorite is, that I can set ACLs for the repository. 

Example:
anonymous: no access to code repository but can show issues and wiki, 
guest (with an account but not a registered for this project): no access to code repository but can create and show issues and wiki, 
developer (registered for this project): full access to the project.

**Comment by takezoe** [comment]
Merged with #282
