### ISSUE TITLE
Trello integration

### ISSUE THREAD

**Issue by dmk23** [gitbucket/gitbucket#1049]
Has anyone looked into integrating Gitbucket with Trello?

Here are examples for how it is done with Github -
http://blog.trello.com/github-and-trello-integrate-your-commits/
http://www.slant.co/topics/1810/compare/~trello_vs_trackduck_vs_github-issues
https://www.mirosvrtan.me/blog/2012/10/github-and-trello-integration/

**Comment by dmk23** [comment]
Trello just opened up the platform to 3rd party integrations -
http://blog.trello.com/introducing-the-trello-power-ups-platform/

**Comment by aadrian** [comment]
IMHO, such an integration would be better suited as a GitBucket plug-in: http://gitbucket-plugins.github.io/

*(maybe we need a label to mark issues as better suited as plug-ins?)*

**Comment by dmk23** [comment]
Agreed. Is there any assessment / comparison as to how making a gitbucket plugin is different from integrating into Github?

**Comment by aadrian** [comment]
>  Is there any assessment / comparison as to how making a gitbucket plugin is different from integrating into Github?

No, but why do you expect such a thing to exist in first place :) ?

**Comment by dmk23** [comment]
Because I'd think you guys might want to make it easier to develop new plugins or migrate github plugins to gitbucket :)

**Comment by aadrian** [comment]
> you guys might want to make it easier to develop new plugins or migrate github plugins to gitbucket :) 

The plug-in support in GitBucket is quite new and might change if many uses cases can't be yet implemented, so a much simpler approach would be to just give it a try and just ask if the API still needs changes:
https://gitbucket.github.io/gitbucket-news/gitbucket/2015/06/29/how-to-create-plugin.html

It's quite problematic writing docs for a moving target, considering that the number of feature requests is simply too huge for such a small team doing this in their spar time, hence: https://gitbucket.github.io/gitbucket-news/recruit/   :).

**Comment by McFoggy** [comment]
Hey the recruit page looks good, I discover it for the first time.

**Comment by takezoe** [comment]
Close outdated question.
