### ISSUE TITLE
hover link anchor in markdown/wiki does not work

### ISSUE THREAD

**Issue by imunolion** [gitbucket/gitbucket#1055]
When I mouse over headline, browser shows link anchor at the left of headline. However, if I move mouse to left, to click anchor, the icon disappears(so I cannot click it).

![anchor](https://cloud.githubusercontent.com/assets/1018469/12440826/43907d5c-bf83-11e5-8803-2505119918c2.png)

**Comment by takezoe** [comment]
@imunolion Right, it needs technique to click... We would like to improve anchor behavior.

**Comment by imunolion** [comment]
@takezoe, @oohira, thanks!
