### ISSUE TITLE
Customized global labels (names, colors, ..) 

### ISSUE THREAD

**Issue by philippeowagner** [gitbucket/gitbucket#1070]
Looking for an easy way to customize these hard coded labels.

    private def insertDefaultLabels(userName: String, repositoryName: String): Unit = {
        createLabel(userName, repositoryName, "bug", "fc2929")
        createLabel(userName, repositoryName, "duplicate", "cccccc")
        createLabel(userName, repositoryName, "enhancement", "84b6eb")
        createLabel(userName, repositoryName, "invalid", "e6e6e6")
        createLabel(userName, repositoryName, "question", "cc317c")
        createLabel(userName, repositoryName, "wontfix", "ffffff")
    }

Any suggestions on that? AFAIK there is no configuration option (eg. by using a config file) for GitBucket.

**Comment by McFoggy** [comment]
Quickest would be system properties which default to the current values, something like:
- `label.bug`
- `label.duplicate`
- `label.enhancement`
- `label.invalid`
- `label.question`
- `label.wontfix`

which could be used _(depending on how gitbucket is maunched of course)_ simply
`java -jar gitbucket.war -Dlabel.invalid=eeeeee`

**Comment by takezoe** [comment]
@philippeowagner You can automate label creation using new APIs in GitBucket 3.11. See #1064.

Also GitBucket has repository creation API. So you can create a repository which has default labels you defined by combination of these APIs.

**Comment by McFoggy** [comment]
Closing the answered question. If answer does not suit your needs, please reopen.

**Comment by philippeowagner** [comment]
@takezoe @McFoggy sorry - the notification is still in my inbox. will give it a try when upgrading to the next version.
