### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by prottonne-usr** [gitbucket/gitbucket#1072]

**Comment by ritschwumm** [comment]
how can i reproduce this?
i tried with ```java -jar gitbucket.war --path /gitbucket``` without an existing ```~/.gitbucket```.
after entering your baseUrl gitbucket, i couldn't even log in any more because all kind of stuff went wrong. which was to be expected, because it was running on port 8080 and not 80.

**Comment by joseosuna** [comment]
I actived SSH server and added localhost/gitbucket like URL base
