### ISSUE TITLE
Indicate when commit count is an estimate

### ISSUE THREAD

**Issue by asmartin** [gitbucket/gitbucket#1080]
Building on #280, would it be possible to instead of simply printing "10001 commits" for large repositories, to instead print "10001+ commits", so that it is clear that the number is an estimate and not the actual number of commits? I am not familiar with scala or the templating engine used, but wouldn't something like this be possible?

src/main/twirl/gitbucket/core/menu.scala.html
````
@@ -116,7 +116,11 @@
             <td style="width: 33%; text-align: center;">
               <a href="@url(repository)/commits/@encodeRefName(id.getOrElse(""))" class="header-link">
                 <i class="octicon octicon-history"></i>
+                @if(repository.commitCount == 10001){
                 <strong>@repository.commitCount</strong> commits
+                } else {
+                <strong>10000&#43;</strong> commits
+                }
               </a>
             </td>
             <td style="width: 33%; text-align: center;">
````

Thanks!

**Comment by takezoe** [comment]
@asmartin Thanks. I fixed by slightly different way, but also your fix seems good!

**Comment by asmartin** [comment]
Awesome, thanks for the fast fix on this!
