### ISSUE TITLE
gitbucket 3.11 requires java 1.8 where 3.10 did not; seems to break plugins

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket#1088]
After upgrading to gitbucket 3.11 a few minutes ago I found it would not start as it usually did after an upgrade. I traced this to gitbucket 3.11 requiring java 1.8 now. I had been running it (fine) with java 1.7 before. This is mainly an FYI but it would be useful to put it in the release notes.

More upsetting though is that plugins no longer seem to work. I pulled the latest gist plugin code, built it for 3.11 and installed the new version, so I am fairly sure it is not the gist plugin upgrade process that is the problem here. Here is one example of the stack trace I see during gitbucket initialization when it is loading plugins. It is repeated once for each plugin I have installed, but this is just one: 

```
Jan 31 21:58:00 flango java[604]: Jan 31, 2016 9:58:00 PM gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1 apply
Jan 31 21:58:00 flango java[604]: SEVERE: Error during plugin initialization
Jan 31 21:58:00 flango java[604]: java.lang.AbstractMethodError: Plugin.gitbucket$core$plugin$Plugin$_setter_$receiveHooks_$eq(Lscala/c
Jan 31 21:58:00 flango java[604]: at gitbucket.core.plugin.Plugin$class.$init$(Plugin.scala:73)
Jan 31 21:58:00 flango java[604]: at Plugin.<init>(Plugin.scala:11)
Jan 31 21:58:00 flango java[604]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Jan 31 21:58:00 flango java[604]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Jan 31 21:58:00 flango java[604]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:4
Jan 31 21:58:00 flango java[604]: at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
Jan 31 21:58:00 flango java[604]: at java.lang.Class.newInstance(Class.java:438)
Jan 31 21:58:00 flango java[604]: at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:149)
Jan 31 21:58:00 flango java[604]: at gitbucket.core.plugin.PluginRegistry$$anonfun$initialize$1.apply(PluginRegistory.scala:146)
Jan 31 21:58:00 flango java[604]: at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
Jan 31 21:58:00 flango java[604]: at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
Jan 31 21:58:00 flango java[604]: at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:146)
Jan 31 21:58:00 flango java[604]: at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.s
Jan 31 21:58:00 flango java[604]: at gitbucket.core.servlet.InitializeListener$$anonfun$contextInitialized$1.apply(InitializeListener.s
Jan 31 21:58:00 flango java[604]: at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.appl
Jan 31 21:58:00 flango java[604]: at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
Jan 31 21:58:00 flango java[604]: at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseCompone
Jan 31 21:58:00 flango java[604]: at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseCompone
Jan 31 21:58:00 flango java[604]: at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
Jan 31 21:58:00 flango java[604]: at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
Jan 31 21:58:00 flango java[604]: at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54
Jan 31 21:58:00 flango java[604]: at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
Jan 31 21:58:00 flango java[604]: at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:835)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:808)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:342)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.Server.start(Server.java:405)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.server.Server.doStart(Server.java:372)
Jan 31 21:58:00 flango java[604]: at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
Jan 31 21:58:00 flango java[604]: at JettyLauncher.main(JettyLauncher.java:64)
```

Any ideas?

**Comment by ritschwumm** [comment]
just guessing as i know nothing about plugins in gitbucket:
* this could be related https://github.com/gitbucket/gitbucket/commit/1b4c621fef5dc06a5750b1031adaf26615c31d60#diff-b6ad79955f6bad8dd5c018d05fd86fc4?
* i'd try recompiling a plugin to see what happens

**Comment by takezoe** [comment]
GitBucket 3.11 requires Java8 by some future reason. Mainly, we want to use recent Java libraries which are using lambda.

And we have to re-compile the Gist plugin as you say. Modification to trait breaks binary compatibility in Scala. It might be better to move `Plugin` to abstract class from trait.

Anyway, we will release the Gist plugin for GitBucket 3.11 as soon as possible. Thanks for your feedback.

**Comment by takezoe** [comment]
gitbucket-gist-plugin 3.11.0 released:
https://github.com/gitbucket/gitbucket-gist-plugin/releases/tag/3.11.0

**Comment by McFoggy** [comment]
Didn't noticed that all plugins needed a recompile, I'll release the two ones hosted in [gitbucket-plugins](https://github.com/gitbucket-plugins/).

**Comment by axb21** [comment]
I do not believe this issue is entirely resolved. When I use gitbucket 3.11 with the new gist plugin 3.11.0 (from [here](https://github.com/gitbucket/gitbucket-gist-plugin/releases/tag/3.11.0)), none of my snippets show up when I click the Gist link at the top of the gitbucket webapp page. If I downgrade gitbucket back to 3.10.1, and the plugin back to 3.10.0, my snippets show up fine.

If it matters, I'm simply running java -jar on the war file from the gitbucket release page, i.e. I'm not using an external servlet container. So upgrading gitbucket means running java -jar on a different war file, and replacing the gist plugin jar file in $HOME/.gitbucket/plugins.

The problem appears to be with listing private snippets on URL/gist in 3.11. Try this:
1. make sure gitbucket 3.11 and gist plugin 3.11.0 are running
2. create a new private snippet by clicking New snippet, etc
3. click away from the gists page to somewhere else
4. click the Gist link at the top of the page (which brings you to URL/gist)
5. **observe that the snippet you created in 2. is not visible (even though you are still logged in as the user who created the snippet)**
6. click New snippet (which brings you to URL/gist/_new)
7. observe that the snippet you created in 2. is now visible on the new snippet page
8. click the Your snippets button (which brings you to URL/gist/USERNAME)
9. observe the snippet you created in 2. is visible in your list of snippets

If you follow the same flow 1-5, but create a public snippet instead of a private one, the behavior appears to be as expected

**Comment by McFoggy** [comment]
@axb21 I think what you are seeing is not related to the binary incompatibility issue described here. You should probably open an issue to [gitbucket/gitbucket-gist-plugin](https://github.com/gitbucket/gitbucket-gist-plugin/issues) project

**Comment by axb21** [comment]
@McFoggy that's a good point. will do, thanks
