### ISSUE TITLE
something wrong about version?

### ISSUE THREAD

**Issue by hcyxsq** [gitbucket/gitbucket#1089]
I just updated to 3.11, but it show me with 0.0 version on top of the page, anything wrong?
![20160201115916](https://cloud.githubusercontent.com/assets/5617150/12708539/6f583e00-c8db-11e5-9622-3a94a417871c.jpg)

**Comment by takezoe** [comment]
@hcyxsq Here is not a place for support. Please read [guideline](https://github.com/gitbucket/gitbucket/blob/master/CONTRIBUTING.md) at first, and send question to [gitter room](https://gitter.im/gitbucket/gitbucket).

**Comment by takezoe** [comment]
@hcyxsq I think your GitBucket instance is failed to migrate. Check `~/.gitbucket/version` and logs.
