### ISSUE TITLE
Poor performance with large repositories

### ISSUE THREAD

**Issue by asmartin** [gitbucket/gitbucket#1092]
Hello,

I am using gitbucket 3.10.1 behind an nginx proxy as per the wiki installation instructions. This works well for small repositories, but I have several repositories with tens of thousands of commits. When attempting to initially load these large repos into gitbucket, the initial push fails/freezes (both over HTTPS and SSH) during the unpacking phase:

```
remote: Resolving deltas:  81% (2657701/3267292)
```

It will get stuck here and never finish (waiting hours). Other times, it will put gitbucket in a bad state, resulting in a "502 Bad Gateway" error when attempting to visit any gitbucket page.

Moreover, if you try to use gitbucket's search functionality on one of these large repositories, it will always fail with "502 Bad Gateway".

I've tried increasing `-Xmx` to `2048M` in `/etc/default/tomcat7` and `client_max_body_size` to `5000m` in the nginx config but this doesn't seem to help. Is there anything that can be done to improve performance of large repositories? Thanks!

**Comment by asmartin** [comment]
Errors in `catalina.out` when attempting to push this large repository over SSH:
```
[sshd-SshServer[3e6d18d0]-timer-thread-1] INFO  o.a.s.s.session.ServerSessionImpl - Disconnecting: 2 - User session has timed out idling after 600000 ms
```

More errors when attempting to push both over HTTPS and SSH:
http://pastebin.com/zpeVAb77

**Comment by ritschwumm** [comment]
dupliace of #558?

**Comment by asmartin** [comment]
Seems possible

**Comment by aadrian** [comment]
@asmartin does the issue still exist with current versions of GitBucket ?

**Comment by asmartin** [comment]
I am no longer using gitbucket so unfortunately I cannot test to see if the
issue still exists. If you can successfully import a large repository (e.g
with 100,000 or 1,000,000+ commits) then I believe it is fixed

On Mar 10, 2018 5:30 AM, "aadrian" <notifications@github.com> wrote:

@asmartin <https://github.com/asmartin> does the issue still exist with
current versions of GitBucket ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitbucket/gitbucket/issues/1092#issuecomment-371979668>,
or mute the thread

**Comment by aadrian** [comment]
@asmartin thank you very much for your feedback :).

GitBucket **can handle** big repositories (a few GB big) without problems (with according hardware and JVM params settings), but 1M+ commits won't be handled correctly by most Git software (and JGit Lib in our case), nor is this in the scope of the project.
