### ISSUE TITLE
git-lfs support

### ISSUE THREAD

**Issue by kraney** [gitbucket/gitbucket#1101]
It would be very nice to be able to use git-annex to manage large binaries, and still be able to push those binaries up to gitbucket.

**Comment by aadrian** [comment]
why not git-lfs?

**Comment by kraney** [comment]
Indeed, why not? Why not both? I'm asking for git-annex to be supported, not advocated or required.

**Comment by kraney** [comment]
Actually, I could be content with git-lfs support only. Whatever works.

**Comment by aadrian** [comment]
> Why not both?

Because JGit only seems to have support for LFS so far, and GitBucket is based on JGit, so it might be a feature that could be implemented.

**Comment by kraney** [comment]
OK, fair enough

**Comment by takezoe** [comment]
I found that JGit had provided LFS server implementation:
https://github.com/eclipse/jgit/tree/master/org.eclipse.jgit.lfs.server

I'm testing it with GitBucket now.

**Comment by kraney** [comment]
Awesome!
