### ISSUE TITLE
Ability to provide initial LDAP configuration

### ISSUE THREAD

**Issue by jmthackett** [gitbucket/gitbucket#1106]
Being able to set LDAP configuration parameters in a file would greatly ease deployment. It might be good if we could specify KV pairs, even if they were only active to override defaults. This would be much easier to manage through eg, ansible or chef (which is what I'm trying to do)

**Comment by McFoggy** [comment]
You can prefill the `GITBUCKET_HOME\gitbucket.conf` with predefined parameters

```
#Mon Feb 15 16:28:44 CET 2016
ldap_authentication=true
ldap.bind_password=pass
ldap.port=1212
ldap.bindDN=someDN
ldap.ssl=true
ldap.tls=true
ldap.host=myldapserver
ldap.mail_attribute=email
ldap.baseDN=anotherDN
ldap.keystore=keystorelocation
ldap.fullname_attribute=name
ldap.username_attribute=uid
ldap.additional_filter_condition=condition
```

Then when you launch the server those parameters are taken into account
![image](https://cloud.githubusercontent.com/assets/1119660/13052887/acea73f6-d401-11e5-9790-0c447bb18564.png)

**Comment by takezoe** [comment]
@jmthackett As @McFoggy says, LDAP settings are configurable by file (default is `~/.gitbucket/gitbucket.conf`). Does it help you?

**Comment by jmthackett** [comment]
Yes, a great deal - I'll have to try it when I can get the time. Thanks very much!

**Comment by McFoggy** [comment]
@jmthackett if we answered your need can you close the issue please?
