### ISSUE TITLE
generating new sessions take ages

### ISSUE THREAD

**Issue by mkrischer** [gitbucket/gitbucket#1111]
hi, gitbucket needs up to 30-40 seconds to show the initial login screens with about 4 cores in vm running at 100%. if you are able to login (ldap access), all other pages are fast as expected. seems like generating new sessions has issues? any tweaks to test?

**Comment by takezoe** [comment]
It's strange... Could you test without LDAP?

And see [guideline](https://github.com/gitbucket/gitbucket/blob/master/CONTRIBUTING.md). Post question to [gitter room](https://gitter.im/gitbucket/gitbucket) before raise an issue. If you can report test results, send it to gitter. We can continue to support you at there.
