### ISSUE TITLE
--gitbucket.home=[DATA_DIR]

### ISSUE THREAD

**Issue by sj476188023** [gitbucket/gitbucket#1124]
How to modify the --gitbucket.home path

**Comment by McFoggy** [comment]
`java -jar gitbucket.war --gitbucket.home=DATA_DIR`

what is exactly your question?

**Comment by sj476188023** [comment]
How to modify the GITBUCKET_HOME path

**Comment by McFoggy** [comment]
How do you launch gitbucket?

`java -jar gitbucket.war --gitbucket.home=c:\gitbucket` will use `c:\gitbucket` to store all its data (git repos, database, config file, ...)

**Comment by sj476188023** [comment]
Tomcat build

**Comment by McFoggy** [comment]
follow instructions on https://github.com/gitbucket/gitbucket/blob/master/doc/directory.md

Either you set env variable GITBUCKET_HOME, or you launch tomcat by setting system property gitbucket.home using in launch properties of tomcat `-Dgitbucket.home=PATH_TO_DATADIR` or lastly you open gitbucket.war, and modify META-INF/web.xml ans set context-path
```
<context-param>
  <param-name>gitbucket.home</param-name>
  <param-value>PATH_TO_DATADIR</param-value>
</context-param>
```
It might be that you can modify the context path inside some tomcat configuration, but I am not a tomcat specialist.

**Comment by aadrian** [comment]
The preferred way to do this with Tomcat is to have your own ```setenv.sh``` or ```setenv.bat``` and put that system property in the ```CATALINA_OPTS``` environment variable in setenv. If Tomcat finds in ```$tomcat/bin/``` directory a setenv file, than it will use it, so there's no need to modify other tomcat start scripts.

Example for such a file: https://gist.github.com/terrancesnyder/986029

**Comment by sj476188023** [comment]
@McFoggy   Thank you

**Comment by McFoggy** [comment]
As it might have been answered, I close the question.
If not please reopen.
