### ISSUE TITLE
The local gitbucket server files stored?

### ISSUE THREAD

**Issue by sj476188023** [gitbucket/gitbucket#1125]
The local gitbucket server files stored? I find the storage inside the path set by a very small document does not look right

**Comment by McFoggy** [comment]
Please ask your question on https://gitter.im/gitbucket/gitbucket

**Comment by McFoggy** [comment]
And in case you were asking why you do no find the same files in the server git repository than in your local directory that you have pushed, it is just because on the server the git repositories are **bare** repositories ie without any file system materialization of their content.
