### ISSUE TITLE
contribution guidelines are 404 NOT FOUND

### ISSUE THREAD

**Issue by c-yan** [gitbucket/gitbucket#1128]
[contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/CONTRIBUTING.md)  are missing though we need read before issue posting

**Comment by c-yan** [comment]
This URL is present in the entry field
Correct URL is [here](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md) ?

**Comment by McFoggy** [comment]
you're right, we have followed new github guidelines to centralize templates & contributing files inside `.gitbucket`, we need to either find the good URL that is rooted to this file or to change our templates.

Thanks for reporting.
