### ISSUE TITLE
Gitbucket backup

### ISSUE THREAD

**Issue by sj476188023** [gitbucket/gitbucket#1130]
How to complete the gitbucket server backup all the warehouse documents and code

**Comment by McFoggy** [comment]
Please, we do not have a lot of documentation but at least read the [existing ones](https://github.com/gitbucket/gitbucket/wiki/Backup) where we describe a cool backup and a hot backup using [gitbucket-h2-backup-plugin](https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin) external plugin.
