### ISSUE TITLE
[Question] Cannot find the .gitbucket in Windows 10

### ISSUE THREAD

**Issue by bcinarli** [gitbucket/gitbucket#1134]
Gitbucket runs perfectly on Windows 10 and Apache Tomcat. After upgrading to 3.12, I wanted to change the GITBUCKET_HOME directory. In the system settings, it says 
"**GITBUCKET_HOME** C:\Windows\system32\config\systemprofile\.gitbucket". 
However, I cannot find the `.gitbucket` folder in systemprofile.

Is it a bug or something like it?

**Comment by McFoggy** [comment]
Which windows user is running your tomcat server?
How do you launch tomcat, via a windows service?

**Comment by bcinarli** [comment]
I've added the Tomcat8.exe to a Windows service to launch automatically. And it uses the "Local System Account" 
However, I've done the first installations via my own windows user.

The windows is a virtual desktop.

**Comment by bcinarli** [comment]
And I think because of this situation, I also cannot install the Gitbucket plugins

**Comment by McFoggy** [comment]
so either:
- you run tomcat using your user (probably not what you expect)
- you define a user for tomcat and you move your .gitbucket to %USERPROFILE%\.gitbucket
- you follow instruction in [#1134](https://github.com/gitbucket/gitbucket/issues/1124#issuecomment-189705343) to define GITBUCKET_HOME

**Comment by imunolion** [comment]
Have you also checked `C:\Users\username\AppData` folder?

**Comment by bcinarli** [comment]
@McFoggy I've just able to move the GITBUCKET_HOME to a new "visible" place, but is it possible to move also all old data to new GITBUCKET_HOME?

**Comment by McFoggy** [comment]
Just move all files from the old location into the new one. Replace the files that have probably been generated in your "new visible" place.

**Comment by McFoggy** [comment]
Closing as answered.
@bcinarli reopen the issue with more information if you are not satisfied of the answer.

**Comment by sekiye** [comment]
I found that at `C:\Windows\SysWOW64\config\systemprofile\.gitbucket` in my environment.
