### ISSUE TITLE
Provide SHA-256 checksum for gitbucket.war please

### ISSUE THREAD

**Issue by nazoking** [gitbucket/gitbucket#1138]
We use `chef` for gitbucket server provisioning and deploy.

`remove_file` ( that is download method of chef ) can check only sha-256 .
https://docs.chef.io/resource_remote_file.html

**Comment by ritschwumm** [comment]
hm. it seems ivy's ChecksumHelper doesn't do sha-256.

**Comment by ritschwumm** [comment]
this works, but is not exactly what i'd call a good idea..
https://github.com/ritschwumm/gitbucket/blob/wip/sha256/build.sbt#L142

**Comment by ritschwumm** [comment]
this is better https://github.com/ritschwumm/gitbucket/blob/wip/sha256/project/Checksums.scala

**Comment by nazoking** [comment]
@ritschwumm thanks you !
