### ISSUE TITLE
More API features for issues

### ISSUE THREAD

**Issue by dernerv** [gitbucket/gitbucket#1147]
More API features for issues like in the GitHub API
- [x] List of all issues with filters: `GET /repos/:owner/:repo/issues`
- [x] Details for one issue: `GET /repos/:owner/:repo/issues/:number`
- [x] Create an new issue: `POST /repos/:owner/:repo/issues`

THX

**Comment by FlYnN91** [comment]
+1

**Comment by aadrian** [comment]
+1

**Comment by phixom** [comment]
+1

**Comment by nazoking** [comment]
#1385 Details for one issue

**Comment by nazoking** [comment]
merged.
