### ISSUE TITLE
Apostroph in issue text isn't handled properly

### ISSUE THREAD

**Issue by kosli** [gitbucket/gitbucket#1148]
We updated our installation from gitbucket 3.10 to 3.12 (docker image from https://github.com/f99aq8ove/docker-gitbucket) and now when creating an issue or adding a comment to an existing one, the apostroph (ASCII 39 ' ) isn't displayed right anymore (in the preview and the saved issue). See the following screenshots:
![20160311-102102_selection_001](https://cloud.githubusercontent.com/assets/203928/13698300/84501d26-e773-11e5-9ea7-7c53fe4d4af4.png)
![20160311-102112_selection_001](https://cloud.githubusercontent.com/assets/203928/13698301/8680fc96-e773-11e5-8c84-eb005b714d9a.png)

**Comment by takezoe** [comment]
@kosli @ilgrosso Hmm... I can't reproduce in my environment. What browser are you using? Could you try to reproduce on the demo site? http://gitbucket.herokuapp.com/

**Comment by ilgrosso** [comment]
@takezoe it seems it cannot be reproduced: I have barely copied [one of my issues](http://gitbucket.herokuapp.com/root/issue1148/issues/1) over the demo site. but everything is working fine there.

Maybe something related to Tomcat deployment?

**Comment by kosli** [comment]
@takezoe i am using the docker file from here: https://github.com/f99aq8ove/docker-gitbucket 
@ilgrosso  are you also running it via docker?

**Comment by ilgrosso** [comment]
@kosli no, plain old Tomcat 7 on Linux

**Comment by aguinane** [comment]
I am having the same issue. Only appears on repos that have an Issue number 39. So possibly an issue with the code that looks for references to issues in comments?

**Comment by haarp** [comment]
Same here, 4.2.1

**Comment by haarp** [comment]
Gitbucket 4.6, the issue remains. I am running the .war directly in openjdk version "1.8.0_111"

**Comment by haarp** [comment]
reproduced on Heroku: https://gitbucket.herokuapp.com/root/test/issues/40
