### ISSUE TITLE
Why the /git prefix for http clone?

### ISSUE THREAD

**Issue by solsson** [gitbucket/gitbucket#1163]
What's the reason for the prefix in the http git url, [server]/git[/Org/repo].git? It's not according to github convention.

Can it be configured away?

**Comment by McFoggy** [comment]
I guess because it was probably easier to route http incoming traffic based on URL matching (especially JGit servlet) than on request accept content &/or content-type.

**Comment by solsson** [comment]
Yes, it's explicit in https://github.com/gitbucket/gitbucket/blob/master/src/main/webapp/WEB-INF/web.xml. I tried with the mapping changed to /* but neither .git checkout nor the UI would work with that.

Conventions are powerful, and imho so is parity between the git URL and the web interface URLs (to source etc) you share within your team. I might take a closer look at what it takes to support changed mapping.

**Comment by takezoe** [comment]
To avoid URL conflict between the git servlet and other controllers on Scalatra web framework.
I think it's not so easy to be configurable in the current GitBucket structure. And we don't have a plan to do it.
