### ISSUE TITLE
Unable to clear Issue filters since 3.13

### ISSUE THREAD

**Issue by imeszaros** [gitbucket/gitbucket#1172]
## Unable to clear Issue filters since 3.13
**Impacted version**: 3.13

**Deployment mode**: *standalone*

**Problem description**:
- Since the UI refreshment in 3.13, if an issue filter is set, it cannot be cleared.
- (freetext search is also missing)

**Comment by hkuno9000** [comment]
me too.
on my site version 3.13, "Milestone" and "Assignee" cannot be cleared.
But "Authors" and "Labels" can.

**Comment by takezoe** [comment]
Fixed.
