### ISSUE TITLE
FAIL - Application at context path /gitbucket could not be started

### ISSUE THREAD

**Issue by georgesuba** [gitbucket/gitbucket#1174]
Hi, was wandering to try this app as it seems to like good way to host my private repos however no matter what I do, tomcat fail to start the app.. Im on ubuntu, have tomcat 7 plus java8 installed. I use Tomcat Web Application Manager to deploy the app as that seems to me the easiest way to deploy this.

I would like to also ask if there is any chance to develop or perhaps deploy this version for normal apache server?

**Comment by takezoe** [comment]
@georgesuba Please check Tomcat log at first. But of course, you can run GitBucket without Tomcat as described in [README](https://github.com/gitbucket/gitbucket#installation):
```
$ java -jar gitbucket.jar
```

**Comment by takezoe** [comment]
@georgesuba And if you can provide additional information about your trouble. Please send it to [the gitter room](https://gitter.im/gitbucket/gitbucket). Here is not for user support as mentioned in [the guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md).
