### ISSUE TITLE
Private repository for team?

### ISSUE THREAD

**Issue by hvqzao** [gitbucket/gitbucket#1177]
I'm currently testing Gitbucket 3.13 and I'm having difficulties in understanding how teams actually work. I don't see an option to add team as Collaborators to private repositories, I'm only able to add single members. How can I use teams for that purpose?

Eventually, is there an option to limit access to given Gitbucket instance (and its publicly hosted repositories) only to authenticated users?

**Comment by takezoe** [comment]
You should create the private repository for the team for your purpose. Choose your team as the owner of repository in the new repository creation form.

**Comment by takezoe** [comment]
> Eventually, is there an option to limit access to given Gitbucket instance (and its publicly hosted repositories) only to authenticated users?

GitBucket does not have such feature currently. Use other way such as BASIC authentication in the reverse proxy instead.

**Comment by takezoe** [comment]
If you have any other question, please send it to [the gitter room](https://gitter.im/gitbucket/gitbucket). Here is not for user support as mentioned in [the guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md).
