### ISSUE TITLE
Group hierarchy or bug?

### ISSUE THREAD

**Issue by julen26** [gitbucket/gitbucket#1178]
**Impacted version**: 3.13

**Deployment mode**: standalone app on Windows 7

**Problem description**:
The group editing screen allows to add another groups as members, even the same group. It doesn't autocomplete, but it allows to write and save.

I wonder whether it's a bug or it's a way of creating hierarchical groups. I think it's a bug because the members of a subgroup can't see the repositories owned by the main group.
Anyway, it could be a nice feature.

Hope this helps.

**Comment by McFoggy** [comment]
Indeed it is a bug.
