### ISSUE TITLE
How to backup the repositories?

### ISSUE THREAD

**Issue by jwdstef** [gitbucket/gitbucket#1180]
Hi,my dear friends,Thank you for your develop such a product.I will use it on my development environment .But i have some questions.
1.How to backup the repositories?
ps:copy HOME/.gitbucket directory to the other disk.and deploy the new gitbucket.war(3.6) on tomcat-webapps.When tomcat started,I sign in http://192.168.1.10:8080/gitbucket but i don't look my backup data.
2.https://github.com/gitbucket/gitbucket/releases,gitbucket.war can't download,did you have another resource link.
please,Point out my mistakes,thanks!

**Comment by McFoggy** [comment]
In order to be sure that noone can find it the documentation has been securely hidden in the wiki... ;-) https://github.com/gitbucket/gitbucket/wiki/Backup

Then for the releases, the release page is a good start: https://github.com/gitbucket/gitbucket/releases

**Comment by McFoggy** [comment]
reopen if not answered correctly

**Comment by jwdstef** [comment]
OK thinks
