### ISSUE TITLE
Dashboard impagination problem

### ISSUE THREAD

**Issue by simmyg89** [gitbucket/gitbucket#1181]
After update from 3.13 to 3.14, the main section of the dashboard, News Feed / Pull Requests / Issues, are presented under the left list as in the image below

<img width="1680" alt="screen shot 2016-05-02 at 22 46 24" src="https://cloud.githubusercontent.com/assets/1280258/14967524/1e9c6020-10b8-11e6-8b14-f901b56573a5.png">

**Comment by VonOx** [comment]
Maybe cache problem ? Try to clean it.

**Comment by simmyg89** [comment]
Problem created by the CDN cache
