### ISSUE TITLE
temporary directory on separate filesystem

### ISSUE THREAD

**Issue by dariko** [gitbucket/gitbucket#1182]
## Issue
**Impacted version**: 
3.14

**Deployment mode**:
docker container in rancher(cattle) environment, `/gitbucket/` on glusterfs, ssl termination via rancher load balancer (haproxy-sni)

**Problem description**:
Whenever I start my server the directory `/gitbucket/tmp` gets deleted and recreated. This takes a long time because `/gitbucket/` is on gluster filesystem (latencies are not optimal)

I tried to mount a local volume on `/gitbucket/tmp/`, but I get this exception
```
java.lang.IllegalStateException: Failed to delete temp dir /gitbucket/tmp
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:376)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:264)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:480)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:516)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:64)
```

I think the problem is in `src/main/java/JettyLauncher.java` where the temporary directory gets deleted and recreated, not emptyed:

```
File tmpDir = new File(getGitBucketHome(), "tmp");
if(tmpDir.exists()){
  deleteDirectory(tmpDir);
}
tmpDir.mkdirs();
```

Is it possible to make the location of the temporary directory configurable or, as an alternative, have the temporary directory emptied instead of recreated?

**Comment by takezoe** [comment]
@dariko I think the temporary directory deletion is not required in fact. So I will remove code which is deleting the temporary directory simply in the next release.

**Comment by dariko** [comment]
thank you!

**Comment by KostaCipo** [comment]
Hi,

I am having the same issue with Gitbucket Version 4.34.0


2020-10-27 14:00:10.169:INFO::main: Logging initialized @178ms to org.eclipse.jetty.util.log.StdErrLog
--
  | 2020-10-27 14:00:10.255:WARN:oejsh.ContextHandler:main: Empty contextPath
  | 2020-10-27 14:00:10.259:INFO:oejs.Server:main: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_262-b10
  | 2020-10-27 14:00:10.482:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@35bbe5e8{/,null,UNAVAILABLE}{file:/home/jboss/gitbucket/bin/gitbucket.war}
  **| java.lang.IllegalStateException: Failed to delete temp dir /gitbucket/data/tmp**
  | at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:535)
  | at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:424)
  | at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:138)
  | at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
  | at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
  | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
  | at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  | at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
  | at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  | at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
  | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
  | at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
  | at org.eclipse.jetty.server.Server.start(Server.java:408)
  | at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
  | at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
  | at org.eclipse.jetty.server.Server.doStart(Server.java:372)
  | at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
  | at JettyLauncher.main(JettyLauncher.java:148)

Is it supposed to delete that directory? Thanks!

**Comment by takezoe** [comment]
@KostaCipo Could you raise a new issue because this is very old one.

**Comment by KostaCipo** [comment]
@takezoe Thanks. I will :-)
