### ISSUE TITLE
Single quotes in issue description displayed as &#39;

### ISSUE THREAD

**Issue by ilgrosso** [gitbucket/gitbucket#1188]
## Issue
**Impacted version**: 4.0.0

**Deployment mode**: Tomcat, with an httpd frontend

**Problem description**:
When creating / editing issues, I always see single quotes reported as &#39;

![image](https://cloud.githubusercontent.com/assets/1064664/15076767/880c2b9e-13ab-11e6-8440-e11789f443e1.png)

**Comment by takezoe** [comment]
This issue looks same as #1148.

**Comment by ilgrosso** [comment]
Correct, I'll watch the other one.
