### ISSUE TITLE
Add support for MySQL 5.6

### ISSUE THREAD

**Issue by msigley** [gitbucket/gitbucket#1189]
I think for alot of us, lack of MySQL 5.6 support is going to prevent us from switching to an external database. MySQL 5.6 is still the most popular version run by most hosting companies, and most MySQL compatible alternatives, such as MariaDB, are only 100% compatible up to the features in MySQL 5.6 at this time.

Would it be a huge undertaking to make GitBucket MySQL 5.6 compatible?

**Comment by msigley** [comment]
Related to #1187.

**Comment by dariko** [comment]
After I got worked around the "create view" situation in the database creation (by manually creating the views as per #1187) I am running my private gitbucket instance without any hiccup.

Have you found any other problem with mysql 5.6?

**Comment by msigley** [comment]
Not specifically, but I really haven't gone looking either. Java programing is not my forte. ;)

This issue is largely from my perspective/experience as a sysadmin.

**Comment by takezoe** [comment]
I've known the VARCHAR length limitation in MySQL 5.6 with UTF-8.

**Comment by takezoe** [comment]
Sorry, my above comment was incorrect. The correct one is that the index column length is limited until 767bytes in MySQL 5.6. Some VARCHAR columns which are indexed exceed this limitation if database charset is UTF-8.

I think it's difficult to support MySQL 5.6 with keeping existing data by this reason.

**Comment by dariko** [comment]
@msigley no problems with code, but dbs peculiarities sure are not my forte...

@takezoe ok, definitely above my abilities!

**Comment by msigley** [comment]
@takezoe converting existing data is a great reason. I guess alot of us will just have to wait until MariaDBa and Percona Server catch up to MySQL 5.7 in this regard in stable releases.
