### ISSUE TITLE
Due Date Calendar broken

### ISSUE THREAD

**Issue by adnae** [gitbucket/gitbucket#1191]
Impacted version: 4.0.0

The Milestones Due Date Calendar is broken. By clicking on the date input field of Javascript Calendar does not open fully. It is not possible to select a date.

Tested with: Chrome and Edge

**Comment by takezoe** [comment]
@adnae Are you saying this situation?
<img width="571" alt="2016-05-13 7 34 05" src="https://cloud.githubusercontent.com/assets/1094760/15246751/40b55dce-18dd-11e6-9062-ab4b0b257be1.png">

**Comment by adnae** [comment]
Yes :)

**Comment by takezoe** [comment]
Fixed.
