### ISSUE TITLE
Cannot disable option "Require status checks to pass before merging"

### ISSUE THREAD

**Issue by hanxue** [gitbucket/gitbucket#1192]
## Problem with protected branch
**Impacted version**: 4.0.0

**Deployment mode**: *jetty-runner on Windows*

**Problem description**:
- Enable branch protection for `develop`
- push to the branch will fail

```
$ git push origin develop 
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 532 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 1 (delta 1)
remote: Resolving deltas: 100% (4/4)
To ssh://hanxue@192.168.1.19:29418/hanxue/repo.git
 ! [remote rejected] develop -> develop (Cannot force-push to a protected branch)
error: failed to push some refs to 'ssh://hanxue@192.168.1.19:29418/hanxue/repo.git'
```

- At [http://192.168.1.19:8080/hanxue/repo/settings/branches/develop](http://192.168.1.19:8080/hanxue/repo/settings/branches/develop), disable the option `http://192.168.1.19:8080/hanxue/vms/settings/branches/develop`

![image](https://cloud.githubusercontent.com/assets/760008/15284905/d9f9e1de-1b86-11e6-8966-cc76da8925f9.png)

- Reload the branch settings again, the option `Require status checks to pass before merging` is sitll selected

![image](https://cloud.githubusercontent.com/assets/760008/15285379/4e707378-1b89-11e6-8b8c-c8a18c94f1d0.png)

**Comment by takezoe** [comment]
This is intended behavior, but it looks not intuitive certainly.

@nazoking Could you improve behavior of branch protection setting form?

**Comment by nazoking** [comment]
@takezoe ok. i try it
