### ISSUE TITLE
Enable request log in gitbucket

### ISSUE THREAD

**Issue by hanxue** [gitbucket/gitbucket#1201]
## How to enable jetty request log in gitbucket

**Impacted version**: 4.0.0

**Deployment mode**: _standalone (java -jar gitbucket.war)_

**Problem description**:
As per issue #1109 , I created `~/Library/Java/Extensions/logback-test.xml`, in my Java classpath with the following content

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%h %l %u %user %date "%r" %s %b</pattern>
    </encoder>
  </appender>

  <appender name="FILE" class="ch.qos.logback.core.FileAppender">
    <file>/var/log/jetty/gitbucket.log</file>
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
  <root level="INFO">
    <appender-ref ref="FILE" />
  </root>

  <logger name="com.gitbucket" level="${gitbucket.logging.level:-INFO}"/>
</configuration>
```

There is a log file at `/var/log/jetty/gitbucket.log`, but no request recorded. Only this

```
14:32:22.044 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@67e13bd0{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
14:32:22.045 [main] INFO  org.eclipse.jetty.server.Server - Started @5124ms
```

I have also tried creating `src/main/webapp/jetty-logging.xml` with the the following contents

```
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Set name="RequestLog">
    <New id="RequestLog" class="org.eclipse.jetty.server.AsyncNCSARequestLog">
      <Set name="filename">/var/log/jetty/yyyy_mm_dd.request.log</Set>
      <Set name="append">true</Set>
      <Set name="extended">false</Set>
      <Set name="LogTimeZone">GMT</Set>
    </New>
  </Set>
</Configure>
```

No log file produced. 

Can anyone advise how can I enable request log for Jetty/gitbucket?

**Comment by takezoe** [comment]
You can configure the embedded Jetty log by Java code in [JettyLauncher](https://github.com/gitbucket/gitbucket/blob/master/src/main/java/JettyLauncher.java).
See details at: http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html

**Comment by takezoe** [comment]
Close outdated questions.
