### ISSUE TITLE
allow collaborators to administrate projects

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1202]
## Issue
**Impacted version**: 3.X, 4.X

**Deployment mode**: not relevant

**Problem description**:
I would like to be able to define project collaborators as being administrators for their project so that:
- they can add and remove other collaborators
- they can define commit rules & protect branches
- they can, as administrator, bypass the above protection rules on purpose
- the real platform administrator do not have to do such tasks for each project

Something simple like the following should be enough
![image](https://cloud.githubusercontent.com/assets/1119660/15532441/255fb330-2260-11e6-807b-a822d0c1d737.png)

**Comment by takezoe** [comment]
Merged with #1286
