### ISSUE TITLE
Attachment link with different domains

### ISSUE THREAD

**Issue by julen26** [gitbucket/gitbucket#1204]
## Attachment link

**Impacted version**: 4.0.0

**Deployment mode**: _standalone app_

I have deployed GitBucket in a server and I can access by two ways:
- http://servername.domain.com:8080
- http://servername.intranet.domain:8080

When accessing from itnranet and attaching a new file, it generates a link like: 
_http://servername.intranet.domain:8080/TestGroup/TestProject/_attached/1464264441738jaGNyDaafc_
The problem is that now, when I enter from the other domain, the link of the file is still the same, instead of _http://servername.domain.com:8080/TestGroup/TestProject/_attached/1464264441738jaGNyDaafc_, so the file (image in this case) is not showing. It requires to log in _servername.intranet.domain_ too.

Hope it helps, and thanks!

**Comment by McFoggy** [comment]
Gitbucket uses some settings to define where the application is located and thus enabling the calculation of url links. If you want to serve gitbucket from different URLs, you have no other choice I guess than putting a redirection in front of it (nginx, apache httpd, ...)

**Comment by aadrian** [comment]
Not a bug. The URL defined in settings page of the installation should be the one used.
