### ISSUE TITLE
Got "HTTP Status 404 - /gitbucket" when upgrade to 4.0

### ISSUE THREAD

**Issue by thearabbit** [gitbucket/gitbucket#1205]
I got error `HTTP Status 404 - /gitbucket` when upgrade to 4.0

![gitbucket error](https://cloud.githubusercontent.com/assets/4495160/15626724/d7725a80-24f6-11e6-8855-b598b5aedeb6.PNG)

**Comment by takezoe** [comment]
@thearabbit Check your log at first.

**Comment by takezoe** [comment]
And send question to the gitter room before raise an issue:
https://gitter.im/gitbucket/gitbucket

Please read the guideline for issues:
https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md

**Comment by thearabbit** [comment]
Thanks for your reply.
I will go to `gitter` for my question
