### ISSUE TITLE
Show the number of commits on the branch.

### ISSUE THREAD

**Issue by just1689** [gitbucket/gitbucket#1206]
## Issue
**Impacted version**: 4.0

**Deployment mode**: standalone

**Problem description**:
- Show number of commits for the branch when landing on a repo's page for desktop & mobile.
- Easy access to the commit history on mobile

See pic for mobile example:
![gitbucket-4 0](https://cloud.githubusercontent.com/assets/3624058/15632947/3f23c236-25a1-11e6-935b-b4b4a27f04c6.PNG)

**Comment by aadrian** [comment]
IMHO this should not be a feature request but a bug (from a usability standpoint it's a serious one). 

The number of commits was always displayed before the layout changes (e.g. we still have many 3.x installations and they display this number, and for the user it's very important).

**Comment by just1689** [comment]
Good point

**Comment by takezoe** [comment]
Fixed to display the commit count on the history button:
![commit_count](https://cloud.githubusercontent.com/assets/1094760/18897328/504dbfda-8564-11e6-8c2e-f940ce09124b.png)

The find button and the history button is displayed in mobile view as well:
![commit_count_mobile](https://cloud.githubusercontent.com/assets/1094760/18897330/532be024-8564-11e6-91f1-91721e06efb5.png)

**Comment by just1689** [comment]
Fantastic! Thank you

**Comment by aadrian** [comment]
@takezoe Thank you!
