### ISSUE TITLE
Put crucial first time login info in the readme...

### ISSUE THREAD

**Issue by nicolinux** [gitbucket/gitbucket#1207]
Great tool, thanks for creating it!

In order to spare the first time user a trip to the FAQ, you could add this tiny piece of crucial info right beneath the installation instruction:

> 
What's default root username and password?
root / root

**Comment by takezoe** [comment]
> Great tool, thanks for creating it!

You are welcome!

> In order to spare the first time user a trip to the FAQ, you could add this tiny piece of crucial info right beneath the installation instruction:

It's here: https://github.com/gitbucket/gitbucket#installation

Is it hard to find? Should we improve this installation guide?

**Comment by nicolinux** [comment]
Doh! Thanks. I didn’t see it because I started it by hand and skipped to the next paragraph.

Best wishes,
Stefan Sorin Nicolin
—
http://about.me/nicolinux
