### ISSUE TITLE
Test SMTP Settings

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1216]
Please add a "Test SMTP Settings" button that would send a Test email to the actual user, in order to check if everything is correctly configured.

Thank you.

**Comment by FlYnN91** [comment]
+1

**Comment by takezoe** [comment]
Sending test mail capability is available in GitBucket 4.2:

![2016-06-09 21 28 54](https://cloud.githubusercontent.com/assets/1094760/15929745/b928e7f0-2e89-11e6-8caf-d45f18f6b55a.png)

**Comment by aadrian** [comment]
> Sending test mail capability is available in GitBucket 4.2

Very nice :).

Thank you!
