### ISSUE TITLE
Data import cause org.scalatra.servlet.SizeConstraintExceededException

### ISSUE THREAD

**Issue by fujitalon** [gitbucket/gitbucket#1219]
I planned to switch database from H2 to MySQL 5.7.
When I try to import data, caught org.scalatra.servlet.SizeConstraintExceededException.
Export data file is 3,502,645 bytes length from H2 database on GitBucket 4.0 Data export xml format.   
Stacktrace is [stacktrace.txt](https://github.com/gitbucket/gitbucket/files/310087/stacktrace.txt).  
I use tomcat7 with apache2.4.7, mod_proxy_ajp.

As my concern, this problem caused by Servlet 3.0 multipart-config setting (cf. http://stackoverflow.com/questions/28564683/how-to-limit-uploaded-filesize-in-tomcat-servlet )  is missing or wrong on my environment.  

Where to put multipart-config element ?

**Comment by fujitalon** [comment]
It can be resolved in a different way.
I export data as SQL and execute sql file on mysql command is succeded.

Thank you.

**Comment by takezoe** [comment]
@fujitalon I would like to add an importing way by mysql command to docs.
