### ISSUE TITLE
Upgrade 3.8 -> 3.14 -> 4.1: Dreaded Plugin Issue

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1223]
## Issue
**Impacted version**: 3.8 Trying to get to 4.1

**Deployment mode**: Standalone

**Problem description**:

Trying to get from 3.8 to 4.1 by deploying new. war files in a standalone environment. 

First try says, "You have to go through 3.14 first" - I guess to do some kind of DB table updates?

OK, but trying that gives me the dreaded:

   ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization

And a very noisy Java traceback.

What am I missing here?

**Comment by McFoggy** [comment]
@tundratim first you have noticed that while upgrading you needed to go first in 3.14 ; it is a mandatory step to go to 4.X. Then in 4.X there was an incompatible change introduced in the plugin API. Thus you need to adapt your installation with new versions of the plugins you use compatible with gitbucket 4.X. 
Keep us informed.

**Comment by tundratim** [comment]
I am seeing this error in 3.14 as well.

**Comment by McFoggy** [comment]
Sorry, some binary incompatibilities were already introduced in 3.11. I have found that I needed for 3.11 to deliver a new version of [gitbucket-h2-backup-plugin](https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin) for example.

Which plugin do you use?

**Comment by tundratim** [comment]
On 06/27/2016 12:16 PM, Matthieu Brouillard wrote:
> Sorry, some binary incompatibilities were already introduced in 3.11. I have found that I needed for 3.11 to deliver a new version of gitbucket-h2-backup-plugin <https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin> for example.
> 
> Which plugin do you use?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/gitbucket/gitbucket/issues/1223#issuecomment-228811589>, or mute the thread <https://github.com/notifications/unsubscribe/AMw83nYDGDSI4pZPrjEuc43mnbAB2Dufks5qQAVjgaJpZM4I_Pcj>.Web Bug from https://github.com/notifications/beacon/AMw83oBf439JQfdTr_4VAlwe-h8qpS8Aks5qQAVjgaJpZM4I_Pcj.gif
> 

gist

-- 
----------------------------------------------------------------------------
Tim Daneliuk     tundra@tundraware.com
PGP Key:         http://www.tundraware.com/PGP/

**Comment by McFoggy** [comment]
@tundratim from [gitbucket-gist-plugin](https://github.com/gitbucket/gitbucket-gist-plugin) page you need version 3.13 for gitbucket 3.14

**Comment by tundratim** [comment]
Aha ... I think I figure out the approach.

1) Stop gitbucket
2) Remove the gist plugin (only one we were using)
3) Run 3.14 to force the required upgrades
4) Stop gitbucket
5) Install the 4.x gist plugin
6) Start 4.1

One other last question, if you don't mind ... what is the purpose of the gitbucket.ser file? This is presumably some kind of java serialization file.

**Comment by tundratim** [comment]
The upgrade to 4.1 worked fine and it starts with the latest gist plugin no problem.  HOWEVER, when I go to look at a Snippet, I see this:

`org.h2.jdbc.JdbcSQLException: Column "X3.ORIGIN_REPOSITORY_NAME" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._6 AS
SELECT
    X3.UPDATED_DATE AS UPDATED_DATE,
    X3.DESCRIPTION AS DESCRIPTION,
    X3.ORIGIN_REPOSITORY_NAME AS ORIGIN_REPOSITORY_NAME,
    X3.ORIGIN_USER_NAME AS ORIGIN_USER_NAME,
    X3.TITLE AS TITLE,
    X3.PRIVATE AS PRIVATE,
    X3.REPOSITORY_NAME AS REPOSITORY_NAME,
    X3.USER_NAME AS USER_NAME,
    X3.REGISTERED_DATE AS REGISTERED_DATE
FROM PUBLIC.GIST X3
WHERE (X3.USER_NAME = ?1)
    AND (X3.PRIVATE = ?2)
ORDER BY =X3.REGISTERED_DATE DESC
LIMIT 10 [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:835)
	at org.h2.command.Parser.prepare(Parser.java:226)
	at org.h2.engine.Session.prepare(Session.java:426)
	at org.h2.engine.Session.prepare(Session.java:413)
	at org.h2.table.TableView.compileViewQuery(TableView.java:106)
	at org.h2.table.TableView.initColumnsAndTables(TableView.java:151)
	at org.h2.table.TableView.init(TableView.java:102)
	at org.h2.table.TableView.<init>(TableView.java:67)
	at org.h2.table.TableView.createTempView(TableView.java:512)
	at org.h2.command.Parser.readTableFilter(Parser.java:1169)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1982)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1867)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1688)
	at org.h2.command.Parser.parseSelect(Parser.java:1676)
        .....`

**Comment by tundratim** [comment]
@McFoggy - neither the 3.13 nor 4.0 gist plugins work with version 3.14 of the war.  4.0 loads quietly with the 4.1 war file, but clobbers gist behavior as described in previous message.

**Comment by tundratim** [comment]
Closing thread.  Moving snippet problem to gist-plugin repo.  Thanks for the help.
