### ISSUE TITLE
4.2: The entries within the left menu are hard to read

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1226]
![image](https://cloud.githubusercontent.com/assets/1677414/16538778/849e05e0-402e-11e6-9eea-f315cafebbae.png)

I checked out 4.2, created an executable war and fired it up. To me, the menu to the left is pretty hard to read.

**Comment by takezoe** [comment]
Hmm... This presentation has been provided by AdminLTE. How do you think about AdminLTE's demo?
https://almsaeedstudio.com/preview

**Comment by uli-heller** [comment]
Thanks! I do have the same issue there, these menu items are kind of hard to read.
