### ISSUE TITLE
4.2 Contrast between the menu bar to the left and the file content pane to the right probably too high

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1228]
I know: This is a matter of personal taste. I general, I do like the new ui. Working with it for a couple of minutes, I think the contrast isn't optimal at the moment. It is hard for me to read the content of a file for example, since there are large black areas combined with large white areas:

![image](https://cloud.githubusercontent.com/assets/1677414/16539314/7c0ad49c-403f-11e6-9788-ed9d72d45c9b.png)

It is even worse when scrolling down. There, the menu is really totally black:

![image](https://cloud.githubusercontent.com/assets/1677414/16539323/c518a2e0-403f-11e6-9cec-c2c2c284c6e5.png)

As mentioned before: Just my personal taste, please don't feel angry about it.

**Comment by takezoe** [comment]
Thanks for your opinion.
I understand and close this issue but we can continue to discus about new AdminLTE based UI in #1226 or [gitter](https://gitter.im/gitbucket/gitbucket).
