### ISSUE TITLE
4.2 Wiki content overlapped by menu bar

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1229]
![image](https://cloud.githubusercontent.com/assets/1677414/16539345/6dfc3bd8-4040-11e6-895d-32c493cf77a7.png)

These should read "Home" and "Welcome". The styling should probably be changed so that there is space of a pixel or two between the menu bar and the content pane.

**Comment by myururdurmaz** [comment]
+1 admin panel
![screenshot_2016-07-02_13-00-57](https://cloud.githubusercontent.com/assets/1057861/16539760/2d871a40-4055-11e6-8a55-d9b98870600e.png)

**Comment by myururdurmaz** [comment]
![screenshot_2016-07-02_13-03-24](https://cloud.githubusercontent.com/assets/1057861/16539767/6238e750-4055-11e6-86a8-c898c7e9c2a1.png)

**Comment by myururdurmaz** [comment]
![screenshot_2016-07-02_13-37-35](https://cloud.githubusercontent.com/assets/1057861/16539910/29cc68ec-405a-11e6-85ea-c637c4b2b09c.png)

firefox 38.8 and gentoo linux

**Comment by takezoe** [comment]
I'm testing the latest version of Chrome and Firefox on Mac, but I can't reproduce overlapping. Hmm...
How about AdminLTE's demo site in your browser?
https://almsaeedstudio.com/preview

**Comment by myururdurmaz** [comment]
windows 8 firefox 46.0.1 looks good
![screenshot_2016-07-02_14-53-22](https://cloud.githubusercontent.com/assets/1057861/16540209/e2a55504-4064-11e6-9e43-102eb83080a9.png)

**Comment by myururdurmaz** [comment]
https://almsaeedstudio.com/preview on linux firefox 38 looks good

![screenshot_2016-07-02_14-55-22](https://cloud.githubusercontent.com/assets/1057861/16540216/0c798346-4065-11e6-828c-3c92f104a0ed.png)

**Comment by myururdurmaz** [comment]
i have upgraded my firefox to 47 on linux machine and fixed my view
![screenshot_2016-07-02_15-06-39](https://cloud.githubusercontent.com/assets/1057861/16540268/b2c8465a-4066-11e6-80cb-828f46e3f619.png)

**Comment by takezoe** [comment]
@myururdurmaz Good :-)

**Comment by uli-heller** [comment]
Things are strange.

I'm on Linux and use google chrome 51.0.2704.106-1. The version has been installed on 2016-06-24, so no updates within the last couple of days.

The pages are OK now, but they definitely looked strange two days before ;) 
Maybe my then-active chrome session  was running  an older version of chrome?

I'm closing the issue...
