### ISSUE TITLE
History view: You can only click at the very right of an entry (for the repo view, it is different/better)

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1230]
When browsing the content of a repo, you can drill down into a folder or look at the content of a file by clicking anywhere on the files's line:

![image](https://cloud.githubusercontent.com/assets/1677414/16539384/cf51e63e-4041-11e6-9a6e-d4bef65b69ba.png)

I like this.

For the history view, only the botton on the very right of the line brings you to the diff:

![image](https://cloud.githubusercontent.com/assets/1677414/16539396/1f32b20a-4042-11e6-9398-ce80d03038e0.png)

Most of the space of the line is kind of wasted. You have to move your mouse all the long way to the right to go to the diff.

**Comment by takezoe** [comment]
Applied `table-hover` class for the commit history table. It would make possible to recognize commit row easily.
