### ISSUE TITLE
Sidebar not shown in account page

### ISSUE THREAD

**Issue by niblings** [gitbucket/gitbucket#1233]
**Impacted version**: 4.2.0/4.2.1
**Deployment mode**: standalone app and deployed tomcat8
**Problem description**: sidebar not shown in account page

--
gitbucket/{account} page screenshot here:
![ss-gitbucket](https://cloud.githubusercontent.com/assets/12636866/16561933/c34be9d8-4236-11e6-83f2-391e2e6d6d46.png)

--
and sidebar-menu (Groups) ul tag not closed.
https://github.com/gitbucket/gitbucket/blob/master/src/main/twirl/gitbucket/core/account/main.scala.html#L26-L31

![ss-gitbucket-src](https://cloud.githubusercontent.com/assets/12636866/16562243/7839bee2-4237-11e6-8bff-b319bbe42497.png)

**Comment by takezoe** [comment]
Already pull request has been opened by @shiena . See #1232.
