### ISSUE TITLE
Inconsistency: Sometimes, the login id shows up and sometimes the user name

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1234]
## Issue
**Impacted version**: 4.2.0

**Deployment mode**: Stand alone app running behind a apache httpd

**Problem description**:

Sometimes, the user name shows up and at other times, the login name shows up.

Click on the upper left -> a list of activities shows up, the login id is mentioned here:

![image](https://cloud.githubusercontent.com/assets/1677414/16567293/2da94038-421d-11e6-94fd-1496d6b92e2d.png)

For most of the other lists, the user name is shown:

![image](https://cloud.githubusercontent.com/assets/1677414/16567312/706100dc-421d-11e6-820b-37376f73bf71.png)

I do prefer the user name.

**Comment by takezoe** [comment]
The login id which you are saying in the list of activities is user name on GitBucket. But user name in the commit log is git user name. Two names are not same essentially.

**Comment by uli-heller** [comment]
Makes sense. Thanks a lot for explaining this to me!

Am 05.07.2016 um 18:27 schrieb Naoki Takezoe:
>
> The login id which you are saying in the list of activities is user 
> name on GitBucket. But user name in the commit log is git user name. 
> Two names are not same essentially.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/gitbucket/gitbucket/issues/1234#issuecomment-230529321>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABmYZjOwM0mAoxZchf8R_ss27PlVs4dlks5qSoXbgaJpZM4JEiwa>.
>


-- 
Uli Heller

daemons point Gesellschaft für Datenverarbeitung mbH
Zahn-Nopper-Straße 1-3, 70435 Stuttgart
Internet: www.daemons-point.com
Tel:+49 711 806708 0, Fax: +49 711 806708 19
mailto:uli.heller@daemons-point.com

Geschäftsführer: Steffen Walter, Uli Heller
Sitz der Gesellschaft: Stuttgart
Amtsgericht Stuttgart, HRB 22333
