### ISSUE TITLE
Span with ".pull-right" class displaying quite strange

### ISSUE THREAD

**Issue by alexkuznetsov** [gitbucket/gitbucket#1235]
### Before submitting an issue to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

## Issue
**Impacted version**: 4.2

**Deployment mode**: standalone app (java -jar gitbucket.war)

**Problem description**:
First screenshot display the problem:
![screenshot_1](https://cloud.githubusercontent.com/assets/1185266/16580987/f70a84b8-42c8-11e6-8e06-53561554bb8e.png)
As you can see, the label with branches count slid down.
I enable some CSS "fixes" (screenshot 2):
![screenshot_2](https://cloud.githubusercontent.com/assets/1185266/16581041/4eac1484-42c9-11e6-82ef-ea441c652b3b.png)
P.S. Then, I open site with that template and sow, some styles for .pull-righs are missed (in red rectangle).
![screenshot_3](https://cloud.githubusercontent.com/assets/1185266/16581085/7806b10e-42c9-11e6-9658-42a9f6d63d0b.png)
So. is it normal or just mistake?

**Comment by takezoe** [comment]
Already fixed in 43456e817a323e17bbdfcfd43eb82e67331ad8fd. Wait for the 4.3 release.

**Comment by alexkuznetsov** [comment]
Ah, it is thery good! Thank you!
