### ISSUE TITLE
Unable to clone repository from gitbucket using git clone ssh://... :   Unable to negotiate key exchange for server host key algorithms

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket#1243]
## Issue
I do not know enough about Apache MINA/SSHD or gitbucket's use of it to know whether that's the source of the problem, but I have seen reference to similar issues (e.g., [here](http://stackoverflow.com/questions/33690689/no-matching-host-key-type-found-apache-mina-sftp-server)) in other applications. That stackoverflow link might be a clue to solving this in gitbucket?

**Impacted version**: 
I am reporting this issue as reflected in gitbucket version 4.2.1, but I believe it will impact all previous versions of gitbucket since it relates to openssh.

**Deployment mode**: 
I run gitbucket.war standalone (basically `java -jar gitbucket.war`)

**Problem description**:
The problem manifests as errors when attempting to clone a git repository hosted by gitbucket using ssh. The clone fails with an error regarding the host key exchange.

The ssh server inside gitbucket appears to only offer `ssh-dss` as a host key exchange algorithm, which has been deprecated in [OpenSSH 7.0](http://www.openssh.com/legacy.html):
`OpenSSH 7.0 and greater similarly disables the ssh-dss (DSA) public key algorithm. It too is weak and we recommend against its use.` 

When attempting to clone a git repository from gitbucket using ssh, I am given the following error:
```
error fetching latest change from git repo at `ssh://MYUSER@MYHOST:29418/MYUSER/MYPROJECT.git':
Unable to negotiate with MYIP port 29418: no matching host key type found. Their offer: ssh-dss
fatal: Could not read from remote repository.
```

On MYHOST one can verify on the command line that the ssh server is only offering `ssh-dss`:
```
MYUSER@MYHOST:~$ ssh -p 29418 localhost
Unable to negotiate with 127.0.0.1 port 29418: no matching host key type found. Their offer: ssh-dss
```

The syslog on MYHOST similarly reflects this issue:
```
Jul 14 00:09:40 MYHOST java[108375]: WARNING: Exception caught
Jul 14 00:09:40 MYHOST java[108375]: java.lang.IllegalStateException: Unable to negotiate key exchange for server host key algorithms (client: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa / server: ssh-dss)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.negotiate(AbstractSession.java:1279)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.handleKexInit(AbstractSession.java:452)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.doHandleMessage(AbstractSession.java:386)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.handleMessage(AbstractSession.java:349)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:848)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:331)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.session.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:57)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.io.nio2.Nio2Session$2.onCompleted(Nio2Session.java:220)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.io.nio2.Nio2Session$2.onCompleted(Nio2Session.java:212)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.io.nio2.Nio2CompletionHandler$1.run(Nio2CompletionHandler.java:34)
Jul 14 00:09:40 MYHOST java[108375]: #011at java.security.AccessController.doPrivileged(Native Method)
Jul 14 00:09:40 MYHOST java[108375]: #011at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:31)
Jul 14 00:09:40 MYHOST java[108375]: #011at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
Jul 14 00:09:40 MYHOST java[108375]: #011at sun.nio.ch.Invoker$2.run(Invoker.java:218)
Jul 14 00:09:40 MYHOST java[108375]: #011at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
Jul 14 00:09:40 MYHOST java[108375]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Jul 14 00:09:40 MYHOST java[108375]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Jul 14 00:09:40 MYHOST java[108375]: #011at java.lang.Thread.run(Thread.java:745)
```

I have tried running gitbucket both with openjdk-8 and with Oracle jdk-8, and the same issue arises in both. I observe this error from a third-party build tool that attempts to clone a repository from gitbucket; because of this I cannot use workarounds suggested by OpenSSH's legacy web site such as changing $HOME/.ssh/config on the client side. This would be an insecure workaround in any case.

**Comment by axb21** [comment]
Bump. Any thoughts on this?

**Comment by hrj** [comment]
@axb21 My ssh problems were solved after I updated the sshd in gitbucket. See #1261 

If you are able to compile and test from that branch, let us know if it works for you.

**Comment by axb21** [comment]
@hrj thanks for this. I guess I should have looked harder through the existing issues and giter before posting my issue, strange I didn't find yours.

It looks like your pull request was merged into master a day ago, so I've cloned master and am attempting to build from source. I'm running into trouble just naively doing `sbt package` and `sbt executable`, so I'm trying to sort that out. Once I do I'll post my observations here; with luck the issue will be fixed. Thanks again.

**Comment by hrj** [comment]
Yeah, the `sbt executable` command didn't work for me on first attempt (the generated war file was incomplete). Try `sbt run` followed by `sbt executable`.

**Comment by takezoe** [comment]
`sbt executable` just generates a war file, so you have to run it as follows:
```
$ sbt executable
$ cd target/executable
$ java -jar gitbucket.war
```
or you can also run GitBucket directly from source code as follows:
```
$ sbt ~jetty:start
```

**Comment by hrj** [comment]
@takezoe The problem is that `sbt executable` on a freshly checked out project doesn't result in a war that contain all dependencies. It works fine after `sbt run` or `sbt ~jetty:start`.

**Comment by axb21** [comment]
@hrj i've had a chance to test this; thank you for the hint about doing `sbt run` first, that worked. However, I still receive the same `no matching host key type found. Their offer: ssh-dss` error that I have been getting all along. I tried both checking out the latest gitbucket source as well as your commit b79498ed9f086881d5b7503f09e1f520426efc50 from Aug 4 where you updated apache-sshd. Did updating apache-sshd solve these ssh-dss-related errors for you?

**Comment by axb21** [comment]
I take it back, the new version of gitbucket works fine with `git clone ssh://...` now. I needed to remove `$GITBUCKET/gitbucket.ser` and modify `$HOME/.ssh/known_hosts` accordingly.

Thanks for your help, @hrj.
