### ISSUE TITLE
branch protection & checks/statuses

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1258]
as stated in my comments of #1248, I installed version 4.3 and configured Jenkins Github Branch Source Plugin to be used with pipeline jobs. 
It works quite well, branches & PR are discovered and build automatically AND build statuses are pushed and received correctly by gitbucket.

My question is related to what is expected to be found in "branch protection" section.

Following image is the PR has seen in gitbucket after a successfull build of jenkins
![image](https://cloud.githubusercontent.com/assets/1119660/17357472/f8e92816-595c-11e6-9e16-328e633326ae.png)

Now here is what is available in branch protection
![image](https://cloud.githubusercontent.com/assets/1119660/17357497/25392e7a-595d-11e6-95da-0ebb964c2aa6.png)

Seeing that I do not understand how I should setup my branch protection so that it ensures that a correct build from CI (jenkins here in my case) is performed before merging. If all pushed statuses have a different name and are interpreted individually by gitbucket I think it is not useable.  
Shouldn't we find a common entry "Jenkins job" and not one dedicated by branch/PR?

**Comment by nazoking** [comment]
umm... it problem happen on github (not gitbucket) ? if it is happen on github, maybe it is github-branch-source-plugin's problem.

**Comment by McFoggy** [comment]
@nazoking not surprising it is the same on github
![image](https://cloud.githubusercontent.com/assets/1119660/17364363/18999fc4-5980-11e6-9d74-242269376d08.png)

I have queried my github data `curl -i https://api.github.com/repos/McFoggy/ghbsp-playground/commits/master/status` and it resulted in

```
{
	"state" : "success",
	"statuses" : [{
			"url" : "https://api.github.com/repos/McFoggy/ghbsp-playground/statuses/f33b4c43160295151ff6c4b176b4e32eee86014d",
			"id" : 681680344,
			"state" : "success",
			"description" : "This commit looks good",
			"target_url" : "http://X.X.X.X:8080/job/ghbsp-playground/job/master/1/",
			"context" : "Jenkins job master",
			"created_at" : "2016-08-03T11:30:04Z",
			"updated_at" : "2016-08-03T11:30:04Z"
		}
	],
...
}
```

It seems that the [Github Branch Source Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Branch+Source+Plugin) uses a different context per Branch/PR.
It works fine if you use fixed branch name, for example from _dev_ to _integration_ with jgitflow but it is totally useless in any other context including PR.

I'll open an issue to the [Github Branch Source Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Branch+Source+Plugin)
