### ISSUE TITLE
LDAP Connection stops working after certain time

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1262]
## Issue

**Impacted version**: 4.3

**Deployment mode**: Tomcat 7 web app

**Problem description**:
We connect to our Active Directory server with LDAPS on port 636.
We leave the GitBucket server running at all times and can log in and work with GitBucket.
At some point when trying to commit to GitBucket server, authentication fails. Logging out and back in to the GitBucket web interface results in the Sign In form being shown all the time, unless I log in with a non Active Directory user, e.g. "root"

A restart of the GitBucket server allows authentication once more. 
Also, logging in as "root" and saving the admin settings (without changing anything) also restores the correct authentication.

**Comment by McFoggy** [comment]
If it can help for reproduction, there are free LDAP servers for tests available

I setup successfully the one from http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/ on our heroku test instance.

Login using `newton/password` succeed.

Here is the conf I used (Bind password= password)

![image](https://cloud.githubusercontent.com/assets/1119660/17440755/345e13f2-5b2e-11e6-9b93-692cfe4224d2.png)

The remaining thing is to reach the _"at some point"_...

**Comment by ritschwumm** [comment]
if this is in one of the larger companies, i'd say "firewall issue"

**Comment by PaulAdams-Conti** [comment]
Thanks for your replies.
Internally the firewall is not activated, so I don't think this is the problem. In any case I just have to save the settings to get it working again, which seems a little strange to me. The information hasn't changed but something is being refreshed to get the connection to the LDAP server up and running again.
Currently we only have a few people using it (and only sporadically) so it is difficult to get a feel for how often this happens.
GitBucket was running all weekend and this morning I had no problems logging in again. Maybe there have been some network interruptions in the past that have caused this problem.
I will keep monitoring the situation to see if I can get any more informtion.

**Comment by PaulAdams-Conti** [comment]
OK, it just happened again. I don't know if this is the cause, but one person is using Atlassian SourceTree with his name and password stored. When he tries to commit using SourceTree, this is when we seem to get the error.
Again I will continue monitoring the situation.

**Comment by PaulAdams-Conti** [comment]
OK I am now up to version 4.8 and it seems I still can't log in sometimes but I think I have found the problem / workaround. 

It may be to do with the fact that I leave SourceTree open and have quite a lot of projects open, that maybe there are numerous sessions created. Then when I try to log in to the web interface it just goes around in circles with the login screen and never lets me in. Using another user account in LDAP works fine (so no LDAP problem) but as soon as I log out and try my normal account login, the same thing happens again.

 I just went to the TomCat Manager app and expired all sessions for the GitBucket app and then I could log in straight away. Is there some kind of session limit in force?

**Comment by ritschwumm** [comment]
another idea: LDAP servers quite often limit the number of queries you can make in a given amount of time, depending on the bind user.

**Comment by PaulAdams-Conti** [comment]
Strange that it worked again as soon as I manually expired the sessions. Plus I have no problems logging in with LDAP in all other applications. If it happens again I will see if I can repeat the workaround by expiring the sessions. It would be at least good to get some kind of feedback as what is wrong rather than just getting the login dialogue emptied.

**Comment by PaulAdams-Conti** [comment]
Definitely not an LDAP (Active Directory) problem. Every time we get a problem where someone can no longer log in, if I go to the Tomcat manager and expire all GitBucket sessions, then they can always log in.

**Comment by PaulAdams-Conti** [comment]
So the problem is actually due to running within Tomcat container. I am now running it standalone and no longer have any problems with users being unable to log in. I will leave it up to you whether to close this issue, or leave it open and rename it to "Login problems when running under Tomcat" so that you can investigate what is going wrong with the session handling.

**Comment by PaulAdams-Conti** [comment]
I am now back under Tomcat as I need https connection.
I think I have solved the problem. Our Active Directory host name can resolve to different IP adresses and this is what seems to cause the problem. I have replaced the FQDN by a single IP address and it now seems to work fine.

**Comment by takezoe** [comment]
Good news. That means we can close this issue.
