### ISSUE TITLE
Upload attachment does not work.

### ISSUE THREAD

**Issue by hantsy** [gitbucket/gitbucket#1264]
I am upgrading GitBucket to 4.3.0.  I have tried to run it in Apache Tomcat 8 or standalone(java -jar).

But I found there is no **selecting them** link in the comment box when creating issues or reply others.
And the DND is also problematic and does not work. I tried to drag an images to the zone, it open the image directly in my browser, I have tried in Firefox and Chrome, got the same result.

Where I need to set up for uploading files?

![gitbucket](https://cloud.githubusercontent.com/assets/854520/17478773/aed0c110-5da0-11e6-864f-25bbdb9ab181.png)

**Comment by takezoe** [comment]
@hantsy It looks a bug. I will fix in the next release. Thanks for your reporting!

**Comment by hantsy** [comment]
Thanks @takezoe
