### ISSUE TITLE
tag a commit from gitbucket

### ISSUE THREAD

**Issue by jypelle** [gitbucket/gitbucket#1265]
Is it possible to add this functionnality ?

It could be very convenient for our build process.

**Comment by lavvy** [comment]
i think this feature is relevant too at least for tracking progress of the project

**Comment by takezoe** [comment]
@jypelle @lavvy Do you mean creating a tag from a commit mesage? or creating a tag for the specified commit on the browser?

**Comment by lavvy** [comment]
yes @takezoe  creating a tag for a specified commit on the browser. Gitbucket already shows created tags but there is no way to tag in the browser. 
You see, it should be easier to tag off a certain commit from the browser , it helps in tracking the progress of a project.

**Comment by takezoe** [comment]
@lavvy Thanks, I understood.

**Comment by SIkebe** [comment]
Tag-based release function was released in v4.21.0 so it makes sense a lot to have this feature.

**Comment by lavvy** [comment]
Yea but there is still no way to tag a commit from gitbucket.
I hope we could be able to create a tag just like we create a branch from
gitbucket.

**Comment by kounoike** [comment]
I don't like GitHub's tag creation flow. So I think it is better way that allow tagging on each commit page as below:

![image](https://user-images.githubusercontent.com/6997928/38780572-cc2b0326-4113-11e8-970c-1da4fbb5ae32.png)

Of course, UI must be re-designed. It just add short html.
