### ISSUE TITLE
Permission of update or delete comments

### ISSUE THREAD

**Issue by nurzico** [gitbucket/gitbucket#1266]
While an user comment on a commit (in line of code in commit or on commit), then any user (admin or normal user) can update or delete those comment (of other user). Shortly any user can delete or update comments of other users. No permission logic of update or delete comments.

**Comment by takezoe** [comment]
@nurzico  Thanks for your reporting! I tested in my environment and I could reproduce this problem for users who is added as collaborator or group manager. How is your case?

They are same as administrator of the repository in the current GitBucket, so they can edit and delete all comment. However I'm considering more detailed permission system in the future version of GitBucket. For example, we can add read-only user to the repository member. By this feature, you will be able to control comment editing or deleting for each users.

**Comment by nurzico** [comment]
@takezoe Thanks for looking into the issue. In my case, a collaborator can edit/remove comments of any user(e.g. root or repo admin). This seems odd to me. 
My assumption was only root or repo admin can edit/remove any comment and a collaborator can edit/remove only his/her comments. Good to hear you will work on it.

**Comment by takezoe** [comment]
Merged with #1286
