### ISSUE TITLE
Pull request webhook JSON dose not contain "merged" (boolean) property

### ISSUE THREAD

**Issue by eyasuyuki** [gitbucket/gitbucket#1271]
## Issue

**Impacted version**: HEAD

**Deployment mode**: *explain here how you use gitbucket : standalone app

**Problem description**:
- Pull request webhook JSON does not contain "merged" (boolean) property.
  c.f.) https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by takezoe** [comment]
@nazoking Any progress? Can I take this issue if you haven't started work?

**Comment by nazoking** [comment]
@takezoe I am sorry, the work has not been started yet. Please take this issue.

If I can wait until the end of the year, I can work at that time. If you solve this issue, I will work on other issues at that time.

**Comment by takezoe** [comment]
@nazoking OK, I take this issue and would like to fix in 4.8.

**Comment by takezoe** [comment]
Added following properties in #1371
- merged
- merged_at
- merged_by

**Comment by eyasuyuki** [comment]
@takezoe Thank you!
