### ISSUE TITLE
Hides sidebar by user choices

### ISSUE THREAD

**Issue by kmarukawa** [gitbucket/gitbucket#1275]
## Issue

**Impacted version**: 4.3 and others

**Deployment mode**: using gitbucket from tomcat

**Problem description**:
- There is no option to hide sidebar (and menu)
- CSS gitbucket-4.3 uses may allows it under certain circumstance (like zooming bigger than 175%)
- However, having such an option user can choose is good idea

Please consider having such an option.  Thanks.

**Comment by eprozium** [comment]
Hiding the sidebar should be theme (layout) specific. This could be persistent with a cookie or localStorage. see #1279

**Comment by aadrian** [comment]
+1 for persistence of side menu (even cookie or local storage would be enough), but right now the toggle is lost when the page is reloaded.

**Comment by kmarukawa** [comment]
I'm still having this issue, no control to the sidebar at right side of wiki pages.  @takezoe solves the similar issue about the navigation bar at left side.  Should I submit this issue again?  Thanks in advance.
