### ISSUE TITLE
Search hangs forever

### ISSUE THREAD

**Issue by imeszaros** [gitbucket/gitbucket#1276]
## Issue

**Deployment mode**: standalone

**Problem description**:
If i try to use the search function, the browser issues the http request (search?q=keyword) but the response never arrives.

I noticed this with previous versions also, currently i'm on 4.3.0. What else info should i provide to help solving this?

Unfortunately i don't have instant access to the host machine, but i have root access on GitBucket.

**Comment by uli-heller** [comment]
I guess this is related to #792 . My impression is that the search is pretty fast as long as you don't habe much data in gitbucket. It is awfully slow after populating gitbucket with some data. My expectation is that this will be fixed when a good search engine like elasticsearch or lucene is used.

**Comment by imeszaros** [comment]
I think this should be a priority. Currently afaik there is no other *quick* method to navigate to an issue by issue number.

**Comment by imeszaros** [comment]
@uli-heller , you are right. On the same gitbucket instance, but in a much smaller repository, the search works just fine.

**Comment by takezoe** [comment]
This plugin which is under development makes Elasticsearch based full text search.
https://github.com/codelibs/gitbucket-fess-plugin

I believe it would help GitBucket users who need repository search.

**Comment by aadrian** [comment]
@takezoe Isn't ElasticSearch an little bit overkill for this data amount?

H2 has full text search http://h2database.com/html/tutorial.html#fulltext   (and all other half-decent DBs too) that performs quite good.

**Comment by takezoe** [comment]
@aadrian I don't think so. It must index all source code in repository, and some users are managing large repository on GitBucket. And I wouldn't like to add dependency to database specific feature from point of view of portability.

Elasticsearch is pure Java solution. It has high reliability and management is easy. We can also embed it into Java application. I think Elasticsearch fits GitBucket perfectly.

**Comment by imeszaros** [comment]
In this case i think the search function should be narrowed down to the h2 database only. If one needs a repo search function, the upcoming fess-plugin could be the option. But currently the search is unusable, and we would mainly use it to navigate among the issues.
