### ISSUE TITLE
Confusing issue list behavior

### ISSUE THREAD

**Issue by hrj** [gitbucket/gitbucket#1277]
## Issue
**Impacted version**: 4.3.0

**Deployment mode**: standalone app

**Problem description**:
If I visit a milestone page and then visit the issue list, then the milestone filter is sticky. That is, only issues from that milestone are visible. However, there is no visual indication that the milestone filter is active. The only way to find out is to click the milestone filter dropdown, and notice that milestone is selected.

My suggested solutions:
* Don't make the milestone filter sticky. If I click on issues link in the sidebar, it should show all issues, without filters.
* If milestone filter is going to be sticky it should show some indication. Either in the UI or in the URL.

**Comment by takezoe** [comment]
@hrj Thanks for your suggestion. Search filter will be not sticky in 4.5.
