### ISSUE TITLE
Select AdminLTE color skin

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1279]
It might be nice if AdminLTE color skin is selectable.

**Comment by eprozium** [comment]
Please allow to change the theme, not just the color from this theme.

Than if you expose the API to plug-ins, users could easily provide themes as a plug-in package. The config page of the specific plug-in would than provide the possible config for that theme.

E.g. There could be a "admin-lte-theme" plug-in that is provided with the distribution, and in it's configuration you can put the color skin selection.

**Comment by kounoike** [comment]
I wrote PR in #1489.

**Comment by takezoe** [comment]
#1489 has been merged.
