### ISSUE TITLE
Add a "plug-in" label to this issue tracker!

### ISSUE THREAD

**Issue by eprozium** [gitbucket/gitbucket#1285]
Add a "plug-in" label to this issue tracker to be able to mark the issues as (potential) "plug-ins", since so many of the feature requests would be better off in some plug-ins.

It's simple to filter by a label, so that users who search for GitBucket plug-in idea can quickly find them.

**Comment by takezoe** [comment]
Good idea 👍

**Comment by takezoe** [comment]
Done: https://github.com/gitbucket/gitbucket/issues?q=is%3Aopen+is%3Aissue+label%3Aplugin
