### ISSUE TITLE
Improve Cookie Security

### ISSUE THREAD

**Issue by Okeanos** [gitbucket/gitbucket#1291]
I noticed that the Cookie set by GitBucket (at least in Version 4.3) uses neither the `Secure` nor the `HttpOnly` directive (as described [here](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies)). I presume these have been omitted to allow for easier deployment of GitBucket as intranet service.

Modifying the Cookie set by GitBucket server-side is definitely possible as described [here for Apache](http://stackoverflow.com/a/24246462/2920585) but I would very much appreciate it if GitBucket either used stricter security settings for its cookies out of the box or allowed for increasing the security via configuration values instead of relying on server-side manipulation.

I presume it would be possible to detect whether or not GitBucket runs on

* a "public", valid domain, i.e. not in an intranet setting,
* and with SSL/HTTPS enabled

to conditionally set the additional directives when feasible as an alternative to hardcoding the settings or making additional configuration values necessary respectively.

**Comment by takezoe** [comment]
Modified to always set `http-only`. Also set `secure` if the base url is configured `https://xxx`.
