### ISSUE TITLE
Disable option for forking.

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1292]
Please add an option in the settings (and the functionality) to be able to disable forking
(the same way it's now possible to disable issues or wiki for a project).

Many projects are not making use it it anyway for intranet projects, and it makes more sense for public open source projects (but this is not the biggest use case of GitBucket anyway).

Thank you.

**Comment by takezoe** [comment]
![2016-10-03 15 27 02](https://cloud.githubusercontent.com/assets/1094760/19029107/088af0fa-897e-11e6-908f-d08a046c6507.png)

**Comment by aadrian** [comment]
Fantastic! Thank you!
