### ISSUE TITLE
Feature request: In /dashboard/issues add the ability to see all issues assigned to a user

### ISSUE THREAD

**Issue by hrj** [gitbucket/gitbucket#1293]
In `/dashbord/issues` I can see all issues across the projects. There is also a way to filter by "Visibility" and "Organisation".

It would also be good to have a way to filter by `assignee:me`, or in general, assigned to any chosen user.

**Comment by takezoe** [comment]
Dashboard issues / pull request switcher had been removed in previous UI updating. It will be restored with new design in GitBucket 4.5.

![dashboard_switcher](https://cloud.githubusercontent.com/assets/1094760/18661519/22c91c08-7f51-11e6-9e09-0a65a80739ee.png)
