### ISSUE TITLE
4.4: Standalone app shows error messages on startup

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1300]
## Issue
**Impacted version**: 4.4 (4.3 is ok)

**Deployment mode**: standalone app

**Problem description**:

Typically, I'm doing something like this:

1. Checkout the release tag
2. `git clean -f`
3. `./sbt.sh clean`
4. `rm -rf target`
5. `./sbt.sh package`
6. `./sbt.sh executable`
7. `java -jar target/executable/gitbucket.war`

For 4.3 (... and "all" versions before), this works ok: [43.txt](https://github.com/gitbucket/gitbucket/files/488862/43.txt)

For 4.4, I'm getting errors: [44.txt](https://github.com/gitbucket/gitbucket/files/488860/44.txt)

**Comment by uli-heller** [comment]
I tried again using the gitbucket-4.4.tar.gz from the releases tab, same result.

**Comment by uli-heller** [comment]
This fixes the issue for me:

``` diff
diff --git a/build.sbt b/build.sbt
index e49451b..b711696 100644
--- a/build.sbt
+++ b/build.sbt
@@ -177,7 +177,7 @@ publishTo <<= version { (v: String) =>
 }
 publishMavenStyle := true
 pomIncludeRepository := { _ => false }
-artifact in Keys.`package` := Artifact(moduleName.value)
+//artifact in Keys.`package` := Artifact(moduleName.value)
 pomExtra := (
   <url>https://github.com/gitbucket/gitbucket</url>
   <licenses>
```

**Comment by takezoe** [comment]
@uli-heller This line is needed to make a jar file which is published to the maven central for plugin developers. You can make an executable war file by `./sbt.sh clean executable` simply.

**Comment by ritschwumm** [comment]
so - this means if you do ```sbt clean package executable``` you get an additional (and unnecessary) jar file inside the war whereas if you do ```sbt clean executable``` you don't?

**Comment by uli-heller** [comment]
@takezoe I tried your suggestion and the executable created by `./sbt.sh clean executable` starts fine. Thanks.

**Comment by uli-heller** [comment]
@ritschwumm I've created several war files:
* the first one by executing `./sbt.sh clean executable` -> starts OK
* the 2nd one by executing  `./sbt.sh clean package executable` -> produces an error
I compared the two war files using `zipcmp` and this is the difference:

```
--- target/executable/gitbucket.war
+++ target44t/executable/gitbucket.war
+    2658488 3c5ae78a WEB-INF/lib/gitbucket_2.11-4.4.0.jar
-   44945769 c53f50c7 WEB-INF/lib/gitbucket_2.11-4.4.0.jar
```

So basically, the jar file is included in both cases, but it has a different content. From what I see, in the 2nd case, the jar file is basically a war file.

**Comment by ritschwumm** [comment]
ouch.. i don't understand yet how this happens - the ```executable``` task depends on the ```package``` task here https://github.com/gitbucket/gitbucket/blob/master/build.sbt#L133 so ```package``` should be executed exactly once in both cases. but then, this is sbt we're talking about - so it's probably something to do with having stuff in the wrong scope somewhere :/

**Comment by uli-heller** [comment]
Using `./sbt.sh clean executable` fixes the creation of the standalone app. Created #1304 for the naming of the war file when executing `-/sbt.sh package`.
