### ISSUE TITLE
ssh clone - GB Configuration Question

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1302]
This isn't so much an issue as a general config question.  I have a standalone implementation of GB wherein one of the users can only clone if they use ssh://username@....   This form will not work for them: ssh://git@....

I suspect key problems, but this did lead me to a more general question.  How/where is GB configured to use the username vs the generic git user for cloning?

**Comment by ritschwumm** [comment]
the user not being able to clon with ssh://git@... probably configured an ssh public key shared with some other user. gitbucket needs a unique ssh key to figure out the gitbucket user when the generic ssh user "git" is used.

have a look at the logfile, there's probably something in it talking about an ambiguous key.

**Comment by tundratim** [comment]
OK thanks, that clears it up...
