### ISSUE TITLE
4.4 and master: "sbt.sh package" creates a war file named gitbucket_2.11-4.4.0.jar (instead of .war)

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1304]
## Issue
**Impacted version**: 4.4, master (4.3 is OK)

**Deployment mode**: NA

**Problem description**:
1. Start with a fresh checkout
2. Execute `./sbt.sh package`
3. Expect creation of target/scala-2.11/gitbucket_2.11-4.4.0.war, instead target/scala-2.11/gitbucket_2.11-4.4.0.jar is created "twice"

```
...
[warn] there were two feature warnings; re-run with -feature for details
[warn] one warning found
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.11/gitbucket_2.11-4.4.0.jar ...
[info] Done packaging.
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.11/gitbucket_2.11-4.4.0.jar ...
[info] Done packaging.
[success] Total time: 224 s, completed 26.09.2016 06:25:34
```

This is a followup of #1300

**Comment by takezoe** [comment]
Once remove package artifact name overriding to solve this issue.

**Comment by uli-heller** [comment]
Works for me now - thanks!
