### ISSUE TITLE
How do you migrate from H2 to another database?

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1306]
## Question

I'm wondering how you migrate your data from H2 to another database, say PostgreSQL or MariaDB.
Due to #1274, I currently do think this might be an approach:

* create an export of your gitbucket instance
* prepare a new instance configured to use a the new database
* start the new instance once -> schema will be created
* import the data created in the first step

Is this the way it is supposed to work? Am I missing something? I thin I'll give this a try within the next weeks...

**Comment by takezoe** [comment]
@uli-heller See https://github.com/gitbucket/gitbucket/wiki/External-database-configuration

Please send such question to the gitter room instead of raising an issue:
https://gitter.im/gitbucket/gitbucket

**Comment by uli-heller** [comment]
Perfect - thanks!
