### ISSUE TITLE
More plug-ins in the live demo!

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1309]
Please always install more (if not all) plug-ins in the demo installation hosted on Heroku.
![gitbucket_demo_plug-ins](https://cloud.githubusercontent.com/assets/140953/18989721/c363dc16-870d-11e6-8c67-6b7851ce5531.png)

Thank you.

**Comment by McFoggy** [comment]
@aadrian all the plugins of the gitbucket organization are there. The others are from the community.
But I agree it would be quite good to have also in parallel an demo community installation.

@takezoe how is maintained the heroku installation? couldn't we maintain two installations?

**Comment by takezoe** [comment]
The demo site on Heroku is being maintained by @xuwei-k. Installed plugins are his choice and I don't know how to maintain in detail.

Anyway, that demo site is his goodwill completely. So I can not request something else to him.

**Comment by McFoggy** [comment]
@takezoe thx perfectly understandable. we'll have to create & maintain a deployable project under the umbrella of the [gitbucket-plugins](https://github.com/gitbucket-plugins/) organization.

**Comment by takezoe** [comment]
@McFoggy 
> we'll have to create & maintain a deployable project under the umbrella of the gitbucket-plugins organization.

or under the gitbucket organization?

**Comment by McFoggy** [comment]
no I was thinking under the gitbucket-plugins organization

**Comment by xuwei-k** [comment]
I have deployed following `Procfile` and jars.

```
├── Procfile
├── gitbucket.war
└── plugins
    ├── gitbucket-announce-plugin.jar
    ├── gitbucket-emoji-plugin_2.11-4.3.0.jar
    └── gitbucket-gist-plugin_2.11-4.3.0.jar
```


Procfile

```
web: java -Dgitbucket.home=/app -Xmx768m -jar gitbucket.war --port="$PORT"
```

and use https://github.com/heroku/heroku-buildpack-jvm-common

**Comment by xuwei-k** [comment]
- I just created repository https://github.com/xuwei-k/gitbucket.herokuapp.com 
- setup auto deploy from GitHub
- invite @McFoggy and @takezoe as collaborators in GitHub and Heroku
- https://dashboard.heroku.com/apps/gitbucket/deploy/github
- I can transfer ownership to https://github.com/gitbucket 

WDYT?

![2016-10-03 15 14 06](https://cloud.githubusercontent.com/assets/389787/19028872/15347fc6-897c-11e6-8e23-6da074f8459e.png)


<hr />


![2016-10-03 15 13 54](https://cloud.githubusercontent.com/assets/389787/19028873/1535a680-897c-11e6-8cf0-2a0217d3b1b4.png)

<hr />

![2016-10-03 15 12 34](https://cloud.githubusercontent.com/assets/389787/19028880/20504d54-897c-11e6-8101-0b2664d7154b.png)

**Comment by McFoggy** [comment]
@xuwei-k first of all many thanks for making this demo app live.

- for the future, I think it would be better to have this repo in the gitbucket organization. full rights on this repo could still be granted to @xuwei-k (or even collab rights on organization)
- then we could "duplicate" that repository and create a `gitbucket.community.herokuapp.com` either under the gitbucket organization or under the gitbucket-plugins organization.
