### ISSUE TITLE
Issue index -- start from

### ISSUE THREAD

**Issue by demon101** [gitbucket/gitbucket#1310]
For simplification of migration from another bug trackers will be useful start from options
Now for example in our bug tracker we have 1000 issues, in gitbucket project it starts from 1 and produces mishmash for me. 
Until then I will import old bugs to gitbucket, I will keep old tracker. And simplest solution for avoiding collisions -- start new issues from for example 2000

I understand, it's hacky.  Is it possible to set start index directly in DB?

**Comment by McFoggy** [comment]
Hi,

it is a _hack_ but it will worked _(and for the moment there is no other choice)_.

I just did it on the demo environment: http://gitbucket.herokuapp.com/
I created a fake issue in a demo project => it' id is 1.
Then I updated the counter in the table used by gitbucket using:

```
UPDATE ISSUE_ID 
SET ISSUE_ID=1000
WHERE USER_NAME = 'root' AND REPOSITORY_NAME='demo-issues-nb'
```

Creating another issue gave it a number 1001

![image](https://cloud.githubusercontent.com/assets/1119660/19019987/d596c9c2-889b-11e6-9028-efd98867189e.png)

**Comment by demon101** [comment]
Cool!
THX
