### ISSUE TITLE
Support creating directories via the GitBucket web interface

### ISSUE THREAD

**Issue by salmasian** [gitbucket/gitbucket#1315]
## Issue
**Impacted version**: 3.14
**Deployment mode**: *with an http frontend*

**Problem description**:
It is possible to create a new file via the web interface of GitBucket. Please allow for creating a new directory via the web interface as well.

**Comment by aadrian** [comment]
You can't create an empty directory with Git.

But in GitBucket while creating a new file (using the web UI), instead of ```file_name.txt``` just type ```new_path/file_name.txt``` and that file will be created in a subdirectory called ```new_path```.

**Comment by salmasian** [comment]
You are right. Closing this as invalid.
