### ISSUE TITLE
Commits not appear in front-page since 4.5.0

### ISSUE THREAD

**Issue by mariodebian** [gitbucket/gitbucket#1318]
## Issue

**Impacted version**: 4.5.0
**Deployment mode**: _apache2 mod_proxy_

**Problem description**:
- _Since upgrade to 4.5.0 commits don't appear in front page (AKA News Feed) only issues_

**Comment by yanma** [comment]
I'm curious about this phenomenon. Maybe I faced the same issue as your report.
As I commented in the issue #993, the news feed doesn't appear when I push the commit over ssh.
Could you describe your problem in detail?

**Comment by mariodebian** [comment]
Commits and pull-requests made with WebUI shows ok, but commits sent with ssh (don't test http) not appear in news feed.

**Comment by McFoggy** [comment]
yesterday evening before the resolution of #1319 and while trying to reproduce it on the heroku demo site I tried to do some commits from the UI and didn't noticed neither that commits were referenced in issues ; perhaps it is related.

**Comment by takezoe** [comment]
Fixed in #1336
