### ISSUE TITLE
Multiple issue reference

### ISSUE THREAD

**Issue by moonwolf-github** [gitbucket/gitbucket#1319]
**Impacted version**: 4.5.0 (probably all versions)

**Deployment mode**: standalone with apache

**Problem description**:
When you mention issue in commit more than once, this commit appears in issue tab multiple times.

**Comment by takezoe** [comment]
@moonwolf-github I haven't possible to understand this problem correctly.
Could you attach screenshot? or add more specific explanation?

**Comment by moonwolf-github** [comment]
![gitbucket](https://cloud.githubusercontent.com/assets/10871358/19341703/db3fff38-912e-11e6-84d5-b3cca81d40ac.png)

As you can see commit **b2d67bf** occurs here twice. That's because issue number is mentioned in commit log twice.

**Comment by takezoe** [comment]
@moonwolf-github Thanks. I understood.
