### ISSUE TITLE
Ldap login with Ldap group

### ISSUE THREAD

**Issue by jimAC2016** [gitbucket/gitbucket#1324]
I have a question regarding using GitBucket with LDAP settings.
How can I setup Gitbucket for accepting users that are members of one specific groups?

**Comment by moonwolf-github** [comment]
Put something like ```memberof=cn=programmers,ou=Group,ou=Main,o=com``` in *Additional filter condition* field (LDAP server must have memberOf extension turned on).

**Comment by jimAC2016** [comment]
I tried this but nothing happens when I log in. I got the following error "LDAP Authentication Failed: User does not exist.". Can I maybe have the query that Gitbucket use? Maybe with that I can debug the query in our environment.

**Comment by jimAC2016** [comment]
I found the problem. I need to be more into some AD table to use the memberof statement.

**Comment by McFoggy** [comment]
> I need to be more into some AD table to use the memberof statement.

@jimAC2016 couldn't it help the community if you explained a little bit more which AD tables/requirements you had to fullfil to get it solved?

**Comment by Fmstrat** [comment]
Since this is the first google result, I'm using a Samba4 AD setup, and the additional filter I needed was:

```
memberof=cn=Git,dc=mydomain,dc=local
```

Where "Git" is my group.
