### ISSUE TITLE
gist plugin stopped working after gitbucket 4.2.1

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket#1329]
Please see gitbucket/gitbucket-gist-plugin#33

## Issue
**Impacted version**: gitbucket 4.2.1

**Deployment mode**: standalone app

**Problem description**:
The gist plugin v 4.0.0 worked with gitbucket 4.2.1 for me, in the sense that:
- I would see a "Snippets" link on the header
- Clicking the Snippets link, or viewing `$URL/gist` would take me to a list of my snippets

See screencap from gitbucket 4.2.1
![cap1](https://cloud.githubusercontent.com/assets/3464572/19011890/29796110-8772-11e6-836e-307f87566ec8.png)

If I upgrade either gist plugin to a newer version (4.2 or 4.3); or, if I upgrade gitbucket to a new version (4.3 onward), the Snippets link is gone and manually hitting `$URL/gist` produces a "Not Found" page. See screepcap from gitbucket 4.5
![cap2](https://cloud.githubusercontent.com/assets/3464572/19011898/96dfbce0-8772-11e6-9d70-1720320e0629.png)

I do not see errors in my syslog. The Snippets simply are not there. Any idea what has happened?

**Comment by axb21** [comment]
In case it's helpful, I tried exporting data from gitbucket 4.5, and it correctly exports data about my gists. They are also located under `$HOME/.gitbucket/gist/$USER`, as they always have been. It seems something went awry with the communication between gitbucket and the plugin? And this may be at the gitbucket level?

**Comment by takezoe** [comment]
Resolved: https://github.com/gitbucket/gitbucket-gist-plugin/issues/33
