### ISSUE TITLE
How to access created issues?

### ISSUE THREAD

**Issue by philippeowagner** [gitbucket/gitbucket#1331]
We are using gitbucket v 3.8 and like to access all created issues per repository.

We found the attachments on the file system, but where are to issues stored? 

Thanks

**Comment by McFoggy** [comment]
They are stored in the DB.
I do  not know if they are accessible via REST API, might be not as such endpoint is not describe in the wiki   https://github.com/gitbucket/gitbucket/wiki/API-WebHook.

**Comment by philippeowagner** [comment]
I assume our version is too old. 

Is it possible to access the DB from command line? If yes, how?

**Comment by McFoggy** [comment]
The DB is not accessible from command line, but gitbucket embed the "H2 console" from which you can query the DB.

1/ copy your DB jdbc url from "System Settings" page

![image](https://cloud.githubusercontent.com/assets/1119660/19556623/38200002-96c2-11e6-8b7d-11d63a321f91.png)

2/ open the H2 console available in the System menu, use the copied URL and login using `sa/sa`

![image](https://cloud.githubusercontent.com/assets/1119660/19556671/72774896-96c2-11e6-832e-98dd5bbca5b8.png)

3/ Play in pure SQL with the DB and the issue related tables starting with the `ISSUE ` one

**Comment by philippeowagner** [comment]
Thanks for your quick response @McFoggy .
Sadly the "DATABASE_URL" is not exposed in version 3.8's System Settings.

**Comment by McFoggy** [comment]
the URL are the same regardless the version.

For example on my windows machine, I installed a 3.8 version using following layout:
![image](https://cloud.githubusercontent.com/assets/1119660/19573927/75865bb2-9708-11e6-8366-dc868c266907.png)

I can the use the following  db url to connect the h2 console : `jdbc:h2:C:\dev\tmp\gitbucket\3.8\gitbucket-data/data;MVCC=true`

Notice that `/data` at the end refers to the database file name `data.mv.db` without the extensions.

If your on linux or mac adapt to a unix path.

**Comment by philippeowagner** [comment]
![screen shot 2016-10-24 at 17 35 58](https://cloud.githubusercontent.com/assets/113043/19652267/79a99d2a-9a10-11e6-8d13-56772b71b7b9.png)

Not sure if the database was loaded correctly... What is a SQL query to list the repos or the issues? 
Thanks for the hand...

**Comment by philippeowagner** [comment]
Cool. Thanks you @McFoggy. I was able to load the database...
