### ISSUE TITLE
How to add a limitation of filesize when pushing?

### ISSUE THREAD

**Issue by Andecy** [gitbucket/gitbucket#1332]
version is 4.5.0

I want to add a global limitation on single file likes 2MB

**Comment by McFoggy** [comment]
I am not sure you can with current version.

With a reverse proxy (nginx, apache httpd, ...) you can easily control the max size of received data (see the wiki here for example https://github.com/gitbucket/gitbucket/wiki/Reverse-proxy-with-Nginx) but this will apply to the whole data sent by the git client not to individual files.

**Comment by takezoe** [comment]
@Andecy Or you can add limitation by application server configuration. For example, `maxPostSize` parameter is available in Tomcat: http://tomcat.apache.org/tomcat-8.5-doc/config/http.html

**Comment by McFoggy** [comment]
@takezoe @Andecy but still this apply to the whole incoming HTTP request (git push content for example) not to individual files.

**Comment by Andecy** [comment]
I hope Gitbucket could add something to conf for limiting individual filesize

`
#Max size of each file in MB. Defaults to 3MB
FILE_MAX_SIZE = 3
`

**Comment by takezoe** [comment]
@McFoggy That's right. It might be possible to add such limitation as plug-in using receiveHooks extension point.

**Comment by takezoe** [comment]
Close outdated question.
