### ISSUE TITLE
"Members" tab in group view do not indicate who in that group is its manager.

### ISSUE THREAD

**Issue by pazaur** [gitbucket/gitbucket#1334]
Would be very helpful to have indication who is the manager of the group in the "members" tab. 
Long version:
In "Collaborators" tab within "Settings" of repository there's a list like:
"username"
"username" (manager) 
"username"

And only there. Unfortunately settings of repository are visible only for managers/admin. 

Ordinary users (even members of the group) have no way to tell who is manager of the group to, in example, request addition to the group.

Gitbucket installed version 4.5.0 .

**Comment by takezoe** [comment]
![group_members](https://cloud.githubusercontent.com/assets/1094760/19710449/4e2b93ce-9b69-11e6-96f7-4b040622f0cb.png)
