### ISSUE TITLE
"SMTP Port" Setting is ignored

### ISSUE THREAD

**Issue by c-yan** [gitbucket/gitbucket#1337]
## Issue
**Impacted version**: 4.6.0

**Deployment mode**: Deployment mode: Windows Server 2012 R2 + Apache 2.4.16 + JDK 8u60 + Tomcat 8.0.32

**Problem description**:
1. I enter 587 to "SMTP Port" field on "System Settings" page.
2. I push the "Apply changes" button.
3. I enter my mail adress and I push the "Send" button near the Text of "Send test mail to".
4. I get an error message becaus of trying to connect to port 465 instead of port 587.

> [Error] org.apache.commons.mail.EmailException: Sending the email to the following server failed : xxxx.xxxx.net:465

**Comment by fujohnwang** [comment]
Same Error , but I indeed use port 465 and external smtp server

**Comment by takezoe** [comment]
@c-yan @fujohnwang Did you check "Enable SSL"?

**Comment by takezoe** [comment]
If yes, the problem will be fixed by 65ece3292a9a9c8fd304cbec7de181dcb24090f7.

**Comment by c-yan** [comment]
> Did you check "Enable SSL"?
yes
> If yes, the problem will be fixed by 65ece32.
thank you!
