### ISSUE TITLE
Allow manual label color entry

### ISSUE THREAD

**Issue by haarp** [gitbucket/gitbucket#1339]
When creating a label in Gitbucket 4.6, one has to use the color picker. You cannot enter the color directly into the hex code box due to a readonly="" attribute. This would be useful if you e.g. want several labels with the exact same color. Please remove the readonly attribute. Thanks!

**Comment by takezoe** [comment]
Fixed in: 3ca0d35a1b26ef8d7db0a55e714260d0d8ff759e
