### ISSUE TITLE
Dropdown list goes out of screen

### ISSUE THREAD

**Issue by haarp** [gitbucket/gitbucket#1340]
In Gitbucket 4.6, when there are many labels are possible assignees, the dropdown list in the issue viewer can grow too large for the screen, making it impossible to reach users below the screen edge. There are no scrollbars.

![screenshot_2016-11-01_12-13-53](https://cloud.githubusercontent.com/assets/781030/19888118/f0767546-a02c-11e6-8889-e681fb00d038.png)

**Comment by takezoe** [comment]
@haarp Can the filter box like the branch dropdown list help you?

**Comment by haarp** [comment]
Yes, that would help I think.

**Comment by takezoe** [comment]
@haarp OK, I merged 4eb148f4a6212406905018167cea3416606464c6 that adds a filter box to labels, milestones and assignees dropdown list on the issue editing form.

**Comment by haarp** [comment]
Great, thank you!
