### ISSUE TITLE
Recent Pushes Not Reflected On Home Page

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1344]
One of the GB instances I manage is failing to show the most recent push updates on the summary page.  If you go to the project repo itself, it looks fine, it's just the overview page that is failing to note the latest push/checkins.

This has only been noted since the 4.5.0 update but it may have been an issue previously, I don't know.

Any ideas?

**Comment by takezoe** [comment]
@tundratim Are you pushing via SSH? If yes, please wait for the 4.7 release at the end of this month because it's already fixed in #1336.

**Comment by tundratim** [comment]
@takezoe - Noted and thanks ...
