### ISSUE TITLE
Upgrade to Scala 2.12

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1346]
Scala 2.12 version of Scalatra <del>2.5.0-RC1</del> 2.5.0 has been released, but Slick is still 2.12.0-M5. We will start updating our code using blocking-slick after Scala 2.12 version of Slick release.

**Comment by xuwei-k** [comment]
slick for Scala 2.12 released
http://repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.2.0-M2/
