### ISSUE TITLE
How to optimize gitbucket performance?

### ISSUE THREAD

**Issue by liangjun0305** [gitbucket/gitbucket#1347]
jetty:9.3.13.v20161014
gitbucket:4.6.60
java:1.8.0_101

git repository : 27
git user: 30+

now , if git repository is large , the  web is slow, and pull is slow, push is slow .
so How to optimize gitbucket performance? please help!

**Comment by takezoe** [comment]
@liangjun0305 Is it quick for small repository on the same GitBucket instance? or all repositories on the same GitBucket instance are slow even if one large repository exists?

**Comment by liangjun0305** [comment]
@takezoe yes, we have one GitBucket instance,Just started very quickly. After a year，Small repository are now slow, and large repository are slower!  
when one pull or push large repository ,the Cpu usage of GitBucket is 100%.

**Comment by takezoe** [comment]
@liangjun0305 How many bytes are large repository? and Could you show spec of your server and JVM configuration (mainly heap size)?

**Comment by liangjun0305** [comment]
@takezoe 
1.7G	/root/.gitbucket/repositories/web/fe.git/
jvm -Xmx3550m -Xms3550m -Xmn2g

**Comment by takezoe** [comment]
@liangjun0305 Thanks, heap size looks enough. It might be limit of JGit. I will test in my environment.

**Comment by McFoggy** [comment]
what would be the best would be to take a JVM recording using Oracle JFR. The easiest is to launch Java Mission Control (jmc.exe in your jdk), attach to the jvm running gitbucket, launch a recording (let's start with default settings of JFR/JMC), start recording before the push and ends after it. Once done, the recording can be shared to anyone for analysis.

**Comment by liangjun0305** [comment]
@takezoe 
![qq 20161124103052](https://cloud.githubusercontent.com/assets/1763076/20584808/22be2858-b231-11e6-8524-1a52a30c08c5.png)
![qq 20161124102739](https://cloud.githubusercontent.com/assets/1763076/20584809/22c41c36-b231-11e6-9e4c-f4f4630a90b1.png)
![qq 20161124102714](https://cloud.githubusercontent.com/assets/1763076/20584810/22c68322-b231-11e6-83c1-a20877d5c655.png)

any idea?  please help! tks!

**Comment by takezoe** [comment]
@liangjun0305 CPU is used for iowait mainly?

**Comment by DevilCoreBlack** [comment]
Hi, 
I have the same problem.
I used Gitbucket on the Windows platform
Java:1.8.0.121 x64(x86 tested too)

You can test by yourself on the large repo such as UNREALENGINE4.15 if you have access.
Clone the UnrealEngine4.15 repo from github, create a new repo in gitbucket and put UE in gitbucket. When it is finished - you'll see that the web, push, pull are very slow only on this repo. And everything works fine on another repo on the same server.

**Comment by takezoe** [comment]
@DevilCoreBlack Thanks, but I couldn't test because it requires to register my GitHub account to access UnrealEngine git repo.

**Comment by aadrian** [comment]
@takezoe https://github.com/wanggogo/UnrealEngine4.15.git works without registration.

I tried the above repo with GitBucket 4.12.1, H2 and no plug-ins active. Even if the repo is huge 1,7GB big with much too many objectss, I can see no performance difference between this one and other very small repos.

**Comment by takezoe** [comment]
Close outdated question.
