### ISSUE TITLE
Cannot start Gitbucket on tomcat7

### ISSUE THREAD

**Issue by maans88** [gitbucket/gitbucket#1351]
Not sure which log files to include here, please let me know and I'll post them.

**Comment by ritschwumm** [comment]
all that have error messages in them, for a start...

**Comment by maans88** [comment]
well this is what I get in tomcat, but not much informative:
Message: 	

> FAIL - Application at context path /gitbucket could not be started


catalina.2016-11-15.log

> INFO: Deploying web application archive /var/lib/tomcat7/webapps/gitbucket.war
Nov 15, 2016 5:09:36 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 5:09:36 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
Nov 15, 2016 5:09:36 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/gitbucket.war has finished in 17,210 ms
Nov 15, 2016 5:09:52 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 5:09:52 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
Nov 15, 2016 5:22:00 PM org.apache.catalina.util.LifecycleBase stop
INFO: The stop() method was called on component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/gitbucket]] after stop() had already been called. The second call will be ignored.
Nov 15, 2016 5:22:01 PM org.apache.catalina.startup.HostConfig undeploy
INFO: Undeploying context [/gitbucket]
Nov 15, 2016 5:22:28 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/gitbucket.war
Nov 15, 2016 5:22:41 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 5:22:41 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
Nov 15, 2016 5:22:41 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/gitbucket.war has finished in 12,530 ms
Nov 15, 2016 6:30:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 6:30:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors

**Comment by maans88** [comment]
catalina.out error messages

> INFO: Deploying web application archive /var/lib/tomcat7/webapps/gitbucket.war
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/slf4j-jdk14-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Nov 15, 2016 10:17:31 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 10:17:31 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
Nov 15, 2016 10:17:31 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/gitbucket.war has finished in 14,646 ms
Nov 15, 2016 10:17:31 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Nov 15, 2016 10:17:32 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat7/webapps/ROOT has finished in 696 ms
Nov 15, 2016 10:17:32 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Nov 15, 2016 10:17:32 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 18722 ms
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/slf4j-jdk14-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Nov 15, 2016 10:17:52 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 10:17:52 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/slf4j-jdk14-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Nov 15, 2016 10:21:29 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 15, 2016 10:21:29 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors

**Comment by McFoggy** [comment]
Isn't there something else?
Can you change logging levels when deployed to tomcat? (perhaps this [wiki page](https://github.com/gitbucket/gitbucket/wiki/Tracing-%26-logging) can help).

**Comment by webard** [comment]
`sudo chown -R tomcat7:tomcat7 /usr/share/tomcat7`

**Comment by takezoe** [comment]
@maans88 Problem has been solved?

**Comment by takezoe** [comment]
Out of date

**Comment by McFoggy** [comment]
by changing the way gitbucket is logging by default (setup a dedicated [log configuration](https://github.com/gitbucket/gitbucket/wiki/Tracing-and-logging)) then you should be able to log into `/var/lib/tomcat7`
