### ISSUE TITLE
4.6: Error messages are hard to read (... a very minor issue)

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1357]
## Issue
**Impacted version**: 4.6 and probably all recent versions

**Deployment mode**: standalone webapp behind an apache rev proxy

**Problem description**:

I enter a "funny url" within the address bar, for example ".../gitbucket/does-not-exist" or ".../gitbucket/heinz/becker". I expect an error message to show up.

The error messages shows up, but it is pretty hard to read:

![auswahl_036](https://cloud.githubusercontent.com/assets/1677414/20646628/31a4f320-b47e-11e6-85d3-1657e7a939bc.png)

**Comment by takezoe** [comment]
Fixed as following:

![2016-12-04 13 32 01](https://cloud.githubusercontent.com/assets/1094760/20864109/210ed0e6-ba26-11e6-96a1-851e77e4a46b.png)

**Comment by uli-heller** [comment]
Thanks a lot, looks great now!
