### ISSUE TITLE
Recent Commits Not Showing On Home Page

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1361]
Noted initially when we upgraded to 4.6.  Was told to wait for 4.7.  Still seeing in 4.7.1:

Recent commits are not showing up on the default gitbucket page, but older ones are.  Problem seems to be variable and not isolated to a particular user or use pattern.

**Comment by takezoe** [comment]
@tundratim Unshown commits were pushed in 4.6? These commits are not shown on the timeline even if upgraded to GitBucket 4.7 because they are recorded at the pushing time.

Newly pushed commits in 4.7, they should be shown.
