### ISSUE TITLE
Sbt errors compiling the project

### ISSUE THREAD

**Issue by masterwto** [gitbucket/gitbucket#1362]
I cloned the source code and installed jdk8 and sbt. I tried to compile the project:
sbt compile
A large quantity of jars were then downloaded. When everything got ready, I got some errors: program packages are not found.
My os is windows.
Will you please correct the dependencies, or may you please pack the ivy & sbt folder ? Scala is new to me. It's really confusing.

**Comment by McFoggy** [comment]
please use the chat room for this kind of problem: https://gitter.im/gitbucket/gitbucket
and post there a bit of the error messages you have ; especially which packages are not found.
Thanks for your understanding.

**Comment by McFoggy** [comment]
I just tested on windows with latest master: `sbt.bat package`

```
D:\dev\projects\oss\gitbucket\gitbucket-app>sbt.bat package | tee build.log

D:\dev\projects\oss\gitbucket\gitbucket-app>set SCRIPT_DIR=D:\dev\projects\oss\gitbucket\gitbucket-app\

D:\dev\projects\oss\gitbucket\gitbucket-app>java  -Dsbt.log.noformat=true -XX:+CMSClassUnloadingEnabled -Xmx512M -Xss2M -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -jar "D:\dev\projects\oss\gitbucket\gitbucket-app\\sbt-launch-0.13.12.jar" package
Listening for transport dt_socket at address: 5005
Getting org.scala-sbt sbt 0.13.12 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.12/jars/sbt.jar ...
        [SUCCESSFUL ] org.scala-sbt#sbt;0.13.12!sbt.jar (1957ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar ...
        [SUCCESSFUL ] org.scala-sbt#main;0.13.12!main.jar (5087ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.12/jars/compiler-interface.jar

....

[info] Done packaging.
[info] Packaging D:\dev\projects\oss\gitbucket\gitbucket-app\target\scala-2.11\gitbucket_2.11-4.7.1.war [info] Done packaging.
[success] Total time: 99 s, completed 1 déc. 2016 17:32:59
```

[build.zip](https://github.com/gitbucket/gitbucket/files/625276/build.zip)

**Comment by masterwto** [comment]
It's OK now. Thank you very much.
I'm tring to translate the pages for deploying in a stand-alone network.


在 2016-12-2 1:06, Matthieu Brouillard 写道:
