### ISSUE TITLE
Cannot push to protected branches

### ISSUE THREAD

**Issue by ArloL** [gitbucket/gitbucket#1367]
## Issue
**Impacted version**: 4.6 & 4.7.1

**Deployment mode**: standalone app

**Problem description**:

Steps to reproduce:
* Create repository
* git clone repository
* Commit a change
* git push origin master (works as expected)
* Protect master branch
* Commit a change
* git push origin master <- Fails

Expected behavior: Commits are pushed to remote branch

Actual behavior: Push is blocked

Error message: Cannot force-push to a protected branch.

Editing files directly in the UI works as expected.

**Comment by McFoggy** [comment]
@ArloL reading more carefully the github definition of "branch protection": https://help.github.com/articles/about-protected-branches/ it looks like gitbucket reacts more or less as defined by the guide except for the last point _Can't be edited or have files uploaded to it from the web_ which is possible in gitbucket.

@takezoe & others: what is your opinion on this behavior?

**Comment by ArloL** [comment]
> Can't have changes merged into it until required status checks pass

Since we don't have any required status checks, I would expect it to work. My main concerns are the first protections 1 and 2.

At the moment I can't understand protection 5. It should be disabled only if there are required status checks or required reviews.

**Comment by McFoggy** [comment]
> At the moment I can't understand protection 5

I agree, for me also pushing a commit fast forward from my clone or editing via web is the exact same.
So basically the question becomes: do we want "branch protection" to allow non force commits?
If yes, then it is a bug, if not a feature.

Let's wait a little bit that our Japan colleagues give their opinion.

**Comment by ArloL** [comment]
I have just tested the behavior on one of my GitHub repositories. I can push a fast-forward to a protected branch without status checks.

**Comment by takezoe** [comment]
Probably it's just a bug of protection logic. I think it should be fixed.
