### ISSUE TITLE
Search for repository names

### ISSUE THREAD

**Issue by meltzow** [gitbucket/gitbucket#1370]
this is a feature. 
We have a lot of repositories. It will be great if we can search for repository names. Just the names, not any content inside the repositories (I know this is not easy)
thx

**Comment by takezoe** [comment]
Added following 2 features for looking for repositories:

1. Filter repositories on the sidebar
![Sidebar filter](https://cloud.githubusercontent.com/assets/1094760/21287989/1639cb90-c4bb-11e6-8173-67073a24e47e.png)

2. Search repository by name on the header of the dashboard:
![Search repository by name](https://cloud.githubusercontent.com/assets/1094760/21287991/2fbcbe24-c4bb-11e6-974a-1fc967ea090d.png)

**Comment by meltzow** [comment]
great!! thx

**Comment by Starkmann** [comment]
Thanks for the fast work, really needed that.
