### ISSUE TITLE
Error when editing a comment on commit

### ISSUE THREAD

**Issue by elion** [gitbucket/gitbucket#1372]
## Issue
**Impacted version**: Encountered with 4.5 and 4.7.1. Probably affected versions: x.x - 4.7.1
**Deployment mode**: Standalone app
**Environment**: 
Linux CentOS-72-64-minimal 3.10.0-327.36.1.el7.x86_64
Raid1
Write cache off
java version "1.8.0_73" Java(TM) SE Runtime Environment (build 1.8.0_73-b02) Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Problem description**:
I was editing a comment I added to a commit. I pressed 'Update Comment' and edited it again and pressed 'Update Comment'.
 
![pic](https://cloud.githubusercontent.com/assets/22718104/21056335/d7d23dde-be3d-11e6-9b5c-11f6cba0389c.png)

Then Gitbucket crashed and started return error 500 for every request: 

```
Server Error
Caused by:
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.. 
```

The process stayed alive and I had to stop it by Linux kill command.

To reproduce:
- comment on a commit
- edit the comment and save it repeatedly without pause between actions
- Gitbucket crashes

Log excerpt:
```
...
18:04:58.483 [qtp1528902577-15] WARN  o.e.j.i.storage.file.ObjectDirectory - Pack file /home/gitbucket/repositories/root/my_repo.git/objects/pack/pack-bba0b5d2e2234655551d40ac643292fd4f1a5acb.pack was deleted, removing it from pack list
18:04:58.483 [qtp1528902577-14] ERROR o.e.j.i.storage.file.ObjectDirectory - ERROR: Exception caught while accessing pack file /home/gitbucket/repositories/root/my_repo.git/objects/pack/pack-6530a195e9672a71c909f1ef88941a8558f3705f.pack, the pack file might be corrupt
java.io.IOException: Unreadable pack index: /home/gitbucket/repositories/root/my_repo.git/objects/pack/pack-6530a195e9672a71c909f1ef88941a8558f3705f.idx
	at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:100)
	at org.eclipse.jgit.internal.storage.file.PackFile.idx(PackFile.java:171)
	at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:262)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:417)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:386)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:378)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:142)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:226)
...
```

**Comment by takezoe** [comment]
Hmm... Your repository might be broken. Maybe you can recover by removing a corrupted pack file:
https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#recovering-from-repository-corruption

**Comment by elion** [comment]
After the restart Gitbucket worked fine, I did not need to do anything special. The problem is the crash.
Can somebody reproduce the problem?

**Comment by takezoe** [comment]
Close outdated questions.
