### ISSUE TITLE
take 5 seconds to load rep at chrome

### ISSUE THREAD

**Issue by raindylong** [gitbucket/gitbucket#1375]
![take5second](https://cloud.githubusercontent.com/assets/1438526/21094953/4c76605e-c094-11e6-8942-f1ebe47ec323.png)

(1) the raw rep size is > 500M
~/.gitbucket/repositories/raindy$ du -h -s godns.git
532M    godns.git

(2) it takes >5s to open this rep at chrome , pls check the attach file

(3)the java progress is ocurried 100% cpu when load rep at chrome , the java version is 1.8.0_72
~/.gitbucket/repositories/raindy$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

(4) test version 4.0~4.71 , same status 

Thanks a lot .

**Comment by takezoe** [comment]
@raindylong It has to walk commits and trees to collect file list information. I expect this walking is slow for the large repository. I tried to cache commits and trees in #1377. Could you try this `cache-commits` branch?

**Comment by raindylong** [comment]
Got it , thanks a lot .

**Comment by takezoe** [comment]
@raindylong Note that `cache-commits` branch is still under development, so it contains some issues. However if it improves performance in your situation, I would like to complete it and merge in the next release.

**Comment by raindylong** [comment]
@takezoe  Clear , so we wait for the 4.8 release & check the large repository again , thanks .

**Comment by takezoe** [comment]
@raindylong I hope to confirm whether this fix improves performance in your case before 4.8 release. If I upload a built war file to someplace, could you test it?

**Comment by raindylong** [comment]
@takezoe , I am happy to do the test , just send me the war file URL , :)

**Comment by raindylong** [comment]
@takezoe , would you send me the download link of cache-commits version ? Thanks .

**Comment by takezoe** [comment]
@raindylong Yes, please wait a moment.

**Comment by takezoe** [comment]
@raindylong I sent the download link to you on the gitter. Check it.

**Comment by Jookia** [comment]
Bumping this issue as I'm encountering it with a git repository of buildroot. Stubbing out getLastModifiedCommit and findLastCommits work around the issue but kind of defeat the purpose of having a web Git UI.

**Comment by SIkebe** [comment]
Close this one since #2466 improved performance on a large repository. Please file an new issue if there is a problem.
