### ISSUE TITLE
h:m:s render to hⓂ️s. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [gitbucket/gitbucket#1378]
## Issue

**Impacted version**: 4.7.1

When I write code block like the following,  on comment, snippets  and so on 

It renders to hⓂ️s. 

```
h:m:s
```

It would better to render like `h:m:s`.

![sample](https://cloud.githubusercontent.com/assets/767650/21128775/eea21fce-c140-11e6-967b-c77e81a79d84.png)

**Comment by takezoe** [comment]
Test h:m:s

**Comment by takezoe** [comment]
Oh, It's rendered as emoji on GitHub as well 😮

**Comment by hiroyuki-sato** [comment]
|| github|gitbucket|
|--|-------|---------|
in code block| `h:m:s`|h:m:s <-- this|
out clode block|h:m:s|h:m:s|

This issue about `in code block` "```" .

**Comment by takezoe** [comment]
Thanks, I understand now.
