### ISSUE TITLE
--prefix requires forward slash, not necessarily obvious

### ISSUE THREAD

**Issue by JVimes** [gitbucket/gitbucket#1379]
## Issue
**Impacted version**: 4.7.1

**Deployment mode**: `java -jar gitbucket.war --port=80 --prefix=/gitbucket --host=myComputerName`

**Problem description**:
The `--prefix` command line argument requires a preceding forward slash, which wasn't obvious to me. Might add that to the readme or made GitBucket handle context path without the slash in the argument.

**Comment by uli-heller** [comment]
Do you really mean `--path` or are you referring to `--prefix` ?

**Comment by JVimes** [comment]
Oops! You're right. Fixed 😅
