### ISSUE TITLE
Username is case sensitive, confuses users signing in

### ISSUE THREAD

**Issue by JVimes** [gitbucket/gitbucket#1380]
## Issue
**Impacted version**: 4.7.1

**Deployment mode**: `java -jar gitbucket.war --port=80 --prefix=/gitbucket --host=myComputerName`

**Problem description**:

The username is case sensitive in the sign-in form, which users don't expect ("why isn't my login working, I typed my password right"). Suggest making usernames not be case sensitive.

**Comment by ritschwumm** [comment]
this is probably more difficult to get right than you think. case folding is quite different from locale to locale - so which would you choose? e.g. how would you explain to your users that their user name might be turkish, but which letters are considered "the same" is calculated according to the rules of the finish language?

**Comment by JVimes** [comment]
Probably :) But GitHub does it. Maybe they limit the characters allowed? Every standard library has ToLower() or case-insensitive compare. If those aren't good, why not side-step the issue by allowing email+password login?

**Comment by aadrian** [comment]
>  But GitHub does it.

GitBucket also allow to connect to an LDAP,  and that complicates stuff since ```user``` and ```password``` must be forwared as they are otherwise many LDAP systems won't work.

**Comment by takezoe** [comment]
Closing old questions.
