### ISSUE TITLE
Where is the user/pass to try out the demo?

### ISSUE THREAD

**Issue by renannprado** [gitbucket/gitbucket#1382]
I just found out about this project and would like to play a little bit with the demo `https://gitbucket.herokuapp.com/`, but I can't login.
Could you guys provide a test login?

**Comment by xuwei-k** [comment]
user: root
password: root

please use [gitter](https://gitter.im/gitbucket/gitbucket) for question.

**Comment by renannprado** [comment]
Don't you think it should be in the readme or in the website?
Thanks, will do it next time.

**Comment by McFoggy** [comment]
The only page where the demo is mentioned is on our [wiki FAQ page](https://github.com/gitbucket/gitbucket/wiki/FAQ).
There the default user/pass is mentioned. I juts move the corresponding paragraph a bit up in the page so that is more visible.
