### ISSUE TITLE
failed to deploy gitbucket.war on wildfly 10.1

### ISSUE THREAD

**Issue by rsoika** [gitbucket/gitbucket#1384]
## Issue
**Impacted version**: 4.7.1

**Deployment mode**: 
I try to deploy gitbucket.war on Wildfly 10.1.0-final.
**Problem description**:
I see the following errors in log file during deployment:

`2016-12-17 13:25:53,706 WARN  [org.jboss.modules] (ServerService Thread Pool -- 81) Failed to define class liquibase.serializer.core.yaml.YamlSerializer$LiquibaseRepresenter in Module "deployment.gitbucket.war:main" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link liquibase/serializer/core/yaml/YamlSerializer$LiquibaseRepresenter (Module "deployment.gitbucket.war:main" from Service Module Loader): org/yaml/snakeyaml/representer/Representer
...
2016-12-17 13:25:53,713 WARN  [org.jboss.modules] (ServerService Thread Pool -- 81) Failed to define class liquibase.serializer.core.yaml.YamlSnapshotSerializer$SnapshotLiquibaseRepresenter in Module "deployment.gitbucket.war:main" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link liquibase/serializer/core/yaml/YamlSnapshotSerializer$SnapshotLiquibaseRepresenter (Module "deployment.gitbucket.war:main" from Service Module Loader): Failed to link liquibase/serializer/core/yaml/YamlSerializer$LiquibaseRepresenter (Module "deployment.gitbucket.war:main" from Service Module Loader): org/yaml/snakeyaml/representer/Representer
`

Finally the application is deployed, but I am unable to login . I got the message

`java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/ssl/Provider`

Is there anything I need to install/deploy first on wildfly? Running in standalone modus works.

**Comment by ritschwumm** [comment]
maybe related to http://stackoverflow.com/questions/13160829/legacy-java-code-use-of-com-sun-net-ssl-internal-ssl-provider ?

**Comment by emag** [comment]
You need to add jboss-deployment-structure.xml into WEB-INF.

See https://github.com/gitbucket/gitbucket/wiki/Deployment-to-JEE-and-Servlet-containers#jboss-7x-wildfly-8x

**Comment by emag** [comment]
I'm not sure the WARN log for NoClassDefFoundError about snakeyaml will cause any critical errors, WildFly will not complain about it by adding the following jboss-deployment-structure.xml.

``` xml
<jboss-deployment-structure>
  <deployment>
    <dependencies>
      <system export="true">
        <paths>
          <path name="com/sun/net/ssl/internal/ssl" />
          <path name="com/sun/net/ssl" />
        </paths>
      </system>
      <!-- add snakeyaml dependency -->
      <module name="org.yaml.snakeyaml"/>
    </dependencies>
  </deployment>
</jboss-deployment-structure>
```

**Comment by rsoika** [comment]
thanks - yes this works. I tested with wildfly 9 and with version 10.1

Why not adding this file general into the project?

**Comment by McFoggy** [comment]
@rsoika probably because we cannot include workarounds for every existing servlet container and their classloader policies. Including wildfly specific files would mean that we support out of the box this platform and that we test on it for every release. We are far from having such testing capacity I guess.  
  
Can you please update the wiki entry on this topic with your trials with wildfly 9 &10? thanks.

**Comment by rsoika** [comment]
I have updated the wiki page.
Also I have developed a install script for linux which can be used to install gitbucket into a wildfly server:

https://gist.github.com/rsoika/2d8bab41b18b9fb133c425277c655af7

**Comment by McFoggy** [comment]
Thanks for the contribution. May I suggest you to simplify the creation of the `jboss-deployment-structure.xml` file by using a `cat > jboss-deployment-structure.xml << EOF` syntax ; it is far more readable/maintainable than the `echo` one.  
For an example you can have a look at the install script of one project of mine [jgitver-maven-plugin install script](https://github.com/jgitver/jgitver-maven-plugin/blob/master/src/doc/scripts/install.sh#L25-L33).
