### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by sandys** [gitbucket/gitbucket#1387]
This is a request that you add the line
"you can simply run it using `java -jar gitbucket.war`  or deploy it to the Servlet 3.0 container such as Tomcat 7.x, Jetty 8.x, GlassFish 3.x or higher."

you dont make it obvious on how easy it is to run gitbucket!

**Comment by takezoe** [comment]
@sandys Is current guidance too complex?
```
1. Download latest gitbucket.war from the release page.
2. Deploy it to the Servlet 3.0 container such as Tomcat 7.x, Jetty 8.x, GlassFish 3.x or higher.
3. Access http://[hostname]:[port]/gitbucket/ using your web browser and logged-in with root / root.
```

**Comment by sandys** [comment]
I'm requesting you to add an additional line saying that it can be simply
run using "Java -jar gutbucket.war".

A lot of developers from the Java world assume that people who are going to
use your application will actually know what "Servlet 3.0" container is .
Most probably they will not.

So why not make it easy for first timer who comes to just download the war
and get started in one line. Later if he decides to go full production, he
can reserch which container etc.




On Dec 25, 2016 08:13, "Naoki Takezoe" <notifications@github.com> wrote:

@sandys <https://github.com/sandys> Is current guidance too complex?

1. Download latest gitbucket.war from the release page.
2. Deploy it to the Servlet 3.0 container such as Tomcat 7.x, Jetty
8.x, GlassFish 3.x or higher.
3. Access http://[hostname]:[port]/gitbucket/ using your web browser
and logged-in with root / root.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitbucket/gitbucket/issues/1387#issuecomment-269107956>,
or mute the thread

**Comment by takezoe** [comment]
@sandys Thanks. I updated README: https://github.com/gitbucket/gitbucket/commit/7f7c55aeeee6fea1239641b14bc85b6b86e16888. How do you feel it?

**Comment by sandys** [comment]
excellent.

just one spelling mistake correction

Of cource, you can also deploy gitbucket.war to the servlet container which
supports Servlet 3.0.

Of *course*, you can also deploy gitbucket.war to the servlet container
which supports Servlet 3.0 (like Jetty, Tomcat, JBoss, etc)

just a suggestion !

also - if I may suggest this to you, you should post gitbucket on
ProductHunt to get more visibility!

**Comment by takezoe** [comment]
Oops.

**Comment by takezoe** [comment]
@sandys Fixed in https://github.com/gitbucket/gitbucket/commit/7608a41f9ca90b3ae24027f0b863d7b8be5837c7. Thanks for your suggestion :-)
