### ISSUE TITLE
Attaching to wiki pages doesn't work

### ISSUE THREAD

**Issue by kmarukawa** [gitbucket/gitbucket#1390]
## Issue
**Impacted version**: 4.8

**Deployment mode**: using gitbucket with tomcat.

**Problem description**:
- Attaching to wiki page doesn't work.  I've tested jpg image and pptx files.
- wiki page tries to attach files, but responds "Uploading your files... Server responded with 400 code"
- Attaching to issue page works great.  Only wiki page doesn't.

**Comment by tux93** [comment]
I can confirm this issue

**Comment by takezoe** [comment]
I can't reproduce in 4.9. Could you try on [the demo site](https://gitbucket.herokuapp.com/) again?

**Comment by kmarukawa** [comment]
@takezoe It's not possible to reproduce the problem on the demo site for me too.

Does 4.9 fix it?  I'm using 4.8 and it still have the problem.  I'll upgrade it to 4.9 and post the results later.

**Comment by tux93** [comment]
On the demo site does work, on my install of 4.9 it still doesn't

My Install is running it with OpenJDK 1.8 and an Apache reverse proxy

**Comment by kmarukawa** [comment]
@tux93 Nice catch!  4.8 works fine as root, but doesn't for a regular user.

**Comment by takezoe** [comment]
Oh I see! Thanks for information. I will try to fix in the next release.
