### ISSUE TITLE
CONTRIBUTING.md: ...reproduce GitHub behavior?

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1392]
```
...
First priority of GitBucket is easy installation and reproduce GitHub behavior, so we might reject if your request is against it.
```

Is reproducing GitHub behavior a first prio, still?

The UI of Gitbucket diverged from GitHub significally since the last couple of versions, so prios might have changed...

**Comment by takezoe** [comment]
Removed: https://github.com/gitbucket/gitbucket/commit/5f4580399b051ae785b9f88a62e0cc74fec47301
