### ISSUE TITLE
how to drop repository?

### ISSUE THREAD

**Issue by robin0909** [gitbucket/gitbucket#1394]
### how to drop repository?

I find i can not drop repository.

**Comment by takezoe** [comment]
Settings -> Danger Zone -> Delete this repository
![dangerzone](https://cloud.githubusercontent.com/assets/1094760/21547710/1229b8e8-ce2b-11e6-9556-8e97edb6455b.png)

Please post questions like this to [the gitter room](https://gitter.im/gitbucket/gitbucket), not here. Read [the contribution guide](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md) at first.
