### ISSUE TITLE
Download ZIP function does not consider .gitattributes crlf configulation

### ISSUE THREAD

**Issue by split-n** [gitbucket/gitbucket#1397]
## Issue

**Impacted version**: 4.7.1

**Deployment mode**:  builtin jetty server on CentOS 7

**Problem description**:
In [this](http://stackoverflow.com/questions/17347611/downloading-a-zip-from-github-removes-newlines-from-text-files/17371220#17371220) answer says, if I set `eol=crlf` in `.gitattributes`, `git archive` command outputs CRLF line endings file. GitHub Download ZIP button too.

I tested with [this branch](https://github.com/split-n/nl-test/tree/attr-text-crlf) .

If I get zip file from GitHub Download ZIP button or clone and `git archive` command, the README.md line endings is CRLF.  
But the ZIP that from GitBucket Download ZIP button, the README.md line endings is LF.

**Comment by uli-heller** [comment]
I guess this might be an issue of JGIT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=342372

**Comment by split-n** [comment]
I checked with GitBucket 4.9 and It seems that it is not fixed.

**Comment by aadrian** [comment]
> I checked with GitBucket 4.9 and It seems that it is not fixed.

Because JGit still hasn't fixed this issue.

**Comment by kounoike** [comment]
In #2014, I replaced JGit archiver to scratch archiver. So, we have a chance to fix this issue. I will try it later.

**Comment by fearedbliss** [comment]
I've also been experiencing the same issue for many months (I thought it was something I did wrong). If I do a git clone, everything comes back to me fine, however if I click the "Download ZIP" button on github, all my files are LF (When I explicitly stated I want all files to be CRLF in gitattributes). So git clone is obeying me but not the Download ZIP functionality.
