### ISSUE TITLE
Cannot send emails with STARTTLS

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket#1410]
Hi,

Office 365 SMTP requires STARTTLS instead of SSL for sending emails. There's no option to enable that in the GitBucket admin panel.

For Jenkins the workaround was adding

~~~
JAVA_OPTS="-Dmail.smtp.starttls.enable=true"
~~~

But here adding that to the Tomcat (in which I run GitBucket) config won't fix the problem. There's no related information in the logs. All the website says is:

> [Error] org.apache.commons.mail.EmailException: sending the email to the following server failed : smtp.office365.com:587

I can't find any related log whatsoever. Tried to run GitBucket in standalone mode with
~~~
java -Dlogback.configurationFile=/opt/gitbucket/config/logback-settings.xml -jar gitbucket.war
~~~

But the mentioned logfiles under `/opt/gitbucket/log` are not created and STDOUT doesn't produce any useful information either.

I tried to patch Notifier.scala with:

~~~
email.setStartTLSEnabled(true)
email.setStartTLSRequired(true)
~~~

But it didn't fix the problem. Additionally, when I try to run my own .war file in standalone mode, it says

~~~
Error: Could not find or load main class JettyLauncher
~~~

So I'm pretty much out of ideas. Did anyone have luck figuring this out?

**Comment by McFoggy** [comment]
@bviktor  are you able to provide a small example/sample app able to send an email  using starttls and a description on how to test? starting from there we'll be probably able to help and find a solution.

**Comment by bviktor** [comment]
Actually, I figured it out. The problem was Tomcat, by default, won't re-extract gitbucket.war, even if it's been updated. I had to manually delete the `gitbucket` and `ROOT` folders, then it started working. PR opened.

**Comment by bviktor** [comment]
Closing this issue as requested in the PR guidelines.

**Comment by McFoggy** [comment]
@bviktor I read again the guidelines (that I wrote initially I guess) because I didn't understood upfront why you closed the issue directly. Closing the issue should be done with the PR commit message so that the issue get closed when the PR is merged.

Can you please amend your commit to add something like `..., fix #1410`

**Comment by bviktor** [comment]
Actually, the commit's 2nd line is "Fixes #1410" isn't that sufficient?

**Comment by McFoggy** [comment]
It should indeed (verified here McFoggy/jira-example-project#1).

It's perhaps a bad habit of mine, but as github, like many tools or default configuration of CLI git log, show only the first line of the commit message I am used to put those _close/fix_ instructions o the first line too.

**Comment by bviktor** [comment]
Alright, should it be at the beginning or at the end of the 1st line?

**Comment by bviktor** [comment]
Also, is it "Fix", or "Fixes" will work as well?

**Comment by McFoggy** [comment]
@bviktor for closing issues on github see [closing-issues-via-commit-messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

As I previously told you github supports the _closing sentence_ to be anywhere in the whole GIT commit message. I was personnaly not aware of that until I tested  it just before.
Currently we have no rule for gitbucket on how to define good commit messages.

**Comment by bviktor** [comment]
Thanks, @McFoggy !
