### ISSUE TITLE
Linkable Line Numbers?

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1417]
We've just upgraded to 4.8 and noticed that line numbers are no longer linkable - i.e, They do not update the URL to take you right to the line number in question.

This may have happened prior to 4.8, but we just noticed it.

Is there some setting or config option we need to know about or is this a bug?

**Comment by takezoe** [comment]
@tundratim Thanks for your reporting. Maybe it's a bug. It will be fixed in 4.9.
