### ISSUE TITLE
when i change group, error occured

### ISSUE THREAD

**Issue by o-matsuo** [gitbucket/gitbucket#1427]
i create new group. -> group1
i create new repository. -> repo1

i create new group -> group2

i try to change group1/repo1 -> group2/repo1
but error occured.

**Comment by nazoking** [comment]
umm.. I try now it on demo site. ( http://gitbucket.herokuapp.com/ )
and do not occur error.

can you teach it
gitbucket version, using plugins, database (mysql, postgresql, h2 )
and StackTrace if you can.

**Comment by nazoking** [comment]
and if you can, please upgrade to version 4.8.

**Comment by o-matsuo** [comment]
ok. i try it.
thank you.

**Comment by o-matsuo** [comment]
it,s ok . thank you
