### ISSUE TITLE
New repositories require master branch

### ISSUE THREAD

**Issue by zy4** [gitbucket/gitbucket#1431]
When I create a new empty repository, I can't `git push -u origin test` when there is no master branch. Somehow the repository remains empty.
So it seems to be required that the default branch has the name __master__. This is not useful for cases where I want to supply only a certain branch without merging it into my local master branch without c&p my local stuff and reinitialize git.

**Comment by takezoe** [comment]
@zy4 As a workaround, you can change a default branch at the repository setting after pushing `test` branch. Then your code will be shown in the repository viewer.

Essentially, a first pushed branch should be set as a default branch. I will fix that way, so please keep this issue open.
