### ISSUE TITLE
Problems on Deploying GitBucket with Nginx proxy_pass

### ISSUE THREAD

**Issue by thomas2d19** [gitbucket/gitbucket#1435]
**Impacted version**: 4.8

**Deployment mode**: Tomcat 7; JDK 8 update 111; ARMv7 Linux; Nginx Proxy

**Problem description**:
I used GitBucket for a long time, and it is a good Git web interface for ARMv7 CPU.  
I'm currently using Nginx proxy to pass the port `80/443` to the Tomcat port `7070`.
```nginx
server {
    ...
    server_name mydomain.com;
    location /gitbucket/ {
        proxy_pass http://127.0.0.1:7070/gitbucket/;
    }
}
```
gitbucket.conf:
```
base_url=https\://mydomain.com/gitbucket
```
The above Nginx server configuration works fine for me to access GitBucket through `mydomain.com/gitbucket/`.    

However when I change the domain to `gitbucket.mydomain.com/` for the GitBucket, It **don't let me login** even password is correct:  
```nginx
server {
    ...
    server_name gitbucket.mydomain.com;
    location / {
        proxy_pass http://127.0.0.1:7070/gitbucket/;
    }
}
```
And the **gitbucket.conf**:
```
base_url=https\://gitbucket.mydomain.com
```
I changed back using `mydomain.com/gitbucket` afterwards, and I can login normally! Can anyone help?

**Comment by officer** [comment]
same issue was reported already.
 
 https://github.com/gitbucket/gitbucket/issues/889

try this.

proxy_cookie_path /gitbucket/ /;

**Comment by thomas2d19** [comment]
Good work! Problem solved!

Thanks, @officer !
