### ISSUE TITLE
Search repository box on login page

### ISSUE THREAD

**Issue by moonwolf-github** [gitbucket/gitbucket#1443]
## Issue
**Impacted version**: 4.9.0

**Deployment mode**: *standalone*

**Problem description**:
On login page there is "search repository" box present. It's useless there as user is not logged in yet.

**Comment by takezoe** [comment]
If user is not logged in, you can search public repositories by the search repository box. I don't think it's not useful.

**Comment by moonwolf-github** [comment]
Ah, right. Completely forgot about this as we require users to log in. Sorry about that.
