### ISSUE TITLE
LFS files not being stored on the gitbucket server

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1450]
## Issue
**Impacted version**: 4.9

**Deployment mode**: Tomcat 7

**Problem description**:
Have just installed 4.9 so that I can test out the LFS support. When uploading an LFS tracked file, I see the LFS symbol, but the file is not available in the gitbucket GUI:

![image](https://cloud.githubusercontent.com/assets/20796832/22698577/3626ee34-ed55-11e6-879e-041c9f457a28.png)

and checking the server, there is no "lfs" folder created in the repository folder:

![image](https://cloud.githubusercontent.com/assets/20796832/22698677/81591d00-ed55-11e6-8d3b-62c6d3c4b4e5.png)

I had the same problem with a "bmp" image file as well.

**Comment by takezoe** [comment]
@PaulAdams-Conti Is your situation same as #1439?

**Comment by PaulAdams-Conti** [comment]
Yes, I checked the logs and it is the same. Thanks for the info. 
Sorry I hadn't found that issue when I searched for "lfs", as I was searching open issues. You were too quick at solving the problem :-)
