### ISSUE TITLE
Add plugins to main codebase for a more complete solution 

### ISSUE THREAD

**Issue by sandys** [gitbucket/gitbucket#1451]
we really love the gitbucket project.  For a lot of first tine users, they only see announcement for gitbucket and dont even realize there is a plugin system for additional functionality. 

you guys have brilliant pieces of functionality like gist, pages.. even the h2 tool to migrate from older versions. 

It is important for end users that you package them together and give them a complete solution. It will be a huge and massive benefit to first time users of gitbucket that they get so much functionality in out-of-the-box install.

**Comment by takezoe** [comment]
Thanks for your opinion.

> For a lot of first tine users, they only see announcement for gitbucket and dont even realize there is a plugin system for additional functionality.

Hmm... I'm sad. 😢 

Isolating codebase of plugins is a solution to keep core slim, so we don't wont to merge them to core. Instead, do you think a more easily way to install plugins (e.g. the console that makes possible to install plugins online) is worth?

**Comment by McFoggy** [comment]
> Instead, do you think a more easily way to install plugins (e.g. the console that makes possible to install plugins online) is worth?

definitively I would vote for such a discovery system with an auto install feature (a bit like Jenkins for example)

Just an idea but to make it easy we could already benefit from the existence of [gitbucket-plugins](http://gitbucket-plugins.github.io/) to host/deliver a parse-able list of plugins.

Then depending on the effort we want to spend there we could:
- just have to expose a workflow to plugin maintainers to update this parse-able list
- and/or implement something to fetch github API to find releases of plugins 
- ...

**Comment by sandys** [comment]
@takezoe 
gitbucket-gist-plugin is 200kb
gitbucket-emoji-plugin is 4mb
gitbucket-pages-plugin is 30kb

you are taking a few mb here and there. 

Alternatives like gitlab etc have hundreds of mb extra (748mb) 

My humble suggestion is that you are over optimizing. You should not even think about these things for the next 200mb or so and instead focus on delivering users a brilliant out of box experience. You are optimizing things that 99.999% users will not mind.

I will still say that the plugin architecture is brilliant! I see a day when lots of people will write gitbucket plugins. But you should focus on building as much great functionality as possible without worrying about size until you hit 200mb or so!

**Comment by takezoe** [comment]
> you are talking a few mb here and there.

No, plug-in codebase is not always so small even if jar file is small. We don't have enough resource to maintain large codebase, so we have to push plugin system. These plugins are example of practical plugin as well.

We can bundle plug-ins which are developed in the gitbucket organization with gitbucket release, but we don't wont merge their codebase to core. It would be nice if users can enable and disable bundled plug-ins easily.

**Comment by aadrian** [comment]
> We can bundle plug-ins which are developed in the gitbucket organization with gitbucket release, but we don't wont merge their codebase to core. 

+1 . IMO too this is the correct way to do it.

>  It would be nice if users can enable and disable bundled plug-ins easily.

+1

Helpful would be also the ability to easily install new plug-ins by just click-ing a name from a list (for the GitBucket installations that have an internet conenction).

**Comment by sandys** [comment]
On Tue, Feb 14, 2017 at 10:41 PM, aadrian <notifications@github.com> wrote:

> We can bundle plug-ins which are developed in the gitbucket organization
> with gitbucket release, but we don't wont merge their codebase to core.
>
> +1 . IMO too this is the correct way to do it.
>
+1 from me too. But definitely bundle a LOT of plugins. Make Gitbucket
Great Again !

**Comment by aadrian** [comment]
Some plug-ins are already bundled: https://github.com/gitbucket/gitbucket#plugins
They can also be enabled/disabled.

There's also a demo project that includes most of them, so it can be used directly: just clone and `run.sh` : https://github.com/gitbucket-plugins/gitbucket-community.herokuapp.com
