### ISSUE TITLE
Accessing a "standalone deployed" gitbucket from the LAN

### ISSUE THREAD

**Issue by brunogenovese** [gitbucket/gitbucket#1456]
## Issue
**Impacted version**: 4.9

**Deployment mode**: standalone app

**Problem description**:

HOW TO REPRODUCE

- Default deploy server standalone as described in the instructions:   "java -jar gitbucket.war"
- Able to access the server web page as http://localhost:8080
- Attempt to access as http://[hostname].[domain]:8080 will automatically redirect to https://[hostname].[domain]:8080.  It of course fails because 8080 is being used for http, not https.

QUESTIONS

1) Is the "standalone" deployment intended for access from the local LAN?  Or is deploying it inside a web application server like Tomcat the only viable way to use it?

- If the server is intended for use from the local LAN when deployed standalone - meaning that other computers in the network can access it for "Git operations" through the one open port (8080 by default) - is all server management expected to be done from localhost?

2) Is there any more complete documentation somewhere than what is in the wiki at https://github.com/gitbucket/gitbucket/wiki?  That wiki does seems more like a random collection of howtos rather than an attempt at user documentation, which makes me think the real documentation is elsewhere.  Especially useful would be a *complete* list of parameters for when starting the server standalone.

**Comment by uli-heller** [comment]
There is a baseUrl in "System settings".

The answers are "no, no, probably no". I use the standalone deployment for some of my instances. Some of them are running in a data center.

**Comment by brunogenovese** [comment]
I had already tried using that base URL.  When I set it in the form http://hostname.domain:port every call (even those aimed at http://localhost:port) got forwarded to https://hostname.domain:port... effectively killing all administration.  The only solution was to completely delete the home directory and start over.

So, am interpreting uri-heller's answer to mean that the only way to setup a standalone instance o be accessible for the web is to use the war in a normal app server like Tomcat and forget about using the standalone option?

**Comment by ritschwumm** [comment]
maybe a browser plugin like https anywhere?

**Comment by McFoggy** [comment]
@brunogenovese I fear not to have fully understood the issue, can you clarify/rephrase it. Why don't you access the instance using what you have setup in the configuration http://hostname.domain:port? Why accessing it using localhost?

**Comment by brunogenovese** [comment]
Let me try to explain better.  What I am experiencing is very strange for any "server".   It happens even when I start it using the default configuration:

1) I am using the latest released .war.  Version 4.9.

2) I can start the server with:  java -jar gitbucket.war.

3) After starting it I can access the management pages using http://localhost:8080.

4) But if I try to access the management/login/user pages using http://hostname.domain:8080 I see the server doing an automatic redirect to https://hostname.domain:8080.  
- That obviously fails since the server uses 8080 for http, not https.  
- Why in the world would the default configuration do that I haven't got a clue.  Maybe the developers were drunk at the time they designed this, or maybe they want to be secure... but they failed to provide a default https configuration at some other port like 8443, so the defaults... fail.  
- And there is no information whatsoever as to how to setup https in the launching command so that the rerouting works.

5) Once I hit that problem I did not go further.  I don't know whether the server works as a Git server accessible from the LAN even if it does not allow management from any machine other than the one it is running on.  That was one of my questions, does it?  Also, maybe the server "can" be configured properly when launching it standalone so that it can be managed from any machine on the LAN, and that is the other question, is there a way to configure it right?  If so how?

Finally, I know that I could run the server inside of a web application server like tomcat, so that it would respond properly to http and https calls, since those would be handled by tomcat itself.  But that would totally defeat the purpose.  The main reason I was looking at gitbucket was that it advertised itself as a simple war that did it all, nice, compact, lightweight and "in theory" simple.  So, if Tomcat is absolutely required... then combined with the lack of documentation, it frankly isn't worth the trouble as there are many alternatives to choose from out there.

It is a bit frustrating because at least in paper it looked perfect.

**Comment by takezoe** [comment]
@brunogenovese 

> But if I try to access the management/login/user pages using http://hostname.domain:8080 I see the server doing an automatic redirect to https://hostname.domain:8080.

I guess that you have a reverse proxy. GitBucket does not do such redirection.

GitBucket does not support SSL directly in standalone mode. So if you want to enable SSL, you have to put a reverse proxy like Nginx or deploy GitBucket on a servlet container which support SSL.

In addition, When you can't access to the admin console in this situation, you can configure GitBucket without GUI by editing `~/.gitbucket/gitbucket.conf` by hand.

**Comment by brunogenovese** [comment]
takezoe, I most definitely have no proxies at all, and nothing that would do the redirection on my end.  As a matter of fact, there is no redirection on anything else I use.

Maybe it is something about version 4.9?

**Comment by uli-heller** [comment]
Am 20.02.2017 um 13:26 schrieb brunogenovese:
>
> I had already tried using that base URL. When I set it in the form 
> http://hostname.domain:port every call (even those aimed at 
> http://localhost:port) got forwarded to 
> https://hostname.domain:port... effectively killing all 
> administration. The only solution was to completely delete the home 
> directory and start over.
>
> So, am interpreting uri-heller's answer to mean that the only way to 
> setup a standalone instance o be accessible for the web is to use the 
> war in a normal app server like Tomcat and forget about using the 
> standalone option?
>
I don't think so.
* I run the standalone version
* I do not use tomcat
* What I do use is a reverse proxy that handles the https encryption and 
talks to the standalone gitbucket via http
* So from a user's point of view, I'm using https
* From gitbucket's point of view, it gets accessed via http
* ... but the base url is https:/...

Best regards, Uli

**Comment by sjas** [comment]
Find your gitbucket.conf (`updatedb; locate gitbucket.conf` might do.)
I believe it gets generated upon first startup?

In there is a `base_url` parameter set, which should cause your problem.

The generated file take's the systems hostname or something, leading to this behaviour.

(If one of the devs will now tell me that all I said is crap, pardon me, I still just try to figure the deployment myself.)

**Comment by takezoe** [comment]
Closing old questions.
