### ISSUE TITLE
Private project owner cannot access forks.

### ISSUE THREAD

**Issue by kyrahabattoir** [gitbucket/gitbucket#1463]
So I am not sure if it is intented or not but when a collaborator fork a private project, his fork, while visible, cannot actually be accessed by people who have access to the parent.

Shouldn't there be some kind of access granted by the parent project over the forks?

**Comment by takezoe** [comment]
@kyrahabattoir Thanks for your feedback.

> Shouldn't there be some kind of access granted by the parent project over the forks?

Yes, I think so. I would like to add that to a plan of the next release.

**Comment by takezoe** [comment]
In my opinion, copying collaborators from the source repository for the private fork might be solution. (GitHub seems to be doing so.)

**Comment by takezoe** [comment]
Done.
