### ISSUE TITLE
SSH Keys now invalid

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1482]
## Issue
**Impacted version**: 4.10

**Deployment mode**: Tomcat 7

**Problem description**:
I previously set up some SSH keys for my account in V4.9 and everything was working fine. Now since V4.10 my keys were suddenly shown as invalid, so I deleted them and tried adding them again but they can no longer be added as I always get the message "Key is invalid".
I had generated 2 keys, one with ssh-keygen and another with Putty Key Generator as described [here](http://hanxue-it.blogspot.com/2014/06/using-ssh-authentication-wth-gitbucket.html), and both had worked, but before I deleted them, both were marked as invalid.

If I use the test: ssh -p 29418 -vT <myserver> this had previously provided the response described in the link, but now I get the following:
>
debug1: Connecting to myserver [10.216.146.132] port 29418.
debug1: Connection established.
debug1: identity file /C=/Users/uid61121/.ssh/identity type -1
debug1: identity file /C=/Users/uid61121/.ssh/id_rsa type 1
debug1: identity file /C=/Users/uid61121/.ssh/id_dsa type -1
debug1: Remote protocol version 2.0, remote software version SSHD-CORE-1.2.0
debug1: no match: SSHD-CORE-1.2.0
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.2
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5 none
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
Connection closed by 10.216.146.132
>
Any ideas what has gone wrong?

**Comment by PaulAdams-Conti** [comment]
Actually, now I think about it a bit more, I think I set up the keys in 4.10, so it probably has nothing to do with the update from 4.9 to 4.10, so I'm not sure what I am missing.

**Comment by takezoe** [comment]
"Key is invalid" is shown if same key has been registered (even if it has been registered by other user).

**Comment by PaulAdams-Conti** [comment]
Gitbucket crashed this morning (could have been Tomcat that crashed) and after a server restart, I could add the same keys once more.
