### ISSUE TITLE
Development Mode for Plug-ins too!

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1484]
Please add a **Development Mode** for plug-ins too!

There's a development mode for GitBucket itself:  https://github.com/gitbucket/gitbucket/blob/master/doc/how_to_run.md#run-for-development  so that source modification is detected and reloaded automatically, but there's no such a mode for the development of the plug-ins themselves :(.

One possibility might be that when in development mode, e.g. the plug-in sources could be linked from a ```/plugins/``` subdirectory and reloaded the same way it's done now for GitBucket itself. 

Thank you.

**Comment by McFoggy** [comment]
When we will have the install/uninstall/update mechanisms for the plugins, we could perhaps do something  like a hot-reloading of the whole plugin once a change is detected.
Until then, the only possibility to have some enhanced reloading capabilities is to use JRebel/MyRebel for your plugin sources. Take care that this hotreloading will only concern features Gitbucket already knows from your initial plugin deployment (in term of gitbucket extensions I mean).  
JRebel has no gitbucket plugin/extension do replay/redo the gitbucket plugin registration mechanism.

**Comment by takezoe** [comment]
I think the plugin hot-deployment which being considered in #1468 makes possible to offer the development mode for plugin as well. We should consider about that at first.

**Comment by McFoggy** [comment]
@takezoe that's what I was refering to.

**Comment by takezoe** [comment]
@McFoggy Do you have any idea to make that? I had tried OSGi in the past, but I felt it's difficult to integrate with GitBucket plugin system. It may be better to make a trick to swap the classloader that loads plugin jar files.

**Comment by McFoggy** [comment]
In our situation, at least for #1468 as we fully control classloading I would suggest to start easy first with classloading swap as you suggest. By that I mean:
- ask the plugin to unload so that it can cleanup things `Plugin.shutdown` (memory, handles, ...). _[see below (1)]_
- throw away the classloader that loaded the plugin
- recreate a new classloader

[1]: Here perhaps we should think of passing more arguments to express `update`, `removal`, `removal with data` action. When called with `removal with data` the plugin could delete data, cleanup schema, ...

**Comment by aadrian** [comment]
> Here perhaps we should think of passing more arguments to express update, removal, removal with data action. When called with removal with data the plugin could delete data, cleanup schema, ...

+1 .

**Comment by takezoe** [comment]
Agree. I will try to make hot plugin deployment (and undeployment) at first!

**Comment by takezoe** [comment]
One problem is that Scalatra needs to mount controller servlets on bootstrapping. Currently it being done in `ScalatraBootstrap` called on the web application context initialization. Is it possible to mount and unmount servlet dynamically?

**Comment by McFoggy** [comment]
Hum... not sure that we can, using pure `javax.servlet` spec, reach this dynamic behavior. Unregistration of servlet is not allowed from what I know.

I am quite sure we can do something for Jetty ie when running standalone ; but not in a generic way that different servlet container would accept.

**Comment by aadrian** [comment]
> One problem is that Scalatra needs to mount controller servlets on bootstrapping.

So Scalatra controllers are Servlets themselves and not dispatched requests like in a Router or RequestDispatcher implementation http://tutorials.jenkov.com/java-servlets/requestdispatcher.html ?


> Is it possible to mount and unmount servlets dynamically?

I don't think it's possible in a generic way. For Tomcat this seems to work:
https://codedump.io/share/iFRHFQIpUNn2/1/is-it-possible-to-dynamically-register-servlets-from-a-javaagent

by using ```org.apache.catalina.deploy.ServletDef``` , and for every application server there seems to be another non-standard way :( .

**Comment by takezoe** [comment]
As an experiment, I added an adapter filter for plugin controllers. It looks to be working well. Maybe it's possible to mount and unmount plugin controllers in this filter.
https://github.com/gitbucket/gitbucket/pull/1487/commits/c760af7810410d9167098c6902938d942f71366e

**Comment by takezoe** [comment]
Plugin hot deployment (#1487) has been merged. It would make possible to auto reloading development plugins as well. I would like to add a command line option to specify an extra plugins directory which is handled as same as `GITBUCKET_HOME/plugins` to help plugin development.
