### ISSUE TITLE
Can't compile with Java9

### ISSUE THREAD

**Issue by xuwei-k** [gitbucket/gitbucket#1490]
replace [`java.util.Base64`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) ?

```
[error] /home/travis/build/xuwei-k/gitbucket/src/main/scala/gitbucket/core/util/AuthUtil.scala:16: type BASE64Decoder is not a member of package sun.misc
[error]       new String(new sun.misc.BASE64Decoder().decodeBuffer(header.substring(6)))
[error]                               ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

- https://travis-ci.org/xuwei-k/gitbucket/jobs/210258433
- https://github.com/xuwei-k/gitbucket/commit/e55ad2ea5bc89b1967675448d4afdaa02ec86145
- https://github.com/gitbucket/gitbucket/blob/a684fa8a8e09e298ae816e150ac7f1a2c026eca4/src/main/scala/gitbucket/core/util/AuthUtil.scala#L16

**Comment by McFoggy** [comment]
makes sense. :+1:
