### ISSUE TITLE
Update documentation (readme and/or Wiki) with the minimal requirements

### ISSUE THREAD

**Issue by rloutrel** [gitbucket/gitbucket#1494]
## Issue
**Impacted version**: 4.10

**Deployment mode**: not applicable

**Problem description**:
I am considering installing gitbucket on my server, but I am concerned by the minimum hardware requirements (mainly CPU and memory).
It would be helpful to have a small overview of what will be used by the application (I mean are we talking about Octocore+16GB or monocore+500MB)?
This could be interesting to adapt the README (and/or the Wiki) without being as exhausted as [Gitlab](https://docs.gitlab.com/ce/install/requirements.html#hardware-requirements)

**Comment by uli-heller** [comment]
https://gitbucket.github.io/gitbucket-news/gitbucket/2017/03/29/benchmark-of-gitbucket.html

According to the link above, it runs quite well on a RasPi. I guess a pull request could be welcome...
