### ISSUE TITLE
Failing to add new files tracked by LFS when using SSH protocol

### ISSUE THREAD

**Issue by diegohavenstein** [gitbucket/gitbucket#1502]
I have a set of repositories managed from a locally running GitBucket server. The repositories are cloned on the drive using ssh protocol, and I track pdf files (among others) using git lfs.

One thing is not working though. When I add a new file which is tracked (e.g. x.pdf) and commit, during push to remote it will fail with following error message:

[master 02b133e] commit message
 1 file changed, 3 insertions(+)
 create mode 100644 test/x.pdf
diego@diego-T420s ~/Documents/test (master)$ git push
Git LFS: (0 of 1 files) 0 B / 920.54 KB                                                                                                                                       
batch request: exit status 1
error: failed to push some refs to 'ssh://git@localhost:29418/diego/Documents.git'

This won't happen if I clone using HTTP protocol. But there it keeps asking for user name and password, which is annoying (therefore I would prefer to keep using SSH)

Any hints on how to make it work? Where can I find helpful log files produced by GitBucket?
Thx
Diego

**Comment by takezoe** [comment]
@diegohavenstein 

Add following configuration to your local repository and try again:
```
git config --add lfs.url "http://YOUR_GITBUCKET_HOST/git/USER/REPO.git/info/lfs"
```

**Comment by takezoe** [comment]
Close outdated questions.
