### ISSUE TITLE
Integration with intellij tasklist

### ISSUE THREAD

**Issue by fistons** [gitbucket/gitbucket#1508]
## Issue
**Impacted version**: 4.10.0

**Deployment mode**: Deployed using tomcat8, with or without nginx proxy

**Problem description**: With IntelliJ, we can connect to several issue manager
![image](https://cloud.githubusercontent.com/assets/972209/24100343/09b6d316-0d74-11e7-9c3e-367f18e71e9c.png)

When I try to add my own installation of gitbucket as a github one, I have this error message: 
```
Can't get queried issues: Dibox/DIBOX - repo%3ADibox%2FDIBOX+state%3Aopen+null
404 Introuvable - Not Found
```

Also, I can't update issue from IntelliJ.

I'm using:
IntelliJ IDEA 2017.1
Build #IC-171.3780.52, built on March 15, 2017
JRE: 1.8.0_112-release-736-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.3-1-ARCH

**Comment by kounoike** [comment]
@fistons Did you click "Test" button in configure dialog?
"Test" checks to server by search action, but GitBucket doesn't implemented it yet.
If you want to use IntelliJ tasks, you don't click "Test" button and click "OK" button. Then you can use it.

**Comment by aadrian** [comment]
> When I try to add my own installation of gitbucket as a github one, I have this error message:

That's a correct behavior, since **GitBucket** is not GitHub.

IntelliJ specific features should be addressed directly to Jetbrains: https://youtrack.jetbrains.com/issues/IDEA

(nobody asked GitBucket support in IntelliJ yet: https://youtrack.jetbrains.com/issues?q=GitBucket :) )
