### ISSUE TITLE
Migrate from joda-time to java.time

### ISSUE THREAD

**Issue by hrj** [gitbucket/gitbucket#1513]
Joda-time was a great library prior to Java SE 8. But since gitbucket targets Java SE 8 now, it is recommended (by joda authors) to migrate to `java.time` API.

How to migrate: http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

**Comment by alodavi** [comment]
Hi! I would like to help you with this issue :)

**Comment by takezoe** [comment]
@alodavi Great. GitBucket is using joda-time for JSON API interface mainly. Could you send a pull request?
