### ISSUE TITLE
Possible Regression?

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1514]
Just noticed in 4.10 

http://gitbucket ..../user/reponame  -> works

http://gitbucket ..../user/reponame/  -> trailing slash breaks and shows jetty error

**Comment by takezoe** [comment]
This is a know issue and pull request exists #604. However I haven't not merged because I’m not convinced whether this is the best way to fix this issue.

**Comment by tundratim** [comment]
Any further progress on this issue?   It seems not to be fixed in 4.16.0
