### ISSUE TITLE
getting avatars of disabled accounts results in 404 (as of 4.11)

### ISSUE THREAD

**Issue by umq** [gitbucket/gitbucket#1516]
`_unknown/_avatar` returns 404 under GitBucket 4.11
<img width="380" alt="2017-04-01 20 43 48" src="https://cloud.githubusercontent.com/assets/18342/24578492/3d46d94a-171c-11e7-9844-1baea6e18ee2.png">

returning an image is expected (gray-man is okay).

**Comment by aadrian** [comment]
This error happens even if the user had an uploaded image (so it's not just for the auto-generated avatar images)
