### ISSUE TITLE
Rename H2 Database File!

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1519]
Please rename the H2 Database file from ```data.mv``` to something more suggestive like ```gitbucket.mv``` or ```gitbucket-db.mv```

Thank you.

**Comment by t-tsutsumi** [comment]
I think this is the way it should be. However, I don't know whether it makes sense to put the effort to improve this while maintaining backward compatibility.

**Comment by aadrian** [comment]
@t-tsutsumi this should be a trivial change for Solidbase :).

**Comment by t-tsutsumi** [comment]
@aadrian I have no idea how to rename the H2 database file using Solidbase (Liquibase). Do you have any idea?

**Comment by aadrian** [comment]
The whole point of Solid base is to be able to migrate "other resources" too besides what Liquibase itself already can.

Copy from ```data.mv``` to ```gitbucket.mv``` before any connection is established as an initial migration step if the DB hasn't been renamed yet in ```InitializeListener.scala``` ?

**Comment by t-tsutsumi** [comment]
I also saw the `InitializeListener.scala`. Currently in GitBucket, when calling the `Solidbase#migrate`, the DB connection has already been established, so it is necessary to rename before that.

Also, I noticed that users who meet the following conditions may be affected.
* Save the H2 console configuration for GitBucket.
* Backup the H2 database with a proprietary method or gitbucket-h2-backup-plugin.

@takezoe Do you have any opinion on this subject?

[Record] The physical file copy while connecting to the database may be dangerous. https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/servlet/InitializeListener.scala#L68-L72

**Comment by aadrian** [comment]
so it's too complicated :(
