### ISSUE TITLE
nested group

### ISSUE THREAD

**Issue by pinghe** [gitbucket/gitbucket#1527]
Is it possible to support nested group?

~~~~
ncomp/sirius.git
ncomp/sirius/manager.git
~~~~

**Comment by takezoe** [comment]
@pinghe I don't think so. It's impossible (or much difficult at least) in the current GitBucket structure. It might be possible to support teams in group like GitHub.

**Comment by aadrian** [comment]
@pinghe why not just create more groups?
e.g. ncomp_sirius/manager.git

One approach what many use for groups (organizations) is to be uppercase compared to users. This way it's easier to distinct them.
