### ISSUE TITLE
LFS Folder Path is Incorrect

### ISSUE THREAD

**Issue by hillin** [gitbucket/gitbucket#1531]
## Issue
**Impacted version**: 4.11

**Deployment mode**: standalone app

**Problem description**:
The **lfs** folder path is incorrect for lfs-enabled projects.
E.g., for the project _bar_ of owner _foo_, gitbucket attempts to create the lfs folder under `GITBUCKET.HOME/repositories/foo/bar/lfs` while all other files are stored under `GITBUCKET.HOME/repositories/foo/bar.git`. The first path, however, is not created while pushing lfs-handled files. 

**Workaround**:
For now I can create the desired lfs folder by myself, and copy all lfs objects (flattened hierarchy) into that folder manually.

**Comment by takezoe** [comment]
`GITBUCKET.HOME/repositories/foo/bar.git` is a bare repository. GitLFS stores tracked files to the another place. By default of GitBucket, `GITBUCKET.HOME/repositories/foo/bar/lfs` is that place.

**Comment by hillin** [comment]
@takezoe no, `GITBUCKET.HOME/repositories/foo/bar/lfs` is not created unless I do it manually. 

I have gitbucket running in a Windows Server 2016 server. under an administrator account and there shouldn't be file system privilege concerns.

**Comment by takezoe** [comment]
@hillin GitBucket makes sure to create lfs directory before storing files:
https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/servlet/GitLfsTransferServlet.scala#L48

If directory creation failed, it throws IOException and response is not 200 OK. So you should have seen some error in results of git push or GitBucket log.

**Comment by hillin** [comment]
@takezoe thanks for looking into this. I tried to create several new repos and magically they all have the lfs folder created successfully. I must have missed something or there might be a corner case, however I can't remember how I set up those incorrect repos, because it was days ago.

I'll let you know if this happens again.

**Comment by takezoe** [comment]
@hillin You are welcome :-)
Can I close this issue once? When you get a same trouble, reopen this issue or raise a new issue.

**Comment by hillin** [comment]
@takezoe yeah sure, please close it.
