### ISSUE TITLE
Can't clone /owner/repo.git style url by git-2.12.2

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1552]
### Before submitting an issue to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

## Issue
**Impacted version**: current master I checked maybe 4.11 too?

**Deployment mode**: standalone app with listen 80 port.

**Problem description**:
- git clone http://localhost/owner/repo.git can't work with current version of git.

```
C:\Users\kounoike\Documents\gitbucket\t>git --version
git version 2.12.2.windows.2

C:\Users\kounoike\Documents\gitbucket\t>git clone http://localhost/root/JenkinsTest.git
Cloning into 'JenkinsTest'...
fatal: unable to update url base from redirection:
  asked for: http://localhost/root/JenkinsTest.git/info/refs?service=git-upload-pack
   redirect: http://localhost/git/root/JenkinsTest.git/info/refs
```

maybe, redirect isn't accepted by current version of git cli?
It is serious  problem for GitBucket-Jenkins integration.

**Comment by kounoike** [comment]
Meybe this thread is related?
https://www.spinics.net/lists/git/msg290960.html

and in #1363 commented this problem too.But I think this is GitBucket's problem.

**Comment by uli-heller** [comment]
I'm not sure if this is supposed to work.

Collegues of mine used URLs like https://{myhost}/gitbucket/person/repo.git
to clone a repo and it "seemed" to work, i.e. you get a local folder named "repo".

BUT: You cannot "push" afterwards.

The correct url for cloning is https://{myhost}/gitbucket/git/person/repo.git

**Comment by kounoike** [comment]
Sorry, I didn't explain it.
I'm using GitBucket with Jenkins GitHub Organization Folder plugin. It uses GitHub Branch Source Plugin.
But, Branch Source Plugin [in this line](https://github.com/jenkinsci/github-branch-source-plugin/blob/a0c41ec8a7231cb1e095cb721bf394b38cac83ac/src/main/java/org/jenkinsci/plugins/github_branch_source/HttpsRepositoryUriResolver.java#L40) assumes GitHub style fetch url such as `http://server/user/repo.git`. it can't use gitbucket or git prefix.

I know correct url, but I want to run cloning by `http://server/user/repo.git`.

**Comment by tsal** [comment]
I hit this same issue today trying to build out a docker stack.  I can't get the app to build locally, or I'd submit a pull request - basically, I think a route regex for `/org/user/reponame.git` that passes it to the same endpoint as /git/.  If I can get a local build working, I'll submit a PR.

**Comment by kounoike** [comment]
I found root cause. By https://github.com/git/git/blob/6628eb41db5189c0cdfdced6d8697e7c813c5f0f/http.c#L1513-L1517 , git checks original URL and redirected URL by `tail`. In current GitBucket(4.15.0), redirect response drops query string.

```
C:\Users\kounoike\Documents\gitbucket>git  http://localhost:8080/root/test.git
Cloning into 'test'...
fatal: unable to update url base from redirection:
  asked for: http://localhost:8080/root/test.git/info/refs?service=git-upload-pack
   redirect: http://localhost:8080/git/root/test.git/info/refs
```

I add query string, it works correctly. I will send PR.
