### ISSUE TITLE
can't subscribe feed

### ISSUE THREAD

**Issue by c-yan** [gitbucket/gitbucket#1557]
## Issue
**Impacted version**: 4.11.10

**Deployment mode**: Windows Server 2012 R2 + Apache 2.4.25 + JDK 8u121 + Tomcat 8.0.43

**Problem description**: I tried to subscribe to /activities.atom with Thunderbird and Outlook, but I got error. I guess that GitBucket returned the redirect response to the login screen. Is there any solution?

**Comment by takezoe** [comment]
Can you open `/activities.atom` in your browser?

**Comment by c-yan** [comment]
I can open /activities.atom in my browser.
But I redirect to login page unless I've already logged in.
Generally, feed readers support BASIC authentication, but they don't support form authentication.

**Comment by takezoe** [comment]
Are you allowing anonymous access?

**Comment by c-yan** [comment]
It is difficult to allow anonymous access.

**Comment by takezoe** [comment]
In that case, there are no solution for now.
