### ISSUE TITLE
https://gitbucket.github.io 404s

### ISSUE THREAD

**Issue by wolftune** [gitbucket/gitbucket#1561]
This is really a meta project issue. You really should make the main site redirect or do something other than 404. Anyone landing on the plain url without the /gitbucket-news will think the project is gone.

**Comment by takezoe** [comment]
Right. Maybe the [gitbucket-news](https://github.com/gitbucket/gitbucket-news) repository should be renamed to `gitbucket.github.io`.

**Comment by t-tsutsumi** [comment]
@takezoe I think that it is better to create the `gitbucket.github.io` repository because it is enough to place the following `index.html`.

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <title>Redirecting to https://gitbucket.github.io/gitbucket-news/</title>
    <meta http-equiv="refresh" content="5; url=https://gitbucket.github.io/gitbucket-news/">
    <script type="text/javascript">
        window.location.replace("https://gitbucket.github.io/gitbucket-news/");
    </script>
</head>
<body>
    <p>If you are not automatically redirected in 5 seconds <a href="https://gitbucket.github.io/gitbucket-news/">click here.</a></p>
</body>
</html>
```

**Comment by takezoe** [comment]
Landing page has been launched! https://gitbucket.github.io/
