### ISSUE TITLE
maxFileSize in FileUploadController should be configureble

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1569]
https://github.com/gitbucket/gitbucket/blob/c5a5c737bf9e4125358a257abfbd7d7ee6c5c88f/src/main/scala/gitbucket/core/controller/FileUploadController.scala#L25

**Comment by wy193777** [comment]
I'm interested in implement this. Is add another command line variable like `--max_file_size` a good solution? Maybe also let it check some config files?

**Comment by takezoe** [comment]
@wy193777 Thanks. It's the best if we can configure it at the admin console. But I'm not sure whether Scalatra's maxFileSize is possible to change dynamically.

As an alternative solution, `--max_file_size` looks good. But it have to be configurable as system property and environment variable as same as `--gitbucket.home` for users who are deploying GitBucket on the application server.
