### ISSUE TITLE
"Settings" -> switches from https to http

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1570]
## Issue
**Impacted version**: 4.12.0

**Deployment mode**: Standalone webapp behind an apache httpd acting as reverse proxy. The apache httpd terminates https.

**Problem description**:
- Login to gitbucket: https://my.server.com/gitbucket/
- Select a repo
- Mouse-over the "Settings" in the navbar at the right side of the screen: https://my.server.com/gitbucket/{group}/repo/settings
- Click on "Settings": https://my.server.com/gitbucket/{group}/repo/settings - 
http://my.server.com/gitbucket/{group}/repo/settings/options shows up in the address bar
- Since the apache httpd isn't listening to http://..., the user sees an error page
- Within gitbucket.conf, I have specified https://... for the Base URL
- I didn't observe the issue with previous versions of gitbucket (as far as I remember)
- Manually  changing the URL within the address bar from http -> https seems to work

**Comment by dbronecki** [comment]
Could you try with latest master? It sounds similar to #1568

**Comment by uli-heller** [comment]
Thanks a lot for giving this hint, I'll give this a try later.

In the meantime, I've found another solution: Setting X-Forwarded-Proto to "https" within the reverse proxy.

**Comment by uli-heller** [comment]
I checked with 16ccf83f7a18bac23e31c2f6caa8f55f0b7f17df: This version doesn't have the issue,
so #1570 is probably a duplicate of #1568.
