### ISSUE TITLE
Hide H2 console in admin panel if using a different DB

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket#1574]
I think the title says it all. It's pointless to have this link if we store nothing in the H2 db.

**Comment by takezoe** [comment]
We can use H2 console to connect other database as well. It may be nice to fill URL and JDBC driver by database configuration as default values.

**Comment by bviktor** [comment]
Oh sorry, I didn't know that. In that case I close this issue as there's already an issue for filling the defaults. Thanks for the info.
