### ISSUE TITLE
MariaDB 10.1.22 + Gitbucket 4.12.1 can't start

### ISSUE THREAD

**Issue by cz-michi** [gitbucket/gitbucket#1580]
Today i tried to migrate my private gitbucket to mariadb and i'm getting this error when starting
java.sql.SQLException: View's SELECT contains a subquery in the FROM clause

i cannot get tracing working as described in wiki :-( so i hope, this is enough info for you

**Comment by t-tsutsumi** [comment]
@cz-michi Unfortunately, GitBucket does not support MariaDB version less than 11.2.1. See also #1187.

**Comment by cz-michi** [comment]
well, thank you!

**Comment by takezoe** [comment]
@t-tsutsumi Thanks for your support. I will add supported version of MariaDB to documentation.
https://github.com/gitbucket/gitbucket/wiki/External-database-configuration
