### ISSUE TITLE
Add Rest endpoints to add/delete collaborators

### ISSUE THREAD

**Issue by alvaroaleman** [gitbucket/gitbucket#1586]
## Issue
**Impacted version**: 4.12.1

**Problem description**:

It would be great if it was possible to configure permissions from scripts. To make this possible, the [Add 
 user as collaborator](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator) and [Remove user as collaborator](https://developer.github.com/v3/repos/collaborators/#remove-user-as-a-collaborator) REST endpoints are required.

**Comment by kounoike** [comment]
This API implemented by #2212
