### ISSUE TITLE
Allow HTML in Markdown

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1591]
Markedj is going to support HTML in Markdown in 1.0.11 (https://github.com/gitbucket/markedj/pull/18), so upgrade after it's released.

**Comment by aadrian** [comment]
What about https://github.com/gitbucket/gitbucket/pull/1323  ?

**Comment by takezoe** [comment]
I'm not working on that for now.

**Comment by McFoggy** [comment]
@aadrian sorry I have been a bit out of all my OSS contributions _(included the ones for gitbucket)_ for the past weeks, so #1323 did not moved forward. Unfortunately, I am really not sure to find time to work on it.

**Comment by takezoe** [comment]
@McFoggy Don't mind. It will be taken over by someone if necessary. I'm waiting for your come-back ;-)

**Comment by McFoggy** [comment]
@takezoe thanks I'll do my best.
