### ISSUE TITLE
why not login

### ISSUE THREAD

**Issue by lt123456** [gitbucket/gitbucket#1593]
###  I login  success ,   I  update userenname and password , but I logout  systeam,  I try again login use new username/password , but I not login!　　
－－－－－
　I want  konw  how  forget password   or   find password !

### thank you  very mush  , I hope you  help， we will become friend,

-  
- centesos 7.0  
- gitbucket 4.9

**Comment by takezoe** [comment]
To initialize GitBucket, remove `~/.gitbucket` directory. All data is removed and GitBucket is backed to the initial state. Then you reboot GitBucket, you can logged-in with root / root.
