### ISSUE TITLE
Feature request: disable email notification

### ISSUE THREAD

**Issue by fistons** [gitbucket/gitbucket#1598]
It would be nice if a user could disable email notification

**Comment by shimamoto** [comment]
I feel that users can be disable all notification on their setting screen. Is this the same as what you imagined?

I just started #628. So I’ll do this later.

**Comment by fistons** [comment]
You are right, I was thinking of something like that, thanks!

**Comment by aadrian** [comment]
> I feel that users can be disable all notification on their setting screen.

IMHO there should be 2 levels of settings for this:
  1. Global
  1. Per Project

#### Global
This should be more for "automated" users than normal users

#### Per Project
This should be the option that most users want.

**Comment by shimamoto** [comment]
In scope of this issue, I will implement 1. Global.

**Comment by takezoe** [comment]
Moved to https://github.com/gitbucket/gitbucket-notifications-plugin/issues/1
