### ISSUE TITLE
[Suggestion] Give each project's wiki it's own public/private toggle?

### ISSUE THREAD

**Issue by kyrahabattoir** [gitbucket/gitbucket#1599]
Since each wiki is its own git repository it would be nice if the wiki could be set as a public repository while keeping the code repo private.

**Comment by aadrian** [comment]
> it would be nice if the wiki could be set as a public repository while keeping the code repo private.

You can always create a second repo that is public, and has the name something like "repo_name_wiki", and contains no sources, or as sources only a simple readme explaining stuff.

**Comment by aadrian** [comment]
Also note that there's the https://github.com/gitbucket/gitbucket-pages-plugin that could be installed to provide pages like the [GitHub Pages](https://pages.github.com/) (minus the automatic Markdown rendering)

**Comment by kyrahabattoir** [comment]
Yes that's always an option i suppose.

**Comment by aadrian** [comment]
There's no need to make the GitBucket more complicated, since as described above, this kind of behavior can already be achieved.
