### ISSUE TITLE
Starting EXTREME Slow on Raspberry pi 3

### ISSUE THREAD

**Issue by kingcraftingnl** [gitbucket/gitbucket#1606]
The last version of GitBucket takes 1 Hour to fully startup on a PI3 And the webpage dous not even Load when its done starting.

**Comment by t-tsutsumi** [comment]
Are you using OpenJDK Zero VM? Zero VM is very slow because it is an interpreter only JVM. This is common in Raspberry PI and not confined to matters of GitBucket.

**Comment by takezoe** [comment]
@t-tsutsumi is right. That is not an issue of GitBucket.
