### ISSUE TITLE
Question About How GB Tracks Forks

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1608]
Here is the workflow in question (all via GB GUI):

- User forks their own instance of repo Foo -> My-Foo    
- GB displays the fact that My-Foo was forked from Foo
- Foo is moved to a different owner
- GB no longer associates My-Foo as a fork of Foo

Two questions:

- Is this correct behavior, or should GB pickup the fact that My-Foo really is a fork of Foo under new ownership?
- What's the best way to reestablish the Foo -> My-Foo forking relationship?

**Comment by takezoe** [comment]
This was a pitfall. I will fix this bug in the next release.

> What's the best way to reestablish the Foo -> My-Foo forking relationship?

Run following SQL on your database to fix relationship:
```sql
UPDATE REPOSITORY SET PARENT_USER_NAME = 'My-Foo' WHERE PARENT_USER_NAME = 'Foo';
```
