### ISSUE TITLE
Possible 4.13 ssh Issue?

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1613]
I upgraded two different GB sites last night with the most recent 4.13 release.  One works as always.  But the other started giving users fits, complaining that the ssh key signature was bogus and that they might be victims of a man in the middle attack.

Is there anything in 4.13 that might have a corner case that messes up ssh key exchanges, say for cloning, pushes, or pulls?   This is really mysterious.  I literally only replaced the .war file and started GB.  No other aspect of the configuration was touched.

Thoughts?

**Comment by takezoe** [comment]
@tundratim What version were you using before upgrading to 4.13?

**Comment by tundratim** [comment]
@takezoe  4.12.1

**Comment by takezoe** [comment]
@tundratim 

> Just to be clear, GB runs its own ssh server and does not rely on system ssh or other config files, correct?

Yes. GitBucket runs [Apache MINA sshd](https://mina.apache.org/sshd-project/) which is a pure Java sshd implementation. It doesn't depend on system ssh or configuration.

In GitBucket 4.11, we had an issue about SSH key (#1523). But I'm not sure this issue is related to your situation.

**Comment by tundratim** [comment]
@takezoe What's strange about this is that I've pretty much tracked your releases in this particular environment.  We've never seen this problem before.   The one thing that jumps out at me is that the system with problems has had a number of different DNS aliases and - as of about 3 months or so ago, was put behind an haproxy for purposes of https termination.  At least some of the failing keys appear to be happening when the repo has the old remote origin in it.  But, like I said, that was never a problem in the past.

The workaround appears to be deleting the offending keys from the user's known_hosts files and - just to be safe - having them reclone using the current and correct hostname via ssh.

I just wanted you guys to be aware of this in case there is a problem within GB itself.
