### ISSUE TITLE
Two simultaneous commits to the same file are successful.

### ISSUE THREAD

**Issue by ymagriso** [gitbucket/gitbucket#1618]
Impacted version: 4.13.0

Deployment mode: gitbucket is deployed on Apache Tomcat without an additional HTTP frontend.

Problem description:
When two users (or more) commit the same file at (almost) the same time, the changes of the last commit are overriding the first commit (in the commits history of the file both commits are listed).

Steps to reproduce:
1) Login to gitbucket with user A from one host.
2) Login to gitbucket with user B from another host.
3) Edit the same file in both hosts (different changes on the same line in the file).
4) Click the "Commit changes" button on both hosts simultaneously.

Expected result:
The last commit attempt should fail with an error that a conflict was encountered.

Actual result:
The changes of the last commit are overriding the first commit (in the commits history of the file both commits are listed).

**Comment by ritschwumm** [comment]
wow.. sounds like a serious bug in jgit.

**Comment by ymagriso** [comment]
Thanks, @takezoe, for the quick response.
The issue is no longer reproducible with versions 4.14 and 4.14.1.
