### ISSUE TITLE
Cannot clone repo using TortoiseGit

### ISSUE THREAD

**Issue by msyadid** [gitbucket/gitbucket#1630]
**Impacted version**: 4.14

**Deployment mode**: *standalone app*

**Problem description**:
I have downloaded the GitBucket 4.14 and running with a command (java -jar gitbucket.war).
I can access the web using URL (http://localhost:8080 user: root, password: root) & create a new repository (example: MYREPO). 
But I cannot clone the repository using Git Client (TortoiseGit).
I got this error message:
 `git.exe clone --progress -v "http://localhost:8080/git/root/MYREPO.git" 
"C:\Users\xxxxx\MYREPO"

Cloning into 'C:\Users\xxxxx\MYREPO'...
fatal: repository 'http://localhost:8080/git/root/MYREPO.git/' not found

git did not exit cleanly (exit code 128) (2199 ms @ 7/4/2017 4:25:05 PM)`

Maybe I miss the configuration or installation? 
Kindly need your help or this is a bug?

**Comment by shiena** [comment]
@msyadid 
I could clone with the following combinations.
* GitBucket 4.14.1 (run on linux)
* Git for Windows: 2.13.1
* TortoiseGit: 2.4.0.2
* Windows 10

Can you clone with the git command?

**Comment by aadrian** [comment]
@msyadid may I suggest trying another client ? e.g. http://www.syntevo.com/smartgit/ ? Unfortunately even the command line is better than Tortoaise :(.

Few suggestions:
 - use the parameters https://github.com/gitbucket/gitbucket#installation mentioned there to beter control your installation
 - tune the logging https://github.com/gitbucket/gitbucket/wiki/Tracing-%26-logging if there are not enugh messages to see the problem.

**Comment by aadrian** [comment]
@msyadid did it worked?
