### ISSUE TITLE
Account (permission)

### ISSUE THREAD

**Issue by dovelet** [gitbucket/gitbucket#1632]
I don't have any rights to the account that I tested. (create account type : normal)

However, when you log in, you can view the repo via the NewsFeed tab.
Even if you click on NewsFeed's hyperlink, you can view the source and download it.

also does not appear on the left, but you can see most of the repo by writing " a " in the top of the " Search Repository ".

And, Internet Browser Input URL of unauthorized repository is accessible.

**Comment by takezoe** [comment]
@dovelet In default, repositories are referable like GitHub. If you want to hide a repository for users who aren't allowed to access a repository, turn to a private repository.
