### ISSUE TITLE
[4.14.1] Scrollbar Issue

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1635]
Confirmed on two different 4.14.1 installations with both Firefox and Chrome:

When you first log in, you are presented with two parallel scrollbars on the right side of the UI.  Thereafter, this behavior comes and goes in an unpredictable way.  This appears to be benign and entirely cosmetic as best as I've been able to determine.

**Comment by takezoe** [comment]
I can't reproduce such situation. Could you upload screen shot?

**Comment by tundratim** [comment]
![gb-4 14 1-dualscrollbar](https://user-images.githubusercontent.com/13384926/27919728-0eebb3a6-6238-11e7-8b0e-119a6dc80a5b.png)

**Comment by takezoe** [comment]
Hm, it's strange...

Did you clear CSS and JavaScript cache? and does this reproduce on demo site?

**Comment by tundratim** [comment]
There are not enough repos on the demo site (https://gitbucket.herokuapp.com/) to cause a scroll bar to appear.  Also, this typically appears after someone logs in and I have no credentials on that site to do that.

**Comment by takezoe** [comment]
You can logged-in the demo site with root / root. I will create repos, wait a moment...

**Comment by takezoe** [comment]
I created 20 repos, and this is a result with my Chrome:

![Chrome](https://user-images.githubusercontent.com/1094760/27920523-cc2e4420-62af-11e7-8844-b0241aed84b4.png)

**Comment by takezoe** [comment]
and Firefox:

![firefox](https://user-images.githubusercontent.com/1094760/27920662-5313aed0-62b0-11e7-8d31-03ab0985e65b.png)

**Comment by tundratim** [comment]
Clearing cache temporarily fixes it on FF and does nothing on Chrome.  Cannot duplicate on demo site.

**Comment by takezoe** [comment]
But I expect it's caused by something like cache in Chrome as well.

Essentially, to avoid such trouble, GitBucket might have to add hash or timestamp to assets such as images, css and js to make sure new version are loaded.

**Comment by mashabow** [comment]
I'm getting the same issue on Firefox, and cache clearing has no effect.

[firefox_gitbucket_fullpage.png](https://user-images.githubusercontent.com/6268183/28003219-fbf8d9da-6576-11e7-972f-34fe190dd4ba.png)

Note that `.wrapper { position: static; }` fixes this for me.
