### ISSUE TITLE
Git commit messages not added to ISSUE_COMMENT table when issue referenced

### ISSUE THREAD

**Issue by mgeorge** [gitbucket/gitbucket#1643]
## Issue
**Impacted version**: 4.14.1

**Deployment mode**: standalone

**Problem description**:
If you commit via the GitBucket interface and reference an issue, the commit messages end up in the ISSUE_COMMENT table which means you see the commits when you look at the associated issue.

When you commit via a Git client this does not happen.  The commits appears in the commits page, but the messages are not added to the ISSUE_COMMENT table, so you can't see the commits from the associated issue.

I feel like I must be missing something here.  Is there a batch process that is supposed to run to synchronise the Git messages with the issues or something?

**Comment by takezoe** [comment]
@mgeorge I tested to commit and push using git command, the commit was shown on the referenced issue as follows:
![issue_comment](https://user-images.githubusercontent.com/1094760/28250244-c6624324-6a9e-11e7-8c83-c887671cc42e.png)

Could you tell more details about your situation such as your git client or a commit message?

**Comment by mgeorge** [comment]
I have tested it with the standard command-line (version 2.13.2) on Arch Linux.  I have also tried the client built into NetBeans 8.2.

The commit message used the usual notation:
```
Message goes here. References #1
```
I don't think this is a client issue.  I used the exact same message in both instances.  If I commit via the GitBucket interface the message appears in the ISSUE_COMMENT table, and I can see the commit from the issue.  If I use any other client it does not.

I tested with a completely clean install of 4.14.1 in standalone mode.

This also happens on our corporate deployment (version 4.13) running standalone behind an Apache reverse proxy for SSL.  This affects our students also who primarily use the NetBeans client.

I will do so more testing and see if I can narrow down the field a little.

**Comment by takezoe** [comment]
> I don't think this is a client issue.

Agree with this. Are you pushing to GitBucket via HTTP(S)?, not SSH? And is it reproduce on demo site too? https://gitbucket.herokuapp.com/

**Comment by mgeorge** [comment]
Seems to be related to the user details of the committer.  If the committer details do not match a GitBucket user (name AND email) then the issue is not linked.

If you have not explicitly added a proper user to the Git repo config then both the git client and NetBeans will try to self-assign one using the hostname of the client as the email address.  Even though the username is correct, the weird email address seems to be causing this problem.

Maybe this could be fixed by using the authenticated username to lookup the account rather than the email address as a fallback if the email address does not match a GitBucket account.

As least I now know what the problem is, and can ensure we have properly configured the users in the git config.

**Comment by takezoe** [comment]
> Seems to be related to the user details of the committer. If the committer details do not match a GitBucket user (name AND email) then the issue is not linked.

That's right. Dropping account check and don't create link if user does not exist might be a solution.

**Comment by mgeorge** [comment]
Given that the same developer may have different user details in their global gitconfigs at different locations (home, office, laptop), I think the canonical identifier should be the GitBucket account details used to authenticate.  If they do want to have different identities for some reason then they have the option of multiple GitBucket accounts.

**Comment by takezoe** [comment]
I meant separating following tasks:

- recording commit messages
- linking them to account

Perhaps account checking isn't required in recording messages.

In addition, if users have 2 or more email addresses, it might be good if it's possible to register multi addresses to one account as same as GitHub.

**Comment by mgeorge** [comment]
Yes, agree that account checking probably isn't required.  You can commit using any details, and the commit and message appears in file explorer, and commit view, so I would expect the same behaviour in the issues view.
