### ISSUE TITLE
The issue title in the log "referenced the issue" cannot be updated when the issue title changed

### ISSUE THREAD

**Issue by tmori3y2** [gitbucket/gitbucket#1651]
## Issue
**Impacted version**: 4.13.0

**Deployment mode**:  using gitBucket which is hosted on a server of a university which is a collaborative research partner via a proxy of my company

**Problem description**:
1. create the first issue
1. create the second issue and refer to the first issue number
1. the log "referenced the issue" generated in the first issue
1. edit the second issue title
1. the second issue title in the log "referenced the issue" cannot be updated in the first issue

Best Regards

**Comment by tmori3y2** [comment]
By the way, no log recorded when the issue title edited.

**Comment by takezoe** [comment]
> the second issue title in the log "referenced the issue" cannot be updated in the first issue
> By the way, no log recorded when the issue title edited.

Both of them are intended behavior for now.
