### ISSUE TITLE
Re-creating group does not work

### ISSUE THREAD

**Issue by rickq** [gitbucket/gitbucket#1653]
## Issue
**Impacted version**: 4.14.1

**Deployment mode**:  gitbucket : standalone app

**Problem description**:
- Create group of a given name
- Delete the group
- Create the group of the same name again
- **ERROR**: *User already exists.*

**Comment by takezoe** [comment]
It can't re-creatie account. Account is disabled when deleted, and only administrators can enabled again in the admin console.

**Comment by rickq** [comment]
Well, I have a group named "ASDF" and I am trying to rename it to "asdf". Since I am not able to delete the group completely and create it again, I see no way how to rename the group.

**Comment by takezoe** [comment]
Yes, no way to rename for now.

**Comment by rickq** [comment]
Thanks for your reply, @takezoe. Ok, I've solved this on sql level directly in data table. You can close this issue.
