### ISSUE TITLE
How To Updrade Old Gist DB

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1663]
I inherited an old instance of GB which I've slowly being cleaning up.  However, the Gist database is very old and is having fits when I try to use latest Gist plugin with 4.15.0:

...initialization: gitbucket-gist-plugin_2.12-4.10.0.jar
java.lang.IllegalStateException: Plugin version is 4.10.0, but database version is 1.2

Best way to fix?

**Comment by aadrian** [comment]
@tundratim  have you tried to use this: https://github.com/gitbucket/h2-migration  ?

> try to use latest Gist plugin with 4.15.0

If your old instance is < GitBucket 3.x than try to update first to the latest from the 3.x series, use the tool above, and the corresponding Gist Plug-in https://github.com/gitbucket/gitbucket-gist-plugin#gitbucket-gist-plugin-  (see that each version of GitBucket works only with specific versions of the plug-in).

Than after you have a functional v3.x GitBucket instance, update it to 4.x.
Please note that starting with GitBucket 4.15, the 4 plug-ins marked with red:
http://gitbucket-plugins.github.io/
are bundled with the distribution, so don't need to be installed like the other plug-ins.

**Comment by tundratim** [comment]
Well, GB itself is working fine and running now on 4.15.0.  The problem is that the GB databases got upgraded along the way, but the Gist DB did not.

**Comment by aadrian** [comment]
> The problem is that the GB databases got upgraded along the way, but the Gist DB did not.

I'm not sure what that means. AFAIK GitBucket has only support for a single DB at the moment,
and the Gist information is in some of those tables.

> In fact, at this point, I'd be happy to blow away the old Gist DB if I knew how because there is little or nothing in there, and start over.

Do an export of the DB information (from the Admin) to a clean new instance, where you copy the Git repos too.

**Comment by takezoe** [comment]
@tundratim See the installation section in README of the gist plugin:
https://github.com/gitbucket/gitbucket-gist-plugin#installation

In addition, please use [gitter](https://gitter.im/gitbucket/gitbucket) if you need support according to [the guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/SUPPORT.md).

**Comment by tundratim** [comment]
I've tried this procedure which appeared to work with 4.15.0 and gist plugin 4.10, however when I go to the snippets page, I see:

ORIGIN_USER_NAME not found
