### ISSUE TITLE
Pull Request Workflow Issue

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1665]
Note that although this was demonstrated on 4.15.0, we are NOT saying this was a newly introduced problem.  This is the first time we've tried this, so cannot comment on when the problem appeared...

Gitbucket version: 4.15.0

Setup:

a)	There exists a group G with a limited number of members
b)	There is a repo R in the group
c)	User U1 is a member of G
d)	User U2 is NOT a member of G
e)	Settings on repo R include: Public, Forks allowed, “All users can view, create and comment on issues and pull requests”, and “All users can view, create and edit wiki pages”

Users U1 and U2 both wish to make contributions to R. Since U2 is not in the group, the only GitBucket way to do this is for U2 to fork the repo, make a change, and issue a pull request back to R.

The following procedure should work for either U1 or U2, but it results in an error for U2:
1)	User forks R to make repo U/R
2)	User clones U/R, makes a change in U/R, commits the change and pushes up to U/R in Gitbucket
3)	User goes the Gitbucket R page, clicks Pull Requests, then New Pull Request
4)	User selects U/R from the “head fork” pull-down menu
XXX At this point, U2 gets an error page “Not Found” – this should not happen
5)	User optionally selects other branches to merge to or from
6)	User can preview the differences, then clicks “Create Pull Request”
7)	User optionally enters comments and clicks “Create Pull Request” again
At this point, there should be a pending pull request on R

**Comment by JLofgren** [comment]
Hi, I just checked and this issue persists in 4.16.0.

**Comment by JLofgren** [comment]
To explain the issue a bit more simply:  This bug prevents non-members from issuing a PR from a fork even if the repo has permissions saying all users should be allowed to fork and issue PRs.

**Comment by tundratim** [comment]
Any further action on this anticipated?

**Comment by takezoe** [comment]
@tundratim I guess this issue has been fixed in 4.20.0 by fix for #1797. Could you test again with 4.20.0?

**Comment by tundratim** [comment]
@takezoe @JLofgren   John and I have just confirmed that the bug *is* fixed. Thanks!

One side effect though:  After testing, I deleted the fork that was used to check things.  Interestingly, the pull request against it remained in place, even though the fork was now gone.  Is this intentional?  Is there are use case for this?

One other small matter: Is there a way to delete pull requests completely so they never appear as having ever been submitted?

**Comment by takezoe** [comment]
> One side effect though: After testing, I deleted the fork that was used to check things. Interestingly, the pull request against it remained in place, even though the fork was now gone. Is this intentional?

Yes.

> Is there a use case for this?

As a design policy of GitBucket, if a pull request is created once, it belong to the target repository. So it remains even if the source repository is deleted. 

> One other small matter: Is there a way to delete pull requests completely so they never appear as having ever been submitted?

No way as same as issues. Offering a way to delete them might breaks references to them. It's same in user accounts. So GitBucket offers logical deletion for users and offers closing for issues and pull requests, not physical deletion.

**Comment by tundratim** [comment]
Issue resolved.  Closing

**Comment by tundratim** [comment]
Issue resolved. Closing.
