### ISSUE TITLE
Add REST endpoint to create and rename a group

### ISSUE THREAD

**Issue by JanKrueger-LHIND** [gitbucket/gitbucket#1667]
## Issue
**Impacted version**: 4.15.0

**Problem description**:
- It would be great to have a REST method, which creates a group.
- It would be great to have a REST method, which renames a group.
- The endpoints (POST and PATCH) are described here https://developer.github.com/v3/enterprise-admin/orgs/

**Comment by kounoike** [comment]
create group supported in 4.31.0 / #2274. rename is difficult in GitBucket. So, I think we can close this issue.
