### ISSUE TITLE
Unable to push into remote repo

### ISSUE THREAD

**Issue by Phaniscm** [gitbucket/gitbucket#1679]
### Before submitting an issue to GitBucket I have first:

- [*] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [*] searched for similar already existing issue
- [*] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

Unable to push the data into repo

## Issue
**Impacted version**: xxxx

**Deployment mode**: deployed gitbucket.war on tomcat server in my ubuntu machine.

**Problem description**:When trying to push the large files getting the issue as follows:
Counting objects: 108, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (104/104), done.
Writing objects: 100% (108/108), 9.73 MiB | 3.00 MiB/s, done.
Total 108 (delta 29), reused 0 (delta 0)
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

- I am trying to resolve this issue in many ways by set the origin,defined post buffer size,track the large files using git lfs.but no use 
- clone the repo as easily but unable to push the 1.2 mb files.
- *explain how to reproduce*

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 408.46 KiB | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by kounoike** [comment]
Proxy issue. I talk about this issue in gitter room.
