### ISSUE TITLE
Users in different network to access cloud application with LDAP authentication

### ISSUE THREAD

**Issue by RSamyPSamy** [gitbucket/gitbucket#1680]
I would like to hear a suggestion from you on the solution that I am trying to build. 
**Given situation:**
1. I have 4 different users in different network
2. One application hosted in cloud
3. Authenticate the users from different network using LDAP to access the application
**Solution:**
Using System.Directories namespace to validate the users against the LDAP individually. The users has to select their respective location during login. 
**Question:** 
1. Is this a right solution?
2. What is required from accessing the LDAP over the internet to validate the user?
3. Is there a way to identify the LDAP URL from the users email id?

Thanks.

**Comment by takezoe** [comment]
I'm not sure about LDAP, but it's not a GitBucket specific topic. I think there is a better place for your question than here.
