### ISSUE TITLE
"Not found" when creating a new folder from within the webui

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1682]
## Issue
**Impacted version**: 4.14.1 and 4.15.0 and probably many others

**Deployment mode**: *standalone app with an http frontend (apache httpd)*

**Problem description**:
- Open the webui
- Look a a project within gitbucket
- Click on the plus sign "+"
- For the filename, enter {folder}/{file}, for example "new-folder/tst.md"
- For the file content, enter some dummy lines
- Click on "Commit changes"

Now, an error message will be displayed:

- address bar: `https://mydomain.com/gitbucket/dp/sandbox/blob/master/a%2Fa.md`
- error message: `The requested URL /gitbucket/dp/sandbox/blob/master/a/a.md was not found on this server.`

**Solution**

Add this to the configuration of the apache httpd:

```
        AllowEncodedSlashes NoDecode
        # Apache22: AllowEncodedSlashes On
```

I've updated the wiki page accordingly.
Maybe you need a similar modification for nginx, too?

**Comment by takezoe** [comment]
I use GitBucket with Nginx as frontend but it works fine for URLs contain encoded slashes with configuration described in [the Wiki page](https://github.com/gitbucket/gitbucket/wiki/Reverse-proxy-with-Nginx).

**Comment by uli-heller** [comment]
Am 2017-09-02 22:46, schrieb Naoki Takezoe:
> I use GitBucket with Nginx as frontend but it works fine for URLs
> contain encoded slashes with configuration described in the Wiki page
> [1].

Fine, thanks for the feedback! So we do have working revproxy 
configurations
for nginx and apache.
