### ISSUE TITLE
Notification emails are not sent for PR code comments

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket#1685]
In GitBucket 4.15 notification emails are not being sent for comments made inline, in the "Files Changed" tab. PR comments made under "Conversation" are received just fine so it's not a configuration error. Any ideas?

**Comment by takezoe** [comment]
This is intended behavior.

There is possibility that a lot of code comments are added to one pull request in the code review. This would cause much notification mails if GitBucket has sent notification mail for each code comments.

**Comment by bviktor** [comment]
I see. But assuming someone only puts a code review comment, how is the PR author supposed to know that a comment has been made and is awaiting response?

**Comment by takezoe** [comment]
You are right. GitBucket should provide a way to notify them. However both the review and the notification system in GitBucket is immature yet. It's related with the activity timeline and plugin APIs as well. We have to carefully consider how to make it, so it may take a while.

For now, you can add an another comment to notify to the PR author.
