### ISSUE TITLE
recovery from repository

### ISSUE THREAD

**Issue by yong-gwi** [gitbucket/gitbucket#1689]
Hi,

My gitbucket settings were initialized unintentionally, but git repository is still fine.
Is there any method to recover past state ? 

Thanks for you cooperation!

Cho

**Comment by aadrian** [comment]
> My gitbucket settings were initialized unintentionally

What does that mean?

> Is there any method to recover past state ?

Have you used the H2 Backup plug-in https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin if you used H2, or other DB Backup tool (if you used MySQL or Postgres) as storage for GitBucket?

**Comment by yong-gwi** [comment]
Hi, 

Thanks for your comments.

> What does that mean?
all of setting ( e.g. registered users, branches, commits, ... )　were deleted/initialized. 
My current page of gitbucket is blank which means that it's absolutely an initial state.
However git repository is still fine, thus  I thought there might be any recovery methods.

> Have you used the H2 Backup plug-in https://github.com/gitbucket-plugins/gitbucket-h2-backup-
plugin if you used H2, or other DB Backup tool (if you used MySQL or Postgres) as storage for GitBucket?
I have not used any Backup tool for gitbucket. If so, is there no method to go back to previous state ?

Best,
Cho

**Comment by takezoe** [comment]
@yong-gwi We don't want to use here for user support. Use [gitter](https://gitter.im/gitbucket/gitbucket) instead if you need our support according to the guidelines:
https://github.com/gitbucket/gitbucket/blob/master/.github/SUPPORT.md
