### ISSUE TITLE
code block rendering is incorrect when use together with gitbucket-asciidoctor-plugin

### ISSUE THREAD

**Issue by kazuki43zoo** [gitbucket/gitbucket#1698]
## Issue
**Impacted version**: 4.16

**Deployment mode**: standalone app

**Problem description**:

I used the GitBucket together with [gitbucket-asciidoctor-plugin](https://github.com/asciidoctor/gitbucket-asciidoctor-plugin/)(gitbucket-4.10-asciidoctor-plugin-assembly-1.0.2.jar), but it does not work fine when using a code block as follow: 

asciidoc source:
```adoc
= Test

.Simple Java class
[source,java]
----
public class Sample {
}
----

This is a sample java code.
```

It is rendering as follow:

![asciidoc](https://user-images.githubusercontent.com/5616270/30119464-c6618f16-9360-11e7-92ac-3df23f4bdc9d.png)

I think a `min-height` of `content` class is too much.
I will expect the following rendering:

![asciidoc-expected](https://user-images.githubusercontent.com/5616270/30119661-73ffc386-9361-11e7-98a5-c325d09a623a.png)
 
What do you think?

**Comment by kazuki43zoo** [comment]
Probably, generated code by the asciidoctor seems that compatibility with AdminELT is not good.

**Comment by aadrian** [comment]
plug-in issue: https://github.com/asciidoctor/gitbucket-asciidoctor-plugin/issues/16
