### ISSUE TITLE
list commits of 1 branch from gitbucket

### ISSUE THREAD

**Issue by duyphong27** [gitbucket/gitbucket#1699]
I am using GitBucket 4.16.0

I have a repository [MyRepository], and i have created [devel1] branch.
Now i want to display list committed of [devel1] branch with files list (using GitBucket API).

I have using URL such as: GET /api/v3/repos/:owner/:repo/commits
but the server returned "Not Found" message.

Any idea for help me. Thanks you and sorry for my English.

**Comment by takezoe** [comment]
Commits API isn't implemented yet. You can see the supported API list at:
https://github.com/gitbucket/gitbucket/wiki/API-WebHook
