### ISSUE TITLE
Add the ability to allow merging out-of-date PR branches

### ISSUE THREAD

**Issue by imeszaros** [gitbucket/gitbucket#1700]
On GitHub, if a branch is protected, it can be specified whether to allow merging out-of-date branches.

See the **loose** setting here: https://help.github.com/articles/types-of-required-status-checks/

This is useful if the development team does not use any automated tests or CI, but usually has multiple PRs simultaneously.

This behavior can be activated on GitHub via a checkbox after activating the status checks option, but GitBucket has no such checkbox.

**Comment by imeszaros** [comment]
@takezoe  What's your opinion on this? If i'd make such a feature, would you accept it?

**Comment by takezoe** [comment]
Yes, it looks a nice feature. I'm waiting for your pull request. 😉

**Comment by imeszaros** [comment]
Since i realized that GitBucket only warns if the branch is out of date, merge PR is still possible, i consider this feature not so important anymore.
