### ISSUE TITLE
Transfer to URL with commit ID by "y" key

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1702]
GitHub (and also GitLab) supports keyboard shortcut `y` which transfers a browser to the URL with commit ID. GitBucket should support it.

**Comment by xuwei-k** [comment]
FYI, there are some keyboard shortcuts other than "y"
https://help.github.com/articles/using-keyboard-shortcuts/

**Comment by takezoe** [comment]
Thanks. Only `t` has been supported currentry.
