### ISSUE TITLE
How to configure standalone GitBucket to use https

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1704]
## Issue
**Impacted version**: 4.15.0

**Deployment mode**: standalone

**Problem description**:
I've been searching for a while now and I can't find a definitive answer on how to configure the standalone GitBucket to use https.

I have a keystore file ready but I don't know how to reference it and supply the password when calling the command line "java -jar gitbucket.war" and also how to force the https connection.

I have seen various issues that mention that https using the standalone GitBucket is not possible, but then I have also seen that adding --https=true was possible, but then it was deprecated, so I'm a bit confused.

Any help would be greatly appreciated

**Comment by kounoike** [comment]
@PaulAdams-Conti use Tomcat :smiley:

**Comment by takezoe** [comment]
or use Nginx or Apache as reverse proxy and configure them to enable https. Anyway, this is not a specific topic of GitBucket.

**Comment by PaulAdams-Conti** [comment]
Thanks for the answers but I thought it could also be specific to GitBucket as I can run https with Jenkins standalone which is also bundles Jetty, so I thought it could be possible with GitBucket.
