### ISSUE TITLE
Anchor dropped after signin

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1706]
I'm using GitBucket with anonymous access disabled by settings.
and assume I want to access http://localhost:8080/root/prtest/blob/master/test.txt#L100.

If anonymous access allowed or already login, I can read test.txt with Line 100.
But, anonymous access disallowed and not logged in, This address redirected to sign-in page.
And after sign-in, browser shows top of test.txt.

Then, scroll to Line 100 manually or paste URL to address bar again... It's not expected behavior.

### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.16.0

**Deployment mode**: standalone

**Problem description**:
- access to http://localhost:8080/root/prtest/blob/master/test.txt#L100
- redirect to /signin
- enter username/password
- browser shows http://localhost:8080/root/prtest/blob/master/test.txt

It should be http://localhost:8080/root/prtest/blob/master/test.txt#L100

**Comment by takezoe** [comment]
@kounoike Hash is not sent to the server. Are there any idea to handle it?

**Comment by kounoike** [comment]
@takezoe I think there is a chance to handle hash when sign in form displayed.

1. access to http://localhost:8080/root/test/blob/master/test.txt#L3
2. redirected by `Unauthorized()` (method: GET)
3. browser shows sign in form and URL is http://localhost:8080/signin?redirect=%2Froot%2Ftest%2Fblob%2Fmaster%2Ftest.txt#L3. **Browser keeps hash!**
4. push sign in, redirect by `signin()` (method: POST)
5. after sign in, hash is dropped.

I think hash can send to server with onSubmit javascript function.
