### ISSUE TITLE
deploy_key generation

### ISSUE THREAD

**Issue by Phaniscm** [gitbucket/gitbucket#1708]
running gitbucket on tomcat8

**Problem description**:
Unable to locate the deploy key in gitbucket.
![deploykey](https://user-images.githubusercontent.com/29204316/30360542-b07a5c64-986f-11e7-8b05-c0d5df34c3d6.png)

- i used following command to generate the deploy key
ssh-keygen -t rsa -b 4096 -C "phani.nalla@redpinesignals.com"
i didn't give any passphrase and passwords.
cat ~/.ssh/id_rsa.pub
copied this id in "/repo/settings/deploykey"
- it throws an error as follows:
deloy_key_hq (Key is invalid.) 

Please lookinto this and do needful.

Thanks,
Phani Kumar.

**Comment by takezoe** [comment]
I tested registering a public key which was generated by same command as you, and it worked fine.

**Comment by Phaniscm** [comment]
ok.i tried several times in different ways,but it throws an error as "key is invalid"

**Comment by takezoe** [comment]
Closing old questions.
