### ISSUE TITLE
Question? Why are file types limited in Issue Attachments?

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1714]
## Issue
**Impacted version**: 4.15.0

**Deployment mode**: Tomcat https

**Problem description**:
Trying to attach a ".doc" file to an issue results in the following response:

`Uploading your files...
Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF.`

Why is this restriction there? We needed to attach a doc file and not a docx file as we have a tool that we use that can only parse ".doc" files and not ".docx" files and this document is relevant to the issue. Is there anywhere that this can be configured?

**Comment by takezoe** [comment]
GitHub had such limitation in the past, but we don't have to follow that now. We consider to remove this limitation or to make configurable by administrators. Thanks for your feedback! 👍
