### ISSUE TITLE
Collaborators in group repo

### ISSUE THREAD

**Issue by jtyr** [gitbucket/gitbucket#172]
There is no option to add collaborators to a repo created in a group. In the case of user repo, the option is there.

User repo:
Setting -> Collaborators -> |_________| [ Add ]

Group repo:
Setting -> Collaborators -> {only list of collaborators inherited from the group setting}

Collaborators defined in the group settings should not be removable in the group repo setting. Only users added in the group repo settings should be removable.

Please add the "Add collaborator" functionality to the group repo settings.

---

Team management would be nicer than adding only single users.

**Comment by codeling** [comment]
This would be really nice, and I don't see it mentioned exactly in https://github.com/gitbucket/gitbucket/issues/282; is this still under consideration?

**Comment by takezoe** [comment]
@codeling Yes, we are considering new permission system in #1286.

**Comment by codeling** [comment]
@takezoe Thanks, great!
