### ISSUE TITLE
Question: Eclipse Mylyn TaskRepository with gitbucket possible?

### ISSUE THREAD

**Issue by dirk-w** [gitbucket/gitbucket#1723]
Hi,

I have a running installation of Gitbucket an use the issues to track my work in my eclipse projects.
Now I asked myself if there is a way to connect the Mylyn Plugin (maybe with the GitHub Connector)?
I could not find anything on the web and in the wiki, so I try this way.

If there isn't a way do you have experience how to implement such a connector?? I have a deep knowledge in Java (a little bit in scala) and can support you or implement such a connector maybe?

Thanks in advance 
kind regards 
Dirk

**Comment by takezoe** [comment]
I guess it does not work currently because GitBucket's issues APIs are minimum. They wouldn't sufficient to work with Mylyn.

**Comment by mgeorge** [comment]
I would suggest looking into providing a Bugzilla compatible wrapper for GitBucket.  A quick survey suggests that most IDEs have support for Bugzilla in their issue management features.  Mylyn has a connector for Bugzilla.
