### ISSUE TITLE
Commit diffs display "Not supported"

### ISSUE THREAD

**Issue by reap3r119** [gitbucket/gitbucket#1727]
**Impacted version**: 4.17.0

**Deployment mode**: Tested on locally-hosted standalone and heroku

**Problem description**:
Viewing the details of a commit displays "Not supported" for every file diff.

![2017-09-30 13-10-41 screenshot](https://user-images.githubusercontent.com/1478389/31048745-1d5612b4-a5e1-11e7-99c7-37981d2eb62d.jpg)

**Comment by uli-heller** [comment]
Same issue here... I'm NOT going to upgrade to 4.17.0.

**Comment by uli-heller** [comment]
I cherry-picked the change and recreated the war file. Now the diff view works for me. Thanks a lot for fixing this so quickly!
