### ISSUE TITLE
Question: build script to new gitbucket ci plugin

### ISSUE THREAD

**Issue by GinoHereIam** [gitbucket/gitbucket#1739]
Hi folks!

I've got a question about the new plugin build script usage.
Can I just enter bash script commands which are available on the host system?

Thanks and best regards
Gino

**Comment by takezoe** [comment]
> Can I just enter bash script commands which are available on the host system?

Yes.

By the way, please use gitter to ask question according to the support guideline because we want to use here to manage bug report and our tasks.
https://gitter.im/gitbucket/gitbucket

or you can ask at the plugin's issues:
https://github.com/takezoe/gitbucket-ci-plugin/issues
