### ISSUE TITLE
View  a list of commits like on github?

### ISSUE THREAD

**Issue by kingdevnl** [gitbucket/gitbucket#1740]
its it possible to View a list of commits like on github?

**Comment by aadrian** [comment]
@kingdevnl have you tried clicking in GitBucket on the same icon as you do in GitHub to see the commits for a repository?

Also please note that for usage/help https://github.com/gitbucket/gitbucket#support

**Comment by kingdevnl** [comment]
Thers no button for it

**Comment by kingdevnl** [comment]
I know that it should be on the Top right next to the FileSearcher,
(Its only seem to be gone in V4.18.0) When i downgrade its there

**Comment by aadrian** [comment]
> Thers no button for it

Yes there is:
![commit_history](https://user-images.githubusercontent.com/140953/31588740-9a629a40-b1f6-11e7-9561-fdaffe4e297f.png)

**Comment by kingdevnl** [comment]
Isnt showing for me this its soo weird

**Comment by reap3r119** [comment]
@kingdevnl Can you take a screenshot of the page?

**Comment by kingdevnl** [comment]
I fixed it by Compilling from src
