### ISSUE TITLE
Lfs not working - Maybe reverse proxy issue?

### ISSUE THREAD

**Issue by tomitrescak** [gitbucket/gitbucket#1767]
Hi, first, let me thank for this AMAZING product. I could not believe how great it is.
I have an issue setting up LFS, normal GIT works fine.

I have gutbucket hidden behind reverse proxy.
It runs at its own url, I have also set up the ROOT url.

This is my .gitconfig

```
[lfs]
  http://my-server
```

But every time I push I receive this:

```
Pushing to http://hugo3.scem.uws.edu.au/tomitrescak/test
batch response: Repository or object not found: http://my-server/tomitrescak/test.git/info/lfs/objects/batch
Check that it exists and that you have proper access to it
error: failed to push some refs to 'http://my-server/tomitrescak/test'
Git LFS: (0 of 1 files) 0 B / 6 B                                              
Completed with errors, see above
```

Oh and I am running Gitbucket 4.18.0

**Comment by tomitrescak** [comment]
Ok thanks to #1536 and the pasted log I have decoded the correct url to

```
#.lfsconfig
[lfs]
    url=http://xxx/git/tomitrescak/test.git/info/lfs
```

**Comment by tomitrescak** [comment]
Having this working ... this is single best thing that happened to me after my daughter was born ;) Thanks for the effort!

**Comment by takezoe** [comment]
Sorry for my delayed reply. You seem to already get to answer, but essentially, it shouldn't need a configuration except just enabling GitLFS by `git lfs install`.

**Comment by tomitrescak** [comment]
@takezoe no worries. My issue as I found out was that I have specified my git repo as:

`http://server/user/repo` as it appears on the web, while correct path is
`http://server/git/user/repo`Then it does not need configuration.
