### ISSUE TITLE
Wiki page incorrect url for 4. Tips - How to Close/Reference issues & pull request

### ISSUE THREAD

**Issue by diufanman** [gitbucket/gitbucket#1770]
**Problem description**:
In the wiki, the escaped url for 
4. Tips - How to Close/Reference issues & pull request
https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-%26amp%3B-pull-request

is incorrect.

The tips can be accessed through the un-encoded url:
https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-&-pull-request

Please fix the link

**Comment by diufanman** [comment]
It is a general issue, URL contains encode "&" (%26amp%3B) are all incorrect:

Same issue found in Tracing & logging
incorrect url:
https://github.com/gitbucket/gitbucket/wiki/Tracing-%26amp%3B-logging

should be
https://github.com/gitbucket/gitbucket/wiki/Tracing-&-logging

**Comment by takezoe** [comment]
@diufanman Anyone can edit the wiki. You can fix directly. 😉

**Comment by diufanman** [comment]
Fixed - change the "&" to "and"

**Comment by takezoe** [comment]
@diufanman Great thanks!
