### ISSUE TITLE
Status check before merging

### ISSUE THREAD

**Issue by diufanman** [gitbucket/gitbucket#1771]
**Problem description**:
Don't know this is a bug or not.
Please see the attached image for the screen shot

In Repository -> Settings -> Branches
I protected a branch but the option "Require status checks to pass before merging" is disabled.

I checked the GitHub for the status API documentation as suggested by the warning, still have no idea how can I make a first status check so that I can check that option.

Can you give an example for this part so that make the option enable?

![image](https://user-images.githubusercontent.com/12424674/32545687-78ce4d06-c4b7-11e7-9e3b-9c1b37047160.png)

**Comment by McFoggy** [comment]
It requires a commit status to have been put for less than 7 days ago I guess.

Commit statuses are pushed by external tools which responsibility is to check that the commit is somehow valid. It can be:
- a CI plugin (in jenkins for example)
- whatever tool using the API to push statuses (code reviews tools, ...)

**Comment by aadrian** [comment]
> Commit statuses are pushed by external tools  ...

I guess the easiest way so far is to just using: https://github.com/takezoe/gitbucket-ci-plugin

**Comment by SIkebe** [comment]
@diufanman All set on this issue?

**Comment by DMmaen** [comment]
> > Commit statuses are pushed by external tools  ...
> 
> I guess the easiest way so far is to just using: https://github.com/takezoe/gitbucket-ci-plugin

How to use this ?

**Comment by zentropia** [comment]
If you are interested in having some sort of pull request peer reviews and manual approval/rejection, you can use the following script as a command line tool to submit commit statuses to the GitBucket API:

- https://gist.github.com/zentropia/e8516555724e98f4f9b2555556a7f8f3
