### ISSUE TITLE
Commits created by GitBucket use user name instead of full name

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1779]
**Original issue**: #125 

**Impacted version**: 4.18

**Deployment mode**:  Standalone app running behind an apache rev proxy

This might be a duplicate of #125 . I'm creating a new issue because:

* the original one ought to be fixed
* I can still observe the error

When committing from the command line, my commits use "Uli Heller" and "whatever@email.com".
Within gitbucket, my full name is "Uli Heller", my login is "uli". Changing a file within gitbucket
produces a commit by "uli" and "whatever@email.com", so the login name is used instead of the full name.

**Comment by McFoggy** [comment]
I do not reproduce the issue on our local 4.18 installation.

Neither on heroku demo app on 4.19

![image](https://user-images.githubusercontent.com/1119660/33768626-0c1a8f1c-dc27-11e7-861a-5e31cad1194b.png)

![image](https://user-images.githubusercontent.com/1119660/33768638-13178978-dc27-11e7-84d1-106174d3e490.png)

**Comment by uli-heller** [comment]
I think I reproduced the error, we might call it a configuration/user error. Below, I described the
behavior using 4.19.3.

- I used to use LDAP auth
- I didn't specify "Full name attribute"
- When doing a login using 4.19.3, my full name changes to the user name used for the login
  (I checked by looking at my profile)
- I don't think this was the case in version 4.18, but maybe I'm wrong
- I reconfigured the LDAP auth using "displayName" for "Full name attribute" and now everything looks OK

**Comment by fredferrao** [comment]
Hi, I am facing this issue on the News Feed, only the username is shown, is this the intended behavior or I too have a configuration error?
gitbucket 4.18.0, with LDAP, CN or displayName configured in  Full Name Attribute
