### ISSUE TITLE
4.19.0 Internal Server Error

### ISSUE THREAD

**Issue by elion** [gitbucket/gitbucket#1787]
## Issue
**Impacted version**: 
4.19.0

**Deployment mode**: 
Standalone app behind nginx. Embedded H2 database.

**Problem description**:
- Cannot view repositories, internal server error. 
- Reproduce: upgrade from 4.18 to 4.19.0

Also, I can not downgrade back to 4.18, Gitbucket says that database version is 4.19.

![image](https://user-images.githubusercontent.com/22718104/33517006-ad771d64-d784-11e7-879a-a053fa53eb1f.png)

`Internal Server Error
java.lang.NoSuchMethodError: gitbucket.core.helper.html.dropdown$.apply$default$5()Lscala/Tuple2;
gitbucket.notifications.html.watch$.apply(watch.template.scala:22)
Plugin.$anonfun$repositoryHeaders$2(Plugin.scala:52)
scala.Option.map(Option.scala:146)
Plugin.$anonfun$repositoryHeaders$1(Plugin.scala:43)
gitbucket.core.html.menu$.$anonfun$apply$6(menu.template.scala:99)
scala.collection.immutable.Stream.map(Stream.scala:415)
gitbucket.core.html.menu$.apply(menu.template.scala:98)
gitbucket.core.repo.html.files$.apply(files.template.scala:42)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$fileList$3(RepositoryViewerController.scala:816)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$fileList$2(RepositoryViewerController.scala:802)
scala.Option.map(Option.scala:146)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$fileList$1(RepositoryViewerController.scala:801)
gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:38)
gitbucket.core.controller.RepositoryViewerControllerBase.fileList(RepositoryViewerController.scala:796)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$7(RepositoryViewerController.scala:155)
gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$7(Authenticator.scala:104)
scala.Option.map(Option.scala:146)
gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$6(Authenticator.scala:99)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
gitbucket.core.util.ReferrerAuthenticator.authenticate(Authenticator.scala:98)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly(Authenticator.scala:93)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly$(Authenticator.scala:93)
gitbucket.core.controller.RepositoryViewerController.referrersOnly(RepositoryViewerController.scala:32)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$3(RepositoryViewerController.scala:155)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)`

**Comment by elion** [comment]
The online demo has the same error
http://gitbucket.herokuapp.com/root/test

**Comment by takezoe** [comment]
It was a version compatibility issue of the bundled notifications plugin. I uploaded GitBucket 4.19.1 with new version of the notifications plugin. Could you try it?
https://github.com/gitbucket/gitbucket/releases/tag/4.19.1

**Comment by elion** [comment]
This fixed the original issue. Still can not access System Administration ../gitbucket/admin/users.

**Comment by takezoe** [comment]
Any error message or stack trace?

**Comment by elion** [comment]
"Not Found".

**Comment by takezoe** [comment]
How do you run GitBucket? Deploy on servlet containers? or `java -jar gitbucket.war`?

**Comment by elion** [comment]
I use it as standalone app `java -jar gitbucket.war` behind nginx with custom Base URL. `/admin/users` worked before 4.19.

**Comment by takezoe** [comment]
Plugins are installed other than default plugins?

**Comment by elion** [comment]
No I have not installed any plugins. I think we can close this issue and I will create a new one.

**Comment by takezoe** [comment]
Indeed. Anyway, I will try to reproduce your situation (access GitBucket with a custom base url).
