### ISSUE TITLE
ssh git-upload-pack

### ISSUE THREAD

**Issue by bc-bjoern** [gitbucket/gitbucket#1791]
Hello,

i try to pull via ssh and i don't know how to debug the following error:

```$ git push --set-upstream live master 
Unknown command: git-receive-pack '/git/b/test.git'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git remote -v 
origin	ssh://git:30000/git/b/test.git (fetch)
origin	ssh://git:30000/git/b/test.git (push)
```

The git-upload and git-receive pack is installed on server and client under /usr/bin and are symlinked to /bin. 

Thanks

**Comment by ritschwumm** [comment]
anything interesting in the server log?

**Comment by bc-bjoern** [comment]
No, just that I'm authenticated successfully. 

`[root@m gitbucket]# su - gitbucket -s /bin/bash
Letzte Anmeldung: Montag, den 04. Dezember 2017, 19:55:55 CET auf pts/1
-bash-4.2$ java -jar gitbucket.war 
2017-12-05 19:35:19.484:INFO::main: Logging initialized @126ms to org.eclipse.jetty.util.log.StdErrLog
2017-12-05 19:35:19.677:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2017-12-05 19:35:20.885:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2017-12-05 19:35:22.340:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-12-05 19:35:22.341:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-12-05 19:35:22.343:INFO:oejs.session:main: Scavenging every 600000ms
19:35:22.567 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
19:35:22.860 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
19:35:22.879 [main] INFO  g.core.servlet.InitializeListener - Check version
19:35:22.879 [main] INFO  g.core.servlet.InitializeListener - Start schema update
19:35:23.683 [main] INFO  g.core.servlet.InitializeListener - Extract bundled plugins
19:35:24.114 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
19:35:24.158 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-notifications-plugin_2.12-1.4.0.jar
19:35:24.406 [Thread-12] INFO  g.core.plugin.PluginWatchThread - Start PluginWatchThread: /opt/gitbucket/.gitbucket/plugins
19:35:24.437 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
19:35:24.437 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
19:35:24.440 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
19:35:24.442 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'QuartzScheduler~job' with instanceId 'job'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

19:35:24.442 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
19:35:24.442 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.3
19:35:24.444 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.
[INFO] [12/05/2017 19:35:24.461] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@2459319c'
19:35:24.487 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
19:35:24.489 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
19:35:25.281 [main] INFO  o.a.s.c.u.s.b.BouncyCastleSecurityProviderRegistrar - getOrCreateProvider(BC) created instance of org.bouncycastle.jce.provider.BouncyCastleProvider
19:35:25.287 [main] INFO  o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of org.apache.sshd.common.util.security.eddsa.EdDSASecurityProvider
19:35:25.431 [main] INFO  gitbucket.core.ssh.SshServer$ - Start SSH Server Listen on 30000
2017-12-05 19:35:25.465:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4f327096{/,file:///opt/gitbucket/.gitbucket/tmp/webapp/,AVAILABLE}{file:/opt/gitbucket/gitbucket.war}
2017-12-05 19:35:25.479:INFO:oejs.AbstractConnector:main: Started ServerConnector@4836ddb5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-12-05 19:35:25.482:INFO:oejs.Server:main: Started @6128ms
19:36:02.582 [sshd-SshServer[11eed657]-nio2-thread-1] INFO  g.core.ssh.PublicKeyAuthenticator - authentication as ssh user bjoern succeeded
19:36:02.738 [sshd-SshServer[11eed657]-nio2-thread-2] INFO  g.core.ssh.PublicKeyAuthenticator - authentication as ssh user bjoern succeeded
19:36:02.860 [sshd-SshServer[11eed657]-nio2-thread-2] INFO  o.a.s.s.s.ServerUserAuthService - Session bjoern@/:20741 authenticated`
