### ISSUE TITLE
PR creation fails from the Pull request section

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1797]
## Issue
**Impacted version**: 4.18

**Deployment mode**: standalone app with an nginx frontend

**Problem description**:
Given a project from user bob.
From a fork, user Joe created a commit in branch b1.
Joe goes to Pull request section of his fork and hits the button "New pull request"

![image](https://user-images.githubusercontent.com/1119660/33651455-2674e212-da66-11e7-91c5-714f8720837e.png)

By default the master branch is taken from Joe fork and the URL states the target is for Bob repository

![image](https://user-images.githubusercontent.com/1119660/33651495-5260f118-da66-11e7-8417-54d4dc762149.png)

Changing the source branch to b1, make the URL to change, user Bob is missing leading in a bad URL.

![image](https://user-images.githubusercontent.com/1119660/33651541-828aa258-da66-11e7-8327-9239cda0d924.png)

Changing manually the url to add bob: `http://morlk964.agfahealthcare.com/joe/demo-ci-jgitver-maven-plugin/compare/bob:master...joe:b1` make the screen to work again

![image](https://user-images.githubusercontent.com/1119660/33651611-d1bd18e2-da66-11e7-81c4-cf50d44e417d.png)

Workaround is;
- either to manually edit the url
- or use the "Pull request" button from the "branches" section
![image](https://user-images.githubusercontent.com/1119660/33651689-105ac5a4-da67-11e7-942c-95f2e378429b.png)

**Comment by takezoe** [comment]
Hmm... I could reproduce it, but it didn't necessarily occur. I will continue to look a occurrence condition.

**Comment by takezoe** [comment]
I found a cause and fixed it!

**Comment by McFoggy** [comment]
you're so efficient! thx
