### ISSUE TITLE
4.19.3: build.sbt still contains 4.19.2

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#1800]
## Issue
**Impacted version**: 4.19.3

I guess you'll have to upgrade all files and release 4.19.4

**Comment by takezoe** [comment]
4.19.3 was released from [maintenance/4.19](https://github.com/gitbucket/gitbucket/tree/maintenance/4.19) branch.

`build.sbt` is here:
https://github.com/gitbucket/gitbucket/blob/maintenance/4.19/build.sbt#L6

**Comment by uli-heller** [comment]
O - I see, my error. Sorry.
