### ISSUE TITLE
gitbucket 4.19.0 on heroku does not work correctly

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1801]
On http://gitbucket.herokuapp.com

when accessing a repository following error is raised

![image](https://user-images.githubusercontent.com/1119660/33768451-6310ccba-dc26-11e7-97fc-9109c9b03f92.png)

uninstalling the Notifications plugin resolves the issue.

**Comment by takezoe** [comment]
Upgraded to 4.19.3.
