### ISSUE TITLE
Git blame view is not displayed correctly

### ISSUE THREAD

**Issue by MasaakiYAMADA** [gitbucket/gitbucket#1805]
## Issue
**Impacted version**: 4.19.2 and 4.19.3

**Deployment mode**: with an http frontend httpd

**Problem description**:
Even if you click the blame tag on the source code display screen, it is no longer displayed correctly.
With the command blame is seen without problems.

**Comment by takezoe** [comment]
It's already fixed in `master` branch and will be released in 4.20.0 at the end of this month.

**Comment by takezoe** [comment]
@MasaakiYAMADA I also fixed in `maintenance/4.19` branch. I can release 4.19.4 if you need it quickly. Do you need it?

**Comment by MasaakiYAMADA** [comment]
@takezoe 
Thank you for your response. 
All right, I can wait. 

For a while we will look at the command. :)
