### ISSUE TITLE
Internal Server Error when trying to protect branch

### ISSUE THREAD

**Issue by source-c** [gitbucket/gitbucket#1806]
## Issue
**Impacted version**: 4.19.3

**Problem description**:
- enter repository settings menu
- select "branches" tab
- "Protected branches" -> select "master"
- Internal Server Error is shown

Error:
`
Internal Server Error
java.time.DateTimeException: Invalid ID for ZoneOffset, non numeric characters found: UTC
`

Trace back:
`
java.time.ZoneOffset.parseNumber(ZoneOffset.java:269)
--
java.time.ZoneOffset.of(ZoneOffset.java:216)
gitbucket.core.controller.RepositorySettingsControllerBase.$anonfun$$init$$17(RepositorySettingsController.scala:182)
gitbucket.core.util.OwnerAuthenticator.$anonfun$authenticate$3(Authenticator.scala:42)
scala.Option.map(Option.scala:146)
gitbucket.core.util.OwnerAuthenticator.$anonfun$authenticate$2(Authenticator.scala:40)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
gitbucket.core.util.OwnerAuthenticator.authenticate(Authenticator.scala:39)
gitbucket.core.util.OwnerAuthenticator.ownerOnly(Authenticator.scala:34)
gitbucket.core.util.OwnerAuthenticator.ownerOnly$(Authenticator.scala:34)
gitbucket.core.controller.RepositorySettingsController.ownerOnly(RepositorySettingsController.scala:25)
gitbucket.core.controller.RepositorySettingsControllerBase.$anonfun$$init$$16(RepositorySettingsController.scala:174)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:33)
org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
...
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
java.lang.Thread.run(Thread.java:748)
`

**Comment by kryskool** [comment]
Hi @source-c 

This issue is already fix in this commit in master https://github.com/gitbucket/gitbucket/commit/adba849ec599779fc8e06e228520467dc30a9c46

Maybe backport un 4.19 branch

**Comment by source-c** [comment]
Yeah, I see #1798 
Thanks a lot. Closing as a dup.
