### ISSUE TITLE
Further plugin extension points

### ISSUE THREAD

**Issue by imeszaros** [gitbucket/gitbucket#1809]
Hello all,

our team is  a big fan of GitBucket, and we would like to extend it via plugins. We would like to attach work hours spent on various issues. To make the integration of these kind of plugins convenient, i think extension points could be made into the listings and forms of various entities (issue, pr, branch, repo, etc), to allow plugins to add shortcut buttons.

For an example on the issue listing and form a plugin could add a new button "Record Work Hours". This button must have access to the issue data to create a redirection URL to the plugin controller with the issue's ID.

What's your opinion?

**Comment by takezoe** [comment]
It looks good. You can add any elements to the sidebar of issues using `issueSidebars` extension point. It might help to create your plugin. See notification-plugin to know how to use this extension point:
https://github.com/gitbucket/gitbucket-notifications-plugin/blob/b87eefb693f5e2e2f01dba5cfa32c1fdfdc9d704/src/main/scala/Plugin.scala#L58-L68

![isues](https://user-images.githubusercontent.com/1094760/34241298-e6ce10cc-e657-11e7-9090-ede4eb85e223.png)

**Comment by imeszaros** [comment]
Thanks for the hint! We can definitely use this option.
