### ISSUE TITLE
Add "Additional filter condition" Example to LDAP Authentication wiki page

### ISSUE THREAD

**Issue by quetsalkoatl** [gitbucket/gitbucket#1810]
I am not sure if this is actually a reason to open an issue:

On the wiki page for the LDAP Authentication Settings https://github.com/gitbucket/gitbucket/wiki/LDAP-Authentication-Settings in the table with the configuration options the option "Additional filter condition" is missing.

After multiple extensive searches on Google, I could not get this to work as I need it. Also I didn't find a lot of information about this in general.
I want to check it a User is memberOf one (or more) in a list of groups so I tried setting it to `(|(memberOf=CN=DEP_S31,OU=Groups,DC=example,DC=com)(memberOf=CN=DEP_S30,OU=Groups,DC=example,DC=com))` or just `(|(memberOf=DEP_S31)(memberOf=DEP_S30))` but nothing worked.

Is this option not for that purpose or working differently?

An actual working example would be greatly appreciated.
Thanks.

**Comment by quetsalkoatl** [comment]
Additional info:
Simply using `memberOf=CN=DEP_S31,OU=Groups,DC=example,DC=com` is working.

**Comment by aadrian** [comment]
@quetsalkoatl 
Since each company structures LDAP a little different, the config process with any software involves allot of trial an error. 
The best approach is to use some LDAP GUI Client (JXExplorer, LDAP Admin, etc) to figure the required config for your system and than if it works apply that setting to GitBucket.

**Comment by quetsalkoatl** [comment]
I found the cause of the issue, it was the outer parenthesis. I could make it work with `|(memberOf=CN=DEP_S31,OU=Groups,DC=example,DC=com)(memberOf=CN=DEP_S30,OU=Groups,DC=example,DC=com)`.

Still, it would be nice to find something like this in the wiki.

@aadrian I was using JXplorer to browse the LDAP.

**Comment by aadrian** [comment]
> Still, it would be nice to find something like this in the wiki.

@quetsalkoatl 
The wiki is editable by the community.

**Comment by quetsalkoatl** [comment]
@aadrian You are right. I guess that's the whole point of this site. Done.

**Comment by baymax11** [comment]
Hii, quetsalkoatl. I'm having trouble configuring ldap auth in gitbucket, once I finish configuring ldap I don't know how to add ldap users to a repo, also I'm unable to login using a ad username, could please help on this ??

**Comment by quetsalkoatl** [comment]
@baymax11 Hi.
I don't think this is the correct place to ask for support (I don't know where you could ask officially though).

So, you can only add LDAP users to a repo if they have logged in at least once to your Gitbucket instance.

As for your issue with the connection to the AD, it's really hard to say without knowing your setup. Is there anything in the log? Is LDAP active on your AD? Does the user you use to connect Gitbucket to your AD have permission to read the LDAP (maybe use an administrator to test at first)?

**Comment by baymax11** [comment]
Thank you so much, now I'm able to do it.

**Comment by quetsalkoatl** [comment]
Glad I could help

**Comment by WanpengQian** [comment]
I think it is better to not add an extra parenthesis to the filter. other software, when user provide a filter, it has parenthesis outside, while paste the filter here just not working. you have to delete the outer parenthesis.
