### ISSUE TITLE
Passwords cannot contain exclamation mark (!)

### ISSUE THREAD

**Issue by kurdtpage** [gitbucket/gitbucket#1811]
## Issue
**Impacted version**: 4.19.3

**Deployment mode**: Standalone app using `java -jar gitbucket.war`, using apache 2, accessed via http://localhost:8080

**Problem description**:
Passwords cannot contain an exclamation mark (!). It says: "Password contains invalid character." in red

**Comment by aadrian** [comment]
@kurdtpage this is not a bug, but a feature.
See https://github.com/gitbucket/gitbucket/issues/1654

**Comment by kurdtpage** [comment]
Great, thanks
