### ISSUE TITLE
Making branch protected throws error

### ISSUE THREAD

**Issue by smckaysmalley** [gitbucket/gitbucket#1815]
When I try to make any of my branches in my repo protected I get the following error:

![image](https://user-images.githubusercontent.com/6520055/34279239-db7b3d34-e66c-11e7-8f03-f901f5703c06.png)

I have verified the issue persists in your online demo hosted on heroku as well.

**Comment by takezoe** [comment]
Duplicated with #1798 and #1806 and it has been already fixed in the master branch. Please wait for the next release on this weekend.
