### ISSUE TITLE
Migration Question

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1823]
I have an instance of GB and could use a bit of help with:

- Want to move ONLY the repos and the user/group configs to a brand new GB instance on another machine. 

- IOW, do not want to copy the entire GB dir tree just the user, groups, admin perms, and repos.

In essence we want to start with a completely clean slate GB instance with no gists or other remnants from the old install.

Is this possible?

TIA,

**Comment by takezoe** [comment]
Use gitter for questions: https://gitter.im/gitbucket/gitbucket

Anyway, there isn't an easy way to do it. You need to copy necessary repositories and related files on the file system, and also need to copy necessary data in the database to the new database by hand.

**Comment by uli-heller** [comment]
@takezoe is the commit really related to this issue?

**Comment by takezoe** [comment]
@uli-heller No, I made a mistake in the commit message. It's #1832.

**Comment by takezoe** [comment]
Closing old questions.
