### ISSUE TITLE
Deleting repository not case sensitive

### ISSUE THREAD

**Issue by Locour** [gitbucket/gitbucket#1826]
# Issue
**Impacted version**: 4.18.0 + 4.20.0

**Deployment mode**: standalone app

## Problem description:
When you have two different repositories, for example "test" and "Test", and you delete the repo "test", intern both are deleted from the database/filesystem but the "Test" repository still exists in the list of repos. </br>
At both situations, when deleting the repository "test" and when taking a look after that at the "Test" repository, the following error message occours:

### Error message:
```` error
Internal Server Error
repository not found: <pathToGitbucket>\home\repositories\<group>\Test.git


org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:582)
--
org.eclipse.jgit.api.Git.open(Git.java:117)
org.eclipse.jgit.api.Git.open(Git.java:99)
gitbucket.core.util.JGitUtil$.getRepositoryInfo(JGitUtil.scala:225)
gitbucket.core.service.RepositoryService.$anonfun$getRepository$2(RepositoryService.scala:227)
scala.Option.map(Option.scala:146)
gitbucket.core.service.RepositoryService.getRepository(RepositoryService.scala:220)
gitbucket.core.service.RepositoryService.getRepository$(RepositoryService.scala:219)
gitbucket.core.controller.RepositoryViewerController.getRepository(RepositoryViewerController.scala:32)
gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$6(Authenticator.scala:99)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
gitbucket.core.util.ReferrerAuthenticator.authenticate(Authenticator.scala:98)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly(Authenticator.scala:93)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly$(Authenticator.scala:93)
gitbucket.core.controller.RepositoryViewerController.referrersOnly(RepositoryViewerController.scala:32)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$3(RepositoryViewerController.scala:155)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:285)
...
````

### Conclusion
It seems that *deleting* a repository is *not* case sensitive.

**Comment by kryskool** [comment]
Hi @Locour 

Can you give us your git version

`git --version`

Regards

**Comment by Locour** [comment]
Hi @kryskool, 

i use git in the following versions:
- version 2.14.1.windows.1
- version 2.13.3.windows.1

Best Regards
Locour

**Comment by takezoe** [comment]
@Locour Is an operatin system of a GitBucket server also Windows?

**Comment by Locour** [comment]
@takezoe Tested on a win 10 machine as well as under ubuntu 16.04 and raspbian stretch

**Comment by uli-heller** [comment]
I cannot confirm this. On Linux, it looks like this using gibtucket-4.20.0, standalone war:

1. Create repos "test" and "Test"
2. Look at the filesystem - both repos exist:
    ```
    uli@ulinuc:~/git/pag/palms$ ls -la ~/.gitbucket/repositories/uli
    insgesamt 0
    drwxrwxr-x 1 uli uli 84 Jan  2 10:11 .
    drwxrwxr-x 1 uli uli 22 Nov 22  2016 ..
    drwxrwxr-x 1 uli uli 76 Jan  2 10:10 test.git
    drwxrwxr-x 1 uli uli 76 Jan  2 10:11 Test.git
    drwxrwxr-x 1 uli uli 76 Jan  2 10:10 test.wiki.git
    drwxrwxr-x 1 uli uli 76 Jan  2 10:11 Test.wiki.git
    ```
3. Delete "test" within gitbucket - ok
4. Look at the filesystem again - repo "Test" still exists:
    ```
    uli@ulinuc:~/git/pag/palms$ ls -la ~/.gitbucket/repositories/uli
    insgesamt 0
    drwxrwxr-x 1 uli uli 42 Jan  2 10:12 .
    drwxrwxr-x 1 uli uli 22 Nov 22  2016 ..
    drwxrwxr-x 1 uli uli 76 Jan  2 10:11 Test.git
    drwxrwxr-x 1 uli uli 76 Jan  2 10:11 Test.wiki.git
    uli@ulinuc:~/git/pag/palms$ 
    ```

So I guess this is not a gitbucket issue. I think it is related to the filesystem on which the repos
are located:

* I'm using ext4, which is a case sensitive filesystem, i.e. "Test" is different from "test"
* Locour is probably using FAT or NTFS, which are case insensitive filesystems, i.e. "Test" is just a different spelling for "test", they are both basically the same object and can't be created/deleted separately

**Comment by Locour** [comment]
@uli-heller Thanks for the reply.
Thats something i didn't think about and yes after testing it in an ext4 environment this issue doesn´t occour. Ty for this hint.

But maybe naming two different repos with the "same" name should be additionally restricted by gitbucket itself. For myself i didn`t think about the filesystem, especially when using a database.

**Comment by uli-heller** [comment]
I propose this check: When creating a new repo, try to access its git files on the filesystem. If they do already exist, then you'll probably run into this issue (... or a similar issue). We should at least display a warning. Maybe we should abort the creation.

**Comment by kounoike** [comment]
@Locour How did you create such two repositories?

I tried to reproduce by these steps:

1. create `Test` repository by root
2. create `test` repository by root

but step 2 throws error and repository doesn't created in repository directory and database.

![20180103-143848 png](https://user-images.githubusercontent.com/6997928/34510035-dced08ba-f093-11e7-97e7-322088482882.png)

**Comment by Locour** [comment]
By root doesnt work, but if you put them in a group gitbucket allows you this

**Comment by uli-heller** [comment]
@kounoike I can confirm this. Creating the repos using a group works fine, i.e. my gitbucket user is named "uli" and I have a group "dp":

* Creating "Test" followed by "test" doesn't work for "uli"
* Creating "Test" followed by "test" works for "dp"

**Comment by takezoe** [comment]
Hm... To avoid such trouble, I suppose GitBucket shouldn't allow case insensitive duplication of users, groups and repositories.

**Comment by takezoe** [comment]
Above duplication checking has been added in #1952.
