### ISSUE TITLE
每次都得手动运行吗?

### ISSUE THREAD

**Issue by jiaxiaogang** [gitbucket/gitbucket#1827]
1. 我下载了v4.2gitbucket.war到centos6.5服务器上;并且在mac上用"终端"java -var gitbucket.war运行起来了;但问题如下:
2. 我关闭终端时,gitbucket跟着关闭;
3. 我每次都必须手动运行终端;并运行java -var gitbucket.war才可以跑起来;
#### 问:我能否不这么麻烦;让gitbucket一直运行在linux服务器上;我随时可以通过xxx.xxx.xxx.xxx:8080访问;

**Comment by takezoe** [comment]
You can run GitBucket in background by the following command:
```
nohup java -jar gitbucket.war &
```

**Comment by jiaxiaogang** [comment]
thanks very much @takezoe ;
