### ISSUE TITLE
Clicking on Submodule requires additional login

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1832]
## Issue
**Impacted version**: 4.20.0

**Deployment mode**: Both as Standalone and under Tomcat 7

**Problem description**:
When clicking on a submodule and the System Setting **Anonymous Access** is set to Deny, you are always asked to log in again even though the link is opening in GitBucket in the same browser where you are already logged in. This is quite frustrating:

![image](https://user-images.githubusercontent.com/20796832/34569178-42e36c70-f168-11e7-87a6-2216a6401681.png)

Cancelling results in an Authorization error:

![image](https://user-images.githubusercontent.com/20796832/34569337-c1e9e92c-f168-11e7-9f6a-a8f857c46b4b.png)

Is it not possible to somehow use the original session when clicking on a submodule?

If you do log in again for this submodule, then the authentication in the new session is retained and you no longer have to log in again when clicking on this submodule in other projects.

**Comment by takezoe** [comment]
Currently, GitBucket generates a link to the submodule's git repository. I will fix it to generate to a link to the repository viewer if submodule is managed on GitBucket.

In addition, it might be nice if submodules are managed on GitHub or BitBucket, then GitBucket generates a link to the repository viewer of them.
