### ISSUE TITLE
Database Editor

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1835]
Sometimes I used H2 console for editing some database fields.
By #1825, H2 concole is removed new database viewer is provided. But it doesn't provide editing operation.

I want to 

- add editing operation to new database viewer

or

- provide H2 console again

**Comment by takezoe** [comment]
> provide H2 console again

Bad idea, we must go forward.

> add editing operation to new database viewer

It makes sense. I agree to improve the database viewer, however I'm not sure what kind of editing operations are supported in H2 console. Is not it substitutable by SQL temporally?

**Comment by kounoike** [comment]
> Bad idea, we must go forward.

Then, provide H2 console again **temporarily** until enough features implemented.

> Is not it substitutableby SQL temporally?

Yes, writing SQL is always substitutable. But it is hard to remember.

I often use H2 console for editing gibucket VERSION field.

```sql
UPDATE VERSIONS SET VERSION = '4.20.0' WHERE MODULE_ID = 'gitbucket-core'
```

is substitutable SQL.

Compared to that, in H2 console, I can rewrite version easily.

I also used H2 console for editing Issue/PR/Comments registered_date field. Because I'm creating GitBucket server stats plugin. It visualize transition of number of Issue/PR/Comments. So, I need dummy data.

**Comment by takezoe** [comment]
> Then, provide H2 console again temporarily until enough features implemented.

Enough features for you? Implementing all features of H2 console is not my plan.

I recommend to setup it at the outside of GitBucket or use more powerful graphical JDBC frontend on your desktop. I suppose it will not take so much time if your development environment is a local machine.

> I often use H2 console for editing gibucket VERSION field.

Does it mean H2 console has a table editor like Excel? Unfortunately, it's not in the scope of the database viewer which should be provided by GitBucket obviously...

**Comment by aadrian** [comment]
+1 for H2 Console to be still active. 

We bundle/activate (for admins only) with every H2 based application, so it should be active in GitBucket too (if H2 is the selected DB).

This H2 Console is not very user friendly (as I see, I suppose the many reason why you created the GitBucket DBViewer in first place :) ), but an admin can do all sort of required jobs with it.

> Does it mean H2 console has a table editor like Excel? 

Yes, and since H2 runs mostly (for performance reasons) in embedded mode, it's the only way to administrate (change/tune/fix) the database.

There are many situations when is not possible to achieve certain tasks with the UI, so being able to quickly edit data for the admin is **very very important**.

**Comment by takezoe** [comment]
Please use this plugin: https://github.com/takezoe/gitbucket-h2console-plugin

**Comment by aadrian** [comment]
@takezoe wow, this is cool :) !

Thank you very much!

P.S. Off-topic, but it's very interesting that many of the GitBucket Plug-ins would be even more useful if they were "Scala(tra) Plug-ins" in fact. I know that there isn't such a thing (yet? :) ) , but many Scala(tra) based webapps would be simplified or made more usable if it were possible to just include a plug-in like this one (or in fact many of the existing GitBucket plug-ins :) ).

**Comment by takezoe** [comment]
GitBucket plugin system is simply hot class reloading. It's usually used to make development quickly by reloading modified classes without restarting a container by frameworks. GitBucket uses this solution to make a dynamic plugin system.

As you know, to make a dynamic plugin system, it tends to be used more heavy solution like OSGi in JVM world.  On the other hand, Jenkins has its own plugin system. I guess it's similar to GitBucket's one. In addition, Java has ServiceLoader for plugins. It's not dynamic, but a standard solution supported in Java standard library.

Anyway, I think there are no standard way to make a dynamic plugin system on JVM, so each applications make their own plugin system in application level. OSGi may be close to the standard, but it's not easy to use.
