### ISSUE TITLE
Database viewer UI

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1836]
In database viewer provided by #1825, when clicking TABLE_NAME, it adds `SELECT * FROM TABLE_NAME`. even if already some SQL in textbox.

![20180107-144443](https://user-images.githubusercontent.com/6997928/34646983-5d584f64-f3b9-11e7-8d1b-ce260dea43bf.png)

It's not useful. So I think it is better behavior:

- Add "Clear" button
- and/or replace all SQL when clicked TABLE_NAME

**Comment by takezoe** [comment]
My plan is adding the context menu for table nodes, and generate select query or run select query directly from the context menu.

**Comment by takezoe** [comment]
Anyway, "Clear" button is useful. I will add it first.

**Comment by takezoe** [comment]
Updated the database viewer:

- Added "Clear" button
- Added the context menu to generate select SQL and it replaces all text in the editor
- "Run query" button became to run only selected text if some text is selected

**Comment by takezoe** [comment]
Rolled back the context menu and implemented same behavior with H2 console when table name is clicked.

- Insert SELECT statement for a clicked table if the editor is empty
- Insert a clicked table name into the caret position if the editor is not empty
