### ISSUE TITLE
Rebase-Merge reverts previous commit/merge

### ISSUE THREAD

**Issue by yusukeh0710** [gitbucket/gitbucket#1838]
## Issue
**Impacted version**: 4.20.0

**Deployment mode**: deployed as standalone jar

**Problem description**:
- 'Confirm merge' with 'Rebase' reverts a previous commit when target review branch is out-of-date with the base branch
- The example of operation for reproducing this problem:
1. `$ git checkout -b branch_a`
1. modify files
1. `$ git push origin branch_a`
1. update base branch such as directly commit-push to base branch, merge through gitbucket, ...etc
1. merge branch_a by 'Confirm merge' with 'Rebase'
===> previous update is removed

**Comment by yusukeh0710** [comment]
Example: commit by above operation#4

![previous_commit](https://user-images.githubusercontent.com/12769277/34671234-19e8b840-f4bd-11e7-8c9c-cdaef057c49c.png)

**Comment by yusukeh0710** [comment]
Example: commit by above operation#5
![merged_commit](https://user-images.githubusercontent.com/12769277/34671322-7abd0590-f4bd-11e7-9b71-7ceb88db80c3.png)

**Comment by yusukeh0710** [comment]
Is it caused by my unexpected usage or software bug?
Thanks.

**Comment by McFoggy** [comment]
@yusukeh0710 sorry I do not see any issue here. The option "rebase-merge" is a kind of rewrite of the history of your commit. Your modification (that occured in branch_a) has been replayed on top of master, creating a new commit. This is exactly the expected behavior.

**Comment by McFoggy** [comment]
I confirm the issue in __4.20.0__. I just tested with the online version and my commit in master, in my case a new file, was not present after the rebase merge commit.
