### ISSUE TITLE
nginx reverse proxy with lfs support

### ISSUE THREAD

**Issue by DevilCoreBlack** [gitbucket/gitbucket#1839]
Hi,

I have installed gitbucket with default port 80 (http://exemple.org) and I want to use nginx reverse proxy to access it with http://different.domain.com/repository

All nginx settings redirect me to http://exemple.org when i enter to http://different.domain.com/repository
Can you write me correct nginx config settings
And tel me - i must set default gitbucket url to exemple.org or must change it to different.domain.com/repository
I use LFS in all my repos
Thx

**Comment by McFoggy** [comment]
Did you tried already to install nginx using our [current wiki page on nginx reverse proxy](https://github.com/gitbucket/gitbucket/wiki/Reverse-proxy-with-Nginx)?

**Comment by DevilCoreBlack** [comment]
Yes and no )))
My Reverse proxy nginx installing on other server (not on git localhost)
I used wiki manual but instead of localhost i put "proxy_pass http://exemple.org" and in "server_name different.domain.com" with used "location /repository"

**Comment by bviktor** [comment]
I don't see how it has anything to do with LFS. We use our "normal" Nginx config for proxying GitBucket and LFS "just works".

**Comment by takezoe** [comment]
Closing old questions.
