### ISSUE TITLE
Internal Server Error when delete a repository

### ISSUE THREAD

**Issue by akiotakahashi** [gitbucket/gitbucket#1842]
**Impacted version**: 4.20.0

**Deployment mode**: standalone app (Windows 10 64bit)
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Problem description**:
GitBucket reports Internal Server Error when try to delete a repository
![error](https://user-images.githubusercontent.com/8023087/34986362-a6031cf6-fafa-11e7-8b53-6c785e077623.jpg)

**Reproduction steps**

1. execute gitbucket
```shell
java -jar gitbucket.war
```
2. create a new repository (named 'test')
3. clone the repository
```shell
git clone http://localhost:8080/root/test.git
cd test
```
4. push a new file
```shell
echo hello > hello.txt
git add .
git commit -m "init"
git push origin master
```
5. try to delete the repo
`GitBucket > Settings > Dander Zone > "Delete This Repository" button`

6. You'll see the error message

**Comment by takezoe** [comment]
See #544 #998 #1649

**Comment by takezoe** [comment]
We are discussing about this issue in #544. As a result of investigation by @kounoike, it seems a JGit issue on Windows. We will continue investigation to report to JGit project, or to fix JGit itself if it's possible.
