### ISSUE TITLE
Jenkins Github Organization plugin difficulties

### ISSUE THREAD

**Issue by dkowis** [gitbucket/gitbucket#1844]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

## Issue
**Impacted version**: 4.20.0

**Deployment mode**: Running as a standalone application

**Problem description**:

I started setting up gitbucket to have a personal "github" to use the Github branch source plugin and Blue Ocean on jenkins. It is able to scan the organization, and that seems to be about as far as it goes.

I'm going to enumerate the problems I had here, and we can talk about how to fix them:

1. Jenkins wants to use a personal access token to authenticate, but gitbucket needs user/password. This is pretty minor, but it'd be nice to be consistent.
1. Jenkins doesn't seem to do anything when the push events happen. I'm not really sure what's going on here, because there were no particular errors, just jenkins didn't build the project as I expected... There's not a history of payloads sent in gitbucket, so I don't know if something went wrong there, or what payload was sent.
1. Jenkins wants to manage webhooks for the organization and the repo. Without having scopes on the access tokens, I guess the user just has to be a manager of the organization. I think the api is not implemented on gitbucket to do this. That might be pretty easy.

Sadly, I'm not actually able to use gitbucket with jenkins to automatically build all my things for me :( Maybe we can easily write the code to do this, but I'm not yet familiar with the code base. Any feedback or "look here" type info would be good.

I'm really impressed with Gitbucket, and I hope we can get this working seamlessly!

EDIT: Updated to reference the plugin I'm using correctly.

**Comment by McFoggy** [comment]
`use the github organization plugin`
which one are you talking about?

There is an example of [GitHub Branch Source Plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin) usage with gitbucket in the wiki referenced in the wiki under the interation section, see the entry ['Gitbucket, Jenkins, Maven, JGitver integration example'](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket)

For you questions:

1. You can define user token in gitbucket, AFAIK they should be useable for API calls.
1. depends on what Jenkins plugin you are using. With [GitHub Branch Source Plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin) payload of standard commits (push, branch creation) are correctly handled and fire immediatly a build in Jenkins, payload of Pull Request do not fire at the moment a build.
1. You can also disable the fact that Jenkins will handle the webhooks and register them by yourself.

**Comment by dkowis** [comment]
It is the GitHub Branch Source Plugin, as I started at that wiki page...hmm.

1: I did use a token first first, and jenkins was unable to authenticate until I put my password in. Could it be because I'm using an LDAP based user? (probably not?)
2. It doesn't seem to be, push events show up in jenkins, but no builds are triggered. I do see in the jenkins logs that a push event was received. I'm not at home right now, so I can't double check my plugins to make sure I didn't screw something up. I'll probably clean them out and reinstall to make sure I didn't install something that conflicts and caused problems.
3. True, but I would like to have it automatically handle the webhooks :) That'd be a feature I'd be willing to work on, or would +1 to see implemented.

**Comment by Rob-Negrete** [comment]
Hi @dkowis,

for me it was a little bit complicated too, but finally I got it with these steps:

1. At GitBucket Create a Personal access token for the given user (it could be a jenkins bot user) http://yourgitbucket.com/:user/_application.

2. At jenkins you need to set a "Secret Text" credential 
http://yourjenkins.com/credentials/store/system/domain/_/newCredentials 
Enter the token into the 'secret' text field.

3. Now you will be available to login at GitBucket with a token.


I hope it helps you.

**Comment by McFoggy** [comment]
@dkowis for 3. ; would be interresting to understand where the problem comes from. Problem in jenkins or bad content of webhook sent by gitbucket. As you propose to help If you could investigate this a bit I am sure it would then help to have this fixed very quickly.

**Comment by joshuacurtiss** [comment]
@dkowis What version of "GitHub plugin" are you using? Perhaps it'll be v1.29.0 or v1.28.1 or something similar...?

**Comment by dkowis** [comment]
Okay, I clobbered jenkins and reinstalled, thinking maybe I buggered up a plugin or something. 

The github branch plugin is: 2.3.2 and github plugin is 1.29.0

I only installed the Blue Ocean plugin, and it pulled in these dependencies, and then, using a user/password credential, I was able to get builds to work, so it's likely something I screwed up.

It'd still be cool to have jenkins be able to manage the webhooks, but perhaps that's something I can work on eventually. I mean now I can fork it to my gitbucket, and have it run builds for me :)

**Comment by McFoggy** [comment]
I just reproduced using the scenario from [Gitbucket, Jenkins, Maven, JGitver integration example](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket) and using latest jenkins version `2.89.3` and latests plugins, most relevants
- [GitHub api plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+API+Plugin): `1.90`
- [GitHub Branch Source Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Branch+Source+Plugin): `2.3.2`
- [GitHub plugin](http://wiki.jenkins-ci.org/display/JENKINS/Github+Plugin): `1.29.0`

Something might have changed in the expected payload of the webhook receiver in jenkins.
Gitbucket has now to fully align with GitHub webhook payload for PR to correct that.

**Comment by McFoggy** [comment]
as defined in v3 [Pull Request Event](https://developer.github.com/v3/activity/events/types/#pullrequestevent) & more precisely in [Pull Request](https://developer.github.com/v3/pulls/#parameters) page, value of field `state` must be either `open` or `closed`.

**Comment by joshuacurtiss** [comment]
This will be excellent incentive for the 4.21.0 release. 😀
