### ISSUE TITLE
GitBucket displays "Not Found" error when copying existing repo

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket#1846]
## Issue
**Impacted version**: 4.20.0

**Deployment mode**: gitbucket war running under Tomcat 7.0.76 on CentOS 7.4. Nginx reverse proxy is also used.

**Problem description**:
When trying to create a new repo by copying an existing one, for a specific repo it shows a "Not Found" error, like this:

https://imgur.com/a/K6bjP

Strangely enough, no error in the Tomcat logs, and it even seems to create the repo nevertheless. No apparent error anywhere, besides this initial one. We already copied another 5 repos from the same host this way without any warning, but this one specific repo errors out first. Any ideas how to track this down?

**Comment by bviktor** [comment]
Okay I think I know. This was the first bigger repo, 42 MB. So I think what happens is that GitBucket doesn't wait until the new repo's files are completely flushed to disk. So all that needs to be done is wait for that, and only then do the redirect to the newly created repo's URL.

**Comment by McFoggy** [comment]
I also confirm that I have seen that in both scenarios:
- creation from remote URL
- fork

**Comment by bviktor** [comment]
Thanks for confirming! I just saw this in the changelog btw:

> Fork and create repository are proceeded asynchronously

Probably related :)

**Comment by takezoe** [comment]
It was a bug. I fixed in 5f0cacd7c1e61365f61b29235e47bae444deafc5.

**Comment by bviktor** [comment]
That was fast, thanks!
