### ISSUE TITLE
Jenkins GitHub Plugin v1.29.0 breaks web hooks with GitBucket

### ISSUE THREAD

**Issue by joshuacurtiss** [gitbucket/gitbucket#1847]
**Impacted version**: 4.18.0

**Deployment mode**: Tomcat

**Problem description**:
Have a successful connection between my Jenkins 2.101 server and my GitBucket 4.18.0 server (sorry for not getting latest version of GB yet). After upgrading some Jenkins plugins, one was the [GitHub Plugin](https://plugins.jenkins.io/github) from v1.28.1 to v1.29.0. 

After the plugin upgrade, my web hooks would fail and running a test would give a message like "Problem accessing /github-webhook/ Signature was expected, but not provided."

This seems to correspond to [GitHub Plug v1.29.0](https://github.com/jenkinsci/github-plugin/releases/tag/v1.29.0) release notes which point to a pull request to [Require a X-Hub-Signature header when receiving a hook payload](https://github.com/jenkinsci/github-plugin/pull/188). 

I hope this research is helpful. 

In the meantime, downgrading to v1.28.1 fixes the incompatibility. 

Sorry for overlooking if this was already addressed in GB 4.19 or 4.20.

**Comment by McFoggy** [comment]
Gitbucket already supports X-Hub-Signature.
You just have to fill the chosen token when defining the webhook:

![image](https://user-images.githubusercontent.com/1119660/35108863-f5688f12-fc74-11e7-8d17-cc4d43f2019a.png)

Can you give it a try please?

**Comment by joshuacurtiss** [comment]
Thank you @McFoggy.  GitHub Plugin v1.29.0 apparently closed the security hole of allowing no signature to be passed. Now a blank security token will be rejected by the GitHub Plugin v1.29.0. 

For anyone else who comes across this problem, you have to create a "Secret Text" entry in the Jenkins credentials area, and assign it to the GitHub Shared Secret configuration, then enter the same shared secret into the web hook configs on the GitBucket side.

## Step-by-step 

### In Jenkins:

1. Click into "Credentials"

2. Create a new "Secret Text" credential.

![jenkins-sig-screenshot-1](https://user-images.githubusercontent.com/6599042/35120408-a0bac2f8-fc5d-11e7-965e-0fcaa6d2a3e9.png)

3. Click into "Manage Jenkins" > "Configure System" and scroll down to your GitHub Servers and click "Advanced..." button.

![jenkins-sig-screenshot-2](https://user-images.githubusercontent.com/6599042/35120451-cf68ec7e-fc5d-11e7-898b-dc8a59f4d202.png)

4. Select the shared text you created earlier.

![jenkins-sig-screenshot-3](https://user-images.githubusercontent.com/6599042/35120476-e0b62f5a-fc5d-11e7-8778-e7f4ab641b74.png)

### In GitBucket:

5. Go into your web hook configuration and type in the same shared secret text.

![jenkins-sig-screenshot-4](https://user-images.githubusercontent.com/6599042/35120513-f8f7d992-fc5d-11e7-84f7-59df5795b765.png)

The web hook should now be accepted.

Hope this helps other folks that encountered the same problem.

**Comment by McFoggy** [comment]
Thank you @joshuacurtiss  for that.

Just a question do you confirm that the key you have generated, stored in Jenkins key store and set in gitbucket webhook IS NOT the authentication key you use to access gitbucket?

![image](https://user-images.githubusercontent.com/1119660/35122468-25d89ab4-fc9f-11e7-8b29-f4e5cd13741b.png)

**Comment by joshuacurtiss** [comment]
Yes @McFoggy, I used special credentials for Jenkins to to authenticate to GitBucket as a "jenkinsbot" user I created, and then a separate, completely different key for "Security Token" specifically for triggering the web hook.

So there are two credentials in the store for the Jenkins/GitBucket integration going on here.

**Comment by bviktor** [comment]
Guys, I'm trying to implement CI builds for GitBucket pushes. So far I've tried with the GitHub Pull Request Builder plugin but I'm having some troubles with it.

My goal is to:
- trigger a build everytime a push is sent for approval, either in a separate branch or pullreq
- report the status back in GitBucket near the merge button

Does the Jenkins GitHub plugin allow this? What credential do I have to enter for the GitHub server?

Also, does the webhook's token need to be entered for each and every GitBucket repo I want this to use with? Coz then it exposes a huge security risk, right?

Related comment: https://github.com/gitbucket/gitbucket/issues/648#issuecomment-365360709

**Comment by bviktor** [comment]
Note: I figured out the GitHub server credential part. It's simply the user's application token. The problem is, the Jenkins GitHub plugin is broken coz it says "failed to verify credentials" or something like that, even though the credentials are fine. Turns out (after a few hours of messing around) that my GitBucket's Nginx frontend apparently has a mixture of SSL ciphers that this stupid plugin doesn't like and can't make an HTTPS connection... will have to open a bug ticket for them, too.

**Comment by joshuacurtiss** [comment]
@bviktor Actually I concur. I had trouble getting GB to trigger Jenkins thru it's HTTPS, even though both my GB and Jenkins are on HTTPS and Jenkins can check out GB repos on HTTPS fine, but I never could get it working the other way.  I actually ended up telling Jenkins to run on HTTPS but left it open on HTTP just so GB could trigger Jenkins. :-/

**Comment by McFoggy** [comment]
@bviktor look at the wiki [automatic builds for maven, jenkins and gitbucket](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket) there I describe how I use `github branch source` plugin to react on push & PR.

**Comment by gradinkov** [comment]
Awesome, thanks a lot, will check it out tomorrow!

**Comment by bviktor** [comment]
Awesome, thanks a lot, will check it out tomorrow!

**Comment by ramvalleru** [comment]
@joshuacurtiss What is the API url of gitbucket. I couldn't find it for my local installation.

**Comment by McFoggy** [comment]
@ramvalleru it is available under `http://HOST:PORT/api/v3` see https://github.com/gitbucket/gitbucket/wiki/API-WebHook

**Comment by ramvalleru** [comment]
@McFoggy I did the entire configuration. Gitbucket sucessfully tested the webhook but when a commit is made to gitbucket, how the jenkins know which pipeline to trigger.

**Comment by McFoggy** [comment]
@ramvalleru I do not use jenkins github plugin but github branch source plugin ; by looking at the [jenkins github plugin doc](https://plugins.jenkins.io/github) it seems it is `JENKINS_BASE_URL/github-webhook/`

**Comment by McFoggy** [comment]
@ramvalleru please switch to [gitter](https://gitter.im/gitbucket/gitbucket) and explain exactly what you want to do with which plugin (github vs github branch source), we're polluting the issue thread let's discuss elsewhere.

**Comment by rajatrawat123** [comment]
My webhooks are not triggering any builds on Jenkins. All I get is an error mentioning 'Malformed repository url'. The clone_url for the repo is something like this http://<gitbucket server>/gitbucket/git/<username>/<reponame>. But the one that is mentioned in the Jenkins logs is missing 'git' in the url.  Below is a screenshot of the Jenkins logs. Could you please help me out finding the solution for this?
![image](https://user-images.githubusercontent.com/26056986/39856091-3c80329a-544c-11e8-9730-6983a685c305.png)
