### ISSUE TITLE
Commit hook for Web editor required

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1854]
I'm writing [heatmap plugin](https://github.com/kounoike/gitbucket-heatmap-plugin). It collects commit information with `git push`. But, it can't count commit which created by Web editor/uploader. I need such plugin hook.

**Comment by takezoe** [comment]
Web editor and uploader should trigger `ReceiveHook` in recent versions of GitBucket. Can you use it?
https://github.com/gitbucket/gitbucket/blob/d9aebbda62e0f2f78768705df2b6efed0198f9d4/src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala#L804-L807

**Comment by McFoggy** [comment]
@kounoike shouldn't your plugin look into the bare git repository using jgit to build the metadata for your heatmap?

**Comment by kounoike** [comment]
@takezoe hmm... but, my plugin doesn't count it. I will check it again.

@McFoggy my plugin counts existing repositories at install time and counts update information by receive hook.

**Comment by McFoggy** [comment]
@kounoike yes sorry I checked the code after having answered, sorry for disturbance.

**Comment by kounoike** [comment]
@McFoggy No problem :smile:

**Comment by kounoike** [comment]
Sorry I found problem in my code. `command.getResult()` returns `NOT_ATTEMPTED`. But my code counts only `OK` command.
