### ISSUE TITLE
We are unable  to see the wiki page https://github.com/gitbucket/gitbucket/wiki/Enabling-SSH-access-to-repository because location header is specified

### ISSUE THREAD

**Issue by toruwest** [gitbucket/gitbucket#1868]
## Issue

**Impacted version**: N/A

**Deployment mode**: N/A

**Problem description**:
This is not a problem of GitBucket software, but may be caused by setting of wiki page. 

We are unable  to see the wiki page https://github.com/gitbucket/gitbucket/wiki/Enabling-SSH-access-to-repository because location header is specified at that page.

If we visit the page, we are redirected to https://github.com/gitbucket/gitbucket/wiki .

Please see the following screen shot of Firefox's log of response header.

![screenshot 2018-01-29 16 32 09](https://user-images.githubusercontent.com/3684590/35498812-2d463d98-0513-11e8-9ed4-ee3367fef16b.png)

**Comment by lx-s** [comment]
If I visit the site, GitHub shows me the web page to "Create a New Wiki Page".

It seems like the particular wiki-page "Enabling-SSH-access-to-repository" has yet to be written.

**Comment by takezoe** [comment]
Sorry, that page hasn't been written yet.
It seems to be redirected to the top page if you don't logged in to GitHub.

**Comment by takezoe** [comment]
Done: https://github.com/gitbucket/gitbucket/wiki/Enabling-SSH-access-to-repository
