### ISSUE TITLE
New database viewer concatenates table names

### ISSUE THREAD

**Issue by bviktor** [gitbucket/gitbucket#1870]
When clicking on table names, the expected behavior is that it replaces the old table name with the new one. Instead, they're concatenated infinitely, e.g.:

~~~
SELECT * FROM ACCESS_TOKENACCOUNTACCOUNT_FEDERATIONACCOUNT_WEB_HOOK
~~~

GB 4.21.2

**Comment by aadrian** [comment]
@bviktor it behaves exactly like the H2 Console :) .

**Comment by uli-heller** [comment]
For me, either of these would be fine:

* `SELECT * FROM ACCOUNT_WEB_HOOK`
* `SELECT * FROM ACCESS_TOKEN,ACCOUNT,ACCOUNT_FEDERATION,ACCOUNT_WEB_HOOK`

Concatenating them with a comma in between would allow me to specify where clauses afterwards...
