### ISSUE TITLE
Openid Connect users ca not authenticate using git CLI client.

### ISSUE THREAD

**Issue by alejandroliu** [gitbucket/gitbucket#1877]
## Issue
**Impacted version**: 4.21.2 (but I suspect affects versions from 4.20 onwards)

**Deployment mode**: standalone app with an http frontend (apache httpd reverse proxy)

**Problem description**:
- Users created used OpenId Connect are not able to authenticate using the "git" command line.
  This means that users can't do `git clone` or `git clone`.
- This is because users created using "OpenId Connect" do not get assigned a password in the
  "ACCOUNT" database table (this is expected, as the authentication is done via OpenId).  This
  is a problem because if the "git" command tries to authenticate with username and password,
  gitbucket only checks the "ACCOUNT" database table.
- A possible solution would be, that when the account is created in [AccountFederationService](https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/service/AccountFederationService.scala#L37), line 37, instead of using an empty string for the password, a default
  possible random password is assigned.  That way, when the user sees their own profile
  they can change it to a known.  Then they can use this known password to authenticate.
- Using the database viewer, I was able to set a password in the Account's table.  Doing so
  allowed me to use the git CLI.

**Comment by takezoe** [comment]
@int128 Could you look at this issue and #1878?

**Comment by int128** [comment]
Sorry, this is a bug. I just thought a user can authenticate by a personal access token but the feature is not implemented yet.

**Comment by alejandroliu** [comment]
Another option would be the code that authenticates "git" connections tries to log in to the OIDC provider (as if it were the browser).  

* Pros: The user can use the same password regardless.
* Cons: Even more implementation than implementing a personal access token.

**Comment by takezoe** [comment]
I merged #1878 because this problem is critical.

However it might not be the best solution. I think using the same password for git authentication is intuitive. On the other hand, using a personal access token might be reasonable because GitHub and GitLab chosen this solution. We should continue to the discussion.

I don't have a strong opinion because I don't use OpenID connect for GitBucket authentication for now. I would like to hear opinions of someone who use it.

**Comment by int128** [comment]
@alejandroliu Sounds good. Does it mean using the following process with the authorization code flow? Is it possible that the git command remembers session?

1. User runs a `git` command.
1. GitBucket sends an authorization URL and `git` command shows it.
1. User opens the URL, enter the ID and password, get an authorization code and enter it to the git prompt.
1. GitBucket sends the code to the IdP, gets an ID token and complete the authentication.

**Comment by alejandroliu** [comment]
@int128 No sorry... After doing some more research, this doesn't seem to be possible.  Apparently the `git` command is unable to do this.  That is why github and bitbucket use the **personal access token** when you enable 2-factor authentication.

**Comment by int128** [comment]
@alejandroliu @takezoe Got. I will take a look at the authentication process and try the personal access token authentication.
