### ISSUE TITLE
Running in raspbian

### ISSUE THREAD

**Issue by vpontin** [gitbucket/gitbucket#1887]
Hi! I'm a bit newbie in linux and i'm trying to use my raspberry 3 model b as a git server, and i'm trying to use gitbucket as server.

i currently trying to run the .war in a USB stick (mounted at /mnt/usb0) in a folder called `gitbucket`. The `start.sh` is the following:

```
#!/bin/sh

cd /mnt/usb0/gitbucket/
while true; do java -jar gitbucket.war --port=15829 --gitbucket.home=/mnt/usb0/gitbucket/data/ --temp_dir=/mnt/usb0/gitbucket/temp &>/mnt/usb0/logs/gitbucket.log; sleep 1; done
```

And then i've added the entry on rc.local, based on [this tutorial](https://www.raspberrypi.org/documentation/linux/usage/rc-local.md):

`/mnt/usb0/gitbucket/start.sh &`

But when i reboot nothing appear in `<pi_ip>:15829`, it always gives me timeout.

What could i do to determine what its not working?

**Comment by yaroot** [comment]
Hi,

- does it start if you log onto it and run `java -jar gitbucket.war`?
- what does the log say?

**Comment by vpontin** [comment]
dunno what i did, but after deleting the whole gitbucket folder and recreating everything from scratch gitbucket now autostart properly via rc.local. Sorry for wasting your time
