### ISSUE TITLE
Question: Is gitbucket compatibile with Discord Webhooks?

### ISSUE THREAD

**Issue by vpontin** [gitbucket/gitbucket#1888]
I got curious because gitbucket claims to be compatible with Github's API.

How can i set up [this](https://support.discordapp.com/hc/en-us/articles/228383668) using gitbucket?

Thanks a lot!

**Comment by takezoe** [comment]
I've never tried Discord, but GitBucket webhook is compatible with GitHub basically. I guess probably GitBucket webhook can work with Discord as alternative of GitHub.

However there are some lack of properties in GitBucket webhooks. So it will not work if Discrod needs these properties.

**Comment by MCmodding4K** [comment]
it doesn't really work :(
I tried all possible URLs and modes, none worked :(

**Comment by vpontin** [comment]
Good to know @MCmodding4K
