### ISSUE TITLE
Too tight file size limitation in Release page (it's 3MB)

### ISSUE THREAD

**Issue by gageas** [gitbucket/gitbucket#1892]
Release page accepts only 3MB by default.
3MB is reasonable limitation for attachment to issues, but it is almost impossible to distribute modern software binaries.
(We know that gitbucket.war is bigger than 50MB)

https://github.com/gitbucket/gitbucket/blob/02a8540875abf8aea26163673cfdb48954f5d531/src/main/twirl/gitbucket/core/releases/form.scala.html#L63

https://github.com/gitbucket/gitbucket/blob/f64d4843f328cbbc8884d309cb6802146d521f7f/src/main/scala/gitbucket/core/util/FileUtil.scala#L82

**Comment by takezoe** [comment]
Agree. Some endpoints like uploading release files and GitLFS should accept larger files than others. We should make them configurable in another configuration items.

**Comment by lavvy** [comment]
So how do one even post a binary file to the repo through command line. For instance uploading a build artifact from a ci to a repo or release. There is nowhere i could find it in the wiki
i have tried this github command from here but no success .

curl 'https://api.github.com/repos/owner/my_repo/releases/:id/assets?access_token=acces_token&name=foo.zip' --header 'Content-Type: application/zip' --upload-file test.zip -X POST

**Comment by takezoe** [comment]
@lavvy Uploading release files API hasn't been supported yet. Could you create an another issue to request it?

**Comment by SIkebe** [comment]
@gageas As per https://github.com/gitbucket/gitbucket/pull/2363#issuecomment-522266565 , the `MaxFileSize` is configurable as follows.
`java -jar gitbucket.war --max_file_size=<max-file-size>`

Your suggestion is to have separate limits between release page and others?

**Comment by gageas** [comment]
@SIkebe 
> Your suggestion is to have separate limits between release page and others?

Yes, it is.
I don't want to allow large file to Issue page, but to Release page.

GitHub accepts ~2GB for Release page, and ~25MB(~10MB for images) for Issue page.

**Comment by skullwritter** [comment]
if @takezoe want's it, i may try to put it on the release as i have in my pull request for UploadTimeout
what u think @SIkebe

**Comment by SIkebe** [comment]
>GitHub accepts ~2GB for Release page, and ~25MB(~10MB for images) for Issue page.

Thanks! @gageas I also found this.
https://help.github.com/en/articles/about-releases#limitations-on-binary-files
https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

I think it's valuable to separate limits :-)
One thing to note is that we should be careful so that users can proceed graceful migration from previous configuration to new one.

**Comment by takezoe** [comment]
Having another parameter for uploading large files sounds good.

**Comment by skullwritter** [comment]
you have the patch-3 from my repo, that includes that
https://github.com/skullwritter/gitbucket/tree/patch-3

**Comment by takezoe** [comment]
How do you think about adding parameters for large files? Maybe, parameter names can be shortened though.

- `--max_file_size_for_large_files`
- `--upload_timeout_for_large_files`

We can use these parameters for large file uploading. It might be only Releases for now, though.

**Comment by skullwritter** [comment]
@takezoe the params available on the new pull request are:
- `--max_file_size_issues=[MAX_FILE_SIZE_FOR_ISSUES]` (defaults to max_file_size)
- `--upload_timeout_issues=[MAX_UPLOAD_TIME_IN_SECONDS_FOR_ISSUES]` (defaults to upload_timeout)
- `--max_file_size_releases=[MAX_FILE_SIZE_FOR_RELEASES]` (defaults to max_file_size)
- `--upload_timeout_releases=[MAX_UPLOAD_TIME_IN_SECONDS_FOR_RELEASES]` (defaults to upload_timeout)
