### ISSUE TITLE
Create ability to define default Git URL (http/ssh)

### ISSUE THREAD

**Issue by edward-of-clt** [gitbucket/gitbucket#1894]
## Issue
**Impacted version**: 4.21.2

**Deployment mode**: standalone app (/var/lib/gitbucket/gitbucket.war)

**Problem description**:
- I need the webhooks to send the ssh url not the http to our Jenkins server. I see no option to change the default, though.
- It would be nice if in the system admin area or within the webhook configuration, you were able to define what link is presented by default.

See image for example:

![image](https://user-images.githubusercontent.com/10331721/36856675-921ff79c-1d44-11e8-9baa-5c82c9e69ce1.png)

**Comment by edward-of-clt** [comment]
Mock up of idea within current codebase:

![image](https://user-images.githubusercontent.com/10331721/36865489-aed962a6-1d5d-11e8-9f41-d423d53d6f85.png)

**Comment by takezoe** [comment]
@edward-of-clt In GitHub, ssh url is set as `ssh_url` property. Does adding this property satisfy your needs? https://developer.github.com/v3/activity/events/types/

**Comment by edward-of-clt** [comment]
Ah beautiful. 
So we are sending the same JSON object as GitHub?

**Comment by takezoe** [comment]
Currently, no. We should update GitBucket to add that property when SSH access is enabled.

**Comment by takezoe** [comment]
@edward-of-clt Sorry, it has been already implemented. Can you use it?
https://github.com/gitbucket/gitbucket/blob/e1c05eb961bc1a264db4292b2024a64836e77edb/src/main/scala/gitbucket/core/api/ApiRepository.scala#L27

**Comment by edward-of-clt** [comment]
It appears that when sending the payload to Jenkins, Jenkins does not recognize the data within the hook to trigger anything. Our preference is to only use ssh. It appears that the only way to trigger builds is for Jenkins to poll the repo.

BitBucket uses this http://jenkins:8080/git/notifyCommit?url=ssh://git@127.0.0.1:29418/demo/nagios.git to trigger the builds, would it be possible to implement a solution to do just that?

A plugin would probably do the job, though.

**Comment by edward-of-clt** [comment]
Currently using the build plugin to do a curl to our Jenkins server.

**Comment by takezoe** [comment]
> BitBucket uses this http://jenkins:8080/git/notifyCommit?url=ssh://git@127.0.0.1:29418/demo/nagios.git to trigger the builds, would it be possible to implement a solution to do just that?

I guess you can do it by just specifying such url as a webhook target url in GitBucket.

![webhook](https://user-images.githubusercontent.com/1094760/36940935-cb392ddc-1f92-11e8-873e-f50402437b8d.png)

**Comment by edward-of-clt** [comment]
I'm going to go ahead and close this, however that above did not really serve as we needed.
We have decided to just bite the bullet and use BitBucket server.

**Comment by takezoe** [comment]
@edward-of-cit Sorry for my inoptimal support. BitBucket server is a great and reasonable tool and has sufficient support from Atlassian if you can pay for it. You will like it!
