### ISSUE TITLE
Add scalafmt to improve code style consistency

### ISSUE THREAD

**Issue by yaroot** [gitbucket/gitbucket#1904]
The code style is fairly inconsistency, and start using a code formatter is the first step to improve it.

I have tested some scalafmt configurations in my [fork](https://github.com/yaroot/gitbucket/tree/scalafmt), this [commit](https://github.com/yaroot/gitbucket/commit/4a7e8ab51a919c25f3868b514929d1b39d740cde) has the reformatted code.

The goal of this ticket is to first discuss if a code formatter is fit for this project, and then to find a suitable configuration.

**Comment by McFoggy** [comment]
+1 for me for anything than can help improving standardization, quality, readiness.

for the content, I would let you scala devs discuss the rules ; I am sure you would hate my java devs preferences ;-)

the only drawback is that once pushed, merges/comparing with old versions will lead in numerous diffs/conflicts. PRs can be difficult to integrate afterwards: there will be a need to apply the same formatting rules on the PR if the PR originated from an older commit.

**Comment by takezoe** [comment]
+1 It will help to reduce unnecessary concern in contributors and developers. It would be much better if we could enable formatters for Twirl templates, JavaScript and CSS as well. However we have to separate JavaScript from Twirl templates before doing it.

Anyway, enabling code formatter is one of good habits in the team development.

**Comment by yaroot** [comment]
I made a PR for scalafmt. As for twirl templates and js/css, should we revisit #1430?

**Comment by takezoe** [comment]
@yaroot Thanks, I merged a pull request which adds scalafmt and reformatted all Scala code. Formatting other kinds of files is a much more difficult task. In particular, I don't know whether it's possible to format Twirl templates. Anyway, it should be handled as an another issue.
