### ISSUE TITLE
Any reason, why markdown editor is absent?

### ISSUE THREAD

**Issue by demon101** [gitbucket/gitbucket#1906]
**Problem description**:
For some users markdown editing without visual editor not so easy
is there a reason for the lack?

where are few nice editors:

https://github.com/sparksuite/simplemde-markdown-editor
https://pandao.github.io/editor.md/
https://rawgit.com/Grafikart/JS-Markdown-Editor/master/dist/demo.html

**Comment by demon101** [comment]
#1793

**Comment by aadrian** [comment]
@demon101 nobody implemented it yet.
