### ISSUE TITLE
Cannot login or access repos after upgrade from 4.4. to 4.22.

### ISSUE THREAD

**Issue by CodingTanna** [gitbucket/gitbucket#1920]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.22.0

**Deployment mode**: Standalone java -jar gitbucket.war

**Problem description**:
I upgraded from gitbucket 4.4. to 4.22.0. The described is to replace the github.war, so I did it. After replacing I can't login and can't push repositories. 
Log after login with loginform(credentials are correct):
`INFO  g.core.service.AccountService - Failed to authenticate:`

Trying to access the repos url throws 404.
At .gitbucket/data and .gitbucket/repositories all repos and user are present.

**Comment by takezoe** [comment]
Can you find any errors in the bootstrap log?

**Comment by CodingTanna** [comment]
What is the bootstrap log? From starting gibucket? 
`root@mydomain:/home/gitbucket# sudo java -jar gitbucket.war --port=8089
2018-03-28 14:39:43.250:INFO::main: Logging initialized @128ms to org.eclipse.jetty.util.log.StdErrLog
2018-03-28 14:39:43.385:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2018-03-28 14:39:44.527:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2018-03-28 14:39:45.645:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-03-28 14:39:45.646:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-03-28 14:39:45.651:INFO:oejs.session:main: Scavenging every 660000ms
14:39:45.822 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
14:39:46.077 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
14:39:46.093 [main] INFO  g.core.servlet.InitializeListener - Check version
14:39:46.093 [main] INFO  g.core.servlet.InitializeListener - Start schema update
14:39:46.709 [main] INFO  g.core.servlet.InitializeListener - Extract bundled plugins
14:39:47.065 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
14:39:47.091 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-notifications-plugin_2.12-1.4.0.jar
14:39:47.247 [Thread-12] INFO  g.core.plugin.PluginWatchThread - Start PluginWatchThread: /root/.gitbucket/plugins
14:39:47.275 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
14:39:47.275 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.
14:39:47.278 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
14:39:47.279 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'QuartzScheduler~job' with instanceId 'job'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

14:39:47.279 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
14:39:47.280 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.3
14:39:47.281 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.
[INFO] [03/28/2018 14:39:47.290] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@20e3c449'
14:39:47.308 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
14:39:47.310 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
2018-03-28 14:39:47.726:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@3c3c4a71{/,file:///root/.gitbucket/tmp/webapp/,AVAILABLE}{file:/home/gitbucket/gitbucket.war}
2018-03-28 14:39:47.738:INFO:oejs.AbstractConnector:main: Started ServerConnector@2dc3271b{HTTP/1.1,[http/1.1]}{0.0.0.0:8089}
2018-03-28 14:39:47.738:INFO:oejs.Server:main: Started @4618ms
`

**Comment by takezoe** [comment]
> What is the bootstrap log? From starting gibucket?

Yes, but it looks no problem.

Do you use LDAP integration? If no, try to update the password of your account in the database to `dc76e9f0c0006e8f919e0c515c66dbba3982f785` directly. You should able to login with a default root password (It's `root`).

**Comment by CodingTanna** [comment]
I found the problem. The service locked like that:
`[Unit]
Description=GitBucket service
After=syslog.target
After=network.target

[Service]
User=gitbucket
ExecStart=/usr/bin/java -jar /home/gitbucket/gitbucket.war --port=8089 --host=127.0.0.1

[Install]
WantedBy=multi-user.target`

I had to change the host... thank you :)
