### ISSUE TITLE
Uploading release asset file with api

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#1925]
I think it will be fine to add an api to upload files to a repository. This will enable the upload of job artifacts from builds and other integrations . Github actually supports all create update delete (crud) . I am thinking this should try and fix #1892

**Comment by lavvy** [comment]
A lot @kounoike  . With the introduction of lfs , there is virtually nothing you cant store. Take for instance this directory https://github.com/iNPUTmice/ComplianceTester/tree/master/reports , it stores test results from different servers and stores on github where it could be subsequently analyzed.
For us we have an automated system that carries out tests at intervals and is expected to upload the result to git for versioned analysis.
Secondly some build artifacts , depending on how or where it was built should find it better to upload a single without cloning the full folder.
For us we have situations where we wish to upload several large files without cloning the whole repo.

**Comment by kounoike** [comment]
@lavvy Sorry, I didn't ask **useful situations**. I ask any **tool** such as Jenkins plugin. GitHub's document doesn't provide complete specifications.  So, we implements partial behavior and check compatiblity with some major tool.

**Comment by lavvy** [comment]
Wow, maybe I am not still understanding though @kounoike but I think it should be made for any uploading tool like curl should be able to upload a content. 
I think this should just be the same thing as web ui file upload with an api front-end so that other applications can utilize it.
