### ISSUE TITLE
Gitmesh integration

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#1926]
i just felt like to start this discussion . How is gitmesh going to marry gitbucket? is it as a plugin or as a merge to the upstream ? And is it not time to start testing the marriage.

**Comment by takezoe** [comment]
Thanks for mentioning this topic! I started gitmesh targeted to be an option of backend of GitBucket when we will need scalability in GitBucket. (Using distributed file system is an another option we can choose right now.)

There are some issues we have to consider other than gitmesh as follows:

- How to make redundancy of GitBucket itself?
- Clustering of servlet based application requires session replication basically. Should we do it? or consider another solutions?
- How to scale the database? In my opinion, we can use database-dependent feature to solve this issue.
- Currently, the basic system configuration is stored as a file. We might have to move it to the database.
- How to handle files outside of git repositories such as attached files?
- How to implement direct bare repository operations like editing files inside of git repositories or merging pull requests?

We should consider the direction of strategy to add scalability to GitBucket as a first step of this discussion.

**Comment by McFoggy** [comment]
> We should consider the direction of strategy to add scalability to GitBucket as a first step of this discussion.

I fully agree. Gitbucket positioned itself as a 'simple to use' git platform. 
Before going into scalability direction, shouldn't Gitbucket development efforts be concentrated in making the platform fully friendly _(as in 'simple to use')_ included in term of administration _(logging, backup/restore, ...),_ plugin management, authentication systems (OAUTH, ...) and probably other topics.

**Comment by takezoe** [comment]
> have more than one GitBucket instance on the same machine (or different ones) so that Orgs or repos get separated/distributed.

Exactly. Federation is one solution to make scalability on GitBucket.

In my opinion, redundancy of GitBucket is important even for small teams. So I think we should consider about this topic before scalability. A database can be clustered in the database side when we use an external database. A remaining issue is clustering of GitBucket instances.

Anyway, scalability is an option in the future. In fact, I have been asked about scalability of GitBucket from some users. I think it would be nice if we can make it but we must keep GitBucket as **simple to use**.

**Comment by lavvy** [comment]
I don't think this would be that of a big problem. Git has so much
simplified scaling in my own thinking.
The two important features of scaling is sharding and replication.
And git has cherrypicking for sharding and mirroring for replication, which
gitmesh can just gum the two features nicely together to give gitbucket
repos redundancy.
The good thing about it is that you shard how you want and when you want .

@aadrian and @takezoe actually pointed it out the way I was thinking it. I
have always felt that git should not follow other approaches from other
projects in scaling its repos, instead it should rely on its approach
whereby everything is guided by commits. Then the database  will be
external and then be guided by it's own best practices in scaling.

**Comment by takezoe** [comment]
Closing old questions.
