### ISSUE TITLE
two or more e-mail address

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1935]
GitBucket requires just one e-mail address.

Many companies sometimes change their name. In most case the e-mail address will change as well.

In such situation, user (or administrator) can change user's e-mail address. However, in such case GitBucket will not be able to resolve the old commit's name for that user.

I think it is better that:

- user has one primary mail address which used for notifications and lookup for git commit log
- user can has more mail address which used only lookup for git commit log

**Comment by aadrian** [comment]
@kounoike dupliate of https://github.com/gitbucket/gitbucket/issues/652
