### ISSUE TITLE
OIDC redirect URI does not respect x-forwarded-proto header

### ISSUE THREAD

**Issue by int128** [gitbucket/gitbucket#1941]
I am using GitBucket behind a SSL load balancer. I found an OpenID Connect redirect URI is `http` even if `x-forwarded-proto` header is set to `https`. It is strange that others such as login redirect are `https`.

We can fix a redirect URI to `https` by setting Base URL in the system settings for now, but it should be set by the `x-forwarded-proto` header.

## Issue
**Impacted version**: 4.23.0

**Deployment mode**: 
```
Web Browser
↓HTTPS
AWS ALB (with ACM SSL certiticate)
↓HTTP
nginx (Kubernetes Ingress Controller)
↓HTTP
GitBucket (Kubernetes pod)
```

The nginx is configured to passthrough `x-forwarded-*` headers.

**Comment by int128** [comment]
A redirect URI is generated from `baseUrl` property in the controller:

https://github.com/gitbucket/gitbucket/blob/cadd1282991762b5c85f10dfadce170f4d4af401/src/main/scala/gitbucket/core/controller/IndexController.scala#L112-L113

`baseUrl` is resolved from `HttpServletRequest`:

https://github.com/gitbucket/gitbucket/blob/cadd1282991762b5c85f10dfadce170f4d4af401/src/main/scala/gitbucket/core/service/SystemSettingsService.scala#L179-L184

On the other hand, scalatra redirect respects the header as follows:

https://github.com/scalatra/scalatra/blob/be9fc5119e6e34c4882d848cf86d9808acea8b68/core/src/main/scala/org/scalatra/ScalatraBase.scala#L696-L700

Any possible solutions?

**Comment by yaroot** [comment]
cannot reproduce, can you share some more details?

![screenshot_2018-04-03t20 14 50 08 00](https://user-images.githubusercontent.com/42634/38248661-c4fa7420-377b-11e8-8e0e-33c45acc6a0b.png)

**Comment by int128** [comment]
I created the OIDC client on Keycloak:

- Issuer: `https://keycloak.example.com/auth/realms/hello`
- Client ID: `gitbucket`
- Valid Redirect URIs: `https://gitbucket.example.com/signin/oidc`

configured GitBucket:

- Base URL: **left blank**
- OpenID Connect: enable

configured nginx proxying the following headers:

```
Request Headers:
	accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
	accept-encoding=gzip, deflate, br
	accept-language=ja,en-US;q=0.9,en;q=0.8
	connection=close
	dnt=1
	host=echoserver.example.com
	upgrade-insecure-requests=1
	user-agent=Mozilla/5.0 (Macintosh; ...
	x-amzn-trace-id=Root=1-5ac39a5f-c7ff25c093719d38b4593d90
	x-forwarded-for=***.***.***.***
	x-forwarded-host=echoserver.example.com
	x-forwarded-port=443
	x-forwarded-proto=https
	x-original-forwarded-for=***.***.***.***
	x-original-uri=/
	x-real-ip=***.***.***.***
	x-scheme=https
```

And then I clicked the OIDC button and GitBucket redirects to:

```
https://keycloak.example.com/auth/realms/hello/protocol/openid-connect/auth?response_type=code&client_id=gitbucket&redirect_uri=http%3A%2F%2Fgitbucket.example.com%2Fsignin%2Foidc&scope=openid+email+profile&state=...
```

**Comment by yaroot** [comment]
Can you post your `~/.gitbucket/gitbucket.conf`, just the `base_url=` line if it exists.

**Comment by int128** [comment]
`gitbucket.conf` does not have `base_url`.
If I set the base url in the system settings, an OIDC redirect URI becomes `https`.

**Comment by int128** [comment]
I will try changing `baseUrl` implementation to respect the header:

https://github.com/gitbucket/gitbucket/blob/cadd1282991762b5c85f10dfadce170f4d4af401/src/main/scala/gitbucket/core/service/SystemSettingsService.scala#L179-L184

**Comment by yaroot** [comment]
Can you test #1942?

**Comment by int128** [comment]
Sorry I struggle to build and run an executable war. Please wait for a moment.

**Comment by int128** [comment]
I have tested the latest commit of #1942 and it works perfectly. Thank you!

```
POST https://gitbucket.example.com/signin/oidc

302
location: https://gitbucket.example.com/auth/realms/hello/protocol/openid-connect/auth?response_type=code&client_id=gitbucket&redirect_uri=https%3A%2F%2Fgitbucket.example.com%2Fsignin%2Foidc&scope=openid+email+profile&state=...
```
