### ISSUE TITLE
Contents API seems unavailable in Version 4.23.0

### ISSUE THREAD

**Issue by m-bermel** [gitbucket/gitbucket#1943]
## Issue
**Impacted version**: 4.23.0 (possibly also 4.22.0 but can't test right now)

**Deployment mode**: war deployed in Tomcat 8.0.36
**Problem description**:
- Access to /api/v3/repos/:owner/:repo/contents/:path results in a 404 error code
- Unfortunately there are no exceptions visible in logging
- Therefore build tools like Jenkins can't find e.g. Jenkinsfile

**Tomcat access log prior to 4.23.0 (should have been version 4.21.2)**
`[29/Mar/2018:13:45:32 +0200] "GET /api/v3/repos/:owner/:repo/branches HTTP/1.1" 200 721
[29/Mar/2018:13:45:32 +0200] "GET /api/v3/repos/:owner/:repo/contents/?ref=refs%2Fheads%2F:branch HTTP/1.1" 200 3270`

**Tomcat access with 4.23.0**
`[06/Apr/2018:11:20:02 +0200] "GET /api/v3/repos/:owner/:repo/branches HTTP/1.1" 200 721
[06/Apr/2018:11:20:02 +0200] "GET /api/v3/repos/:owner/:repo/contents/?ref=refs%2Fheads%2F:branch HTTP/1.1" 404 23`

Note that i replaced the exact owner, repository and branch with the respective placeholder _:owner_, _:repo_ and _:branch_

**Comment by takezoe** [comment]
It will be fixed in #1940.
