### ISSUE TITLE
Javascript slowdowns for large pull requests

### ISSUE THREAD

**Issue by dkowis** [gitbucket/gitbucket#1945]
## Issue
**Impacted version**: 4.23.0

**Deployment mode**: Deployed standalone .war file

**Problem description**:
Basically, with a large pull request, the page lags on javascript execution long enough to cause firefox to ask if I want to wait or kill the script. 

It's pretty easy to recreate, just make a significant amount of changes. It'd be a good first step to at least only execute that javascript when the tab for viewing the source files is executed. Long term would be to implement some kind of perpetual loading, or efficient loading of those diffs so that it doesn't cause slowdowns trying to do it all at once.

Sample of size that causes a problem: https://gitbucket.light.kow.is/dkowis/monopolytracker/pull/1 is the actual pull request
![image](https://user-images.githubusercontent.com/28048/38473290-4235e5a2-3b53-11e8-929f-ccfe8625eb18.png)

**Comment by takezoe** [comment]
Exactly. For now, GitBucket doesn't display diff if the pull request contains large number of files. However, maybe we need another solution like lazy rendering for large diff.

**Comment by muzuiget** [comment]
I can confirm, it does't need to a large change, just 200 lines change will cause Firefox to popup that asking.

**Comment by pluk77** [comment]
Is there perhaps a way to render the UI with all diffs 'closed' by default and only open them (and therefore render the actual diff ui) upon clicking on it? This would solve most problems with large PRs as files generally need to be looked at one at a time anyway.

If you point me in the direction of the JS that renders the UI I can perhaps assist in finding a solution?

**Comment by takezoe** [comment]
Will be dealt in #3157
