### ISSUE TITLE
Turn of "Compare & pull request" button

### ISSUE THREAD

**Issue by iAmNaz** [gitbucket/gitbucket#1970]
## Issue
**Impacted version**: 4.20.0

**Deployment mode**: *standalone app with http frontend (apache using mod_proxy)*

**Problem description**:
Hi, how do I turn off the "Compare & pull request" button that appears below the repository description without turning off pull request just the list of suggestions?

**Comment by lavvy** [comment]
yeah  i have been thinking of this too . sometimes it can be discomforting

**Comment by kounoike** [comment]
I don't know how GitHub detect to suggest to create PR. But I think it is sufficient to detect by branch's last commit date.

- suggest to create PR for branch which contains recently pushed commit (for example, 3 days)
- don't suggest old branch

How about this plan?

**Comment by takezoe** [comment]
Fixed in 6029d9ef29f9c6fa2b2e535bee4e44f8bd4a9684.
