### ISSUE TITLE
Trigger a Jenkins Pipeline after a Push

### ISSUE THREAD

**Issue by llaaccssaapp** [gitbucket/gitbucket#1978]
Hi.

I try to trigger a jenkins pipeline after i do a push in a gitbucket repo. 
The GitBucket plugin in jenkins only alows me to add this trigger in a freestyle project and not in a pipeline. 
My try with the github jenkins plugin was not successfully. If i use the github plugin, i see the push in jenkins log, but no builds are triggered. Can anyone help how to trigger a jenkins pipeline build after push in gitbucket? 

Thank you very much.

**Comment by McFoggy** [comment]
the easiest is to use `github branch source plugin` as described in the [wiki](https://github.com/jgitver/jgitver-maven-plugin/wiki/automatic-builds-for-maven%2C-jenkins-and-gitbucket). It will allow you to use pipeline and to offer a callable webhook to automatically trigger builds on commit/branch/pr/tags.

**Comment by llaaccssaapp** [comment]
Is there also somewhere a wiki, how to do this with a normal pipeline build?

**Comment by McFoggy** [comment]
Would you mind writing down here on in a wiki page how you have setup your build/jenkins/gitbucket (plugins version, configuration, some screenshots,...). That will certainly help the community and the next guys that will come after.

Thanks for your participation.
