### ISSUE TITLE
What if forks button be at the top right

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#1993]
What if the forks button leave the side menu to the top right of the repository. Just thinking aloud.

**Comment by takezoe** [comment]
In fact, it was there before, but I moved it to the side menu in modifying design. It was important make a clear difference with GitHub at that time. However I guess that applying AdminLTE was enough for the purpose, so I wonder if we can move the button to there again.

**Comment by lavvy** [comment]
Yeah. I followed the github stuff then. But we are now using an entirely
different theme altogether adminLTE.

Easily accessible fork button helps for better collaboration.

**Comment by kounoike** [comment]
How about this?

![image](https://user-images.githubusercontent.com/6997928/39954878-dc8a88f6-5601-11e8-90d5-38639a00a2f5.png)

**Comment by takezoe** [comment]
I created a pull request #2005, but I'm not sure which interface is better.

**Comment by kounoike** [comment]
I'm creating "template from repository" feature. I think that it is advantageous to aggregate repository creation menus.

![20180512-162455](https://user-images.githubusercontent.com/6997928/39955330-1f5db954-5608-11e8-8162-180686103a06.png)

But, #2005 has at least an advantage. It provides fork count.

**Comment by lavvy** [comment]
I think the fork count mode is cool.

**Comment by kounoike** [comment]
hmm... GitBucket normally shows "number of XXX" as badges on the left side menu. So, fork count should be rendered as badge too.

**Comment by takezoe** [comment]
Fork has a different concept from repository creation (or copying). It should be independent of them.
