### ISSUE TITLE
ZIP/tar.gz archive doesn't contain LFS files

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1998]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.24.1, current master

**Deployment mode**: standalone/sbt jetty:start

**Problem description**:

step to reproduce:
- push some files as LFS
- get ZIP by use "Download ZIP" button or 0tag/release page's link

problem:
ZIP doesn't contains LFS file contents. It only contain pointer.

**Comment by PeppeJ** [comment]
Similarly cloning a repo (via web gui) also does not clone LFS files properly, only the pointer which won't work.
