### ISSUE TITLE
Windows - Tomcat - Where is ~/.gitbucket/gitbucket.conf?

### ISSUE THREAD

**Issue by cap5lut** [gitbucket/gitbucket#1999]
Hi,
i wanted to try out GitBucket. I used it via Tomcat on Windows:
Gitbucket 4.24.1
Tomcat 9.0.8 (as service)
Windows 10

After some playing around with it, and doing some initial configurations, I broke it because I forgot to add the protocol to the URL base just as in https://github.com/gitbucket/gitbucket/issues/1071 . But because I'm on Windows I have issues locating the configuration file.

**Comment by SIkebe** [comment]
DId you check `C:\Users\{user}\.gitbucket`?

**Comment by cap5lut** [comment]
Yeah, there it wasnt, but that `{user}` brought me to the idea to check where system has it's home directory and there I found it.
It located at `C:\Windows\system32\config\systemprofile\.gitbucket`
Thanks for your help!
