### ISSUE TITLE
Line comment disappears.

### ISSUE THREAD

**Issue by himeyon** [gitbucket/gitbucket#2002]
## Issue
**Impacted version**: 4.24.1

**Deployment mode**: glassfish5.0

**Problem description**:
- It will disappear when reloading the browser after entering line comments for commit.

![01](https://user-images.githubusercontent.com/4468822/39901215-1325449c-5502-11e8-84cc-f52830f190b9.png)
![02](https://user-images.githubusercontent.com/4468822/39901222-1b1cabc2-5502-11e8-8608-07eb63a2b71e.png)

Reload browzer.

![03](https://user-images.githubusercontent.com/4468822/39901225-1d36a52a-5502-11e8-8152-3e121724b6b0.png)

**Comment by SIkebe** [comment]
I can repro this, too. 4.23.1 works fine.
