### ISSUE TITLE
Edit button on pull request screen does not work

### ISSUE THREAD

**Issue by c-yan** [gitbucket/gitbucket#2021]
## Issue
**Impacted version**: 4.24.1

**Deployment mode**: Windows Server 2016 + Apache 2.4.27 + JRE 8u161 + Tomcat 8.5.20

**Problem description**:
Nothing happens when I press the "Edit" button to the left of the "New pull request" button on the pull request screen.　(Events are not attached when viewed in browser development tool)

**Comment by SIkebe** [comment]
@c-yan duplicate of #2000

**Comment by c-yan** [comment]
@SIkebe Sorry, I searched by "Edit", but I failed to find it.
