### ISSUE TITLE
Hide version string in login screen

### ISSUE THREAD

**Issue by Brice-xCIT** [gitbucket/gitbucket#2023]
## Issue
**Impacted version**: 4.24.1

**Deployment mode**: standalone

**Problem description**:
In order to make it harder for an attacker to identify what version of GitBucket is running on a public server, it would be nice to have an option (or a default behavior?) of hiding the version string on unauthenticated areas of the app (e.g. login screen).

**Comment by lavvy** [comment]
Yeah I am thinking in that direction too. I am feeling that the server
version should be somewhere inside the admin section. Because I believe the
users job is to use and admins job is to administer :)

**Comment by Brice-xCIT** [comment]
@lavvy I agree! Normal users probably don't need the information either.

**Comment by takezoe** [comment]
Right. I will move it to the admin page.
