### ISSUE TITLE
"Settings" not visible to Collaborator with Admin rights

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#2031]
## Issue
**Impacted version**: 4.24.1

**Deployment mode**: *Tomcat 7*

**Problem description**:
- We have a private repository called ToolsGroup/Sequencer 
- User is a member of ToolsGroup but not a Manager of this group
- User has specifically been added as an Admin Collaborator for this repo, so that she can access the repo Settings
- When she logs in, the "Settings" link is not available in the menu.

From my point of view the Collaborator Admin permissions must override the Group permissions, otherwise there is no point in having the Admin permission in the Collaborators tab.

Just testing as I write this issue and it looks like she has the correct permissions because if she puts in the URL for the Settings page directly, she can access the pages. So it looks like the only problem is that the "Settings" entry is missing from the menu.

**Comment by kounoike** [comment]
I reproduced this.

I found:

- `user2` is **not** a member of ToolsGroup
- `user2` as an Admin collaborator for this repo.
- `user2` can't see `Settings` link in the menu

**Comment by PaulAdams-Conti** [comment]
Not fixed in 4.25.0. Still no Settings in menu, but still can access the settings via URL:

![image](https://user-images.githubusercontent.com/20796832/40644832-b167b628-6324-11e8-86f0-dc67f18af3a0.png)
