### ISSUE TITLE
[Question] Login/logout seems to redirect

### ISSUE THREAD

**Issue by aanno** [gitbucket/gitbucket#2033]
I've set up gitbucket 4.24.0 as a docker container (f99aq8ove/gitbucket) behind a reverse apache proxy as documented (https://github.com/gitbucket/gitbucket/wiki/Reverse-proxy-with-Apache).

This setup is well and healthy - BUT I got redirected when I try to log in (or log out). The redirect will use the docker network intern host name ('gitbucket_container' in my case). Certainly the browser cannot resolve the name (typing in the real address gets me back and now I'm logged in as well).

I tried to use the --host option. But in this case gitbucket wants to bind to the given host name (and this - of course - also fails).

Perhaps I'm missing something here, but maybe gitbucket needs a configureable redirect URL for my use case?!?

**Comment by kazuki43zoo** [comment]
Probably, you can resolve difference of hostname/port using "Base URL" in System Settings.

**Comment by takezoe** [comment]
While "Base URL" is configured in `GITBUCKET_HOME/gitbucket.conf`, you can specify it as a system property as `-Dgitbucket.base_url` as well.

In fact, all parameters in `gitbucket.conf` can be configured by the system property like `-Dgitbucket.<key>`. This is nice way to configure GitBucket in docker. [f99aq8ove/gitbucket](https://hub.docker.com/r/f99aq8ove/gitbucket/) container seems to support `JAVA_OPTS` to pass options to JVM, so I think passing via this environmental variable is the easiest way to configure your container.

**Comment by aanno** [comment]
Thank you for the prompt and helpful comments. Of course, I also missed that the "Base URL" could be set in the web gui from the "User -> System administration -> System settings" if logged in as administrator.
