### ISSUE TITLE
GitBucket returns [object Object] in IE 

### ISSUE THREAD

**Issue by neriudon** [gitbucket/gitbucket#2038]
## Issue
**Impacted version**: 4.25.0

**Deployment mode**: standalone app

**Problem description**:
GitBucket returns `[object Object]` in IE ver.11 when I click toggle buttons in comment-list. 
It works fine in Google Chrome ver.64.0.3282.167.
![capture](https://user-images.githubusercontent.com/24728007/40696419-c86349aa-6400-11e8-973b-46ea475c41b7.png)

**Comment by bviktor** [comment]
IE is [officially EOL'd](https://support.microsoft.com/en-au/help/17454/lifecycle-faq-internet-explorer) and only receives security updates now. It's a legacy piece that can't be (and shouldn't be) supported forever. I'd advise you to make the switch to Edge, Firefox, Chrome, Vivaldi or any other current, actively supported browser.

**Comment by neriudon** [comment]
@bviktor Oh, I see. I will switch to other browsers instead of IE. Thanks!
