### ISSUE TITLE
Hide search bar on login screen

### ISSUE THREAD

**Issue by Brice-xCIT** [gitbucket/gitbucket#2058]
## Issue
**Impacted version**: 4.25.0

**Deployment mode**: standalone

**Problem description**:
A further security improvement that could be done to the login screen is hiding the search bar, thus preventing potentially malicious input from being fed to the app anonymously.

![capture](https://user-images.githubusercontent.com/29726153/41024851-a271e132-6970-11e8-8b51-8b9ef3f7f3ba.png)

**Comment by aadrian** [comment]
Also hide any other plug-in info unless it was programmed with the intent of doing something on the login page.
