### ISSUE TITLE
Issue with reverse proxy tutorial (Apache2)

### ISSUE THREAD

**Issue by vpontin** [gitbucket/gitbucket#2062]
I added the code from [here](https://github.com/gitbucket/gitbucket/wiki/Reverse-proxy-with-Apache) in /etc/apache2/sites-available/gitbucket.conf , but when i ran a `sudo a2ensite gitbucket` and after a `sudo systemctl reload apache2` i got this error:

```
Jun 10 20:21:55 BUTCH apachectl[1296]: AH00526: Syntax error on line 1 of /etc/apache2/sites-enabled/gitbucket.conf:
Jun 10 20:21:55 BUTCH apachectl[1296]: AllowEncodedSlashes takes one argument, Allow URLs containing '/' encoded as '%2F'
Jun 10 20:21:55 BUTCH apachectl[1296]: Action 'start' failed.
```
What i did wrong?

**Comment by takezoe** [comment]
Have you tried `AllowEncodedSlashes On`?

**Comment by vpontin** [comment]
Found the problem. The following comment "# ... or "On" for Apache-2.2" were what caused the problem

**Comment by takezoe** [comment]
Ah, I see. It's confising.
