### ISSUE TITLE
Error connecting with MariaDB

### ISSUE THREAD

**Issue by vpontin** [gitbucket/gitbucket#2063]
I was following [the tutorial](https://github.com/gitbucket/gitbucket/wiki/External-database-configuration), but after restarting gitbucket to connect with database:

`java.sql.SQLException: Specified key was too long; max key length is 767 bytes|Query is: ALTER TABLE gitbucket.COMMIT_STATUS  ADD CONSTRAINT IDX_COMMIT_STATUS_1 UNIQUE (USER_NAME, REPOSITORY_NAME, COMMIT_ID, CONTEXT)`

**Comment by ApertureDevelopment** [comment]
I have the same issue

**Comment by takezoe** [comment]
You have to enable large index in MySQL or MariaDB.
I guess this answer in StackOverflow will help you: https://stackoverflow.com/a/43403017/5390951

FYI, this configuration is unnecessary in MySQL 5.7.7 or later, but I'm not sure about MariaDB.

**Comment by vpontin** [comment]
Thanks. For now i switched back to H2 (its a personal server anyway) but once i have free time i will test it.
