### ISSUE TITLE
Question: Syncing a fork

### ISSUE THREAD

**Issue by badstorm** [gitbucket/gitbucket#2072]
Hi, there is a way to sync a fork with an upstream repository directory form the Web Gui?

Thanks
Marco

**Comment by takezoe** [comment]
There is no way for now.

**Comment by takezoe** [comment]
Ah... It might be possible by creating pull request from an upstream repository to a fork and merge it with rebase option, but you should do it for each branch.

**Comment by aadrian** [comment]
@badstorm @takezoe what about the Mirror Plug-in ? https://github.com/alexandremenif/gitbucket-mirror-plugin

**Comment by McFoggy** [comment]
I think that we need to tag this as a feature request. Both above solutions are so heavy/complicated/hacks that it will probably not answer the need for "simple" users not able to sync with 2 git commands.

**Comment by aadrian** [comment]
@McFoggy that plug-in does exactly that :) . Just install it and use it for the projects that are needed.

If this is so important, than the plug-in can be deployt with the release like it's done with few of the other plug-ins too.

**Comment by McFoggy** [comment]
@aadrian I do not think that we (gitbucket) need a plugin to update a fork from upstream. We are not talking about a synchronization between gitbucket and another git repo but just of a feature that can avoid people of doing manually some `git pull + git push`.
The need expressed above is not to sync external repos ; just to rebase easily a fork inside the same gitbucket installation.

**Comment by takezoe** [comment]
Closing old questions.
