### ISSUE TITLE
Allow non-users to submit issues

### ISSUE THREAD

**Issue by matthewp** [gitbucket/gitbucket#208]
It would be great if there were a way for non-users to submit issues to public repositories. I wouldn't want to allow anonymous issues, however perhaps you could add GitHub authentication which defaults to a new User Type of Issues Only... just a suggestion. Great project.

**Comment by jmolinaso** [comment]
+1

**Comment by Dwarfex** [comment]
+1 definitely 

----- Reply message -----
Von: "Julio Molina Soler" <notifications@github.com>
An: "takezoe/gitbucket" <gitbucket@noreply.github.com>
Cc: "Dwarfex" <h.oelze@wemake-it.de>
Betreff: [gitbucket] Allow non-users to submit issues (#208)
Datum: Di., Jan. 27, 2015 17:45
+1 

&mdash;

**Comment by minicl55** [comment]
+1

**Comment by takezoe** [comment]
Merged with #1286
