### ISSUE TITLE
The left pane "Recent updated repositories" shows nothing after upgrade to 4.26.0

### ISSUE THREAD

**Issue by quanmltya** [gitbucket/gitbucket#2089]
Upgrade from 4.25 to 4.26, then the left pane "Recent updated repositories" shows nothing.
In the previous version of gitbucket (4.25), that pane always show the latest updated repos.
All plugins has been upgraded to newest version.

**Comment by quanmltya** [comment]
Thanks!
Go through some settings and this is the results:
I own some repos (such as repo A, repo B).
- If I set those repos to private then nothing in the sidebar.
- If I set my repos to public then they display in the sidebar.
Current logged in user is me.
I think it is a bug with core or plugins.

**Comment by SIkebe** [comment]
Ah, that reproduced to me, too 😕

**Comment by demon101** [comment]
same problem. As a workaround, I use dashboard tab. Wating for fix
