### ISSUE TITLE
MySQL charset error

### ISSUE THREAD

**Issue by eddir** [gitbucket/gitbucket#2091]
**Impacted version**: 4.26.0

**Deployment mode**: *standalone app*

**Problem description**:
There is a bug, when trying to insert 4 byte charset symbols like russian text:
`Incorrect string value: '\xF0\x90\x8D\x83\xF0\x90...' for column 'DESCRIPTION'` *(table REPOSITORY)*
 It can be resolved by change charset in database, table, field and connection to utf8mb4. Could you change it by default to utf8mb4?

**Comment by takezoe** [comment]
> It can be resolved by change charset in database, table, field and connection to utf8mb4. Could you change it by default to utf8mb4?

That is MySQL configuration, not GitBucket one. You should change the default charset of MySQL.
