### ISSUE TITLE
Problems setting up reverse proxy on nginx

### ISSUE THREAD

**Issue by vpontin** [gitbucket/gitbucket#2094]
I'm trying to set up a reverse proxy for my gitbucket on nginx.

When i try to put this line on `/etc/nginx/nginx.conf`:

`proxy_cache_path /var/lib/nginx/cache levels=1:2 keys_zone=cache:512m inactive=1d  max_size=60g;`

it gives me this error when running `sudo nginx -t`:

```
nginx: [emerg] "proxy_cache_path" directive is not allowed here in /etc/nginx/nginx.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

What i did wrong this time?

**Comment by takezoe** [comment]
Write `proxy_cache_path` inside `http` directive:
ngx_http_proxy_module.html#proxy_cache_path

Please send question to [gitter room](https://gitter.im/gitbucket/gitbucket) before creating an issue according to the [guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/SUPPORT.md).

**Comment by vpontin** [comment]
Thanks, but i didnt have a account on the said website.

Other thing: the reverse proxy for nginx guide is partially incomplete. To fully make the redirect work i need to incorporate the subdirectory concepts from apache guide, and even after managing to make a [working script](https://gist.github.com/vpontin/f074dd4ab99ae9a8f2c108170f9d39ce) (i mean, being able to reach gitbucket from it) it disables my root index page.

**Comment by takezoe** [comment]
You can logged in to gitter using your GitHub account.
