### ISSUE TITLE
Add details to issues/pr search results

### ISSUE THREAD

**Issue by kmasuyama** [gitbucket/gitbucket#2101]
**Impacted version**: 4.26.0

**Deployment mode**: Apache tomcat 9.0

**Problem description**:
It would be great to see some additional details on the Issues/PR search results. 

Currently, search results from either the Issues page or Pull Requests page returns matches from both, under the misleading heading "We've found X issues." It is necessary to follow each link to see which type it is, and also its status open or closed. Github handles this nicely with colored symbols and query filters (e.g. is:issue) - would something similar be possible?

**Comment by takezoe** [comment]
How about separating Issues and Pull requests search results?

![search](https://user-images.githubusercontent.com/1094760/42870519-0ccd68f4-8ab3-11e8-8a31-4a6c00e004d3.png)

**Comment by takezoe** [comment]
@kmasuyama Added "Closed" label. See #2110.
