### ISSUE TITLE
Math rendering in markdown/wiki

### ISSUE THREAD

**Issue by kmasuyama** [gitbucket/gitbucket#2107]
**Impacted version**: 4.26.0

**Deployment mode**: Apache tomcat 9.0

**Problem description**:
It'd be great to see math rendering supported in markdown documents, especially in the wiki. It seems to be a fairly common [extension to CommonMark](https://github.com/commonmark/CommonMark/wiki/Deployed-Extensions#math), although not GFM.

**Comment by aadrian** [comment]
@kmasuyama https://github.com/gitbucket/gitbucket/pull/1323

**Comment by kmasuyama** [comment]
@aadrian thanks for the link - that issue didn't pop up on searching for math terms (eg math, mathml, mathjax, katex...). 

I'm looking forward to the update, and I hope a math extension is included.

**Comment by takezoe** [comment]
We already hava a plugin for this: https://github.com/onukura/gitbucket-mathjax-plugin/issues/3
