### ISSUE TITLE
Problems with comment folding in Pull Requests

### ISSUE THREAD

**Issue by kmasuyama** [gitbucket/gitbucket#2111]
**Impacted version**: 4.26.0

**Deployment mode**: Apache tomcat 9.0

**Problem description**:
Some comments made to previous commits on a PR are not folded, even though the code they were made on have been changed/deleted. They still show the filename above the comment (instead of 'kmasuyama commented X days ago'), but no code is displayed. I haven't been able to find a specific cause, or determine why some are folded and others aren't.

Also, clicking on the toggle (javascript:$('.fold-comments-n').toggle();) does not work. It just redirects to a page only displaying [object Object].
![toggle](https://user-images.githubusercontent.com/209727/42930885-36ce41f2-8b79-11e8-8184-ec7220247dbb.png)

**Comment by takezoe** [comment]
> Some comments made to previous commits on a PR are not folded

This is correct behavior if the commented line isn't modified by subsequent commits. But not displaying diff for these comments is a bug. It's fixed in #2114. 

> Also, clicking on the toggle (javascript:$('.fold-comments-n').toggle();) does not work.

All toggle buttons in the Conversation tab? What's your browser?

**Comment by kmasuyama** [comment]
> This is correct behavior if the commented line isn't modified by subsequent commits.

The behavior I saw was that some comments remained unfolded even though their associated line of code had been deleted or modified. In these cases, there are no toggle buttons but also no code displayed.

![screenshot_2018-07-23 implement geomagnetic model igrf2015 - pull request 27 - masuyama aocssim 1](https://user-images.githubusercontent.com/209727/43051397-4c781702-8e54-11e8-901d-676371676eee.png)

> All toggle buttons in the Conversation tab? What's your browser?

All buttons as in the screenshot below. I'm using Firefox 61.0.1. The toggle worked with no problem on Chrome 67.0.3396.99

![screenshot_2018-07-23 implement geomagnetic model igrf2015 - pull request 27 - masuyama aocssim](https://user-images.githubusercontent.com/209727/43051249-0614d856-8e52-11e8-80eb-9af1194b488b.png)

**Comment by takezoe** [comment]
> The behavior I saw was that some comments remained unfolded even though their associated line of code had been deleted or modified. In these cases, there are no toggle buttons but also no code displayed.

This is what I wanted to say. This problem is fixed in #2114.

> I'm using Firefox 61.0.1. The toggle worked with no problem on Chrome 67.0.3396.99

Thanks. I will test with Firefox.
