### ISSUE TITLE
Recent updated repositories showing static data

### ISSUE THREAD

**Issue by lakshykar** [gitbucket/gitbucket#2118]
Recently i have deployed recent build released on 30th Jun 18.

After that Recent updated repositories not showing correct result, it is showing static information every time even though there are changes in other projects but those projects not showing in Recent updated repositories section.

Attaching screenshot code changes in 
![screenshot from 2018-07-25 10-47-21](https://user-images.githubusercontent.com/9511081/43180933-5e27658e-8ff8-11e8-8c08-212c70f1bce9.png)

**Comment by takezoe** [comment]
This problem seems to overlap with #2089. It has been already fixed and will be released in the next version (4.27.0).
