### ISSUE TITLE
Security issue: Transfer repository ownership allows any user to frame any other

### ISSUE THREAD

**Issue by SagePtr** [gitbucket/gitbucket#2132]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

## Issue
**Impacted version**: 4.25.0

**Deployment mode**: demo on https://gitbucket.herokuapp.com

**Problem description**:

Any logged in user can create potentially bad repository and set anyone as its owner.

How to reproduce:
1. Create new empty repository.
2. Configure local git to use victim's name and email.
3. Add something illegal of offensive to this repository.
4. Transfer repository ownership to victim.
5. Call the police (or victim's boss, victim's wife, or anyone else who will hate victim for this content) before victim notice his new repo and delete it. In bloody regime countries like Russia it can even cost victim's freedom.

Step (2) cannot be prevented by git design itself (it allows unsigned commits).
Step (4) can be prevented by transfer confirmation. In Github, if you transfer repo to someone else, new owner will receive notification and he needs to confirm this transfer to become new owner, he cannot be set as repo owner without his will.

**Comment by Sherpard** [comment]
Having an history of project ownership could also make the trick. doesn't it?

**Comment by takezoe** [comment]
If you serve GitBucket on the public space, this is a critical problem. Introducing confirmtation like GitHub is not so easy in the current GitBucket implementation, so I think it's better to provide following options:

- Disable transferring repository ownership
- Allow transferring for only GitBucket administrators

Anyway, repository transfer operation should be recorded in activity logs.

**Comment by takezoe** [comment]
Repository operations including transferring repository can be restricted by #2469. If you need to operate GitBucket on the public space, you can prohibit these possibly problematic repository operations. Also, transferring repository operation is now logged by #2468. These updates will be available in the next version (4.34.0).

Since what we can do for now is all done, I will close this issue.
