### ISSUE TITLE
Unhandled error with the create repository API (orgs)

### ISSUE THREAD

**Issue by Crayon2000** [gitbucket/gitbucket#2133]
## Issue
**Impacted version**: 4.27.0

**Deployment mode**: 
* OS: Windows Server 2012 R2
* Server: IIS with URL Rewrite
* Service: NSSM to run GitBucket as a service
* Database: MariaDB 10.2.14

**Quick Info**:
* It looks like the same problem as #2030 but with an organization instead of a user.

**Problem description**:
* When using the request (POST 127.0.0.1:8080/api/v3/orgs/_myorg_/repos) I get an unhandled error
* The body is `{"name":"test"}`
* The repository is created but I get an 500 Server Error with this response: `{"message":"Internal Server Error"}`
* Using GET with the same URL is working
* Using POST with the same request a second time is working: `{"message":"A repository with this name already exists on this account","documentation_url":"https://developer.github.com/v3/repos/#create"}`
* Log: [error.txt](https://github.com/gitbucket/gitbucket/files/2320994/error.txt)

Let me know if you need more information.

**Comment by hpalmer** [comment]
I have seen this same problem. It appears that the Option returned by getRepository on line 355 of ApiController.scala is None. So it throws an exception. It seems that the DB session associated with the HTTP request is not working for getRepository at that point. I do not know why. But I have a patch that uses a new DB session to call getRepository, and that fixes the problem for me.

I am running Tomcat 7 and MySQL 5.7 on Windows 7, and the problem can be reliably repeated without my patch.

[ApiController.zip](https://github.com/gitbucket/gitbucket/files/2363130/ApiController.zip)

With or without the patch, it does actually create the repository.

**Comment by hpalmer** [comment]
> I can't reproduce this problem. Could you give me any other hints? For example, What authentication method do you use to access API?

I'm using basic authentication. Sorry, I did not notice the reference to [#2030](https://github.com/gitbucket/gitbucket/issues/2030) before. But it is very likely the same cause in this case, since I'm using MySQL.

**Comment by naudachu** [comment]
This problem is still reproducible with LDAP auth and Organization is created not into LDAP, but into gitbucket itself
