### ISSUE TITLE
In version 4.25 and later versions, if you download Zip on a branch with a slash it will result in NotFound error

### ISSUE THREAD

**Issue by hikki1217** [gitbucket/gitbucket#2136]
## Issue
**Impacted version**: 4.27.0

Tomcat9.0(jre1.8.0_171)
Windows Server 2012 R2 Standard

4.25以降のバージョンにて、スラッシュが含まれるブランチをZipダウンロードするとNot FoundエラーとなりZipダウンロードができません。

アップデート前は4.8を利用していましたが、その時はどのようなブランチでもZipダウンロードが可能でした。

In 4.25 and later versions, Zip downloading branches containing slashes results in Not Found error and Zip download can not be done.

Prior to updating, we used 4.8, but at that time Zip downloading was possible for any branch.

スラッシュがあるブランチ（Branch with slash）
![01_feature](https://user-images.githubusercontent.com/42337514/44895139-ee6c2b00-ad2d-11e8-93fe-81a99210e388.png)

スラッシュがあるブランチのZipダウンロード後（After Zip download of branch with slash）
![02_feature_zipdownload_error](https://user-images.githubusercontent.com/42337514/44895142-f035ee80-ad2d-11e8-8f8b-4feb1bdf429b.png)

スラッシュが無いブランチ（Branch without slash）
![03_master](https://user-images.githubusercontent.com/42337514/44895144-f1671b80-ad2d-11e8-86f7-e74cf26a83ab.png)

スラッシュが無いブランチのZipダウンロード後（After Zip download of branch without slash）
![04_master_zipdownload_success](https://user-images.githubusercontent.com/42337514/44895147-f1ffb200-ad2d-11e8-883e-4c876d79d9d8.png)

**Comment by takezoe** [comment]
A download problem for branches which contain '/' has been fiexed in GitBucket 4.27: https://github.com/gitbucket/gitbucket/commit/33a676f221f3c9b6bd59e1f2c986533bbe316794

The brannch name in download URL in your screenshot looks to be encoded correctly, but an unencoded URL seems to be requested. Could you check a sent URL from your browser (e.g. by looking at the developer tools of your browser) and an actual requested URL (e.g. by looking at the access log iof the server)?


'/'を含むブランチがダウンロードできないという問題はGitBucket 4.27で修正されています: https://github.com/gitbucket/gitbucket/commit/33a676f221f3c9b6bd59e1f2c986533bbe316794

添付していただいたスクリーンショットを見るとブランチ名は正しくURLエンコードされていますが、なぜかURLエンコードされていないURLが送信されているように見えます。実際にブラウザから送信されたURL（ブラウザ付属のDeveloper Toolsで確認できます）とサーバで受信したURL（サーバのアクセスログなどで確認できるかと思います）を確認していただけないでしょうか？

**Comment by hikki1217** [comment]
Although explanation was missing, Redmine is executed with apache 2 on this server.
A 404 error was output to access.log of apache2, but 404 error was not output to localhost_access_log of tomcat.

説明が漏れていましたが、このサーバにはRedmineをapache2で実行しています。
apache2のaccess.logには404エラーが出力されていましたが、tomcatのlocalhost_access_logには404エラーは出力されていませんでした。

[(apache2)access.log](https://github.com/gitbucket/gitbucket/files/2344809/apache2.access.log)
[(tomcat)localhost_access_log.2018-09-03.txt](https://github.com/gitbucket/gitbucket/files/2344810/tomcat.localhost_access_log.2018-09-03.txt)
![feature](https://user-images.githubusercontent.com/42337514/44976603-abfe5480-afa0-11e8-84f5-50f81ee5771f.png)

**Comment by takezoe** [comment]
Close because this issue has been already fixed.
