### ISSUE TITLE
Error when accessing the wiki page of a project

### ISSUE THREAD

**Issue by Coding-Kiwi** [gitbucket/gitbucket#2139]
## Issue
**Impacted version**: 4.28.0

**Deployment mode**: java gitbucket.war as a service on linux debian, with nginx reverse proxy

**Problem description**:
I created a wiki page for a project and it worked fine, I came back weeks later and get an Internal Server Error:
org.eclipse.jgit.errors.MissingObjectException: Missing tree 77802bf6fd2c51e9001665f7e7e6c8abcfd8436e

[Full Stacktrace Pastebin Link](https://pastebin.com/Sa9MkAtb)

**Comment by takezoe** [comment]
Hmm... I have no idea.
