### ISSUE TITLE
Unable to create new repos after upgrade from GB 4.13 --> 4.27 and H2 --> PostGres

### ISSUE THREAD

**Issue by fomcl** [gitbucket/gitbucket#2149]
Hello,

We migrated from H2 to Postgres database and we also upgraded from Gitbucket v4.13 to v4.27. We had a fresh Win10 VM, reinstalled Tomcat, installed Postgres 9, Java 8. Then we installed GB v4.13, migrated from H2 to Postgres, upgraded to GB 4.27. We tweaked the Java heapsizes because otherwise, hitting 'Pull requests' would give a StackOverflowError.

Everything works fine, except that we're no longer able to create new repos. I get a `Not Found` message and in the localhost access log I see: 

```
10.4.21.160 - - [24/Sep/2018:09:46:03 +0200] "POST /new/validate HTTP/1.1" 200 2
10.4.21.160 - - [24/Sep/2018:09:46:03 +0200] "POST /new HTTP/1.1" 302 -
10.4.21.160 - - [24/Sep/2018:09:46:03 +0200] "GET /me/foo42 HTTP/1.1" 404 6721
10.4.21.160 - - [24/Sep/2018:09:46:03 +0200] "GET /me/_avatar?20180924094545 HTTP/1.1" 200 2763
```

Iinitially, I thought the error was simply related to missing avatar images, so I populated the repos/data dir with blank avatar images, one for each known user.

Now, if I log in with my *root* account (not 100 % sure if this matters), I see one of the following when I try to create a new repo:
* First attempt (?) `Failed to create repository
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "label_label_id_key" Detail: Key (label_id)=(274) already exists`
* Subsequent attempts: `Not found`
* Happened only once:  repo successfully created.

Not sure if it's related, but in in the Catalina logs I see hundreds of lines like this:
```
22-Sep-2018 19:55:46.429 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1] (value [scala.util.DynamicVariable$$anon$1@6143eb96]) and a value of type [scala.None$] (value [None]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

I can post more log info if needed.

**Comment by takezoe** [comment]
@fomcl I guess that you haven't updated sequence values described here:
https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#postgresql

**Comment by fomcl** [comment]
Hi, thanks for your quick reply. During the migration we did in fact update those sequence values as per your instruction in https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#postgresql

**Comment by takezoe** [comment]
@fomcl Hmm... but your error seems to be caused by sequnce value conflict. Could you try updating sequence values once again?

**Comment by fomcl** [comment]
ok, I could. But is this a potentially dangerous operation? Many of my colleagues are currently using Gitbucket. Perhaps it's better if I clone that VM? And is the Not Found error also caused by a sequence value conflict?

**Comment by takezoe** [comment]
> But is this a potentially dangerous operation? Many of my colleagues are currently using Gitbucket. Perhaps it's better if I clone that VM?

These operations set sequence value as maximum value + 1. So I think it's not dangerous operation basically, but of course it's better to test in the isolated environment if it's possible.

> All operations set sequence value as maximum value + 1. I think it's not dangerous operation basically, but you should test isolated environment if it's possible.

I'm not sure, but GitBucket redirects to the repository after the creation progress page, so if repository creation failed, it can cause 404 error.

**Comment by fomcl** [comment]
@takezoe : thanks, hat makes sense. Good to know that the 404 error and the PSQLException may have a common cause/solution.  I will re-run the code in https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#postgresql to see if this fixes things.

**Comment by fomcl** [comment]
@takezoe:  I  ran the SQL snippet on https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#postgresql and indeed, I can create new repos again! I am 99% sure I did run the script previously, right after the huge generated .sql migration script. Is it possible that an upgrade to Gitbucket v4.27 undid this SETVAL code? Anyway **THANKS** for your help!
