### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by johndrinkwater** [gitbucket/gitbucket#2153]
## Issue
**Impacted version**:  `4.29.0`

**Deployment mode**: Running the latest .war as a standalone app.

**Problem description**:
Basically exactly the same as https://github.com/gitbucket/gitbucket/issues/326, the ssh URL is being populated with `git` username, which fails during `git clone` with permission denied.

gitbucket is running under the local user `john`, with a gitbucket non-admin username of `water`.

It is a fresh install, with a new user, enabled ssh, installed two plugins (gist+pages).

**Comment by uli-heller** [comment]
I tried to verify this with my test instance. I upgraded from 4.28.0 to 4.29.0. Cloning via SSH works as before.

**Comment by uli-heller** [comment]
Co workers used to have issues, they used the wrong URL for cloning. You have to use the URL displayed at the upper right:

![image](https://user-images.githubusercontent.com/1677414/46460189-8345c680-c7bb-11e8-9cce-01ef09113597.png)

Example for the URL: ssh://git@localhost:2222/dp/test.git

**Comment by nauevg** [comment]
Hello. using docker variant (image 292acf1d99e0, gitbucket version 4.35.3, docker command - "docker run -d -p 8080:8080 -p 29418:29418 -v /srv/gitbucket:/gitbucket gitbucket/gitbucket"). same problem - can not clone or push over ssh. base url set. ssh host set. ssh key added. i can see traffic on port 29418 inside container, but no luck. same time i can clone over http.

**Comment by nauevg** [comment]
tried new version (4.37.2, docker image - 3f28d8184280) - now it works. I can clone repo over ssh. thanks for updates!

**Comment by takezoe** [comment]
Updating Apache MINA SSHD in recent version might have solved the issue, not intentionally though :-P
