### ISSUE TITLE
How to release

### ISSUE THREAD

**Issue by pvhieuit** [gitbucket/gitbucket#2170]
Hi guy,

I want to create release like this [Gitbucket Release](https://github.com/gitbucket/gitbucket/releases) how to do that
In Gitbucket, I clicked on the release tab but did not see anything. Please help. Thanks in advance

![image](https://user-images.githubusercontent.com/18276928/47083254-3ee60c00-d23a-11e8-8c31-a7f4a6340bdc.png)

**Comment by takezoe** [comment]
Creating a tag is necessary to create a release in GitBucket.

**Comment by pvhieuit** [comment]
Hi @takezoe 
Thank you for support, but can you explain more?

**Comment by takezoe** [comment]
You need to create git tag.

**Comment by pvhieuit** [comment]
Got it, thank you so much!
