### ISSUE TITLE
dead link in wiki

### ISSUE THREAD

**Issue by nkchan** [gitbucket/gitbucket#2173]
I found dead link in gitbucket wiki
It item is  `Installation on CentOS 7 with PostgreSQL and Tomcat`

Please confirmation, this link.

I wloud like to know Centos Manual

**Comment by takezoe** [comment]
That link is to an external web site and we don't have a way to know the content of the linked page. What we can do is just removing the link.

**Comment by takezoe** [comment]
By the way, if you can read Japanese, you'll be able to find some articles which explains how to install GitBucket on CentOS by Google search. 😉
