### ISSUE TITLE
web hooks configuration URIs for groups redirect to home page

### ISSUE THREAD

**Issue by jupld** [gitbucket/gitbucket#2184]
The "Service Hooks" link is present in left menu when logged in as the group owner and displaying group page `/groupName/`, but clicking on it silently redirects to home page.

My guess is that the `oneselfOnly` authenticator prevents the `/:userName/_hooks` URNs from being reached on a group.

See:
* [src/main/twirl/gitbucket/core/account/edithook.scala.html](https://github.com/gitbucket/gitbucket/blob/4.29.0/src/main/twirl/gitbucket/core/account/edithook.scala.html)
* [src/main/scala/gitbucket/core/controller/AccountController.scala#L430](https://github.com/gitbucket/gitbucket/blob/80b50f6fa9647de10f7d6d7fb6d200ac065adc82/src/main/scala/gitbucket/core/controller/AccountController.scala#L430)

**Comment by bathizte** [comment]
Moreover 
- as root : the webhook link is not displayed for given group BUT : 
![screenshot from 2018-11-13 10-52-23](https://user-images.githubusercontent.com/1695453/48405633-ec154c80-e732-11e8-82ad-7b9ed20f4fb2.png)

- accessing the /group/webhook URL by hand gives access 
![screenshot from 2018-11-13 10-53-21](https://user-images.githubusercontent.com/1695453/48405643-f20b2d80-e732-11e8-9af1-f47e35e1687d.png)

**Comment by takezoe** [comment]
@jupld @bathizte Thanks for reporting. I created a pull request #2196 to fix this problem. Please take a look if you have a chance.

**Comment by bathizte** [comment]
Hello, 
I finally took the time to test in our development environment. The fix is indeed working. 
Thanks !
