### ISSUE TITLE
 Inline comment notification

### ISSUE THREAD

**Issue by TatsuyaKumon** [gitbucket/gitbucket#2203]
**Impacted version**: 4.29.0

**Deployment mode**: standalone app

**Problem description**:
I'm setting for Slack notification by webhook configuration.
- Not notified to Slack when inline pull-request comment is written.
- Notified to Slack when the normal pull-request comment is written.

In past gitbucket versions such a problem did not occur.

**Comment by takezoe** [comment]
@TatsuyaKumon This problem still occurs even in GitBucket 4.30.1?

**Comment by TatsuyaKumon** [comment]
@takezoe This problem has not occured in Gitbucket 4.30.1.
Thanks.

**Comment by takezoe** [comment]
@TatsuyaKumon Thanks for your reporting. So I closed this issue as fixed in `4.30.1`.
