### ISSUE TITLE
Issue during a clean install - mysql8.0 - gitbucket 4.29.

### ISSUE THREAD

**Issue by PERAGIT** [gitbucket/gitbucket#2216]
Hello, 

Not sure if this should be a new issue also posted it under a questions that hasn't gotten a response in a bit. 
My apologies in advance if this is posted in the wrong place.

The issue we are having is as follows during a clean install using mysql 8.
 
Failed to add the foreign key constraint. Missing index for constraint 'IDX_ISSUE_COMMENT_FK0' in the referenced table 'issue' 

Using the latest version of gitbucket available 4.29. Any ideas how to make it work with this version?

Thank you.

Luis Esquivel

_Originally posted by @PERAGIT in https://github.com/gitbucket/gitbucket/issues/2150#issuecomment-445874856_

**Comment by takezoe** [comment]
MySQL 8 is not tested yet.  We use [this library](https://github.com/wix/wix-embedded-mysql) for automated test of database migration scripts. But this library doesn't support MySQL 8.

Anyway, please use MySQL 7 for now.
