### ISSUE TITLE
GitBucket logo not rendered with Tomcat 9.0.14

### ISSUE THREAD

**Issue by paulchen** [gitbucket/gitbucket#2218]
I'm running GitBucket 4.30.0 (i.e. the most recently released version) on an instance of Apache Tomcat. Today I upgraded Tomcat from 9.0.13 to 9.0.14. Since doing this, the GitBucket logo in the upper left corner of the web page doesn't get rendered anymore (neither with Google Chrome nor with Mozilla Firefox).

I found out that /assets/common/images/gitbucket.svg is now delivered using the Content-Type text/html instead of image/png. I'm not sure whether this is a issue in Tomcat or in GitBucket.

Steps to reproduce:

- Download Apache Tomcat from 9.0.14 from https://tomcat.apache.org/download-90.cgi, extract it and start it up.
- Download gitbucket.war and place it into Tomcat's webapps folder.
- Visit http://localhost:8080/gitbucket/

When following the above steps using Tomcat 9.0.13, the logo gets rendered as expected. The image is also rendered properly when running GitBucket using "java -jar gitbucket.war".

**Comment by Jarthianur** [comment]
I also noticed exactly the same issue with Tomcat 8.5.37 and GitBucket 4.30.1.
