### ISSUE TITLE
404 on click the release path in the timeline when i change the release name

### ISSUE THREAD

**Issue by leokstudio** [gitbucket/gitbucket#2221]
## Issue
**Impacted version**: 4.30

**Problem description**:
1. I change the release name
2. in the timeline page, i click the new release name
3. goto 404

**Comment by takezoe** [comment]
This looks like a bug. But I'm not sure if we should fix it because the timeline is activity **log**. So we must not update the past history. Disabling link is okay, but it would make the timeline slower because it requires to make sure existence of each release.

**Comment by takezoe** [comment]
@leokstudio Anyway I can't reproduce this issue.

> in the timeline page, i click the new release name

What is timeline? First, I guessed it's activity timeline, but I couldn't find a log related to new release name there. Is it the list of releases (`owner/repo/releases`)? If so, the link target shouldn't be changed if you change the release name.

**Comment by leokstudio** [comment]
@takezoe yeah, its the activity timeline,But I can't reproduce this bug right now，its work wll in 4.30.1, just close it. thank you
