### ISSUE TITLE
4.30.0: sbt executable fails: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#2222]
## Issue
**Impacted version**:  4.30.0

Buldind the executable fails, probably due to missing 1.6.0 -> 1.7.0 within src/main/resources/bundle-plugins.txt?

**Comment by uli-heller** [comment]
@takezoe I think you should create a version 4.30.1, since c20a434 is not part of 4.30.0 and 4.30.0 fails on `sbt executable`

**Comment by takezoe** [comment]
Yeah, actually we have a plan of 4.30.1 because 4.30.0 has some other bugs. It will be released by the end of this year.
