### ISSUE TITLE
Jenkins fails to detect Jenkinsfile

### ISSUE THREAD

**Issue by mrxr16** [gitbucket/gitbucket#2225]
## Issue
**Impacted version**:

 * GitBucket: 4.30.0
 * Jenkins: 2.150.1
 * Jenkins GitHub Branch Source Plugin: 2.4.1

**Deployment mode**: standalone app with an haproxy https frontend

**Problem description**:
- Jenkins fails to detect the presence of "Jenkinsfile" in all branches
- Followed wiki to set up multibranch pipeline and pointed to gitbucket - worked for 13 months with all versions of gitbucket tried since then
- Upgraded bitbucket to 4.30.0 and Jenkins now fails to find any "Jenkinsfile", although it does detect all branches
- No errors in GitBucket/Jenkins log files

Not sure if related to #1946 but the code seems to have been refactored quite a bit since then XD

GitBucket log lines:

````
11:56:19.850 [scala-execution-context-global-77] INFO  g.core.service.WebHookService - Content-Type: application/x-www-form-urlencoded
````

Jenkins log lines:

````
Dec 18, 2018 11:56:19 AM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
INFO: Received PushEvent for https://gitbucket.example.com/GroupName/dummy from 192.168.xxx.xxx ? https://jenkins.example.com/github-webhook/
Dec 18, 2018 11:56:24 AM com.squareup.okhttp.internal.Platform$JdkWithJettyBootPlatform getSelectedProtocol
INFO: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
````

Jenkins "Scan Repository Log":

````
Started by user mrxr16
[Tue Dec 18 11:35:27 CET 2018] Starting branch indexing...
11:35:27 Connecting to https://gitbucket.example.com/api/v3 using jenkins/******
Examining GroupName/project-name

  Checking branches...

  Getting remote branches...

    Checking branch master

  Getting remote pull requests...
      ‘Jenkinsfile’ not found
    Does not meet criteria

    Checking branch update-readme

  2 branches were processed

  Checking pull-requests...

    Checking pull request #2
      ‘Jenkinsfile’ not found
    Does not meet criteria

  1 pull requests were processed

  Checking tags...

  Getting remote tags...

  0 tags were processed

Finished examining GroupName/project-name

[Tue Dec 18 11:35:30 CET 2018] Finished branch indexing. Indexing took 2.9 sec
Finished: SUCCESS
````

**Comment by kounoike** [comment]
I can reproduce it. and hooks HTTP request/response by Fiddler.

![image](https://user-images.githubusercontent.com/6997928/50158352-3e8bef00-0317-11e9-9d50-314a243912b3.png)

I found the problem for no.11. /api/v3/repos/:user/:repository/contents/?ref=.... returns 404.
I think this problem is trailing slash problem.

**Comment by MedeilPlusCloudCust** [comment]
Unable to find med-express-medeilcloudhq-payment from git git@github.com:vanuston-intelligence/med-express-medeilcloudhq-payment.git
Finished: FAILURE
