### ISSUE TITLE
csv file support

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#2237]
Any plans for csv files viewing just like  github

**Comment by lavvy** [comment]
hi @kounoike, which of your plugins can i create this issue for ? gitbucket-xlsx-plugin or gitbucket-html5media-plugin . Can you per chance add .csv file format in one of your plugins. Its really awesome to have same rendering ability in GB for csv files cloned from GH.

**Comment by kounoike** [comment]
@lavvy I wrote prototype https://twitter.com/ko_noike/status/1083387048566738944, https://github.com/kounoike/gitbucket-csv-plugin . But csv format has many variations. I gave up to finish this work.

**Comment by lavvy** [comment]
So good . I appreciate it. i am testing it

**Comment by takezoe** [comment]
We now have this plugin! https://github.com/onukura/gitbucket-csvtsv-plugin
