### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by MikeAirey** [gitbucket/gitbucket#2238]
## Issue
**Impacted version**: *4.30.1*

**Deployment mode**: *Demo*
![2018-12-31 13_11_26-application error](https://user-images.githubusercontent.com/7135657/50553582-9fdf9500-0cfd-11e9-910d-3edc0e47507e.png)

**Problem description**:
- Online Gitbucket demo reports "Application Error"
- HTTP response is 503 Service Unavailable

**Comment by SIkebe** [comment]
I verified the site got to normal.
