### ISSUE TITLE
MySQL Db Issue.

### ISSUE THREAD

**Issue by qashoou** [gitbucket/gitbucket#2257]
for versions and stuff, see attached images.
I have a default installation of gitbucket, and now i have to use mysql db, I have migrated the h2 database to mysql. All tables are in there. But when I run the war, it says it cant find table VERSIONS.

When i try to add the table, it says its already there with the required data.

![image](https://user-images.githubusercontent.com/5079901/51832478-9ce4be00-2316-11e9-9146-3bd628c3eb66.png)

![image](https://user-images.githubusercontent.com/5079901/51832504-ad953400-2316-11e9-8307-7780864d871d.png)

**Comment by couling** [comment]
This is most likely a mysql issue.  On a linux server mysql table names are case sensitive.  So if you create a table `versions` you can't select from `VERSIONS`.

**Comment by qashoou** [comment]
yup. did figure that out. Thanx alot.
also, I was thinking that we should have a wiki with a step-by-step database configuration from H2 to mysql etc.
