### ISSUE TITLE
Code Lines Anchors are missing.

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#2291]
Links (anchors) to code lines seem to be missing  in GitBucket.

E.g. something like:
https://github.com/gitbucket/gitbucket/blob/master/src/main/java/gitbucket/core/util/PatchUtil.java#L62

Thank you.

**Comment by takezoe** [comment]
Links (anchors) to code lines are already available in GitBucket. Try to append `#L<line_number>` to the url of blob view as same as GitHub.
