### ISSUE TITLE
Migrating: from H2 to MySQL and using MySQL DB

### ISSUE THREAD

**Issue by alexvancasper** [gitbucket/gitbucket#2299]
## Issue
**Impacted version**: 4.31.2 and others (checked from 4.0 till 4.31.2)

**Deployment mode**: 
I am trying to use GitBucket in standalone mode on Ubuntu 18.04 with MySQL 5.7

**Problem description**:
If I install the GitBucket with default settings (H2 DB) then the GitBucket works very well.
If I try to use MySQL DB,  then I add new lines into the database.conf with mysql connection detail, then restart the GitBucket. After that the GitBucket showed 503 Error, Service Unavailable.
The GitBucket's database user has full access to the MySQL server.
The problem with configuration of the MySQL server, it does not have necessary table structure.
Exporting data from H2 database does not help becasue the export file has wrong syntax for importing it into the MySQL Server.

All actions were done with the default settings on clear operating system.
Instruction that I used for installing:
https://github.com/gitbucket/gitbucket/wiki/Install-as-a-systemd-Service
Connecting to the MySQL:
https://github.com/gitbucket/gitbucket/wiki/External-database-configuration

Please provide necessary skeleton for MySQL database and table structure.

Thank you.

**Comment by takezoe** [comment]
GitBucket creates necessary tables at the first startup if database is empty. I guess that GitBucket couldn't connect to the database.

Could you find any error message or stacktarce in the log file?

**Comment by alexvancasper** [comment]
It did not create any tables. The error is DB error.
I will try to connect logs. no problem.

**Comment by kurdtpage** [comment]
I have this problem as well, using version 4.31.2 and changing from H2 to MariaDB 10.1.30, which should be compatible with MySQL 5.7.

I have created a blank database and a user as per https://github.com/gitbucket/gitbucket/wiki/External-database-configuration

The error is: 
> java.sql.SQLSyntaxErrorException: (conn=312985) Table 'ACCOUNT' already exists

I manually deleted all tables and tried again, now I get:
> java.sql.SQLException: View's SELECT contains a subquery in the FROM clause|Query is: CREATE OR REPLACE VIEW ISSUE_OUTLINE_VIEW AS| SELECT|   A.USER_NAME,|   A.REPOSITORY_NAME,|   A.ISSUE_ID,|   COALESCE(B.COMMENT_COUNT, 0) + COALESCE(C.COMMENT_COUNT, 0) AS COMMENT_COUNT| FROM ISSUE A| LEFT OUTER JOIN (|   SELECT USER_NAME, REPOSITORY_NAME, ISSUE_ID, COUNT(COMMENT_ID) AS COMMENT_COUNT FROM ISSUE_COMMENT|   WHERE ACTION IN ('comment', 'close_comment', 'reopen_comment')|   GROUP BY USER_NAME, REPOSITORY_NAME, ISSUE_ID| ) B| ON (A.USER_NAME = B.USER_NAME AND A.REPOSITORY_NAME = B.REPOSITORY_NAME AND A.ISSUE_ID = B.ISSUE_ID)| LEFT OUTER JOIN (|   SELECT USER_NAME, REPOSITORY_NAME, ISSUE_ID, COUNT(COMMENT_ID) AS COMMENT_COUNT FROM COMMIT_COMMENT|   GROUP BY USER_NAME, REPOSITORY_NAME, ISSUE_ID| ) C| ON (A.USER_NAME = C.USER_NAME AND A.REPOSITORY_NAME = C.REPOSITORY_NAME AND A.ISSUE_ID = C.ISSUE_ID)|java thread: main

**Comment by takezoe** [comment]
MariaDB 10.2.1 or higher is required:
https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#mysql-57-or-higher
