### ISSUE TITLE
Discord webhook isn't working

### ISSUE THREAD

**Issue by DarkScientist** [gitbucket/gitbucket#2300]
Hi, 

I'm using gitbucket as a systemd service on Ubuntu 18.0.4 and I've a problem. 

The discord webhooks aren't working, it sends back "cannot send an empty message".

How can I fix it please? 

Thanks!

**Comment by kounoike** [comment]
https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

> In addition to the URL, you have some more GitHub-specific options to choose from. For content type, stick with application/json. Discord's webhook format really likes JSON. In the next section, you can choose to customize what kind of events trigger webhook messages. 

I got "cannot send an empty message" when webhook url without `/github`. I got successful result when url ends with `/github`.

**Comment by kounoike** [comment]
`Test hook` button shows "ERROR", but message is appear on discord.

**Comment by DarkScientist** [comment]
That works, thanks a lot!
