### ISSUE TITLE
SMTP Notifications aren't working

### ISSUE THREAD

**Issue by DarkScientist** [gitbucket/gitbucket#2301]
Hi, 
I'm using gitbucket as a systemd service and I've set up the smtp server.
Sending a test email works but the Global Annonce doesn't send anything and I've no notifications. 

How to fix that?

**Comment by kounoike** [comment]
GitBucket doesn't send e-mail to oneself.

**Comment by DarkScientist** [comment]
But what is the goal of the smtp configuration?

**Comment by takezoe** [comment]
What is "Global Annonce"? GitBucket does not have such functinality in default.

Do you use this plugin?
https://github.com/gitbucket-plugins/gitbucket-announce-plugin

**Comment by DarkScientist** [comment]
Yes, I use this plugin which is automatically purposed by default.

Le sam. 13 avr. 2019 à 20:17, Naoki Takezoe <notifications@github.com> a
écrit :

**Comment by takezoe** [comment]
So please create an issue in the plugin's repository.

**Comment by DarkScientist** [comment]
That was not my question, I only mentioned it.
My question was "what is the aim of the smtp configuration excepted for the announce plugin? Does it send notifications?"

**Comment by takezoe** [comment]
GitBucket offers API for sending email to plugins and SMTP configuration is used in this API. But I'm not sure if the announce plugin use this API (I guess probably it uses this API, though) and also I'm not sure if the plugin works with the latest version of GitBucket.
