### ISSUE TITLE
Kotlin Plugin Support

### ISSUE THREAD

**Issue by caffeine-mgn** [gitbucket/gitbucket#2305]
Requires the ability to write plugins in Kotlin/Java language.
Can't interop normal between Scala and Kotlin.

**Comment by takezoe** [comment]
We don't have such plan. Actually, I don't think it's possible to offer Java/Kotlin support for plugin development in the current GitBucket architecture.

**Comment by aadrian** [comment]
@caffeine-mgn any scala project (so a GitBucket plug-in too) can consume JARs, so GitBucket can too. So you can make a plug-in in Scala, and use your JAR (where your code was written in Kotlin/Java) and and just use it.

**Comment by takezoe** [comment]
What @caffeine-mgn saying is that he wants to write GitBucket plugin in Kotlin/Java, not Scala.

While some major Scala projects like Akka offer Java compatible API, I think it's impossible in GitBucket because GitBucket strongly relies on Scala specific frameworks like Scalatra and Slick, and plugins must use them.

**Comment by takezoe** [comment]
I close this issue because I think there is no possibility to support Kotlin/Java in plugin development in the current GitBucket architecture.

@caffeine-mgn Thanks for your feedback anyway.

**Comment by aadrian** [comment]
@takezoe I understand, but what I'm saying is that only the part that interacts with the GitBucket API needs to be in Scala. The rest could be in Kotlin/Java, since a Scala based projects can use other JARs (GitBucket itself is also using quite a few of them).

**Comment by takezoe** [comment]
>  only the part that interacts with the GitBucket API needs to be in Scala. The rest could be in Kotlin/Java

That's true. However most parts of GitBucket plugin would need to interact with GitBucket (or Scalatra/Slick) API actually.

**Comment by caffeine-mgn** [comment]
You can create interfaces instead of classes. As I know scala's interfaces looks like simple java/kotlin interfaces. And then plugin can call those interfaces.

**Comment by takezoe** [comment]
GitBucket uses Scala specific language features and frameworks. Usually, plugin's also need to use them. It's almost impossible to decouple them from plugin's codebase on the current design of GitBucket.
