### ISSUE TITLE
How can I delete an issue?

### ISSUE THREAD

**Issue by kongziming** [gitbucket/gitbucket#2307]
![Snipaste_2019-04-30_16-23-18](https://user-images.githubusercontent.com/19622288/56948950-4892e980-6b64-11e9-9e7d-51d2d5f0fe70.jpg)
I can not find where to delete an issue. Hope your help. Thanks.

**Comment by SIkebe** [comment]
@ikongziming  GitBucket does not have "delete issue" function. You can "close issue" instead.

**Comment by McFoggy** [comment]
or really if you know what you do, you can delete the issue entry in the DB.

take care of referential integrity before deleting from `ISSUE` table you must delete referenced entries in `ISSUE_NOTIFICATION`, `ISSUE_LABEL` and `ISSUE_COMMENT` tables.

proceed with care and keep a backup before.

**Comment by takezoe** [comment]
Thanks @SIkebe and @McFoggy for answering.

@kongziming I close this issue because I don't have anything to add. If you have futher question, feel free to ask us in the gitter room: https://gitter.im/gitbucket/gitbucket
