### ISSUE TITLE
Extract data.mv.db

### ISSUE THREAD

**Issue by prabhakarlad** [gitbucket/gitbucket#2311]
After sudden power cut my gitbucket service is failing, how do i extract the DB to respective git repositories any pointers would be helpful

**Comment by McFoggy** [comment]
If you could explain a bit more the current outage you are facing you could receive more help.

> service is failing

What kind of error?

> how do i extract the DB to respective git repositories 

What do you mean?  
Do you have backups?

If you look at `$GITBUCKET_HOME\data` you will find:

- `data.mv.db` : the h2 DB file if you use H2 as default database
- a directory `repositories` which contains per user/group the bare git repositories for projects & wikis

**Comment by takezoe** [comment]
Close as duplicate because this looks like same question as #2310.
