### ISSUE TITLE
use inline links in markdown

### ISSUE THREAD

**Issue by guominfang** [gitbucket/gitbucket#2314]
I used the inline link in the readme.md file of the project. After clicking, the interface could not jump to the correct position normally.

inline link ：
```
[tip](./tip)
```
demo png : <https://upload-images.jianshu.io/upload_images/3876376-76972510ec967124.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240>

**Comment by SIkebe** [comment]
Which version of GitBucket?

**Comment by SIkebe** [comment]
And which page?

**Comment by guominfang** [comment]
I'm very sorry, that the warehouse of the company is not open to the Internet, so I can only describe the problem. The picture is the description of the problem I want to convey.

GitBucket version：4.29

Thank you!

**Comment by SIkebe** [comment]
>GitBucket version：4.29

Ah, the issue was fixed in 4.31.X
https://github.com/gitbucket/gitbucket/pull/2249

Could you refer the issue template next time😄 ?

**Comment by SIkebe** [comment]
>The picture is the description of the problem I want to convey.

![403](https://user-images.githubusercontent.com/17608272/57424609-31828480-7253-11e9-9fe5-cfb9fa1c097b.PNG)

**Comment by guominfang** [comment]
Oh.I will.

Thank you!
