### ISSUE TITLE
Diff between arbitrary commits in gitbucket?

### ISSUE THREAD

**Issue by sdbbs** [gitbucket/gitbucket#2315]
## Issue
**Impacted version**: not sure

**Deployment mode**: installation on a NAT server

**Problem description**:

I would like to have a diff in Gitbucket from two arbitrary revisions. Closest I could get to is adding `/compare` to a repository URL; as an example, here is a public GitBucket installation I've found (apparently it is v 4.21.2):

* https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics

I can append `/compare` to this URL, getting https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics/compare - which then gets redirected to:

* https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics/compare/master...master

It apparently defaults to comparing *branches* (considering the auto-appended `master...master`), and so the default output is:

![gitbucket_compare_01](https://user-images.githubusercontent.com/48317456/57515640-6a822e00-7313-11e9-9361-417fafe9bb06.png)

... "There isn't anything to compare. ; nigel.stanger:master and nigel.stanger:master are identical."

So, I can go to check out the commit hashes by looking at the history at this link:

* https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics/commits/master

... and there's only 5 commits here; in descending order:

```
ee4600b
8316299
c18605b
17d1441
77d770d
```

So let's say I want to compare the 4th (8316299) and 2nd (17d1441) commit - so I just try replacing those hashes in the compare URL, instead of the branch names:

* https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics/compare/8316299...17d1441

... however, I get:

![gitbucket_compare_02](https://user-images.githubusercontent.com/48317456/57516004-26dbf400-7314-11e9-92a6-f9775919962a.png)

... "There isn't anything to compare.  nigel.stanger:8316299 and nigel.stanger:17d1441 are identical. " - which is, clearly, not true (in terms of commit hashes, at least - although, it seems "compare" may be intended just for pull requests, in which case it probably interprets "8316299" and "17d1441" as branch names).

I would have loved a checkbox in the history commits list, next to each commit hash; then if I have checked two of those boxes, I could have clicked a "compare" button or similar to obtain styled HTML of the diff between those commits - however, I'd do just fine, if there is just an existing functionality where I could paste in commit hashes in a URL (as I tried to do above).

So, is there an existing way to compare/diff arbitrary revisions/commit hashes in gitbucket?

**Comment by takezoe** [comment]
@sdbbs Sorry for my late response. Try putting commit id in reverse order as:
https://isgb.otago.ac.nz/infosci/nigel.stanger/docker-analytics/compare/17d1441...8316299
