### ISSUE TITLE
Disable PR marge with WIP title

### ISSUE THREAD

**Issue by forest6511** [gitbucket/gitbucket#2319]
Im new to Gitbucket.
Is there the function to disable the button of merge when putting 'WIP' on PR title?

Best,

**Comment by kounoike** [comment]
I think it is bad design. GitHub's "Draft PR" is more better. Because it is explicitly appeared in UI.

**Comment by forest6511** [comment]
Thank you telling me about 'Draft PR'!
Yes, something like the feature of  'Draft PR'.
