### ISSUE TITLE
Commit diff doesn't seem to be working

### ISSUE THREAD

**Issue by kurdtpage** [gitbucket/gitbucket#2328]
## Issue
**Impacted version**: 4.31.2

**Deployment mode**: Windows Server 2008, Apache 2.2, java v1.80_201, http://localhost:8080/gitbucket

**Problem description**:
Commit diff doesn't seem to be working. Also, cannot view any code changes.
![image](https://user-images.githubusercontent.com/1308716/59400208-c7797400-8dea-11e9-9eb4-fa95378f6383.png)
If I click Patch, it shows me a screen like:
```
diff --git a/Scripts/paydialog.js b/Scripts/paydialog.js
index 32e801d..efcb3ab 100644
--- a/Scripts/paydialog.js
+++ b/Scripts/paydialog.js
@@ -1,4 +1,4 @@
-var debug = true;
+var debug = false;
```
Clicking on the icon beside the filename doesn't do anything, and this page does not show any code. Clicking on Split shows the same screen (with no code)

**Comment by joobisb** [comment]
@kurdtpage Can you please specify the version that you are using, because in the latest version 4.31.2, it seems to be working.
![image](https://user-images.githubusercontent.com/13068144/59752979-d788cc00-92a0-11e9-90dd-2d8dbb83bc30.png)

**Comment by kurdtpage** [comment]
Turns out the problem was I was running gitbucket twice. I am using RDP to remote into a VPS, my other session was logged out and so I ran the "java -jar gitbucket.war" command again. As soon as I closed the other instance, it started working fine again.
