### ISSUE TITLE
Line number highlighting does not work

### ISSUE THREAD

**Issue by gageas** [gitbucket/gitbucket#2340]
## Issue
**Impacted version**: 4.31.2

**Deployment mode**: Any

**Problem description**:

Line number highlighting (`#Lxxx` in location hash) does not work properly.

`updateHighlighting` function causes error when called by onload event.

Called by onhashchange event, it works.

https://github.com/gitbucket/gitbucket/blob/96f871641765ddb3c13ebb77d80975c0d68723a9/src/main/twirl/gitbucket/core/repo/blob.scala.html#L106-L108

<img width="986" alt="無題" src="https://user-images.githubusercontent.com/40446/60584023-13ef1880-9dc7-11e9-9409-575ebbd7dda5.png">

**Comment by takezoe** [comment]
Hmm... It works.

<img width="679" alt="Screen Shot 2019-08-12 at 15 25 51" src="https://user-images.githubusercontent.com/1094760/62848251-bf1fb580-bd15-11e9-9ed7-84c00408d67b.png">

**Comment by SIkebe** [comment]
I often saw this before, too. When I encounter this, the highlighting got to work after trying Ctrl + F5 several times.
However I cannot repro this anymore(Windows 10, Chrome 76.0.3809.100).

@gageas Which OS and browser are you using?

**Comment by gageas** [comment]
My env is Windows 10 and Chrome 76.0.3809.100.

How to reproduce:

1. Open any text file on gitbucket.
2. Append `#Ln` suffix and press Enter. (This step works fine.)
3. Click URL bar and press Enter. (This step causes error.)

![record](https://user-images.githubusercontent.com/40446/62914995-c1dde180-bdcd-11e9-90bc-180f47d63278.gif)

**Comment by SIkebe** [comment]
Thanks! @gageas 

I can repro the behavior in latest Chrome, Chromium Edge, too.
FireFox has no issue.
Highlighting in Edge does not work from the very beginning...

**Comment by SIkebe** [comment]
@gageas I can not repro this issue anymore with latest Chrome(78.0.3904.87). Are you still seeing this?

**Comment by SIkebe** [comment]
I can not repro with Chrome 83.0.4103.106 and Windows 10 1903, too.
v4.33.0 and current master branch both have no problem.

@takezoe Should clear milestone and close this for now? If anyone can repro, then reopen again.

**Comment by takezoe** [comment]
Thanks for confimation. That makes sense.
