### ISSUE TITLE
GitBucket for graphics/images [New Feature Request]

### ISSUE THREAD

**Issue by KnightCoder** [gitbucket/gitbucket#2347]
## New Feature Request
GitBucket for graphics and images. The tool will become useful for the graphics teams as well, thereby increasing the user base.   

Github supports this. [Read more here](https://github.blog/2011-03-21-behold-image-view-modes/).

**Feature description**:
- *Must be able to commit, push, pull etc. just like we can do with source codes.*
- *Must be able to diff old vs new image/graphics. For ref. look at how Github does it. Link given above*

**Comment by kounoike** [comment]
Did you try it? GitBucket already have image diff. Of cause you can commit/push/pull images.

**Comment by KnightCoder** [comment]
Oh I'm sorry. Was not aware of it. Could you please share a link/write up
about this.

**Comment by takezoe** [comment]
We don't have documentation for users which describes GitBucket features on by one. Also, we don't have enough resource to make it.
