### ISSUE TITLE
what's the default value of the options?

### ISSUE THREAD

**Issue by alaxcc** [gitbucket/gitbucket#2353]
what 's the default value of follow options?
--port=[NUMBER]
--prefix=[CONTEXTPATH]
--host=[HOSTNAME]
--gitbucket.home=[DATA_DIR]
--temp_dir=[TEMP_DIR]
--max_file_size=[MAX_FILE_SIZE]

**Comment by takezoe** [comment]
The default values of these properties are:

- port: `8080`
- prefix: `/`
- host: `null`
- gitbucket.home: `~/.gitbucket`
- temp_dir: `<gitbucket.home>/tmp`
- max_file_size: `3 * 1024 * 1024`
