### ISSUE TITLE
Invalid ssh key message when trying to add a key

### ISSUE THREAD

**Issue by michael-newsrx** [gitbucket/gitbucket#2357]
**Impacted version**:  GITBUCKET_VERSION | 4.31.2

**Deployment mode**: Apache HTTPD AJP <-> Tomcat 8

**Problem description**:
Unable able to add a public SSH key to my profile. Keeps giving me "invalid key" with no indication as to nature of actual error.

My key is from id_rsa.pub is in the form of:

ssh-rsa AAAA...XULJ michael@michael-desktop

**Comment by takezoe** [comment]
You can see debug messages by changing the log level of GitBcuket:
https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/ssh/SshUtil.scala

See the following documentation to configure GitBucket's logging system:
https://github.com/gitbucket/gitbucket/wiki/Tracing-and-logging

**Comment by skullwritter** [comment]
same error here

**Comment by michael-newsrx** [comment]
We ended up restarting our full tomcat server as the bouncy castle stuff wasn't loading properly. We are considering switching to the docker version to deal with the class path issues and tomcat.
