### ISSUE TITLE
segmentation fault when using in raspberry pi

### ISSUE THREAD

**Issue by erfan-azhdari** [gitbucket/gitbucket#2359]
## Issue
**Impacted version**: 4.32.0

**Deployment mode**: *Using `java -jar gitbucket.war` on raspberry pi 3 B+ (ARMv7 linux kernel)*

**Problem description**:
when I try to use `java -jar gitbucket.war` it fails with a segmentation fault
`pi@raspberrypi:~/gitserver $ java -jar gitbucket.war `
`Segmentation fault`

I don't know what to do but here's the output of  `uname -a`.
`Linux raspberrypi 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux`

This system has 1GB of RAM and a quad-core ARMv8 SOC(The Kernel is built for ARMv7).

**Comment by kounoike** [comment]
Could you tell me more specific information?

- OS: Raspbian Buster with desktop and recommended software /
Raspbian Buster with desktop / Raspbian Buster Lite?
- Java: oracle-jdk? openjdk? 8? 9?

At least I know, some jdk requires X client libraries. But, raspbian-lite does not have such libraries.

**Comment by kounoike** [comment]
Ah... one more question. Really first line of output is "Segmentation fault"? no any output?

**Comment by erfan-azhdari** [comment]
Thank you for your fast response.

The output of `java --version` is
`openjdk 11.0.3 2019-04-16`
`OpenJDK Runtime Environment (build 11.0.3+1-Raspbian-1)`
`OpenJDK Server VM (build 11.0.3+1-Raspbian-1, mixed mode)`

I am using OpenJDK 11.0.3 Built For ARM.
and the the program only outputs `Segmentation fault`

**Comment by erfan-azhdari** [comment]
I found the solution.
It works fine with OracleJDK8 for armhf.
