### ISSUE TITLE
Several Issues Noted With GB 4.32.0

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#2360]
I am seeing a couple of things that are of concern:

- Even the though the latest version of the gist plugin is present, it does not appear in the administrative interface of 4.32.0 nor can I find anywhere in the UI to create or read gists.  I don't actually think this is new behavior in that I had this problem previously as well.   I have run the recommended H2 commands in case this is an artifact of 3.x but no joy in any case.

- The RST plugin has stopped working as of 4.32.0  and no longer appears in the  admin interface even though it is present in plugins/

**Comment by takezoe** [comment]
> Even the though the latest version of the gist plugin is present, it does not appear in the administrative interface of 4.32.0 nor can I find anywhere in the UI to create or read gists.

Do you find `gitbucket-gist-plugin-4.18.0.jar` in `.gitbucket/plugins/.installed`? If no, the latest version of Gist plugin is not installed somehow. It should be installed automatically in GitBucket 4.32.0.

> The RST plugin has stopped working as of 4.32.0 and no longer appears in the admin interface even though it is present in plugins/

As we described in [the release announcement](https://gitbucket.github.io/gitbucket-news/), plugin's backwards compatibility is broken in 4.32.0, so rst-plugin need to be fixed. Please report it to rst-plugin side.

**Comment by tundratim** [comment]
> Do you find gitbucket-gist-plugin-4.18.0.jar in .gitbucket/plugins/.installed? 

Yes

> Please report it to rst-plugin side.

Will do

**Comment by takezoe** [comment]
I tested GitBucket 4.32.0 and Gist plugin 4.18.0 worked in default.

<img width="954" alt="Screen Shot 2019-08-12 at 13 27 08" src="https://user-images.githubusercontent.com/1094760/62845676-f46fd780-bd04-11e9-8b8e-6ec5ee6bdf51.png">

You should see the following logs in bootstrapping if default plugins have been installed correctly.

```
13:24:38.733 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins
13:24:38.825 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-gist-plugin-4.18.0.jar
13:24:39.069 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-emoji-plugin-4.6.0.jar
13:24:39.078 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-notifications-plugin-1.8.0.jar
13:24:39.137 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-pages-plugin-1.8.0.jar
```

**Comment by tundratim** [comment]
Hmmm, I am seeing this:

21:16:54.411 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-gist-plugin-4.18.0.jar
org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "MODE"; SQL statement:
ALTER TABLE PUBLIC.GIST ADD MODE VARCHAR(10) DEFAULT 'PUBLIC' NOT NULL [42121-199]


And this:

21:16:54.701 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-notifications-plugin-gitbucket_4.31.2-1.7.0.jar
java.lang.NoClassDefFoundError: scala/Serializable

**Comment by takezoe** [comment]
You still have trouble in two plugins. Let's see separately.

## gist-plugin

Your gist plugin is failing to migrate to 4.2 for some reason.
https://github.com/gitbucket/gitbucket-gist-plugin/blob/master/src/main/resources/update/gitbucket-gist_4.2.xml

I need to know the following things what I asked in the previous comment to show a way to correct your environment:

> - The contents of `VERSIONS` table

## notifications-plugin

Your notifications plugin seems old. The latest version is 1.8.0:
https://github.com/gitbucket/gitbucket-notifications-plugin/releases/tag/1.8.0

1.8.0 should be installed automatically if you use GitBucket 4.32.0. If it doesn't work, try to once remove `.gitbucket/plugins` directory and restart GitBucket. GitBucket will re-install the bundled latest version of plugins automatically.

**Comment by tundratim** [comment]
notifications-plugin fixed per your directions.  Thanks!

Here is VERSIONS table:


MODULE_ID | VERSION
-- | --
emoji | 4.6.0
pages | 1.8.0
notifications | 1.8.0
gitbucket-core | 4.32.0
rst | 0.4.0
gist | 2.0.0

**Comment by takezoe** [comment]
Really? The initial version of gist plugin is 3.6.0. 2.0.0 has never released.

Anyway, try to run the following SQL, then restart GitBucket:

```sql
UPDATE VERSIONS SET VERSION = '4.18.0' WHERE MODULE_ID = 'gist';
```

**Comment by tundratim** [comment]
Yup, that fixed the Snippets thing.  Thanks!

I previously forgot  to mention that I am also seeing errors in this form and I'm not sure if they matter.  It seems not to affect correct operation, but I'd be interested in your read on what's going on here:


17:12:42.332 [qtp777874839-11] WARN  o.c.e.a.WarnAboutCache2kAllUsage - Usage of the artifact cache2k-all is deprecated, please update your dependencies. See: https://cache2k.org/docs/latest/user-guide.html#getting-started
17:12:46.000 [qtp777874839-11] ERROR g.c.c.PullRequestsController - Catch unhandled error in request: Request(GET //gitbucket.tundraware.com/tundra/grpcdemo/pulls?labels=invalid%2Cduplicate%2Cquestion%2Cbug&milestone=none&priority=none&author=tundra&state=closed&sort=comments&direction=desc)@2f8ff3b8
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "grpcdemo"; SQL statement:
select "USER_NAME", "REPOSITORY_NAME", "MILESTONE_ID", "TITLE", "DESCRIPTION", "DUE_DATE", "CLOSED_DATE" from "MILESTONE" where ("USER_NAME" = ?) and ("REPOSITORY_NAME" = ?) order by "DUE_DATE", "CLOSED_DATE" desc, "MILESTONE_ID" desc [22018-199]


Again many thanks for your patient help.

**Comment by tundratim** [comment]
It sure seems like the H2 database is borked, at least in some places.

The instance of gitbucket I am running is essentially used only by me, although other people pull from it occasionally.

Is there a practical way to just recreate GB from scratch with the latest war file, recreate my account, and then push the dozens of repos I manage there while maintaining full commit history etc.?

**Comment by takezoe** [comment]
The best way is taking backup of H2 database periodically and restoring from the latest backup. Furthermore, I recommend using an external database instead of the default H2 database if it's possible. PostgreSQL is my recommendation.

**Comment by tundratim** [comment]
Right, but if I want to start from complete zero and just create all my repos with full commit history, is there a clean way to do that?

**Comment by takezoe** [comment]
I think so if you don't have any backup of database and bare repositories.

**Comment by tundratim** [comment]
So ... I went back and created a brand new instance of GB with nothing in it.  Then repo-by-repo, I created the new repo on the server and did `git push -u origin master` from my local copies of the repos.  

This seems to have fixed all my goofy behavior and Snippets now also work properly.

Am going to close this unless you see something I did that is incorrect.

Thanks for the help.
