### ISSUE TITLE
gitbucket版本升级

### ISSUE THREAD

**Issue by xiaotao2014** [gitbucket/gitbucket#2374]
请问如何从4.31.2升级到4.32.0

**Comment by SIkebe** [comment]
Google translate: 
>How to upgrade from 4.31.2 to 4.32.0

**Comment by SIkebe** [comment]
@xiaotao2014 Hi! Have you read these instruction? Or you have any problem with upgrading?
https://github.com/gitbucket/gitbucket#installation
https://github.com/gitbucket/gitbucket/wiki/FAQ#7-how-to-upgrade-gitbucket

**Comment by SIkebe** [comment]
@xiaotao2014 Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
