### ISSUE TITLE
org.h2.jdbc.JdbcSQLNonTransientException encountered after upgrading Gitbucket from 4.29 to 4.32

### ISSUE THREAD

**Issue by rockccf** [gitbucket/gitbucket#2376]
## Issue
**Impacted version**: 4.32.0

**Deployment mode**: standalone app

**Problem description**:
- Login to GitBucket Web, Click the "History" button of any file and you will see the error.

> org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.ArrayIndexOutOfBoundsException: 2"; SQL statement: select "COMMIT_STATUS_ID", "USER_NAME", "REPOSITORY_NAME", "COMMIT_ID", "CONTEXT", "STATE", "TARGET_URL", "DESCRIPTION", "CREATOR", "REGISTERED_DATE", "UPDATED_DATE" from "COMMIT_STATUS" where (("USER_NAME" = ?) and ("REPOSITORY_NAME" = ?)) and ("COMMIT_ID" = 'c5550a224c8dcc26958706df6223251709ac5ef1') order by "UPDATED_DATE" desc [50000-199]

**Comment by rockccf** [comment]
Clicking on "Pull requests" gives this error.

> org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.ArrayIndexOutOfBoundsException: 2"; SQL statement: select x2.x3, x2.x4, x2.x5, x2.x6, x2.x7, x2.x8, x2.x9, x2.x10, x2.x11, x2.x12, x13."COMMIT_STATUS_ID", x13."USER_NAME", x13."REPOSITORY_NAME", x13."COMMIT_ID", x13."CONTEXT", x13."STATE", x13."TARGET_URL", x13."DESCRIPTION", x13."CREATOR", x13."REGISTERED_DATE", x13."UPDATED_DATE" from (select "USER_NAME" as x3, "REPOSITORY_NAME" as x4, "ISSUE_ID" as x5, "COMMIT_ID_FROM" as x10, "COMMIT_ID_TO" as x11, "IS_DRAFT" as x12, "REQUEST_USER_NAME" as x7, "REQUEST_BRANCH" as x9, "BRANCH" as x6, "REQUEST_REPOSITORY_NAME" as x8 from "PULL_REQUEST" where (("USER_NAME" = ?) and ("REPOSITORY_NAME" = ?)) and ("ISSUE_ID" = ?)) x2, "COMMIT_STATUS" x13 where ((x2.x3 = x13."USER_NAME") and (x2.x4 = x13."REPOSITORY_NAME")) and (x2.x11 = x13."COMMIT_ID") [50000-199]

**Comment by takezoe** [comment]
Your H2 database file seems to be broken. H2 recovery tool might be your help.
http://www.h2database.com/javadoc/org/h2/tools/Recover.html

**Comment by rockccf** [comment]
Somehow, the error is gone but I did not do anything.
Thanks @takezoe , will close this issue.
