### ISSUE TITLE
cannot edit milestone

### ISSUE THREAD

**Issue by RedBow** [gitbucket/gitbucket#2379]
## Issue
**Impacted version**: 4.32.0 (possibly earlier, did not test)

**Deployment mode**: Deployed in Tomcat 8.5.45, along with a few other applications. It is running as non-privileged user "tomcat:tomcat". Reverse proxied using Apache 2 with mod_proxy

**Problem description**:
- Changing milestone due date or description fails with message "milestone already exists" appearing in red letters under the milestone's title.
- *Steps to reproduce*:
  1. login to gitbucket
  2. open a project (or create a project)
  3. if a milestone on this project does not already exist, create one
  4. go to the "Milestones" page (link on the left side navigation bar)
  5. select a milestone and click "edit" (under the progress bar)
  6. change the description or the date, but do not change the title.
  7. click the green button labeled "Update milestone"
  8. red text "milestone already exists" appears
  9. navigate back to "Milestones" page (link on left side navigation bar)
  10. check if edits to milestone were saved.
  11. they were not saved.
- *Possible workaround*
  1. navigate to edit milestone page
  2. change description or due date
  3. edit the title by appending "-edit"
  4. click the green button labeled "update milestone"
  5. gitbucket returns you to the milestones page, note that the edits you wanted were made, but the milestone title is different.
  6. click the edit button on the milestone
  7. remove the "-edit" suffix from the title
  8. click the green button labeled "update milestone"
  9. git bucket returns you to the milestones page. the milestone is as it should be.

**Comment by SIkebe** [comment]
@RedBow Dup of #2362
