### ISSUE TITLE
Database Deadlock when accessing /api/v3/user

### ISSUE THREAD

**Issue by Sherpard** [gitbucket/gitbucket#2392]
### Before submitting an issue to GitBucket I have first:

- [X] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [X] searched for similar already existing issue
- [X] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.31.0 And Above 

**Deployment mode**: Docker container using https://hub.docker.com/r/f99aq8ove/gitbucket/ and PostgreSQL as Database Backend

**Problem description**:
When using API calls, to /v3/user and a valid authentication, the database enters in a deadlock state.

When too many request are required, the HikariCP connection pool starves, and no more request are served.

I've traced the issue down to PR #2267 . 
What I've seen at pgAdmin, is that there's a query idle in transaction, and another waiting to perform an update. 

The state after an attempt is:
* 'idle in transaction': Select data from Account
* 'locked': Update account set lastAction....

At the moment, a way to prevent gitbucket from getting starved is to set a flag to postgre user, that adds a timeout for connections that are 'idle in transaction'.

## Steps to reproduce
* Start a postgresql instance
* Configure gitbucket to use postgresql as database
* make a query to api `curl http://localhost/api/v3/user -u username:password` **before any user logs in**
* The request should not complete, unless you kill the postgresql connection (pgadmin should display the issue on the dashboard).

Edit: Added @SIkebe annotation on "how to reproduce"

**Comment by SIkebe** [comment]
I can not repro this issue. What I did is...
1. Run `docker-compose up -d` using [this definition](https://github.com/SIkebe/gitbucket-utility/blob/develop/docker-compose.yml)
2. Run `curl http://localhost:8080/api/v3/user -u root:root`
3. Check pgAdmin4 dashboard and verified there is no 'locked' state

@Sherpard Am I missing something?

**Comment by Sherpard** [comment]
The differences that I see with my current setup, is pg version. I'm using pg10.5. And that I'm using an LDAP backend to do the Auth. 

This Monday I'll try a clean setup, so I can improve how to reproduce.

**Comment by Sherpard** [comment]
> I can not repro this issue. What I did is...
> 
> 1. Run `docker-compose up -d` using [this definition](https://github.com/SIkebe/gitbucket-utility/blob/develop/docker-compose.yml)
> 2. Run `curl http://localhost:8080/api/v3/user -u root:root`
> 3. Check pgAdmin4 dashboard and verified there is no 'locked' state
> 
> @Sherpard Am I missing something?

Seems to be an issue with Postgres 10.5.

Swapped postgres tag to 10.5 on the definition you provided, cleaning everything up, and running should surface the issue.

[Here](https://gist.github.com/Sherpard/e5e5bc38339918bcfb8b34a371d2fec1) is a modified version of your definition

**Comment by SIkebe** [comment]
Ah...like this?

![idle-in-transaction](https://user-images.githubusercontent.com/17608272/68116060-40659d80-ff3d-11e9-9033-5137fda1f067.png)

**Comment by SIkebe** [comment]
I can repro even with latest version of PostgreSQL.
More accurate steps are below.

1. Run `docker-compose up -d` using [this definition](https://github.com/SIkebe/gitbucket-utility/blob/develop/docker-compose.yml)
1. Run `curl http://localhost:8080/api/v3/user -u root:root` **before any user log in to GitBucket**

**Comment by Sherpard** [comment]
yep,  you caught it!. 
On most cases it should not be a problem. as most people go trough website instead of api, but on my case, there's a jenkins CI Server, and periodically calls /user api. and locks the whole git server.
