### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by rcsilva83** [gitbucket/gitbucket#240]
Hello,

It would be very good if GitBucket had a global search like GitHub has, so we could search through all repositories.

**Comment by FlYnN91** [comment]
Is there any more info if this could be implemented?

**Comment by takezoe** [comment]
@FlYnN91 No progress. I think it requires the full text search engine. Maybe we can use Elasticsearch in embedded mode for this purpose.

**Comment by FlYnN91** [comment]
@takezoe Thanks for the update. I (and others I think) would really like to see the search capability. If only I knew Scala, I'd try to help. Thanks.

**Comment by uli-heller** [comment]
Do we have an idea on how to do this? From my perspective, these are valid implementation alternatives:

* elasticsearch embedded
* lucene embedded
* solr embedded
* elasticsearch separated
* solr separated

From what I understand, embedding elasticsearch and solr is discouraged for production use, but I maybe wrong on this.

For lucene, there is a pull request:

* #693 - closed

For solr, there are these projects caring about git history:

* https://github.com/garysieling/solr-git
* https://github.com/arafalov/git-to-solr

What's the strategy here? Can I help somehow?

**Comment by takezoe** [comment]
There is a plug-in to search GitBucket using Elasticsearch:
https://github.com/codelibs/gitbucket-fess-plugin/

**Comment by McFoggy** [comment]
the plugin is now referenced in the [plugins](http://gitbucket-plugins.github.io/) site: gitbucket-plugins/gitbucket-plugins.github.io#13
