### ISSUE TITLE
Destination [..]/plugins/.installed cannot be created/deleted

### ISSUE THREAD

**Issue by codeling** [gitbucket/gitbucket#2402]
**Impacted version**: 4.32
**Deployment mode**: Tomcat 9.0.16 running on Ubuntu 18.04.3 LTS
**Problem description**:
I recently played around running gitbucket under podman (via the docker image), but then podman started freezing up on me, so i decided to move back to running gitbucket directly under tomcat again. I moved the gitbucket data out of the volume to /srv/gitbucket, deployed gitbucket.war in /var/lib/tomcat9/webapps, after extraction adapted gitbucket.home in /var/lib/tomcat9/webapps/gitbucket/WEB_INF/web.xml to point to /srv/gitbucket, then started up tomcat.
On startup, I now get:
```
29-Nov-2019 20:57:24.120 SCHWERWIEGEND [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [gitbucket.core.servlet.InitializeListener]
 java.io.IOException: Destination '/srv/gitbucket/plugins/.installed' directory cannot be created
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1070)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1028)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:286)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:283)
```
(SCHWERWIEGEND = FATAL in german).
I've tried creating that directory via the `tomcat` user (under which tomcat9 runs under ubuntu), and it works just fine. If the directory exists, gitbucket reports that it can't delete the directory. So there must be some other security or access control mechanism interfering, but I can't figure out which... any experience with such issues? Any pointer what i could check?

**Comment by takezoe** [comment]
That's weird. GitBucket does nothing special.
https://github.com/gitbucket/gitbucket/blob/94f9d42fc4f55bd3e3826becd4d16289a08f0451/src/main/scala/gitbucket/core/plugin/PluginRegistry.scala#L268-L273

I guess that a permission problem on your system. You need to create `/srv/gitbucket` directory as `tomcat` user in your case.

**Comment by codeling** [comment]
> I guess that a permission problem on your system. You need to create /srv/gitbucket directory as tomcat user in your case.
I think so too, but I don't know through which system. The /srv/gitbucket directory exists, and is owned by tomcat (the user running tomcat9 and therefore gitbucket), as does the plugins directory under it. I have tried creating the  `.installed` folder mentioned in the message via command line as tomcat user (which works), then gitbucket complains that it cannot delete that directory ;).
There must be some security or other mechanism in place which somehow prevents gitbucket from access, yet I don't know what it could be. i am running this under ubuntu, so maybe I should ask in ubuntu forums...

**Comment by codeling** [comment]
Finally found it - in Ubuntu, tomcat runs in a systemd sandbox now! See https://stackoverflow.com/questions/56827735/how-to-allow-tomcat-war-app-to-write-in-folder !
Solution is to add an "/etc/systemd/system/tomcat9.service.d/override.conf" file with content:
```
[Service]
ReadWritePaths=/srv/gitbucket
```
So gitbucket is working very fine now! Hopefully this information might be of some use to some other gitbucket users too!

**Comment by codeling** [comment]
By the way is there a best practice of where to put settings such as the data directory location when deploying as .war? Currently I modified the web.xml inside of the `/var/lib/tomcat9/webapps/gitbucket/WEB-INF` folder - but that will probably get overwritten when I next update gitbucket, so I was wondering maybe there is some better place?

**Comment by takezoe** [comment]
You can specify the data directory through a system property `gitbucket.home` or an environmental variable `GITBUCKET_HOME`.
https://github.com/gitbucket/gitbucket/blob/d322f772e8dfe434b15f8aab15fc7dbee0bec92a/src/main/scala/gitbucket/core/util/Directory.scala#L10-L28
