### ISSUE TITLE
LDAP authentication: New users NEED to exist in Gitbucket first

### ISSUE THREAD

**Issue by ChristianKoessel** [gitbucket/gitbucket#2407]
## Issue
**Impacted version**: 4.32.0

**Deployment mode**: standalone app with postgresql

**Problem description**:
LDAP authentication is configured and working but new users can't login:
` [qtp87285178-91] INFO  g.core.service.AccountService - Failed to authenticate: BA23462`

Then I (as admin) created the account BA23462 with fake password/full name/mail.
Now the user can login with his LDAP password and the account is updated with full name and mail from LDAP.

I could reproduce this by deleting the user from the ACCOUNT table and also with different users.

LDAP access is working, I could verify this by login attempts with non-existing users or invalid credentials, in these cases I got appropriate log messages.

**Comment by takezoe** [comment]
This looks like a bug. If I remember correctly, GitBucket's LDAP authentication mechanism has been designed to create an account on GitBucket at the first authentication.

**Comment by ChristianKoessel** [comment]
I solved the problem by looking at the code: if the account is not found gitbucket tries to find one with the same mail address (from LDAP) and this was the admin account...

Sorry for that!
