### ISSUE TITLE
Diff not appear in PR preview

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2415]
## Issue
**Impacted version**: Current master (not released)

**Deployment mode**: standalone app

**Problem description**:
Diffs don't appear in PR preview because `old.data('val')` and `head.data('val')` return `undefined`.

![image](https://user-images.githubusercontent.com/17608272/72153262-c3e5b400-33f0-11ea-8eb9-5a4a7800869a.png)

**Comment by SIkebe** [comment]
Related to cb87d126de1e1f22501a977f7b2ac50a7176791d
@takezoe thoughts?

**Comment by takezoe** [comment]
Ugh... Let me see on this weekend.
