### ISSUE TITLE
Password limitations

### ISSUE THREAD

**Issue by boughtonp** [gitbucket/gitbucket#2425]
The GitBucket FAQ contains the disturbing question "[What's limitation of password](https://github.com/gitbucket/gitbucket/wiki/FAQ#3-whats-limitation-of-password)" which is answered as:

>GitBucket has a limitation of password as below.
>
>    Use alphanumeric character, "-", "_" and "."

I was about to raise this as a documentation bug, but testing with the demo application suggests this limitation is currently in place!

**Comment by boughtonp** [comment]
I just found the insane justification in #1612

Guess I move on to trying another git web app.

**Comment by takezoe** [comment]
GitBucket has an option to disable this limitation.

- https://github.com/gitbucket/gitbucket/wiki/Basic-configurations
- https://github.com/gitbucket/gitbucket/issues/1654

For the standalone mode: `--validate_password=false` works. Also, it can be configured by an envronment variable: `GITBUCKET_VALIDATE_PASSWORD=false`.

Actually, I'm considering that making this option default.

**Comment by takezoe** [comment]
Dropped the password validation in https://github.com/gitbucket/gitbucket/pull/2439.
