### ISSUE TITLE
Anonymous users can see information

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2428]
## Issue
**Impacted version**: 4.33.0

**Deployment mode**: standalone app

**Problem description**:
For now, anonymous users can see GitBucket information even if you deny anonymous access in system settings.
![image](https://user-images.githubusercontent.com/17608272/74600163-daa6b700-50d0-11ea-9355-4e6fa9b73ae4.png)

How can we improve this by...
* Only logged-in users can see the notification if anonymous access is denied in system settings.
* Add new option to allow/deny anonymous access to the information like this.
  ![image](https://user-images.githubusercontent.com/17608272/74600226-720c0a00-50d1-11ea-81eb-6c8be0db0c41.png)

**Comment by takezoe** [comment]
> Only logged-in users can see the notification if anonymous access is denied in system settings.

I think this option is more intuitive.
