### ISSUE TITLE
Implement git refs API

### ISSUE THREAD

**Issue by ziggystar** [gitbucket/gitbucket#2437]
## Feature request: implement API
**Impacted version**: 4.33.0

I'm trying to get Jenkins with Github plugin to build my tags. Right now Jenkins does not discover any tags, and I think by scanning through plugin source (though I'm not 100% sure) that the GitHub plugin queries this part of the GitHub API, which I think is currently not implemented:

[Git Tags](https://developer.github.com/v3/git/tags/)

This is from the Github branch plugin [GitHubSCMSource](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java):

```
                request.listener().getLogger().format("%n  Getting remote tags...%n");
                // GitHub will give a 404 if the repository does not have any tags
                // we could rework the code that iterates to expect the 404, but that
                // would mean leaking the strange behaviour in every trait that consults the list
                // of tags. (And GitHub API is probably correct in throwing the GHFileNotFoundException
                // from a PagedIterable, so we don't want to fix that)
                //
                // Instead we just return a wrapped iterator that does the right thing.
                final Iterable<GHRef> iterable = repo.listRefs("tags");
```

This is the respective code I found within the Jenkins Github API plugin [GHRepository](https://github.com/github-api/github-api/blob/master/src/main/java/org/kohsuke/github/GHRepository.java):

```
    /**
     * Retrieves all refs of the given type for the current GitHub repository.
     *
     * @param refType
     *            the type of reg to search for e.g. <code>tags</code> or <code>commits</code>
     * @return paged iterable of all refs of the specified type
     * @throws IOException
     *             on failure communicating with GitHub, potentially due to an invalid ref type being requested
     */
    public PagedIterable<GHRef> listRefs(String refType) throws IOException {
        final String url = String.format("/repos/%s/%s/git/refs/%s", getOwnerName(), name, refType);
        return root.createRequest().withUrlPath(url).toIterable(GHRef[].class, item -> item.wrap(root));
    }
```

## Response format
This actually doesn't look like rocket science:

Here is request for Gitbucket tags: https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags

```
[
  {
    "ref": "refs/tags/1.0",
    "node_id": "MDM6UmVmOTM1MDc0NjoxLjA=",
    "url": "https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags/1.0",
    "object": {
      "sha": "1f164ecf2f59190afc8d7204a221c739e707df4c",
      "type": "tag",
      "url": "https://api.github.com/repos/gitbucket/gitbucket/git/tags/1f164ecf2f59190afc8d7204a221c739e707df4c"
    }
  },
  {
    "ref": "refs/tags/1.1",
    "node_id": "MDM6UmVmOTM1MDc0NjoxLjE=",
    "url": "https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags/1.1",
    "object": {
      "sha": "8aec16bf7f164e99605a26b337a79246ca374303",
      "type": "tag",
      "url": "https://api.github.com/repos/gitbucket/gitbucket/git/tags/8aec16bf7f164e99605a26b337a79246ca374303"
    }
  },
  ...
]
```

**Comment by ziggystar** [comment]
I've just checked again, and apparently Gitbucket implements this API somehow, also the commit comment states to support the Jenkins plugin. It's behavior is a bit strange, but now I don't know exactly whether `.../git/refs/tags/` should work (to make Jenkins happy) or not. At least it does not work for me.

**Comment by joshuacurtiss** [comment]
+1 on implementing [Git Refs for API v3](https://developer.github.com/v3/git/refs/). As of [this commit](https://github.com/jenkinsci/github-api-plugin/pull/49/commits/3c1f581d6d509b586facbca169d15af1134acb2a) in the official Jenkins plugin for GitHub API, it breaks if you're using GitBucket. I now have to hold the Jenkins GitHub API plugin back at version 1.111.4 to continue using GitBucket.

**Comment by takezoe** [comment]
Maybe this can fix the issue if what we need to implement is only 'get a reference' API? https://github.com/gitbucket/gitbucket/pull/2459

**Comment by joshuacurtiss** [comment]
So it seems! That’ll be easy fix for now!

**Comment by bitwiseman** [comment]
@SIkebe  

Sorry for the all the trouble around this.

Suggest you reopen this or I can create a new issue.  In GitHub REST API v3 there are two endpoints now: 

* Get a one ref or an array of refs: `git/refs/<ref_name>` - older 
* Get an array of refs: `git/matching-refs/<ref_name>` - newer
* Get a single ref: `git/ref/<ref_name>` - newer

The github-api library tried to move to using `git/ref` to get single refs, but that broke older versions of GitHub Enterprise (which don't include it).  So, we rolled back to using 'git/refs' with an additional check of the returned `ref` string to make sure the item returned is correct to mimic the new API behavior.   Both of paths are broken for gitbucket but for different reasons.  😢 

Again, sorry for the trouble.  I suggest you reopen this because most of the api is still not implemented: 

https://github.com/gitbucket/gitbucket/blob/3534b7172d4b8ee439349817a20d73e20e960299/src/main/scala/gitbucket/core/controller/api/ApiGitReferenceControllerBase.scala#L56-L74

Or I could open a new issue.

**Comment by ziggystar** [comment]
I can confirm that Jenkins does not discover tags in GitBucket with version 4.34.0 and the current GitHub Plugin in Jenkins.

**Comment by bitwiseman** [comment]
@ziggystar 
This should be fixed using the latest github-api and github-branch-source plugins in Jenkins.

**Comment by ziggystar** [comment]
@bitwiseman 
As of today, I'm on the current versions:
![image](https://user-images.githubusercontent.com/459632/91407064-c6dbca80-e842-11ea-906b-ff6fb95317c5.png)

Also I'm on Gitbucket 4.34.0.

If you have a working setup, can you please share your Jenkins config?

I'm also under the impression the the discovery in Jenkins is flaky. I had to add a match-all-wildcard parameter to the discovery settings to get the message "0 tags found" (or similar) to show up. Without the match-all, there would not even be a notice about tags in the discovery log of Jenkins.

As of today, I cannot even get the "0 tags found" to appear anymore.

**Comment by bitwiseman** [comment]
@ziggystar 
You are talking about `githbucket->github-api->github-branch-source` issues.  
I do not have a working gitbucket setup.  Sorry. 

I'm happy to continue this discussion in https://gitter.im/jenkinsci/github-branch-source-plugin if you like.
