### ISSUE TITLE
[Error] SSH Server is not going well

### ISSUE THREAD

**Issue by Dokman** [gitbucket/gitbucket#2441]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.33.0

**Deployment mode**: *explain here how you use GitBucket : standalone app
**Problem description**:
When i setup the SSH if i put localhost on server it works but if i put my dns it does not work.
if i use the localhost it works but my partner can't clone a project error from his cmd

![image](https://user-images.githubusercontent.com/2290904/79328794-e79c2700-7f16-11ea-8689-90692afedb0c.png)

**Comment by nauevg** [comment]
@Dokman check current version (4.37.2) - it works over ssh with hostname in my case.

**Comment by takezoe** [comment]
Let me close this issue since the issue seems to have been solved. Updating Apache MINA SSHD in recent version might have solved the issue, not intentionally though :-P
