### ISSUE TITLE
help: big js/css/png not load corrently when use Nginx as reverse proxy 

### ISSUE THREAD

**Issue by pbpf** [gitbucket/gitbucket#2446]
#1862 
 Issue
**Impacted version**: 4.30 above

**Deployment mode**: use Nginx as reverse proxy

**Problem description**: big js/css/png not load corrently
Example:
>:  curl   server/assets/common/images/feed.png    success (feed.png  2k)
     curl   server/assets/common/images/gitbucket.png     failed(gitbucket.png 15k)

![image](https://user-images.githubusercontent.com/6541871/80611945-e23df100-8a6d-11ea-8a26-2e4fe5156b37.png)

![image](https://user-images.githubusercontent.com/6541871/80615471-4cf12b80-8a72-11ea-90bf-29bd642005d8.png)

**Comment by takezoe** [comment]
@pbpf Could you show your Nginx configuration?

**Comment by takezoe** [comment]
Closing old questions.
