### ISSUE TITLE
Support "add webhook to repository" via REST API

### ISSUE THREAD

**Issue by solvingj** [gitbucket/gitbucket#2453]
### Before submitting an issue to GitBucket I have first:
- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.33.0

**Deployment mode**: From gitbucket docker image

For CI workflows and other automated use-cases, we need the ability to add a webhook to a repository through the REST API.  Webhook configuration does not appear to be supported over REST API yet.  

For what it's worth, it looks like the class that gives the functionality to the UI is here:
https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala#L234

**Comment by SIkebe** [comment]
GitHub equivalent
https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by solvingj** [comment]
Here is an article which describes how the webhooks for pull requests should be auto-created for all repositories under an organization when setting up organization-wide integrations between Jenkins and Github:  https://support.cloudbees.com/hc/en-us/articles/115003019232-GitHub-Webhook-Pipeline-Multibranch

**Comment by onukura** [comment]
For webhook api we need `hook_id` for request (e.g. GET `/repos/{owner}/{repo}/hooks/{hook_id}`), but currently WEB_HOOK table does not have `id` column or something which can identify 
Immutable index of each record. We might need to add new column...?

**Comment by solvingj** [comment]
Good question for @takezoe . I'm not sure .

**Comment by takezoe** [comment]
> Immutable index of each record. We might need to add new column...?

Looks like there is no other straightforward way. A workaround is using the hash value of hook url as the identifier, but I don't like such tricky workaround.

**Comment by solvingj** [comment]
Thanks to everyone involved.  This is extremely helpful.  I will test ASAP.
