### ISSUE TITLE
File size limit for releases

### ISSUE THREAD

**Issue by fridobobo** [gitbucket/gitbucket#2463]
I just create my first release yesterday. What I was trying to achive is to add my compiled files to this release as a single zip file. Unfortunally the size for the upload seems to be limited to 3MB, which is to small for most of my releases. 

Please provide the ability to add bigger files by default or make the Maximum size configurable.

**Comment by SIkebe** [comment]
You can configure max file size via CLI options or environmental variables. Have you tried them?
https://github.com/gitbucket/gitbucket/wiki/Basic-configurations#cli-options

**Comment by skullwritter** [comment]
tomcat8 configuration:
https://github.com/gitbucket/gitbucket/wiki/Tomcat8-configuration

**Comment by fridobobo** [comment]
Solved by @SIkebe . The Feature is already Theresa you just need to find it ;-)
https://github.com/gitbucket/gitbucket/wiki/Basic-configurations#cli-options

Thank you very much
