### ISSUE TITLE
Support for other DVCS/DRCS 

### ISSUE THREAD

**Issue by sirinath** [gitbucket/gitbucket#248]
It would be great to have support for other DVCS/DRCS going forward.

E.g.
1) Mercurial - main alternative to Git. More easy to use.
2) Bazzar - Git alternative. Middle road from Mercurial and Git
3) Darcs - many functional programming languages use this format

Good to have
4) Fossil - sourceforge supports this
5) Any other system supported by Souceforge, BerliOS, etc.
6) Veracity

**Comment by menangen** [comment]
Well nice idea is add mercurial with Jython, but in mercurial there are C compiled modules...so, may be need rewrite this modules into java code...
