### ISSUE TITLE
[FEATURE REQUEST] Function to quote / embed code into Wiki and Issue

### ISSUE THREAD

**Issue by Nunocky** [gitbucket/gitbucket#2485]
## Issue
**Impacted version**: 4.33.0

**Deployment mode**: Apache Tomcat

I would like to have the ability to quote and embed code in the Wiki, Issue.

e.g.
https://qiita.com/YumaInaura/items/3509e76dbe20c3502d5b

**Comment by skullwritter** [comment]
@Nunocky as the imagem in the comments?
![image](https://user-images.githubusercontent.com/7103685/88162485-f161b480-cc00-11ea-8fc2-1743dc998fe5.png)

**Comment by Nunocky** [comment]
> Sorry it's in Chinese i believe, the section of the "PullRequest や Issue や コメント欄にURLを貼り付ける"
> ![image](https://user-images.githubusercontent.com/7103685/88162485-f161b480-cc00-11ea-8fc2-1743dc998fe5.png)

Yes. 
I want to embed code snippets into issues and wiki.

→ https://github.blog/2017-08-15-introducing-embedded-code-snippets/

**Comment by onukura** [comment]
As a trial, I made simple [plugin](https://github.com/onukura/gitbucket-embedding-plugin) which replace code link to embed snippet on markdown by JS.
Although It is not good way at all to achieve this feature, as it should be done by modifying md renderer of GitBucket, it works in certain condition.
