### ISSUE TITLE
Is possible to group repositories by projects?

### ISSUE THREAD

**Issue by metalpalo** [gitbucket/gitbucket#2486]
Hi all,

My question is very simple. I would like to achieve something like in Bitbucket. That means that grouping certain repositories under some group(projects) and taking it also in url for fetching.

Another question: Is possible to create repository in subfolder. If so it could be considered a project. 
What I see now that all created repositories live in flat directory GITBUCKET_HOME/repositories/{userName}

thanks
brpalo

**Comment by skullwritter** [comment]
@metalpalo you have to create a new "group"
![image](https://user-images.githubusercontent.com/7103685/88162986-8f557f00-cc01-11ea-9652-9cad743348ee.png)
and then when creating a repo, you'll have to select it:
![image](https://user-images.githubusercontent.com/7103685/88163144-c461d180-cc01-11ea-881a-d6a21c0a64ad.png)

**Comment by metalpalo** [comment]
@skullwritter thank you very much, 
I didn't know that it could be used for this purpose :)

**Comment by skullwritter** [comment]
you're welcome
