### ISSUE TITLE
JSON files break the diff UI

### ISSUE THREAD

**Issue by pluk77** [gitbucket/gitbucket#2503]
We are using version 4.34 with a mariaDB db and run it as:

```java -jar gitbucket/gitbucket.war```

When viewing a commit I can only see the unified and split diff for the first few files. Thereafter is shows nothing, file not supported or file to big.

I understand the 'file not supported' and 'file too big' but why are the others not showing? We did not have this problem with version 4.33.

It seems like a json file breaks the diff UI as commits without a json files seems to work fine. All diffs for files before the json file work as expected, thereafter they are all blank. Not entirely sure if the json files are the cause or it it is pure coincidence. 

in the JS console I do see this:
```
Source map error: Error: request failed with status 404
Resource URL: http://172.21.72.71:8080/assets/vendors/jquery-textcomplete-1.8.4/jquery.textcomplete.min.js?20200803173958
Source Map URL: dist/jquery.textcomplete.min.map
```
as well as

```
Uncaught TypeError: params.oldText.split is not a function
    JsDiffRender http://172.21.72.71:8080/assets/common/js/gitbucket.js?20200803173958:104
    diffUsingJS http://172.21.72.71:8080/assets/common/js/gitbucket.js?20200803173958:80
    renderOneDiff http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8454
    render http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8526
    setTimeout handler*render http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8531
    setTimeout handler*render http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8531
    renderDiffs http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8534
    <anonymous> http://172.21.72.71:8080/root/prehmisPAS/commit/088744df891e01cabc6d20afc12ed5b766df64e5:8301
    jQuery 13
gitbucket.js:104:63
```

**Comment by pluk77** [comment]
Is there anybody else that has this issue?

**Comment by pluk77** [comment]
It seems that some json files work, while others don't. In the below example the first three work, thereafter everything is blank. This hampers the functionality of pull requests as I can not see the changes. I now also noticed an uncaught TypeError in the console

![image](https://user-images.githubusercontent.com/524179/92115103-3c6f0a00-edf2-11ea-8e67-82d43a27dc1b.png)

**Comment by pluk77** [comment]
Not sure if this is somehow usefull, but it appears to me that the JS that is supposed to render the Diff is unable to fully read the JSON text properly.

I had a look at the HTML and this is the part of the DOM that causes the error:

```
<tr class="diff-collapse-4 collapse in">
<td style="padding: 0;">
<div id="diffText-4" class="diffText"></div>
<input type="hidden" id="newText-4" data-file-name="public/bundles/prehmistheme/entrypoints.json" data-val="{
  &quot;entrypoints&quot;: {
    &quot;style&quot;: {
      &quot;js&quot;: [
        &quot;/bundles/prehmistheme/runtime.277810ea.js&quot;
      ],
      &quot;css&quot;: [
        &quot;/bundles/prehmistheme/style.378b3649.css&quot;
      ]
    }
  }
}">
<input type="hidden" id="oldText-4" data-file-name="public/bundles/prehmistheme/entrypoints.json" data-val="{
  &quot;entrypoints&quot;: {
    &quot;style&quot;: {
      &quot;js&quot;: [
        &quot;/bundles/prehmistheme/runtime.df2fadaa.js&quot;
      ],
      &quot;css&quot;: [
        &quot;/bundles/prehmistheme/style.d7b1d3da.css&quot;
      ]
    }
  }
}">
</td>
</tr>
```

**Comment by SIkebe** [comment]
@pluk77 Hmm I can't repro the issue.

![image](https://user-images.githubusercontent.com/17608272/92124831-394b3c80-ee39-11ea-82db-260083dd5c49.png)


Could you provide a minimum repro project so that we can investigate this further?

**Comment by pluk77** [comment]
I will try my best. When debugging, in both IE as well as FF, I see that somehow the old and net text is not correctly extracted from the dom:

![image](https://user-images.githubusercontent.com/524179/92210993-02544580-ee90-11ea-9ef6-1337fcbb8a1a.png)

as both oldText and newText come through as objects, not as text as happens with the other changes in the same commit:

![image](https://user-images.githubusercontent.com/524179/92211166-4b0bfe80-ee90-11ea-911f-0d70f9d5a282.png)

**Comment by pluk77** [comment]
So I did some testing and I created a text file which breaks the JS:

```
{
  "entrypoints": {
    "style": {
      "js": [
        "/bundles/prehmistheme/runtime.277810ea.js"
      ],
      "css": [
        "/bundles/prehmistheme/style.378b3649.css"
      ]
    }
  }
}
```

Did some more tests and found I could get the UI to break with a single text line. In the below change, the oldText js variable seems to be fine, but the newText variable throws a "Uncaught TypeError: params.newText.split is not a function" error. 

I think it is a pattern problem, as the same pattern is in the JSON files, which is probably why they break the JS.

Creating a .json file with this line:

```
{"":{{}}}
```

and after committing it, changing it to this:

```
{"":{"":{}}}
```

**Comment by pluk77** [comment]
It could have something todo with the way .data() is processing the value:

[jQuery .data()](https://api.jquery.com/data/)

"Every attempt is made to convert the attribute's string value to a JavaScript value (this includes booleans, numbers, objects, arrays, and null). A string is only converted to a number if doing so doesn't change its representation (for example, the string "100" is converted to the number 100, but "1E02" and "100.000" are left as strings because their numeric value of 100 serializes to "100"). When a string starts with '{' or '[', then jQuery.parseJSON is used to parse it; it must follow valid JSON syntax including quoted property names. A string not parseable as a JavaScript value is not converted.

To retrieve a data-* attribute value as an unconverted string, use the attr() method"

It could be that because a JSON file starts with a '{', it is parsed and returned as a valid JSON object, hence it is not returned as a string and therefore .split() is not available?
