### ISSUE TITLE
Issue completion in issue and PR comment

### ISSUE THREAD

**Issue by onukura** [gitbucket/gitbucket#2505]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

Username completion is implemented already, but not for issue completion.
It would be useful completion show up when you type `#`.

like this
![image](https://user-images.githubusercontent.com/26293997/89560529-18032a80-d852-11ea-9770-c48fe238ecdb.png)

**Comment by SIkebe** [comment]
Duplicate of #568?

**Comment by onukura** [comment]
@SIkebe  It seems to me... didn't notice... So I close this issue and I will mention #568 from #2513 ! Thanks!
