### ISSUE TITLE
Missing commit overview

### ISSUE THREAD

**Issue by fridobobo** [gitbucket/gitbucket#2512]
I just startet with gitbucket (coming from bonobo) and think this is a really great product. Especially the extensibility. But I also think there is missing one basic feature. In other Servers (like bonobo) there was a list of all commits. By clicking on a commit there where details regarding the commit displayed, especially what files were changed in that commit. This feature was very usefull, so where to find it or why is it not implemented?

See those Screenshots for bester understanding: 
https://bonobogitserver.com/resources/img/screenshots/commits.png
https://bonobogitserver.com/resources/img/screenshots/diff.png

**Comment by SIkebe** [comment]
@fridobobo Do you mean features like below images?

![image](https://user-images.githubusercontent.com/17608272/90312164-3e555400-df3d-11ea-81bc-71b188d74a60.png)

![image](https://user-images.githubusercontent.com/17608272/90312130-ed456000-df3c-11ea-844e-64837ce65d75.png)

![image](https://user-images.githubusercontent.com/17608272/90312124-e0287100-df3c-11ea-8a9b-b7512a86a6eb.png)

**Comment by fridobobo** [comment]
Oh, thats the feature I was searching for. I think it's a bit Hidden on its current place. Maybe it it an good idea to push it as an main menue entry called "commits" to the left sidebar.

**Comment by SIkebe** [comment]
> I think it's a bit Hidden on its current place. Maybe it it an good idea to push it as an main menue entry called "commits" to the left sidebar.

AFAIK, GitHub, Gitea, and GItLab also have a link (button) to the commit history on their repository top page just like GitBucket. So it's a very common place to have such a link.

* GitHub
![image](https://user-images.githubusercontent.com/17608272/90312956-68117980-df43-11ea-9ba7-e8ec2c476e4c.png)

* Gitea
![image](https://user-images.githubusercontent.com/17608272/90312967-795a8600-df43-11ea-9119-1dc608dc494b.png)

* GitLab
![image](https://user-images.githubusercontent.com/17608272/90312979-8d05ec80-df43-11ea-8df4-f5ebde81e23b.png)

note: GitLab and BitBucket also has one on the side bar, too.

![image](https://user-images.githubusercontent.com/17608272/90313069-6dbb8f00-df44-11ea-96ab-27fbf6d4b574.png)

I think the principal of GitBucket is its simplicity, ease of use and extensibility. In addition, considering that many plugins choose their links on side bar, IMO, I don't think that's a good idea to increase the number of links on the side bar by default.
However if a large number of users are also confused about this design and upvote your idea, then it's reasonable to reconsider the design of side bar.

**Comment by fridobobo** [comment]
I think it depends very much on your personal worflow.  When I work on a software repo I haven't used for a few days my first look is into the commits, cause I want to know what the last changes were and if someone else worked at the project in the meantime. At the very first moment this information is more important to me than the list of files. That's why I would have put in the sidebar at first or second entry. But that's just my opinion. I also accept if other think that this feature isn't usefull.

**Comment by SIkebe** [comment]
As I said above, a link to the commit history is not a hidden feature. It's on the repository top page, a very common place across different git-hosting services not only GitBucket.
@fridobobo Could you edit the title of this issue so that it explains the feature you request?

**Comment by SIkebe** [comment]
(Anyway, I don't think it's a good time to revamp the side bar design as @kasancode is working on a migration to AdminLTE 3.X) https://github.com/gitbucket/gitbucket/pull/2424

**Comment by SIkebe** [comment]
Close this for now. If many users consider this link is too difficult to find, we may redesign it.
