### ISSUE TITLE
Record DELETE activity of wiki page

### ISSUE THREAD

**Issue by onukura** [gitbucket/gitbucket#2522]
## Issue
**Impacted version**: all

Currently GitBucket reocrd activity of wiki only for CREATED and EDITED.
Because `ActivityService `has only `recordCreateWikiPageActivity `and `recordEditWikiPageActivity`. It would be nice if there is `recordDeleteWikiPageActivity `too and record page deletion.

**Comment by jyoo980** [comment]
I'd be interested in taking this one on 🙂

**Comment by jyoo980** [comment]
Attempted in #2523

**Comment by jyoo980** [comment]
This was closed by #2537

**Comment by onukura** [comment]
Thanks for your work!!
