### ISSUE TITLE
how to check repo size in gitbucket

### ISSUE THREAD

**Issue by Xavihernandez93** [gitbucket/gitbucket#2527]
hi team ,iam new to gitbucket i want to know how to check the size of my project / repo 

please help me with this

**Comment by takezoe** [comment]
Just clone a repository and check the diretctory size?

Or bare repositories are under `~/.gitbucket/repositories/<username>/<reponame>.git` of GitBucket server machine. You may be able to check the size of these directories.

**Comment by takezoe** [comment]
Do you need a way to check repo size on Web UI?

**Comment by Xavihernandez93** [comment]
yes how to see on UI ?

**Comment by takezoe** [comment]
Currently, there is no way to see the repo size on UI.

**Comment by Xavihernandez93** [comment]
oh  i see , thanks for the reply it would have been great we had that feature :) .
