### ISSUE TITLE
Autocomplete window messed up if candidate is too long

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2531]
## Issue
**Impacted version**: 4.35.0 (not yet released)

**Deployment mode**: standalone app

**Problem description**:
#2513 enabled autocompletion for issues/PRs. When one of the candidates is too long, the autocomplete window will get strange. 

![image](https://user-images.githubusercontent.com/17608272/91638668-16411700-ea4c-11ea-9cf1-80247e187a62.png)

Should we cut out the issue title, or split into several lines like GitHub? I think the former would be easy to implement and enough for GitBucket's use case.
(FYI, GitHub allows only 256 characters for issue title but GitBucket does not limit the length as long as your DB allows)

![image](https://user-images.githubusercontent.com/17608272/91638819-17267880-ea4d-11ea-8bff-e3b651af2feb.png)

**Comment by SIkebe** [comment]
@onukura Thoughts?

**Comment by onukura** [comment]
@SIkebe hmm... why not limit the number of character and add `...` at the end like below(limit by 50 characters)?
I guess we don't need show whole title on the completion list if you have first 50 characters.

![image](https://user-images.githubusercontent.com/26293997/91640237-02e77900-ea57-11ea-8cc9-fca4023552c4.png)

**Comment by onukura** [comment]
@SIkebe Actually it means user completion has same issue. I tried long user name with maximum length(=100). 

![image](https://user-images.githubusercontent.com/26293997/91640380-1f37e580-ea58-11ea-85d2-97a9fa0b700a.png)

**Comment by SIkebe** [comment]
> why not limit the number of character and add `...` at the end like below(limit by 50 characters)?

IMHO, that would be OK. Sorry, I should have come up with this case in your PR 😅 
Once you enter the issue number, you can get whole title as a tooltip (#2532 ).
![image](https://user-images.githubusercontent.com/17608272/91640564-81451a80-ea59-11ea-8ad4-f8f388818e96.png)

-----

>Actually it means user completion has same issue. I tried long user name with maximum length(=100).

Right. So I thought cutting out the candidate will be easier to implement, too.
There are few cases that user name is so long, but issue/PR title can be.

**Comment by onukura** [comment]
@SIkebe I made PR #2534  for this issue.
