### ISSUE TITLE
Add support for GitHub API v3 delete-comment endpoint

### ISSUE THREAD

**Issue by jyoo980** [gitbucket/gitbucket#2539]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

This is a `TODO` in `ApiIssueCommentControllerBase.scala` that I want to take on.

**Comment by onukura** [comment]
solved by #2540
