### ISSUE TITLE
Create new repository from existing repository URL

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#255]

**Comment by simmyg89** [comment]
+1
something like this:
https://import.github.com/new

**Comment by aadrian** [comment]
+1 for the github import style.

**Comment by pchard** [comment]
is this implemented?

**Comment by aadrian** [comment]
I think this should be better as a Plug-in, since this way there could be various implementations (e.g. importing issues too, or from other VCS-es too - like GitHub already does)

**Comment by lavvy** [comment]
Any news on this feature

**Comment by aadrian** [comment]
@lavvy as it looks now, this feature could be implemented as a **plug-in**, as it does not seems to require functionality not already provided by the existing API. 

List of already existing plug-ins done by the community: http://gitbucket-plugins.github.io/
