### ISSUE TITLE
Does it not support github api search?

### ISSUE THREAD

**Issue by benbendiadai** [gitbucket/gitbucket#2554]
I need to search content from files in my project. There is search code api in github api, but it doesn’t work in gitbucket. Is it incompatible?

**Comment by SIkebe** [comment]
Yes, GitBucket does not support GitHub [Search API](https://docs.github.com/en/rest/reference/search) for now.
Supported APIs are listed here.
https://github.com/gitbucket/gitbucket/wiki/API-WebHook

Instead, you can use [gitbucket-fess-plugin](https://github.com/codelibs/gitbucket-fess-plugin) to search contents across multiple repositories, though.

**Comment by benbendiadai** [comment]
> Yes, GitBucket does not support GitHub [Search API](https://docs.github.com/en/rest/reference/search) for now.
> Supported APIs are listed here.
> https://github.com/gitbucket/gitbucket/wiki/API-WebHook
> 
> Instead, you can use [gitbucket-fess-plugin](https://github.com/codelibs/gitbucket-fess-plugin) to search contents across multiple repositories, though.

Thanks for the reply
But,I want to search from the API instead of the page, can this plugin do it?

**Comment by SIkebe** [comment]
I don't know much about Fess, but it seems to have a Web API.
https://fess.codelibs.org/13.9/api/api-search.html

**Comment by benbendiadai** [comment]
> I don't know much about Fess, but it seems to have a Web API.
> https://fess.codelibs.org/13.9/api/api-search.html

Thanks,I'll try it

**Comment by takezoe** [comment]
Closing old questions.
