### ISSUE TITLE
Function to create new branch and PR when user edit file on UI.

### ISSUE THREAD

**Issue by onukura** [gitbucket/gitbucket#2559]
## Issue
**Impacted version**: 4.34.0

**Problem description**:

Currently when you edit file on UI (web browser), commit changes directory on a current branch. It would be nice if we can choose direct commit or **create new branch and start PR**.

- example of GitHub. 

    ![image](https://user-images.githubusercontent.com/26293997/94345841-c150ea80-0063-11eb-85f5-c54e03021381.png)

**Comment by takezoe** [comment]
In that case, is the branch created in the same repository? or created in the forked repository?

If it's created in the forked repository, this option should be available for not only users who can write to the repository but also who cannot have a permission to write to the repository but can create a pull request.

**Comment by onukura** [comment]
> In that case, is the branch created in the same repository? or created in the forked repository?

I thought `the same repository`.

**Comment by takezoe** [comment]
Hm, if my understanding is correct, GitHub allows that non-committers also can create a pull request using that option. Looks like hidden branches are created in the same repository.

Anyway, my point is who can use that option? Would you follow GitHub behavior? or allow only users who have write permission to the repository?

**Comment by aadrian** [comment]
> or allow only users who have write permission to the repository?

+1

In an (Github) Enterprise scenario, IMHO this makes more sense, and keep configuration and security simpler.

**Comment by onukura** [comment]
> GitHub allows that non-committers also can create a pull request using that option.

I didn't know that...

IMHO as @aadrian said, it is simple and make sense that only users who have write permission to the repository has permission to do this action.

**Comment by takezoe** [comment]
Yeah, I totally agree with allowing this to users who have write permission to te repository because if we once allow it to wider users, it will be impossble to restrict later. Starting with the simplest would be better.
