### ISSUE TITLE
Bug with Webhook API implementation

### ISSUE THREAD

**Issue by solvingj** [gitbucket/gitbucket#2596]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.35+

**Deployment mode**: standalone app

**Problem description**:

The webhooks endpoint was very generously implemented on repositories here:

https://github.com/gitbucket/gitbucket/pull/2551/files

But when I try to use it, it only creates webhook for event `push`. Even if I specify `pull_request` only. 

```
-d '{"name":"jenkins","config":{"url":"http://jenkins:8080/github-webhook/","events":["pull_request"]}}'
```

I believe a mistake was made where `"push"` was hardcoded.

https://github.com/gitbucket/gitbucket/pull/2551/files#r521762944

I believe it's supposed to accept any of the following options:

Create - Branch, or tag created.
Gollum - Wiki page updated.
Issue comment - Issue commented on.
Issues - Issue opened, closed.
Pull request - Pull request opened, closed, or synchronized.
Pull request review comment - Pull request diff commented on.
Push - Git push to a repository.

**Comment by onukura** [comment]
@solvingj I tried this API with following body and it worked. Could you try with `event` property outside `config` ?

```
{"config": {
    "url": "viaAPI6@gb.com",
    "content_type": "json",
    "secret": "123456"
  },
  "events": ["push", "pull_request"],
  "active": false}
```

**Comment by solvingj** [comment]
That was the problem, fixed, thank you.
