### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by alhirzel** [gitbucket/gitbucket#2599]
# Issue
**Impacted version**: deployment at Heroku

**Deployment mode**: deployment at Heroku

**Problem description**:
- https://gitbucket.herokuapp.com/ is down

> # Application error
>
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
`heroku logs --tail`

**Comment by av8ta** [comment]
Still down two months later.

**Comment by takezoe** [comment]
Looks like it's working now, although we did nothing. Maybe the lack of credits? Not really sure though.
