### ISSUE TITLE
Internal Server Error when delete this repository

### ISSUE THREAD

**Issue by s-takatsu** [gitbucket/gitbucket#2628]
## Issue
**Impacted version**: 4.35.3
**os version**: windows 10 pro, windows server 2016 both

**Deployment mode**: use GitBucket : standalone app,

**Problem description**:
when delete this repository , occured

*****
Internal Server Error
org.apache.commons.io.IOExceptionList: 1 exceptions: [java.io.IOException: Unable to delete file: c:\opt\gitbucket\.gitbucket\repositories\root\hoge.wiki.git\objects]
*****

**Comment by shreejanshrestha** [comment]
Same issue is appearing probably from 4.34.0.
Error log below:
-
Internal Server Error

org.apache.commons.io.IOExceptionList: 1 exceptions: [java.io.IOException: Unable to delete file: f:\gitbucket\tmp\20210131\.\home\repositories\root\test0.wiki.git\objects]

org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:345)
org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1206)
gitbucket.core.service.RepositoryService.$anonfun$deleteRepository$1(RepositoryService.scala:241)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
gitbucket.core.service.RepositoryService.deleteRepository(RepositoryService.scala:237)
gitbucket.core.service.RepositoryService.deleteRepository$(RepositoryService.scala:236)
gitbucket.core.controller.RepositorySettingsController.deleteRepository(RepositorySettingsController.scala:26)
gitbucket.core.controller.RepositorySettingsControllerBase.$anonfun$$init$$51(RepositorySettingsController.scala:433)
gitbucket.core.util.OwnerAuthenticator.$anonfun$authenticate$1(Authenticator.scala:38)
scala.Option.map(Option.scala:242)
gitbucket.core.util.OwnerAuthenticator.authenticate(Authenticator.scala:36)
gitbucket.core.util.OwnerAuthenticator.ownerOnly(Authenticator.scala:30)
gitbucket.core.util.OwnerAuthenticator.ownerOnly$(Authenticator.scala:30)
gitbucket.core.controller.RepositorySettingsController.ownerOnly(RepositorySettingsController.scala:26)
gitbucket.core.controller.RepositorySettingsControllerBase.$anonfun$$init$$50(RepositorySettingsController.scala:430)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:180)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
scala.Option.flatMap(Option.scala:283)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
scala.collection.immutable.Stream.flatMap(Stream.scala:206)
org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFilter.scala:64)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
scala.collection.AbstractIterable.foreach(Iterable.scala:920)
gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:80)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:572)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
org.eclipse.jetty.server.Server.handle(Server.java:516)
org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
java.lang.Thread.run(Unknown Source)

**Comment by takezoe** [comment]
This error has been reported frequently by Windows users in the past and our conclusion is this is not avoidable on Windows. Our solution is deleting a repository logically at the time and queueing delete requests and delete the repository physically later asynchronously. Though I'm not sure if we already have an issue for this, it cannot be implemented immediately anyway.

**Comment by s-takatsu** [comment]
Thank you for contacting me.
When I use version 4.32.0 now, 4.32.0 works fine.
We will use version 4.32.0.

**Comment by takezoe** [comment]
@s-takatsu Hmm... Some changes between 4.32.0 and 4.34.0 (reported by @shreejanshrestha ) affected? or it might be a timing issue? Anyway, identifying the root cause would be difficult. Please let me know if you get the same error even on 4.32.0. 🙇

**Comment by shreejanshrestha** [comment]
> 
> Our solution is deleting a repository logically at the time and queueing delete requests and delete the repository physically later asynchronously.

@takezoe san,
Would be very very thankful if implemented in this way. Complete logical delete, followed by phvsical delete.

Thank you in advance, and looking forward to it.

**Comment by shreejanshrestha** [comment]
I was debugging this issue. Don't know whats the solution.
The reason behind the problem is, some files inside the wiki folder has read only attributes set. I could delete without problem from web inteface of gitbucket, if the read only attribs are manually removed.

For the time being the work around is to remove the read only attribs before deleting.
