### ISSUE TITLE
organization's repository does not created, when use create_repo API with an unmanaged user 

### ISSUE THREAD

**Issue by s-takatsu** [gitbucket/gitbucket#2642]
## Issue
**Impacted version**: 4.35.3
**os**: windows 10
**jdk**: openjdk-11.0.3

## description
When using the create_repo API with an unmanaged user of an organizational object, nothing creates a repository.
When using the create_repo API with an unmanaged user, a repository can be created.

## code
        g = Github(base_url="http://localhost:8080/api/v3", login_or_token=user_name, password=password)

        org = g.get_organization(login=group_name)

        org.create_repo(name=repo_name, private=True, description=repo_name)

**Comment by takezoe** [comment]
What does 'an unmanaged user' actually mean?

**Comment by s-takatsu** [comment]
sorry.
it's mean "Not Magager" user, 
it's mean "Member" user .

**Comment by takezoe** [comment]
I see. Thanks for the clarification!
