### ISSUE TITLE
com.github.bkromhout:java-diff-utils:2.1.1 disappeared from Maven Central

### ISSUE THREAD

**Issue by kvtb** [gitbucket/gitbucket#2676]
`com.github.bkromhout:java-diff-utils:2.1.1` disappeared from Maven Central

Please, consider to upload a copy somewhere else

**Comment by kvtb** [comment]
It can be downloaded from https://bintray.com/bkromhout/maven/java-diff-utils/2.1.1, but whole bintray is going down

**Comment by takezoe** [comment]
Maybe we should move to this successor library: https://github.com/java-diff-utils/java-diff-utils
