### ISSUE TITLE
SVG files are served with wrong mimetype

### ISSUE THREAD

**Issue by redfellow** [gitbucket/gitbucket#2723]
## Issue
**Impacted version**: 4.33.4 & 4.35.3

**Deployment mode**:  docker

**Problem description**:
When hitting "RAW", SVG images are served as `Content-Type: text/plain;charset=utf-8` instead of `Content-Type: image/svg+xml`. Same applies when an `.md` document is referencing a svg with a relative path. PNG/JPG work as expected, probably because browsers try to be smart.

**Comment by takezoe** [comment]
That's due to the security reason because SVG files can contain script that can run on web browsers: https://github.com/gitbucket/gitbucket/pull/2389

**Comment by redfellow** [comment]
Alright, but is there any way to turn that safety measure off? Our repos are completely private, and we use SVG images in our documentation, and it would be great if SVG images worked in markdown (now it just generates a broken image icon).

**Comment by takezoe** [comment]
Hm, adding a repository-level option to allow rendering SVG files (and other files) might be a good idea.

**Comment by takezoe** [comment]
Created a pull request (https://github.com/gitbucket/gitbucket/pull/2806). I think it works for this but could be controversial to provide such an option. Could you give your opinion about it?

**Comment by redfellow** [comment]
Looks good to me!

**Comment by takezoe** [comment]
@redfellow Thanks for your comment. I modified the precautionary statement slightly and merged. It will be available in the next version.
