### ISSUE TITLE
Proposal: Allow titles to be longer than 100 characters

### ISSUE THREAD

**Issue by udaken** [gitbucket/gitbucket#2724]
## Issue
**Impacted version**: 4.35.1

**Deployment mode**: standalone app with Jetty

**Problem description**:
When creating a pull request, GitBucket will show an error "Title cannot be longer than 100 characters.".
I've encountered this error many times.
However, I was able to make the name longer than 100 characters by changing the title after creating the pull request.

Would you like to relax the length of the title when creating a pull request?

**Comment by takezoe** [comment]
The title of issues and pull requests is TEXT column. 
https://github.com/gitbucket/gitbucket/blob/ab218f85409c3584f32ec64382cc3afa87e3667c/src/main/resources/update/gitbucket-core_4.0.xml#L197

Probably, we don't need to have a limitation for the length of the title of issues and pull requests.

**Comment by udaken** [comment]
Thanks, @takezoe 

GitBucket is so useful!
