### ISSUE TITLE
Updating to 4.35.3 broke the access to the repositories

### ISSUE THREAD

**Issue by Brokkonaut** [gitbucket/gitbucket#2809]
## Issue
**Impacted version**: 4.35.3

**Deployment mode**: Webapp in a Tomcat container (Apache Tomcat/9.0.48)

**Problem description**:
Today I updated gitbucket, since the update I can no longer access any repository. Login is working but not much else (i see the repositorys but when I try to access them I only get errors)

When I try to access a repository in the browser I get the following message:

javax.servlet.ServletException: Während der Filter Bearbeitung trat eine Exception auf
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.sql.SQLException: Connection is closed
	com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	com.sun.proxy.$Proxy5.setAutoCommit(Unknown Source)
	com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414)
	com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	slick.jdbc.JdbcBackend$BaseSession.endInTransaction(JdbcBackend.scala:517)
	slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:32)
	com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

The logged exception (there are thousands like this in the logs...) is:
https://hastebin.com/malobuxehu.properties

I'm using the H2 database for the storage.

I think gitbucket might have failed updating some database tables or so? At least it looks like that..

**Comment by Brokkonaut** [comment]
Switching to a mysql database backend fixed the issue, so I don't need any support, but I leave it open in case there is something that should be fixed here.

**Comment by takezoe** [comment]
H2 database is often broken. But if login worked, the database was also alive. It's weird.

Anyway, taking a backup before upgrading is always recommended. Using an external database (PostrgeSQL/MySQL) is also recommended.

**Comment by takezoe** [comment]
I would close this because I couldn't find something that needs to be fixed on GitBucket side. Please let me know if you have further troubles in GitBucket upgrading.
