### ISSUE TITLE
Question about (MS) SQL Server support.

### ISSUE THREAD

**Issue by gzp-crey** [gitbucket/gitbucket#2812]
**Impacted version**: based on master head 
I've tired to add sql server support as we have some cloud hosted servers already. Adding the connection handling was quite easy:
```
    object MSSQL extends DatabaseType {
        val jdbcDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        val slickDriver = BlockingSQLServerDriver
        val liquiDriver = new MSSQLDatabase()
    }
```

But migrations has a few issue, that can be solved "locally":
 - create or replace view should be altered to something like `if exist drop`
 - the LiquibaseMigration treats the FALSE (TRUE) as column names
The more concerning part is the foreign key IDX_COMMIT_STATUS_FK2. sql server has some issue with the onupdate and ondelete=CASCADE as it creates some circular reference according to sql server. Is this CASCADE abused in the features or is it just a natural choice for the other db backends. (It'd be hard to tell without going into details and understanding how each feature works.
```
Introducing FOREIGN KEY constraint 'IDX_COMMIT_STATUS_FK2' on table 'COMMIT_STATUS' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
```

(At this point I've stopped experimenting with the port)

Do you know any other blocking issue or incompatible feature ?

**Comment by takezoe** [comment]
Solidbase supports database-specific migration: https://github.com/gitbucket/solidbase#apply-rdbms-specific-configuration so `create or replace view` case can be covered. For `CASCASE`, however, GitBucket might rely on the `CASCADE` behavior in the application level.

Unfortunately, I'm not familiar with SQL Server. So I don't know whether there are other issues to support SQL Server.
