### ISSUE TITLE
Feature request: Custom SSH URL

### ISSUE THREAD

**Issue by Ami-OS** [gitbucket/gitbucket#2818]
## Issue
**Impacted version**: 4.35.3

**Deployment mode**: Tomcat 9 + PostgreSQL + Apache reverse proxy

**Problem description**:

![螢幕擷取畫面 2021-07-11 174534](https://user-images.githubusercontent.com/58389183/125190617-a1945700-e270-11eb-8960-df5aa844ddf0.png)

I setted port forward, The SSH URL displayed on the Web UI is not what I need :-(

I hope the SSH URL is configurable (Can even remove the port).

Thx. :-)

**Comment by keywordsalad** [comment]
@takezoe I’m wanting this same feature. Would I be good to submit a PR or are there some additional considerations to be taken into account?

**Comment by takezoe** [comment]
@keywordsalad Great. That's appreciated! I think there is no special consideration that need to be taken into account.
