### ISSUE TITLE
Finer privilege control

### ISSUE THREAD

**Issue by kastork** [gitbucket/gitbucket#282]
In enterprise settings there's a need for slightly more control over privileges.

Currently we have:

Public
- All users and guests can read this repository.
- Owner/collaborators can write

Private
-Collaborators/Group Members can read  and write.

Needed:

Either,
-Private needs to have user by user control over write privileges.

or, have another level:

SemiPrivate
-Guests can't read
-Logged in members can read
-Collaborators/Group Members can read and write.

**Comment by takezoe** [comment]
Merge with #1286
