### ISSUE TITLE
how to deploy it to heroku help

### ISSUE THREAD

**Issue by gautamjethe** [gitbucket/gitbucket#2852]
I got the error while deploying it to heroku :

```
Not a valid command: stage (similar: last-grep, set, last)
remote:        [error] Not a valid project ID: stage
remote:        [error] Expected ':'
remote:        [error] Not a valid key: stage (similar: state, target, tags)
remote:        [error] stage
```

please help me @takezoe

**Comment by takezoe** [comment]
This repository could be a reference how to deploy GitBucket to Heroku:
https://github.com/gitbucket/gitbucket.herokuapp.com

**Comment by takezoe** [comment]
I would close this since it doesn't seem a GitBucket issue. Feel free to send your message in Gitter room (https://gitter.im/gitbucket/gitbucket) if you have further questions.
