### ISSUE TITLE
Doesn't accept ed25519 keys.

### ISSUE THREAD

**Issue by Charadon** [gitbucket/gitbucket#2926]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.36.2

**Deployment mode**: *Standalone app running under NetBSD, with reverse proxy under nginx*

**Problem description**:
For some reason, the ssh server in gitbucket will not take my ed25519 key. When I attempt to connect, I get this error (IP and Port has been redacted): 
`Unable to negotiate with xxx.xxx.xxx.xxx port xxxx: no matching host key type found. Their offer: ssh-rsa`
It seems that it only accepts ssh-rsa keys, however if old issues are to be believed, this should've been fixed years ago. Has anything changed?

The key in question was generated like this: `ssh-keygen -t ed25519 -b 521`

**Comment by gemmaro** [comment]
This may be related to #2495.

**Comment by Charadon** [comment]
> This may be related to #2495.

I dunno, but I don't sign my commits. The only other time i've seen this error outside of gitbucket was when I upgraded from openssh 6 to openssh 8, and it dropped SHA1 RSA Key support. That's actually the whole reason I went to ed25519 keys =P

**Comment by takezoe** [comment]
EDDSA support was added to bc-java in https://github.com/bcgit/bc-java/issues/636 and seemed to be released in 1.65 (https://github.com/bcgit/bc-java/commit/ab48c9114e2e4c916072cc9c6b8e461fe6c04ac5). However, the latest JGit still uses bc-java 1.60.
