### ISSUE TITLE
Audit login/logout inside activity.log

### ISSUE THREAD

**Issue by drumbsd** [gitbucket/gitbucket#2928]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: ALL

**Problem description**:

In activity.log there a lot of information about what user are doing inside the git repos but seems that it's missing the information about user login/logout. I need to find this information in other file or it's something that can't be logged at the moment?

**Comment by takezoe** [comment]
Currently, login and logout are not logged.

**Comment by drumbsd** [comment]
Yep sorry I didn't know the use of gitter. By the way, since I didn't find any kind of questions about login/logout logging maybe it is worth to write this information inside the FAQ? Which is the right workflow? Can I edit directly the FAQ adding a paragraph where we explain where user activity are logged and the current limitation?

**Comment by takezoe** [comment]
It's documented here: https://github.com/gitbucket/gitbucket/blob/master/doc/activity.md

**Comment by drumbsd** [comment]
Perfect many thanks
