### ISSUE TITLE
Where Gitbucket support synchronous pre-receive hooks?

### ISSUE THREAD

**Issue by lngg057** [gitbucket/gitbucket#2942]
## Issue
**Impacted version**: 4.36.2

**Deployment mode**: *standalone app*

**Problem description**:
- *For project reasons, I am trying to integrate Git Commit access control in gitbucket. The initial tool selected is **Verigreen***
- *According to Verigreen's official description. The prerequisite for using Verigreen is **"git provider supporting synchronous pre-receive hooks"**.*
- *Because I could not find the relevant document description of Gitbucket , I would like to ask whether gitbucket supports synchronous pre-receive hooks, thank you very much*

**Comment by takezoe** [comment]
If you mean server-side git hook, GitBucket doesn't support it.

**Comment by takezoe** [comment]
Ah, but GitBucket has an extension point that is similar to server-side hook. It can be used to add additional access control for git push.

**Comment by lngg057** [comment]
> Ah, but GitBucket has an extension point that is similar to server-side hook. It can be used to add additional access control by plugins.

Thank you for your reply~
