### ISSUE TITLE
TomCat deployment error `NoClassDefFoundError: javax.servlet.http.HttpSessionListener`

### ISSUE THREAD

**Issue by ThePrez** [gitbucket/gitbucket#2960]
## Issue
**Impacted version**: 4.37.1

**Deployment mode**: 
Web Container: TomCat 10
Java version: Java 11 (IBM Semeru)
Operating System: IBM i

**Problem description**:
When deploying in TomCat 10, deployment fails. The logs show:
```fortran
28-Dec-2021 14:35:33.990 SEVERE [http-nio-9080-exec-2] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [gitbucket.core.servlet.SessionCleanupListener]
java.lang.NoClassDefFoundError: javax.servlet.http.HttpSessionListener
```
The root cause is simply that GitBucket is using Java EE and TomCat is using Jakarta EE. It does work if I follow [the TomCat migration steps](https://tomcat.apache.org/migration-10.html). 

This issue is really more of a curiosity: are there any plans to adopt Jakarta in the future?

**Comment by ThePrez** [comment]
Based on the answer, we should update the main README for the project, where it says:

> You can also deploy `gitbucket.war` to a servlet container which supports Servlet 3.0 (like Jetty, Tomcat, JBoss, etc)

To perhaps something like:

> You can also deploy `gitbucket.war` to a servlet container which supports Servlet 3.0 (like Jetty, Tomcat, JBoss, etc). If Jakarta EE is required, you may need to go through a migration process (for example, TomCat as a migration tool documented here).

**Comment by takezoe** [comment]
Thanks. We will update README for now and will migrate GitBucket to Jakarta EE at some point in the future (#2985)

**Comment by takezoe** [comment]
By the way, does Tomcat's migration tool actually work for GitBucket? If no, or not sure, we may not have to mention it in README. I prefer to say just like "GitBucket doesn't support Jakarta EE yet." in that case.

**Comment by codeling** [comment]
I just tried running on Tomcat 10 and hit this issue.

> It does work if I follow [the TomCat migration steps](https://tomcat.apache.org/migration-10.html).

Which exact steps? Did you use the migration tool or did you rely on the automatic conversion during deployment? If the latter, do you know where the legacyAppBase folder is situated on debian systems? I guess /var/lib/tomcat10/webapps-javaee, but this folder doesn't exist yet, is it enough to create it?

I tried the migration tool, but now I get another error - I used to set the gitbucket home folder through an environment variable, and this doesn't seem to work.

Seeing that Tomcat9 actually isn't available anymore on the current stable debian 12 - are there any plans to migrate to Jakarta EE? Or what other platform could I run it instead?

Thanks!
