### ISSUE TITLE
Rejected commit not announced when using web editor

### ISSUE THREAD

**Issue by ziggystar** [gitbucket/gitbucket#2971]
## Issue
**Impacted version**: 4.37.1

I have written a plugin that performs server-side checking of commit messages using the prereceive hook. This is working when pushing from a local repository. The push fails the generated error message is shown.

But when I am using the integrated editor to make a commit that results in a rejection, no error is shown. Everything looks as if the commit was successful. GitBucket is even showing the committed file content right after pressing 'Commit'. But when reloading, the commit has disappeared.

**Comment by takezoe** [comment]
https://github.com/gitbucket/gitbucket/blob/baa9caf010bd9c1e92ef5cbc798cdd8fb03d3d01/src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala#L180
