### ISSUE TITLE
How to configure Jetty idle timout?

### ISSUE THREAD

**Issue by evryjohanandersson** [gitbucket/gitbucket#3021]
For a large repo I am getting the error:
   2022-03-25 15:31:59.244:WARN:oejshC.ROOT:qtp254413710-20: Internal error during upload-pack from E:\gitbuckethome
        \repositories\Documentation\doc.git
   java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms

As far as I can conclude from googling, this is due to a change in a Jetty parameter 'jetty.http.idleTimeout' that had its default value lowered from 5min to 30s in some Jetty version. 
Is there a gitbucket commandline parameter to set this value?
If not, is there some file I can put in GITBUCKET_HOME that will change the value.
I am running under Windows Server 2016.

**Comment by takezoe** [comment]
Do you use embedded Jetty? Unfortunately, GitBucket doesn't have such a parameter for embedded Jetty, but it might be worth adding if it can solve your issue.

**Comment by evryjohanandersson** [comment]
We are just using 'gitbucket.war', I was assuming it had Jetty bundled. 
Yes, it would be nice with a commandline parameter perhaps so we can add something like below to our gitbucket.bat
%java2% -Xmx5G -jar %~dp0\gitbucket.war --jetty.http.idleTimeout=300000

**Comment by takezoe** [comment]
#3027 will allow to specify Jetty idle timeout by `jetty_idle_timeout` and set 5 min if not specified.
