### ISSUE TITLE
Issue or pull request last updated time is overwritten from another repository

### ISSUE THREAD

**Issue by kaz-on** [gitbucket/gitbucket#3052]
**Impacted version**: 4.37.2 

**Deployment mode**: standalone app

**Problem description**:
Issue or pull request last updated time is overwritten from another repository.

*Step to reproduce*:
1. Create two (or more) repositories such as `repoA` and `repoB`.
2. Create an issue `#1` in `repoA`.
3. Create an issue `#1` in `repoB`.
   **It is important that the issue number is the same for `repoA#1` and `repoB#1`.**
5. Access the following APIs and verify that both last updated times are correct in the `updated_at` field.
   * `<GitBucket_URL>/api/v3/repos/<Owner>/repoA/issues/1`
   * `<GitBucket_URL>/api/v3/repos/<Owner>/repoB/issues/1`
6. Add a comment to `repoA#1` **only**. Do nothing to `repoB#1`.
8. If you access the above APIs again, **the last updated time of `repoB#1` is the same as that of `repoA#1`.**

*Note*:
There seems to be a problem with the database update process, not the API, because the values in the database have been changed.

**Comment by takezoe** [comment]
@kaz-on Fixed in #3053. Thank you for the reporting!
