### ISSUE TITLE
README. MD Chinese garbled code

### ISSUE THREAD

**Issue by wencyGit** [gitbucket/gitbucket#3100]
- gitbucket version 4.37.2
- README. MD Chinese garbled code

![image](https://user-images.githubusercontent.com/21151964/182526512-6ba01e7d-a384-41dc-9033-a4537e672744.png)

**Comment by takezoe** [comment]
Seems like the same issue as https://github.com/gitbucket/gitbucket-docker/issues/35?

**Comment by takezoe** [comment]
Identified that this issue is caused by upgrading Scalatra from 2.7.1 to 2.8.0 in GitBucket 4.36.2 (https://github.com/gitbucket/gitbucket/pull/2834). Looks like something changed in Scalatra 2.8.0 affected.

**Comment by takezoe** [comment]
Identified that the root cause is upgrading juniversalchardet library on Scalatra in https://github.com/scalatra/scalatra/pull/1092. The same fix (replacing US-ASCII with UTF-8) is necessary in GitBucket too.
