### ISSUE TITLE
SSH broken in v4.38.0

### ISSUE THREAD

**Issue by porkotron** [gitbucket/gitbucket#3129]
## Issue
**Impacted version**: 4.38.0

After upgrading to 4.38.0 I get "broken pipe" when connecting with ssh.
#3128 seems to fix it. Might be related to this: https://issues.apache.org/jira/browse/SSHD-1285.

**Comment by takezoe** [comment]
#3128 has been released as a part of 4.38.1

**Comment by porkotron** [comment]
Yes ssh works again in v4.38.1
