### ISSUE TITLE
Drop Java 8 support

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#3145]
### Before submitting an issue to GitBucket I have first:

- [ ] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] searched for similar already existing issue
- [ ] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: xxxx

**Deployment mode**: *explain here how you use GitBucket : standalone app, under webcontainer (which one), with an http frontend (nginx, httpd, ...)*

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by aadrian** [comment]
@takezoe if one really wants to drop java 8 support, than it would make sense to jump to Java 17 directly (since it's LTS)

**Comment by takezoe** [comment]
The main motivation of dropping Java 8 support is Scalatra 3 will require Servlet 5.0 and Jetty 11 which support Servlet 5.0 (and even Jetty 10) requires Java 11. In order to upgrade to Scala 3, we have use Scalatra 3.

In short, dropping Java 8 support is required to upgrade to Scala 3 (in the future).

Currently, I plan to use Java 11 to build GitBucket release artifacts. Of course, it would also work with Java 17.
