### ISSUE TITLE
News feed is not visible for colaborator

### ISSUE THREAD

**Issue by lfgcas** [gitbucket/gitbucket#3148]
## Issue
News feed is not visible for "Normal" collaborators.

**Impacted version**: 4.38.2

**Deployment mode**: 
gitbucket is running as a service in an ubunut 20.04 server

**Problem description**:
When you have all your repositories private, and adding an user as a "Normal" collaborator, the news feed is not showing at all eventhough there is plenty information on that feed.

![image](https://user-images.githubusercontent.com/28535030/193164496-279035d4-0231-404f-a5fa-feba5096bfe6.png)

### this is a view with the admin:

![image](https://user-images.githubusercontent.com/28535030/193167781-b7eff52c-94ba-4c50-96e6-28ee8e03289d.png)

**Comment by SMauchle** [comment]
In our use-case it would make sense to see all activities of a repository (no matter if public or private) that the user sees (via group assignment or simply as a single collaborator) as default. As a result, before we start working on our project, we can see at first glance which repositories have been changed and which a developer might have to pull.
