### ISSUE TITLE
Some questions about java 19

### ISSUE THREAD

**Issue by lemdev** [gitbucket/gitbucket#3155]
Hi Takezoe,
First thanks a lot for yours work, I use gitbucket daily with my teams and it is work very well.
I am writing to you with a quick question. I am currently running gitbucket on Tomcat 8 with jdk 1.8 and I am looking to migrate all my java api to openjdk19 with Tomcat 10.
So, my questions, would gitbucket will be functional on this setup although you specify on the welcome page that is needs java 8? 
If yes, would you see any objection to use this updated setup?
If no, do you think it will be easy, for me to git clone the source code and build the project on java 19 ?
If no, do you have an idea of when you will migrate to java 19 or java 18 ? 
Thanks, by advance for your time and your works.
Kinds regards
O.

**Comment by takezoe** [comment]
The current version of GitBucket is based on Servlet API 3.1.0 so you have to use servlet container which supports this version of Servlet API.

**Comment by 210hcl** [comment]
Is the Servlet API decides whether GitBucket can be run on Jakarta EE?
In my Wildfly, it said
````
22:28:56,004 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "gitbucket.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"gitbucket.war\".undertow-deployment.UndertowDeploymentInfoService" => "Failed to start service
    Caused by: java.lang.NoClassDefFoundError: Failed to link gitbucket/core/servlet/GitRepositoryServlet (Module \"deployment.gitbucket.war\" from Service Module Loader): Failed to link org/eclipse/jgit/http/server/GitServlet (Module \"deployment.gitbucket.war\" from Service Module Loader): Failed to link org/eclipse/jgit/http/server/glue/MetaServlet (Module \"deployment.gitbucket.war\" from Service Module Loader): javax/servlet/http/HttpServlet"}}
````

**Comment by takezoe** [comment]
GitBucket isn't compatible with JakartaEE yet due to JGit's GitServlet doesn't support it.
