### ISSUE TITLE
Issue on postgreSQL table definitions.

### ISSUE THREAD

**Issue by pea-sys** [gitbucket/gitbucket#3175]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.38.2

**Deployment mode**: *tomcat*

**Problem description**:
The url column definition for the web_hook table is character varying(400).
On the other hand, the url column definition in the web_hook_bk table is character varying (200).
If the web_hook_bk table is a backup table for web_look, there is a problem.

gitbucket\src\main\resources\update\ gitbucket-core_4.35.xml

![web_hook](https://user-images.githubusercontent.com/49807271/198259001-499a6d0a-4d66-4d1d-aca7-a9681ee2d361.png)
![web_hook_bk](https://user-images.githubusercontent.com/49807271/198259012-4272ac90-b4c9-4ed1-ac87-ca5dfcd5fac9.png)

**Comment by takezoe** [comment]
`web_hook_bk` table is created as a backup in GitBucket 4.35 migration and never used after the migration.

**Comment by pea-sys** [comment]
Thank you for your answer, am I correct in understanding that if a url of more than 201 characters is registered in the web_hook table, the migration may fail when upgrading to version 4.35?

**Comment by takezoe** [comment]
No, that column is expanded after 4.35 migration. `web_hook_bk` is a backup table created at the point of 4.35.

**Comment by pea-sys** [comment]
Thanks for your response.
I was wrong in my perception.
