### ISSUE TITLE
Logging out does not log out from OIDC provider

### ISSUE THREAD

**Issue by Mangatome** [gitbucket/gitbucket#3216]
## Issue
**Impacted version**: 4.38.4

**Deployment mode**: Docker container behind Nginx, Keycloak as OIDC provider.

**Problem description**:
I'm generally very happy with the way GitBucket handles OpenID Connect sign-in. I followed the [documentation](https://github.com/gitbucket/gitbucket/wiki/OpenID-Connect-Settings#keycloak) to set up integration with Keycloak and everything works fine.

However, once an OIDC user has signed in, logging out of GitBucket does not seem to log out the user out of single-sign on. So by clicking "sign in with OpenID Connect" again, the user is automatically logged in GitBucket again.

To clarify, the steps are:
1. Log in GitBucket using OIDC
2. The OIDC provider asks for credentials. Enter them. 
3. User is now logged in GitBucket. Log out user out of GitBucket. 
4. Log in GitBucket again using OIDC
5. User is now logged in GitBucket without being asked for credentials.

I'm not sure if this is common practice in the SSO/OIDC world, but I expected the user to be asked for credentials the second time too. Is this behaviour on purpose?

**Comment by takezoe** [comment]
Hm, GitBucket's sign-out action might have to redirect to the logout endpoint if the user has been signed-in with OpenID connect?
https://openid.net/specs/openid-connect-rpinitiated-1_0.html

**Comment by takezoe** [comment]
Created a pull request https://github.com/gitbucket/gitbucket/pull/3219 to fix the issue, but this hasn't been tested and I'm not confident whether or not this fix is valid.

**Comment by Mangatome** [comment]
Awesome, I will test and report back.

**Comment by takezoe** [comment]
I tested this pull request with Keycloak and it seems to work as expected.
