### ISSUE TITLE
Change port after a while using a gitbucket instance (rPI3b+)

### ISSUE THREAD

**Issue by vico93** [gitbucket/gitbucket#3236]
## Issue
**Impacted version**: 4.38.4

**Deployment mode**: Running gitbucket .jar via systemd

**Problem description**:
More a question than a problem, is possible to switch the port of a github instance **after** it already have repositores and data on it?
Because i tried switching my `--port` argument from 8080 to another (eg.: 6666) and when i started again gitbucket i couldn't connect either in 8080 or in 6666.
For reference, i'm selfhosting my gitbucket instance on my Raspberry Pi 3b+, in the same network of my PC and i ran it using `systemd`. It's on the `.service` file that the port argument is stored, and i tried to change on that when i got the issue.
Is there other thing i need to tweak to switch the port?

**Comment by takezoe** [comment]
It's possible to change the port number. But if you have configured the base url with the port number when you were initially running GitBucket on 8080, you may have to change the base url configuration. If you can't change the configuration on Web UI, you can directly modify `~/.gitbucket/gitbucket.conf`.

**Comment by vico93** [comment]
Well, i decided to reinstall the gitbucket to change the port.

Thanks a lot for all the help!
