### ISSUE TITLE
Pushing to repository is very slow

### ISSUE THREAD

**Issue by ziggystar** [gitbucket/gitbucket#3271]
## Pushing takes 30+s 
**Impacted version**: 4.37.2

**Deployment mode**: within tomcat on linux

I've profiled it, and the problem (or at least a major part of it) appears to be [this line](https://github.com/gitbucket/gitbucket/blob/8160c93c153f513d133cfbb86532b35be3b47ae4/src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala#L263) within the `preReceiveHook`. Enumerating all commits takes a long time in our repository with 30k commits.

This variable is used to later check for new commits [here](https://github.com/gitbucket/gitbucket/blob/8160c93c153f513d133cfbb86532b35be3b47ae4/src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala#L316). As a side note: making the `Seq` a `Set` results in faster checks, but this is not the issue here.

Isn't there a faster way of identifying the new commits? My first (probably wrong) try was to remove `existIds` and replace it by a direct `resolve` on the repository. But this doesn't work, since we have already merged them once we are in the `postReceiveHook` right?

In my plugin, I'm using `JGitUtil.getCommitLog(git, cmd.getOldId.getName, cmd.getNewId.getName)` within the `preReceiveHook`  to check all new commits in a push for commit message validation. Could this work here?

**Comment by takezoe** [comment]
```
JGitUtil.getCommitLog(git, cmd.getOldId.getName, cmd.getNewId.getName)
```
Can this exclude commits in other branches already pushed?

**Comment by takezoe** [comment]
> Can this exclude commits in other branches already pushed?

No, this doesn't exclude commits exist on other branches.

**Comment by takezoe** [comment]
https://github.com/gitbucket/gitbucket/pull/3284 may solve this issue.

**Comment by ziggystar** [comment]
@takezoe Just to let you know: Your change improved the situation. We are now down to 10s for pushing. This is still pretty slow, but acceptable.
I think there are still a couple of performance issues. 

A little rant here (don't get me wrong, you've put in a lot of work into this project and it's amazing what you achieved):
I don't think working on cluster support before optimizing the single instance case is the correct approach. I would guess that a factor 10-100 is achievable in many cases. 

And we're still not talking about the complicated/annoying optimizations, like avoiding heap allocations. *This* issue was simply about the code doing the wrong thing, so the cost grew linearly with repo age, instead of staying constant. Things like this should be identified and fixed first.

Just my two cents. Anyway, thanks for your great work!

**Comment by takezoe** [comment]
@ziggystar Thank you for sharing your status and suggestion.

> I don't think working on cluster support before optimizing the single instance case is the correct approach.

Recent my works related to cluster support doesn't intend to provide cluster support officially, just my interest when I looked at Gitea's HA support :-) Also, it's not for making things faster.

> This issue was simply about the code doing the wrong thing

Yeah, I would like to know how we can check existing commit ids without this at commit hook.
