### ISSUE TITLE
"Create Pull Request" option not offered for forks with recent pushes to main/master branch

### ISSUE THREAD

**Issue by richfell-org** [gitbucket/gitbucket#3302]
## Issue
**Impacted version**: 4.39.0

**Deployment mode**: standalone app

**Problem description**:
After pushing a commit on the master branch from a clone to the origin GiBucket fork and then accessing the fork with GitBucket UI, the button with the "Create Pull Request" is not displayed.  However, if the same is done from a branch other than master the "Create Pull Request" button is displayed.

**Steps to reproduce**

1. Fork a repo on GitBucket
2. clone the fork
3. commit changes to the master branch in the clone
4. push changes to the fork (origin)
5. Use GitBucket UI to access the forked repo

Expected: "Create Pull Request" should be present when accessing the fork with GitBucket UI

Actual: "Create Pull Request" button is not present

**Comment by takezoe** [comment]
"Create Pull Request" button isn't shown for the default branch in the current implementation. It might be better to show it in forked repositories.
