### ISSUE TITLE
Cannot fork repo except github

### ISSUE THREAD

**Issue by zyppe** [gitbucket/gitbucket#3341]
**Impacted version**: 4.39.0(Maybe)
I want to fork a repo from gitea or gitlab or [Pagure](https://pagure.io/pagure) and it failed. It will cause "Files" display that this is an empty repo and the "branchs" output the log
````Internal Server Error
java.lang.NullPointerException
````

You can see it at my gitbucket https://git.findnothing.cyou/ZhuningOS-Devel/redhat-rpm-config
I fork this from https://src.fedoraproject.org/rpms/redhat-rpm-config.git

**Comment by takezoe** [comment]
Do you mean that creating new repository on GitBucket from those services fail?

I tried it and succeeded on the latest version of GitBucket on my laptop. Could you have a full stacktrace?

<img width="1260" alt="Screen Shot 2023-10-22 at 17 54 56" src="https://github.com/gitbucket/gitbucket/assets/1094760/39cc48e7-b8d8-4823-bc46-c2628e8cf371">

<img width="1023" alt="Screen Shot 2023-10-22 at 17 55 20" src="https://github.com/gitbucket/gitbucket/assets/1094760/090d7cb3-576d-4520-99d4-fdbbc730c5f2">

**Comment by zyppe** [comment]
After I update my gitbucket into 4.40.0, this bug disappear.
