### ISSUE TITLE
pull requests / issues - long web loading time

### ISSUE THREAD

**Issue by lc1337** [gitbucket/gitbucket#3394]
**Impacted version**: 4.39.0

**Deployment mode**: Standalone app. Run by Windows task scheduler.

**Problem description**:
Opening pull reqests (/dashboard/pulls), global issues (/dashboard/issues) or a specific project's issues (/username/projectname/issues) takes almost 2 seconds, even though there are no pull requests and only 5 issues. Other pages, like the home page/news feed, project detail (branches, releases, labels ..) pages are loaded really fast.

![image](https://github.com/gitbucket/gitbucket/assets/8530123/cbf55e1b-cf03-496e-bac2-163c543a7cc7)

Every time a mentioned page is loaded, a CPU utilization spike on the server caused by java can be observed. Otherwise, the server has no performance issues and plenty of reserve.

The setup is pretty much basic. No additional plugins, no tinkering with config, default database settings.

A gitbucket home folder size is 2.5 GB. There is 60 repositories. Most of them have only 1 branch with initial commit.

What may be the cause of the performance problems?

**Comment by takezoe** [comment]
Many relatively complex SQLs are issued to show issues and pull requests, so it could be slower than other pages. I don't know spec of your machine but I guess you are using the default embedded h2 database. You can use an external database (on another machine) if database is bottleneck.

**Comment by lc1337** [comment]
By updating JRE to latest version (not sure what was the previous version) the ~2s loading time (of /dashboard/issues) decreased to ~1s.

I have tried to use 10.4.28-MariaDB on the same machine (Intel core i5-4670, 8GB RAM) instead of the default H2 one and it further got into 100-200ms. By outsourcing the DB on to different machine (ryzen 7 3700X, 16GB RAM, 10.4.28-MariaDB) the results are same.

So I guess the problem is solved, the delay is almost not noticable now :) But still, it's weird that with almost empty database it takes so much time, even if queries are complex. For comparison, loading time of repositories (/dashboard/repos) is 30ms.
