### ISSUE TITLE
Unable to create group in gitbucket with springboot api methods

### ISSUE THREAD

**Issue by Archanareddy2906** [gitbucket/gitbucket#3456]
### Before submitting an issue to GitBucket I have first:

- [ ] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] searched for similar already existing issue
- [ ] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: xxxx

**Deployment mode**: *explain here how you use GitBucket : standalone app, under webcontainer (which one), with an http frontend (nginx, httpd, ...)*

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by takezoe** [comment]
@Archanareddy2906 Could you give more information?

**Comment by Archanareddy2906** [comment]
When I am trying to create a repository under a group with git credentials as root credentials, repository is getting created under that user. Can you provide me the base url path and parameters to create a repository inside a group

**Comment by Archanareddy2906** [comment]
Got the answer
