### ISSUE TITLE
Error after cloning the repository

### ISSUE THREAD

**Issue by tahaghafuri** [gitbucket/gitbucket#3465]
## Issue
**Impacted version**: 4.40

**Deployment mode**: *standalone app with an nginx*

**Problem description**:
- *When a repository is cloned, none of the sections work, neither does it display the files, nor does the branch section work.*
- *There is always an error in the branches section:[https://git.proginow.xyz/tahaghafuri/miniz/branches](https://git.proginow.xyz/tahaghafuri/miniz/branches)*
- *It also shows no files when files should be shown:[https://git.proginow.xyz/tahaghafuri/miniz](https://git.proginow.xyz/tahaghafuri/miniz)*
- *The address of the main clone repository is taken:https://github.com/richgel999/miniz*

**Comment by tahaghafuri** [comment]
@takezoe Please Help Me.

**Comment by tahaghafuri** [comment]
Also, again this error is also observed for the repository:
https://git.proginow.xyz/tahaghafuri/libsodium
https://git.proginow.xyz/tahaghafuri/libsodium/branches
Even I disabled all plugins, still the same problem persists.

**Comment by tahaghafuri** [comment]
Logs:
<html><body>
<h1>Internal Server Error</h1>
      
        
          <h2>java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.lib.AnyObjectId.hashCode()" because "id" is null</h2>
          
org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:115)
--
org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:76)
org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:31)
org.eclipse.jgit.internal.storage.file.LooseObjects.hasCached(LooseObjects.java:99)
org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:359)
org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1117)
org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:1028)
gitbucket.core.util.JGitUtil$.$anonfun$getBranches$1(JGitUtil.scala:1254)
scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
scala.collection.convert.JavaCollectionWrappers$JListWrapper.map(JavaCollectionWrappers.scala:138)
gitbucket.core.util.JGitUtil$.getBranches(JGitUtil.scala:1251)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$103(RepositoryViewerController.scala:978)
scala.util.Using$.resource(Using.scala:262)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$102(RepositoryViewerController.scala:972)
gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$4(Authenticator.scala:94)
scala.Option.map(Option.scala:242)
gitbucket.core.util.ReferrerAuthenticator.authenticate(Authenticator.scala:92)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly(Authenticator.scala:86)
gitbucket.core.util.ReferrerAuthenticator.referrersOnly$(Authenticator.scala:86)
gitbucket.core.controller.RepositoryViewerController.referrersOnly(RepositoryViewerController.scala:41)
gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$101(RepositoryViewerController.scala:970)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:284)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:278)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:180)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:38)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:277)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:276)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:38)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:252)
scala.Option.flatMap(Option.scala:283)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:250)
scala.collection.immutable.LazyList$.$anonfun$flatMapImpl$1(LazyList.scala:1050)
scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state$lzycompute(LazyList.scala:259)
scala.collection.immutable.LazyList.scala$collection$immutable$LazyList$$state(LazyList.scala:252)
scala.collection.immutable.LazyList.isEmpty(LazyList.scala:269)
scala.collection.LinearSeqOps.headOption(LinearSeq.scala:57)
scala.collection.LinearSeqOps.headOption$(LinearSeq.scala:56)
scala.collection.immutable.LazyList.headOption(LazyList.scala:240)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:171)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:183)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:203)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:183)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:152)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:38)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:125)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:38)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:38)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:38)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:125)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:121)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:38)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:43)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:36)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:38)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:177)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:38)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:152)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:151)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:38)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:76)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFilter.scala:64)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
scala.collection.AbstractIterable.foreach(Iterable.scala:933)
gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:80)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:174)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:174)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:174)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:183)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:203)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:183)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:152)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:38)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:125)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:38)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:38)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:38)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:125)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:121)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:38)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:43)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:36)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:38)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:177)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:38)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:152)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:151)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:38)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:76)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:270)
slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:28)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:270)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:263)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:270)
gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
org.eclipse.jetty.server.Server.handle(Server.java:563)
org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
java.base/java.lang.Thread.run(Thread.java:1583)


</body>
</html>

**Comment by takezoe** [comment]
Hmm, I can't reproduce the error so far. I want to understand your situation clearly first:

- The original repo works fine
- You forked that repo
- You see error in the forked repo

Is my understanding correct?

In that case, do you think if your source repo has any special characteristics?

**Comment by takezoe** [comment]
I guess that error could happen when the default branch has no commit. I don't know how such situation happens but does this apply to your situation?

**Comment by tahaghafuri** [comment]
@takezone Yes, your understanding is correct. I also forked some repositories that have the same problem.

**Comment by takezoe** [comment]
Ah, you mean you created a repository by cloning from GitHub?

**Comment by tahaghafuri** [comment]
Yes

**Comment by takezoe** [comment]
> I guess that error could happen when the default branch has no commit. I don't know how such situation happens but does this apply to your situation?

Looks like this is the root cause of your error because GitBucket's default branch is now `main` but the source repository doesn't have it.

Setting the default branch to `master` on GitBucket would eliminate the error.

<img width="1085" alt="Screen Shot 2024-01-14 at 15 04 55" src="https://github.com/gitbucket/gitbucket/assets/1094760/64bfc87a-1780-4e9f-895e-3b94f837b07a">

I will consider if GitBucket can automatically set the default branch when a repository is created by cloning an external repository to avoid such confusion.

**Comment by tahaghafuri** [comment]
Thank you
