### ISSUE TITLE
Permission system?

### ISSUE THREAD

**Issue by dmk23** [gitbucket/gitbucket#347]
Just installed GitBucket, really like it so far and considering its use for primary Git hosting

One thing that makes me quite concerned is what looks like insufficient (as far as I can see) controls for managing permissions of user accounts. This is very important in a team environment where we may have short-term/temporary contract developers we are not yet ready to trust fully and have to manage carefully.

Specific concerns we see with non-Admin users -

1. They can always create repos (cluttering the system)
2. They can make their repos public (risking public exposure of code)
2. Disabling a user erases all their repos (which do not get restored when user is re-enabled)
3. User could self-erase their account (completely removing all record of their work)
4. User could erase their repos (to the same effect)
4. Removing and disabling users seems to do exactly same thing (losing repos)

Are there plans to address such issues in the near future, especially related to protection from data loss and unauthorized exposure of private repos?

EDIT: Here is GitLab permission system for comparison/reference (behind demo login)
http://demo.gitlabhq.com/help/permissions

**Comment by aaronharder** [comment]
+1

**Comment by takezoe** [comment]
Merged with #1286
