### ISSUE TITLE
Update official docker image with newest releases

### ISSUE THREAD

**Issue by Mangatome** [gitbucket/gitbucket#3522]
Hello, I am using the docker image at https://hub.docker.com/r/gitbucket/gitbucket but it hasn't been updated since a few versions. Is it deprecated, and if so, what is the current official solution?

**Comment by takezoe** [comment]
We have forgotten yo update this repository: https://github.com/gitbucket/gitbucket-docker

**Comment by takezoe** [comment]
But now the official docker images are pushed to GitHub Registry, not DockerHub:
https://github.com/gitbucket/gitbucket-docker/pkgs/container/gitbucket

**Comment by takezoe** [comment]
Published the latest version to GitHub Registry:
https://github.com/gitbucket/gitbucket-docker/pkgs/container/gitbucket/246235707?tag=4.41.0
