### ISSUE TITLE
Apache mod_jk?

### ISSUE THREAD

**Issue by werne** [gitbucket/gitbucket#354]
Does anything say against using mod_jk for a Tomcat (since this is the preferred and efficient connector) installation instead of mod_proxy?

The docs seem to list the later: https://github.com/takezoe/gitbucket/wiki/Reverse-proxy-with-Apache

tnx.

**Comment by aadrian** [comment]
@werne There's nothing specific GitBucket requires, that needs to be configured in a working mod_jk+tomcat solution. https://tomcat.apache.org/connectors-doc/

IMO this issue can be closed.

**Comment by takezoe** [comment]
@aadrian Thanks for your support!
