### ISSUE TITLE
Does GitBucket has Package Registry

### ISSUE THREAD

**Issue by kerwincwc** [gitbucket/gitbucket#3563]
### Before submitting an issue to GitBucket I have first:

- [X] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [X] searched for similar already existing issue
- [X] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.41

**Deployment mode**: *standalone app in debian*

**Question**:
- *Does gitbucket allow for package registry like adding a package using composer in gitbucket*

**Comment by takezoe** [comment]
Here is a GitBucket plugin to host Maven repository on GitBucket:
https://github.com/takezoe/gitbucket-maven-repository-plugin

Also, I had tried to support Docker registry on GitBucket and here is my attempt to implement Docker registry on JVM:
https://github.com/takezoe/docker-registry

However, as far as I know, there are no GitBucket plugins that support composer.
