### ISSUE TITLE
upload file max size 3Mib issue

### ISSUE THREAD

**Issue by hebo209812** [gitbucket/gitbucket#3567]
![startup-cmd](https://github.com/user-attachments/assets/de87543e-45f0-48ad-93c4-52ee117e54b7)
start gitbucket with cmd:
java -jar gitbucket.war --gitbucket.home=/data/gitbucket --max_file_size=6000000000

but can not upload files ?
![problem](https://github.com/user-attachments/assets/458cf98d-d5ec-440c-b6b9-cabaf213274b)
Anyone ,help me ?

**Comment by takezoe** [comment]
`--max_file_size` has been moved to System Settings.

**Comment by takezoe** [comment]
Updated the doc: https://github.com/gitbucket/gitbucket/wiki/Basic-configurations
