### ISSUE TITLE
Certain characters are not available in User-defined CSS

### ISSUE THREAD

**Issue by bs-kawano** [gitbucket/gitbucket#3619]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.41.0

**Deployment mode**:
* OS: CentOS Linux release 7.9.2009
* web server: apache httpd 2.4.6
* app server: apache tomcat 9.0.11
* java: openjdk version "11.0.16.1" 2022-08-12 LTS

**Problem description**:
When I try to set CSS with User-defined CSS, the following problems occur.

- “>” cannot be used in CSS selector.
- single and double quotation marks cannot be used in property values.

I hope you can respond.

**Comment by takezoe** [comment]
#3661 fixed this issue too.
