### ISSUE TITLE
User-defined CSS is loaded before some plugins (especially the file explorer plugin)

### ISSUE THREAD

**Issue by rayachristian** [gitbucket/gitbucket#3633]
I'd like to create a custom css file using the “User-defined CSS” feature. 
However, the css file is inserted into the html code before the file explorer plugin css file.
This means that the plugin css file has a higher priority and that some parameters in the “User-defined CSS” section are never used.

**Comment by takezoe** [comment]
It is not controllable if plugins add CSS dynamically using JavaScript.
https://github.com/gitbucket-plugins/gitbucket-explorer-plugin/blob/c647b3468c47db59f667dae4bd4e6349cbe2f0c3/src/main/scala/Plugin.scala#L37-L53

It might be better to provide an extension point to allow plugins inserting HTMLs in `<head>`.

**Comment by takezoe** [comment]
Or GitBucket should add User-defined CSS also by JavaScript dynamically after plugins.

**Comment by rayachristian** [comment]
Thanks for your gitbucket project! I don't know how is handle the plugins, maybe the issue is the file explorer plugin itself. However i think the best solution is to insert dynamically the User-defined CSS section after plugins. The idea is to be sure this CSS section is the higher priority for css style.
