### ISSUE TITLE
Malformed POST will cause Internal Server Error

### ISSUE THREAD

**Issue by sanel** [gitbucket/gitbucket#3636]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 	4.40.0

**Deployment mode**: docker + apache http as a proxy

**Problem description**:
Send a malformed POST request, e.g.
```sh
curl -L -X POST https://host/hello.world?%ADd+allow_url_include%3d1+%ADd+auto_prepend_file%3dphp://input
```
and gitbucket will respond with `Internal Server Error, Please contact your administrator`. This could be a way for attacker to further dig and try all sort of ways to DoS gitbucket. Instead, gitbucket should not report it as error, but gracefully report 404 and log exception (if any) in syslog.

I'm getting frequent attacks like this, obviously someone figured this out.

**Comment by takezoe** [comment]
In that case, 400 should be returned because query string is invalid as URI.
