### ISSUE TITLE
list-repository-tags schema inconsistent with GitHub after 4.36.2

### ISSUE THREAD

**Issue by ZdzislawDyrman** [gitbucket/gitbucket#3641]
## list-repository-tags schema inconsistent with GitHub 
**Impacted version**: after 4.36.2 till 4.41.0

**Deployment mode**: standalone app

**Problem description**:

I'm querying for list-repository-tags. 
Using version up to 4.36.2 output schema looks same as github:

```
curl http://gitbucket.example.com:8080/api/v3/repos/user/repo/tags -s | jq | head
[
  {
    "name": "v1.0.0",
    "commit": {
      "sha": "f9d35b9638c59e1cf68ac0e6c90bb8aafaa600c2",
      "url": "https://gitbucket.example.com/user/repo/commits/f9d35b9638c59e1cf68ac0e6c90bb8aafaa600c2"
    },
    "zipball_url": "https://gitbucket.example.com/user/repo/archive/v1.0.0.zip",
    "tarball_url": "https://gitbucket.example.com/user/repo/archive/v1.0.0.tar.gz"
  },
```
  
While using every version above 4.36.2 output schema looks different: 

```  
curl http://gitbucket.example.com:8080/api/v3/repos/user/repo/tags -s | jq -r '. | fromjson' | head
[
  {
    "ref": "refs/tags/v1.0.0",
    "node_id": "",
    "url": "https://gitbucket.example.com/api/v3/repos/user/repo/git/refs/tags/v1.0.0",
    "object": {
      "sha": "3f53af78ae0812b1f0a3882b7f619d4e0d5a5f68",
      "type": "commit",
      "url": "https://gitbucket.example.com/api/v3/repos/user/repo/commits/3f53af78ae0812b1f0a3882b7f619d4e0d5a5f68"
    }
```

Is it on purpose?

**Comment by takezoe** [comment]
It was changed by https://github.com/gitbucket/gitbucket/pull/2807

**Comment by ziggystar** [comment]
So the difference is between `https://api.github.com/repos/gitbucket/gitbucket/git/refs/tags/` and `https://api.github.com/repos/gitbucket/gitbucket/tags`.

So the format my original PR changed should be served under `<repo>/git/refs`, while under `<repo>/tag` the old format should be served.

**Comment by takezoe** [comment]
Ah, I see. In that case, reverting `<repo>/tags` is fine.
