### ISSUE TITLE
Local unit test for gitbucket home fails

### ISSUE THREAD

**Issue by ziggystar** [gitbucket/gitbucket#3657]
The following test fails for me. This is annoying, since I want to automatically run them before commit.

It fails because my gitbucket appears to be under `/home/<user>/.gitbucket`. How is this supposed to work. When looking at the code that calculates `Directory.GitBucketHome`, there is nothing that makes this happen.

Do I need to set the ENV variable when developing? That's a bit tedious to setup.

```{scala}
  describe("GitBucketHome") {
    it("should set under target in test scope") {
      assert(Directory.GitBucketHome == new java.io.File("target/gitbucket_home_for_test").getAbsolutePath)
    }
  }
```

**Comment by takezoe** [comment]
How did you run tests? `sbt test` automatically setup the test environment:

https://github.com/gitbucket/gitbucket/blob/92304ac8c66a5620b34301634fb990f25dcefa3c/build.sbt#L96-L97

**Comment by ziggystar** [comment]
This appears to be the problem. I'm running the test from IDEA. Was also trying to setup auto format/test before commit because I keep having some problems there. So quick fix would be to create the directory and define  the property.

If it keeps bugging me I'll see if I can find a solution for this. Thanks.
