### ISSUE TITLE
Tab expansion

### ISSUE THREAD

**Issue by dmk23** [gitbucket/gitbucket#387]
Right now tab character in the source code (e.g. Java) is being expanded to 8 spaces in the code view screen. This seems quite excessive, especially if the code has a mix of tabs characters and spaces (corresponding to 4 spaces per tab).

It should be possible to configure the number of spaces to expand the tabs to or at least have a more sensible default (1 tab = 4 spaces).

**Comment by motobrew** [comment]
+1 this

**Comment by nazoking** [comment]
The github has blob page parameter like ts=4.
see http://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github#answer-23522945

**Comment by nazoking** [comment]
memo: it can only by css `tab-size: 4`.
https://developer.mozilla.org/ja/docs/Web/CSS/tab-size

**Comment by ritschwumm** [comment]
the github-solution is a bit underpowered, imho.
- it forgets you set that whenever you navigate to another file
- and even if it didn't, you'd want per-project settings (assuming people can at least agree on _one_ tab width within a single project..

**Comment by ron4mac** [comment]
+1 per project tab expansion setting

**Comment by kounoike** [comment]
I made PR #1966. It supports `.editorconfig` in repository.

**Comment by adrian-constantin** [comment]
8 spaces is the expected tab size, but not a convenient indent size, see: https://terminatorul.wixsite.com/blog/post/tabs-and-tab-size

**Comment by takezoe** [comment]
Anyway, we can now use `.editorconfig` to control intent/tab size. Can we close this issue?
