### ISSUE TITLE
BaseURL will not allow port to be specified

### ISSUE THREAD

**Issue by agr1277** [gitbucket/gitbucket#399]
When turning on SSH access for an internal project, I needed to also specify baseURL, this field does not allow ports to be specified so the system attempts to access pages at [baseurl]/admin for example. This is occuring when running gitbucket with default settings, only turning on SSH and setting baseURL to be the IP:PORT

**Comment by takezoe** [comment]
I see. Maybe ssh base url configuration is needed.

**Comment by takezoe** [comment]
I raised a new issue #734
