### ISSUE TITLE
ios fullscreen web app support

### ISSUE THREAD

**Issue by chenjb1975** [gitbucket/gitbucket#451]
please add the following tag:  `< meta name="apple-mobile-web-app-capable" content="yes" >`
So that it can be viewed as a web app and full screen on ipad

**Comment by takezoe** [comment]
Current version of GitBucket provides slightly support for mobile. Could someone test on iOS? and is this PR still necessary for iOS support?

**Comment by takezoe** [comment]
Out of date.
