### ISSUE TITLE
Audit functionality?

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#456]
Is there any audit functionality in GitBucket, or is it at least planned?

Unfortunately we are not allowed to install GitBucket without such audit support, and the Tomcat access logs are not considered useful.

**Comment by takezoe** [comment]
Unfortunately, we don't have any plan about audit functionality.

**Comment by aadrian** [comment]
If GitBucket would have https://github.com/gitbucket/gitbucket/issues/730 than that would fulfill most audit criteria, since the admin could see the activity of every user.

**Comment by aadrian** [comment]
#730 would be the equivalent of audit functionality.
