### ISSUE TITLE
Loss of response, applications don't crash, restart recovery

### ISSUE THREAD

**Issue by mysoko** [gitbucket/gitbucket#460]
Jstack content is too large, 

click on the Dropbox link https://www.dropbox.com/s/0324hfqcc2q9e33/7131.txt

Looks like database lock problem,
TransactionFilter.scala code:

``` scala
Database(req.getServletContext) withTransaction { session =>
```

Used in this way, Is it right? Didn't use connection pool?

**Comment by takezoe** [comment]
Close because this issue looks obsolete. Now GitBucket has a connection pool and offers external database support (MySQL or PostgreSQL).
