### ISSUE TITLE
gitbucket have serious performance problems. 

### ISSUE THREAD

**Issue by mysoko** [gitbucket/gitbucket#463]
gitbucket have serious performance problems. 

Local to patch the connection pool #460 , on-line connection is not enough occurrence 

Later positioning code, gitbucket achieve similar hibernate in the Open Session in View mode, the db session in the servlet filter. 

While coding convenient, but there are a lot of internal and mixed use git, but git projects particularly when jgit read very slowly (5 ~ 10s +), then the database session will not be released, more than one person will use a full . . 

Also: h2 can not do more monitoring, since the use of slick, it should choose more database support, such as support for mysql

Data: 
project number: 150 
Maximum commit: 13000

**Comment by cvrebert** [comment]
Similar to #441.

**Comment by hansgru** [comment]
I'm not sure if this would play a role here, but if we deploy our internal application (h2+scalatra based on Tomcat) in a similar manner like gitbucket does, than it's much slower compared to using the Tomcat built in Connection Pool (not the DBCP one), by using a DataSource defined in server.xml .

**Comment by takezoe** [comment]
Close because this issue looks obsolete. Now GitBucket has a connection pool and offers external database support (MySQL or PostgreSQL).
