### ISSUE TITLE
Some buttons are not responding

### ISSUE THREAD

**Issue by ziggystar** [gitbucket/gitbucket#472]
In Firefox (where I do have some privacy plugins like Ghostery, Noscript, AdBlock installed but they should be disabled on my site), the following buttons do not respond:
- "Click to create a pull request for this comparison" has never worked (it's working in Chromium)
- "Edit" to select branches for new pull request has only worked once or twice (works in Chromium)
- the login button on the front page (next to the news list) doesn't work in Firefox, nor in Chromium

Does anyone know why the buttons on the pull-request page are that problematic?

With my limited JS knowledge, I was able to locate the following code

```
  $('#show-form').click(function(){
    $(this).hide();
    $('#pull-request-form').show();
  });
```

When I execute in the JS console `$('#show-form')`, I retrieve the button for creating the pull request.
When I execute `$('#pull-request-form').show()`, then the form is shown (which doesn't happen when clicking it). It appears, that somehow the code to install this handler is never executed.

I noticed that the JS code inside the HTML file is after the closing `</body></html>` tag. Is this legal?

**Comment by ziggystar** [comment]
I'm getting the same JS error with other buttons, and also when using drop-down lists to assign users to issues. There are really many interface components that don't work in Firefox.

**Comment by takezoe** [comment]
Close because this issue looks out of date.
