### ISSUE TITLE
option to make (generated) html available in wiki

### ISSUE THREAD

**Issue by fomcl** [gitbucket/gitbucket#475]
Hi,

It would be great if generated documentation from tools like Doxygen, Roxygen or Sphinx could be made available in the wiki. This seems to be possible in Github [1, 2]. Can it be done with Gitbucket too?

Thanks and keep up the good work!!

Albert-Jan

[1] http://blog.transifex.com/post/31979487717/hosting-sphinx-on-github
[2] http://daler.github.io/sphinxdoc-test/includeme.html

**Comment by takezoe** [comment]
You would be able to host generated HTML files by [gitbucket-pages-plugin](https://github.com/gitbucket/gitbucket-pages-plugin).
