### ISSUE TITLE
gitbucket doesn't log failed login attempts by default

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket#499]
By default, when run with java -jar or within an external jetty container, gitbucket does not appear to log failed login attempts, even if the log level is set to ALL.

This would be a nice feature to have to monitor malicious login attempts, or to use something like fail2ban to block malicious people or bots.

**Comment by takezoe** [comment]
As a minimum support, added logging authentication failure.

**Comment by thefiredragon** [comment]
@axb21 do you have a regex for fail2ban? and a little how to? best regards
