### ISSUE TITLE
Network graph

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#5]

**Comment by pcqpcq** [comment]
+1 for this

**Comment by FlYnN91** [comment]
+1 for this

**Comment by Darkkrye** [comment]
+1 :+1: for this too :)

**Comment by milieu** [comment]
+1

**Comment by nickstokes** [comment]
+1

**Comment by okamoto-takuya** [comment]
+1

**Comment by McFoggy** [comment]
isn't the [commitgraphs-plugin](https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin) what you are looking for?
If the feature is felt to be a gitbucket core one, then a promotion of the plugin (including a cleanup/refacto perhaps) could be an option.

**Comment by aadrian** [comment]
> isn't the commitgraphs-plugin what you are looking for?

Not really.  The commitgraph shows something like this:
https://github.com/gitbucket/gitbucket/graphs/commit-activity
and the network graph should show something like this:
https://github.com/gitbucket/gitbucket/network

**Comment by mrkm4ntr** [comment]
I've implemented this feature as [plugin](https://github.com/mrkm4ntr/gitbucket-network-plugin).
Please try it!

**Comment by takezoe** [comment]
@mrkm4ntr Great! It would be nice if your plugin is added to [gitbucket community plugins](https://gitbucket-plugins.github.io/).

**Comment by takezoe** [comment]
I sent a pull request: https://github.com/gitbucket-plugins/gitbucket-plugins.github.io/pull/8

**Comment by McFoggy** [comment]
PR merged
