### ISSUE TITLE
Read-only private forks?

### ISSUE THREAD

**Issue by mgeorge** [gitbucket/gitbucket#520]
So I want to share a project with a bunch of students which they fork so that they can make their own modifications.  I don't want the students to see each other's forks (to prevent plagiarism of assessed work), and they also should not be allowed to push back to the original project (so they don't corrupt the original project).

I can think of two ways of doing this, but GitBucket allows neither:
- Make the shared repo public, and get the students to create a fork, which they then make private.  Currently GitBucket does not allow the fork to be made private.  Is there any technical reason for this?
- Make the shared repo private, and add the students as read-only contributors.  They can then create a fork (which would be private by default).  Currently GitBucket does not have read/pull-only collaborator support.

Are there any technical reasons for preventing forks of public repos from being made private?

**Comment by bhack** [comment]
:+1:

**Comment by aaronharder** [comment]
:thumbsup:  Public read-only would be an incredibly useful enhancement.

**Comment by asmartin** [comment]
+1

I would really like to be able to configure read-only/pull-only collaborators on a number of repositories in my gitbucket install

**Comment by mgeorge** [comment]
Guest mode on the repository resolves the problem.

**Comment by mgeorge** [comment]
Actually further testing shows that collaborators can see each other's repositories despite them being private.

Private should mean private.

**Comment by aadrian** [comment]
> Private should mean private

@mgeorge GitBucket just follows the naming conventions of other similar tools. In that context there are 2 options for a repo: "private" and "public" and this does not make the distinction **who** can see what, but simply if **authentication** is required or not to see a repo.

"Who can see what" is defined by the Group the project is part of (and users belonging to that group) and also by the collaborators (with specific roles) that can be assigned to a certain project.

**Comment by mgeorge** [comment]
The "Copy existing git repository" feature does what I need.  Closing.
