### ISSUE TITLE
Using RSA SSH keys instead of DSA keys

### ISSUE THREAD

**Issue by v1r0x** [gitbucket/gitbucket#553]
I thought I submitted this issue yesterday, but now there is no issue...

I created a new user and wanted to add my local ssh key to my account on my gitbucket instance, but it wasn't accepted. So I read a few tutorials and they all had ssh-dss keys, so I created a new key using the DSA algorithm instead of RSA and it worked.
But, all my keys are created using RSA and I'd like to use them for gitbucket.

Is this my fault and RSA is supported or is only DSA supported? And if only DSA is supported: Are there any plans on supporting RSA? Would be great.

**Comment by buzztaiki** [comment]
In OpenSSH 7.0, 1024-bit diffie-hellman-group1-sha1 key exchange
   is disabled by default at run-time.

see. http://lists.mindrot.org/pipermail/openssh-unix-announce/2015-August/000122.html, http://www.openssh.com/legacy.html

**Comment by buzztaiki** [comment]
I think gitbucket must support rsa key exchange in near future.

**Comment by lefou** [comment]
+1

**Comment by sebastiancadena** [comment]
+1

**Comment by takezoe** [comment]
Already fixed in 3.8 (https://github.com/gitbucket/gitbucket/pull/905), and updated in 3.10 (https://github.com/gitbucket/gitbucket/pull/1020).

**Comment by imunolion** [comment]
(According to gitter information,) If you still have this error even in newer version, you might have to delete existing `gitbucket.ser` and restart gitbucket to generate a new one. It works for me at 3.10.
