### ISSUE TITLE
Java heap space error while pushing 4GB repo

### ISSUE THREAD

**Issue by mossix** [gitbucket/gitbucket#558]
I'm facing some problem with Gitbucket 2.4. I've migrated codebase of my app from SVN to Git and now I'm trying (without success) to push it to GitBucket. Command crashes as shown below:

```
$ git push -u origin master
Counting objects: 75943, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (21792/21792), done.
Writing objects: 100% (75943/75943), 4.09 GiB | 35.76 MiB/s, done.
Total 75943 (delta 60272), reused 67810 (delta 53298)
error: unpack failed: error Java heap space
To http://server/git/some-repo.git
! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'http://server/git/some-repo.git'
```

My GitBucket is hosted on Tomcat on Windows machine with 4GB of RAM.

I've already tried to:
1. put `"set CATALINA_OPTS=-Xms1g -Xmx2g"` in catalina.bat
2. set following properties in gitconfig on machine when GitBucket is installed:

```
    [pack]
    windowMemory=100m
    packSizeLimit=200m
```

but I'm still receiving the same error.

How can I fix this issue? Or, is there any way to push sources without packing/compressing? - because it looks like unpacking causes the problem.

I would really appreciate any help! Thanks.

**Comment by ritschwumm** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=312868 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=394078 could be relevant here

**Comment by aadrian** [comment]
@mossix @ritschwumm I can can push 4Gb repos without problems: the machines need however at least 8Gb in this case.

Please reopen this issue if with more RAM you problem still persists. Also please try however with recent (>=4.18.0) versions of GitBucket.
