### ISSUE TITLE
Constant OverlappingFileLockException on code change

### ISSUE THREAD

**Issue by chuwy** [gitbucket/gitbucket#562]
When I'm trying to run gitbucket with `~ ;copy-resources;aux-compile` I getting OverlappingFileLockException after several code changes. It's really annoying to restart container after each change.
I've found one [solution](http://stackoverflow.com/questions/8545783/auto-reloading-files-in-scala-lift-sbt-11), but despite it reloading automatically it still need a lot of time.

**Comment by aadrian** [comment]
@chuwy and what you propose that we should do about this?

**Comment by chuwy** [comment]
Hey @aadrian! Sorry it was too long time ago - I don't remember any details about the problem. If you don't have any ideas either or think this is "wontfix" - please feel free to close.
