### ISSUE TITLE
autocompletion for # or @ in issues

### ISSUE THREAD

**Issue by snb-otk** [gitbucket/gitbucket#568]
![2014-12-03 20 33 16](https://cloud.githubusercontent.com/assets/7676046/5279786/ba954a6a-7b2b-11e4-891b-ab79d3a0baea.png)
![2014-12-03 20 33 28](https://cloud.githubusercontent.com/assets/7676046/5279787/bab7dd0a-7b2b-11e4-834b-44b66b252e0d.png)

添付画像のように、githubでは、#や@を入力した際に表示される
autocomplete（suggest）機能は未実装でしょうか？

**Comment by takezoe** [comment]
autocompletion of username has been available since 4.3:
https://gitbucket.github.io/gitbucket-news/gitbucket/2016/07/30/gitbucket-4.3.html
