### ISSUE TITLE
Issues view is extremely slow compared to others

### ISSUE THREAD

**Issue by vsapronov** [gitbucket/gitbucket#572]
Hello,

Thank you for developing GitBucket!

I needed some git web-based face server and GitBucket turned out to be the easiest to setup and run.
My server platform is limited in resources (2 ARM cores, 2 Gb RAM) but everything seems to be working with acceptable speed. Only Issues view is extremelly slow. Other views are opening much faster. Even single issue view is pretty fast.

Do you see any particular reason why this view is slower then others? I could help it to fix though I will need some leading hints where to look at...

You can see  performance here:
http://device.test123.syncloud.it:10001 with root user and root password. Please don't hack me :)

**Comment by takezoe** [comment]
Close because this issue looks out of date.
