### ISSUE TITLE
Is there release page?

### ISSUE THREAD

**Issue by a-monty-only** [gitbucket/gitbucket#607]
I want release page like "https://github.com/takezoe/gitbucket/releases".

**Comment by XWolfOverride** [comment]
+1

I Think a releases page is the better way to publish binaries (i'm now using an external PHP page for this)

Thanks! This is a great project!

**Comment by FlYnN91** [comment]
+1

**Comment by Fmstrat** [comment]
+1 There is a link for releases, but no way to create one! :)

**Comment by wingerd** [comment]
+1

**Comment by qingliangcn** [comment]
+1

**Comment by AkihiroTakamura** [comment]
+1

**Comment by kounoike** [comment]
WIP.
![223141-release test - release 1 - kounoike gitbucket-ipynb-plugin - google chrome](https://cloud.githubusercontent.com/assets/6997928/25063977/70fd06e6-222b-11e7-9049-51f082c58364.png)

**Comment by kurdtpage** [comment]
To create a new release, use these commands:
```
git tag -a v0.1.1 -m "Release test"
git push origin v0.1.1
```
Now go into the Releases page.
Source: https://git-scm.com/book/en/v2/Git-Basics-Tagging
