### ISSUE TITLE
Support ed25519 for SSH

### ISSUE THREAD

**Issue by colindean** [gitbucket/gitbucket#617]
When I submit my SSH public key

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICKHoRRTDdoqmEQ9YFNFn75K0w6wdh1labhDzDCtTRO+ colindean
```

Gitbucket tells me that it's invalid. It's definitely valid, but perhaps Gitbucket doesn't support ed25519 yet. That'd be a nice feature to have.

**Comment by colindean** [comment]
Workaround: use an RSA key.

**Comment by takezoe** [comment]
@tanacasino Is it possible to support ed25519?

**Comment by tanacasino** [comment]
GitBucket uses Apache mina sshd for SSH Key, but Apache mina sshd does not supported ed25519.
So it's hard to support.

**Comment by tanacasino** [comment]
FYI: https://issues.apache.org/jira/browse/SSHD-440

**Comment by otofune** [comment]
apache mina sshd now supports ED25519 key, above issue was resolved. (and now status is 'resolved'.)
is there any progress?

**Comment by takezoe** [comment]
@otofune Great news! Thanks for information. I would like to start work for support it.
