### ISSUE TITLE
Live demo hosting?

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#62]
Any plans to host a live version of gitbucket for demo purposes?

There are quite a few cloud providers that offer free hosting for demo/non-commercial purposes.

http://stackoverflow.com/questions/14606788/hosting-java-app-on-free-web-hosting-site  (and many more)

**Comment by demon101** [comment]
now it's empty. where I can have a look at demo?
On my current instance no commit history at issue page

**Comment by McFoggy** [comment]
@demon101 the instance is refreshed every day, so it is often empty. It is jut a demo env.
