### ISSUE TITLE
Proposal: Add "issue subscriptions" to manage notification logic

### ISSUE THREAD

**Issue by marklacroix** [gitbucket/gitbucket#628]
## Overview

As described in the [wiki page](https://github.com/takezoe/gitbucket/wiki/Notification), notifications are sent out to specified users when an event occurs. This contrasts current GitHub functionality which has the concept of _subscriptions_ to determine who is notified.

I propose that we introduce the concept of _subscriptions_ to issues in Gitbucket. For the purposes of this proposal, the term _issues_ includes _pull requests_
## Subscribing

At issue creation, the following users will be auto-subscribed:
- Repository owner and collaborators
- Issue creator
- Repository watchers (if implemented in the future)

Additionally, the following events will auto-subscribe a user:
- Issue assignment
- @-mentions

Finally, any user can subscribe or unsubscribe to an issue via a new UI element to be added on the view issue page. This UI element only appears for logged-in users
## Sending Notifications

All subscribers to an issue will receive a notification for the following events:
- Issue creation
- Comment creation
- Status update

**Exception to above**: the user who initiates the action will not receive a notification
## Database Table

Issue subscriptions will be tracked in a new table

`ISSUE_SUBSCRIPTION`
- `USER_ID`
- `REPOSITORY_NAME`
- `ISSUE_ID`
- `SUBSCRIBER_USER_NAME`
- `REASON` - e.g. `author`, `owner`, `assigned`, `subscribed`, `mentioned`, `collaborator`, `watcher`
## UI Mockup

| Example Subscribe UI | Example Unsubscribe UI |
| --- | --- |
| ![gitbucket-subscribe](https://cloud.githubusercontent.com/assets/1167829/6196338/9cbd7096-b3a5-11e4-9918-08bcd12c1016.png) | ![gitbucket-unsubscribe](https://cloud.githubusercontent.com/assets/1167829/6196346/b533542e-b3a5-11e4-9bfc-ded8e6745f70.png) |

**Comment by hansgru** [comment]
+1

**Comment by Okeanos** [comment]
Any progress on this as a whole or at least the general ability for accounts to turn of e-mail notifications in general?

**Comment by Starkmann** [comment]
Would really love to see this feature as well. :-)

**Comment by takezoe** [comment]
[gitbucket-notifications-plugin](https://github.com/gitbucket/gitbucket-notifications-plugin) will be bundled in default since GitBucket 4.15.0

**Comment by marklacroix** [comment]
Thanks guys. Looking forward to having this available in 4.15. Keep up the amazing work!
