### ISSUE TITLE
Primer vs Bootstrap

### ISSUE THREAD

**Issue by marklacroix** [gitbucket/gitbucket#675]
GitHub has released their CSS toolkit. Any thoughts about switching to it from Bootstrap?

http://primercss.io/

**Comment by hansgru** [comment]
-1

IMO there are more important features in the issue tracker than the used CSS toolkit :). The actual UI looks very good, and the mindshare of Bootstrap is also big enough, so IMO is a waste of resources to change exactly that part.

**Comment by takezoe** [comment]
We are now working for moving to Bootstrap3 with GitHub theme in #999.
