### ISSUE TITLE
issue refer comment can not be created when we create a pull request.

### ISSUE THREAD

**Issue by troter** [gitbucket/gitbucket#695]
When we created/edited a issue, added/edited issue comments, edited a pull request, or added/edited pull request comments, issue refer comment will be created.

But when we created a pull request, issue refer comment will not be created.

**Comment by kounoike** [comment]
@takezoe This issue is already fixed by this code:
https://github.com/kounoike/gitbucket/blob/6029d9ef29f9c6fa2b2e535bee4e44f8bd4a9684/src/main/scala/gitbucket/core/controller/PullRequestsController.scala#L767

**Comment by troter** [comment]
Thank you for the notice.
