### ISSUE TITLE
WebHook payload JSON has wrong values and names

### ISSUE THREAD

**Issue by denizk0** [gitbucket/gitbucket#698]
The WebHook Payload JSON have some issues:
1. pusher.login, repositiry.owner.login are actually Display Name, instead of actual login. commits[].author, committer, pusher etc use the field named 'name'.
2. repository.watchers_coun field (note the missing t).

And a few notes:
1. commits[].url gives 404. My guess that API is not implemented yet
2. the payload is actually a application/x-www-form-urlencoded with the single field "payload" containing JSON. Why not passing application/JSON?
3. i think it would be useful to set a global WebHook, used across all the repos

**Comment by tomkokura** [comment]
gitbucket 3.1.1 + gith を使っておりますが、gitbucket 3.1.1のWebHook の payload でいくつか値が"undefined"になっている箇所がありました。
実際のjsonも添付してみました。

I use gitbucket 3.1.1 and gith.
WebHook supplies wrong payload at gitbucket 3.1.1.
There are some "undefined" values like below.

{ original:
   { pusher:
      { login: 'Hoge+Huga',
        email: 'hoge@example.com',
        type: 'User',
        site_admin: true,
        created_at: '2015-03-15T04:31:31Z',
        url: 'https://example.com/gitbucket/api/v3/users/Hoge+Huga',
        html_url: 'https://example.com/gitbucket/Hoge+Huga' },
     ref: 'refs/heads/master',
     commits: [ [Object] ],
     repository:
      { name: 'RepositoryName',
        full_name: 'work/RepositoryName',
        description: 'test',
        watchers: 0,
        forks: 0,
        private: true,
        default_branch: 'master',
        owner: [Object],
        forks_count: 0,
        watchers_coun: 0,
        url: 'https://example.com/gitbucket/api/v3/repos/work/RepositoryName',
        http_url: 'https://example.com/gitbucket/git/work/RepositoryName.git',
        clone_url: 'https://example.com/gitbucket/git/work/RepositoryName.git',
        html_url: 'https://example.com/gitbucket/work/RepositoryName' } },
  files:
   { all: [ 'README.md' ],
     added: [],
     deleted: [],
     modified: [ 'README.md' ] },
  tag: '',
  branch: 'master',
  repo: 'undefined/RepositoryName',
  sha: undefined,
  time: undefined,
  urls:
   { head: '',
     branch: '/tree/master',
     tag: '',
     repo: 'https://example.com/gitbucket/api/v3/repos/work/RepositoryName',
     compare: undefined },
  reset: undefined,
  pusher: undefined,
  owner: undefined,
  matches: {} }

**Comment by tomkokura** [comment]
"undefined"の件ですが、良く調べたら gith 側の問題みたいでした。
失礼いたしました。

Sorry, I made a mistake.
Issue of "undefined" seems be guth's one.

https://github.com/danheberden/gith/blob/master/lib/gith.js
https://developer.github.com/v3/activity/events/types/

**Comment by nazoking** [comment]
> 1. pusher.login, repositiry.owner.login are actually Display Name, instead of actual login. commits[].author, committer, pusher etc use the field named 'name'.

#755 fixed

**Comment by nazoking** [comment]
> 1. commits[].url gives 404. My guess that API is not implemented yet

in github, it indicate `html` url, and I fixed it on #919
