### ISSUE TITLE
Add non-group members to repository collaborators

### ISSUE THREAD

**Issue by ndarilek** [gitbucket/gitbucket#724]
I like the ability to add collaborators to a group and have them automatically repository collaborators. However, I'd like to add non-group members to repositories as collaborators.

For instance, say I have a private installation for my company. I use the groups feature to combine logically-related repositories, so for instance myapp/myapp is myapp's code, myapp/blog is its static blog, etc. I want to hire someone to work on myapp, but I only want them to have access to myapp/myapp. As it stands, it looks like I need to add them to the myapp group, thus giving them access to myapp/blogand friends.

Most ideal would be per-repository/group ACLs. Failing that, I'd like to give a collaborator access to myapp/myapp without granting access to everything else under the myapp group.

Thanks.

**Comment by McFoggy** [comment]
Isn't #727 PR  answering your need?

**Comment by haarp** [comment]
That's not quite the same. Allowing individual users access even to repos owned by groups is somewhat different than PR #727.

**Comment by takezoe** [comment]
Merged with #1286
