### ISSUE TITLE
Sites functionality!

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#726]
Hi,

GitHub already has support for "sites", but the implementation and handling seems quite confusing and complicated (with the special gh-pages branch).

GitBucket has a very nice support for WIKI by using another Git repo with the `_WIKI` suffix.

Support for "sites" could be implemented in a similar clean way the WIKI is implemented.
So the repo structure would look like:

```
repo
repo_WIKI
repo_SITE
```

see #703

**Comment by aadrian** [comment]
+1

**Comment by takezoe** [comment]
[gitbucket-pages-plugin](https://github.com/gitbucket/gitbucket-pages-plugin) is available.
