### ISSUE TITLE
Export the gitbucket ERD to other formats too.

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#765]
Please export the ERD  of gitbucket
https://github.com/takezoe/gitbucket/blob/master/doc/gitbucket.erd

 to other formats too, e.g. PNG image too, and include it in the WIKI page, a DDL to be inspected easily, etc.

**Comment by aadrian** [comment]
+1 for a PNG and a complete DDL.

**Comment by aadrian** [comment]
Feature Request moved to a plug-in more suitable to implement it.
