### ISSUE TITLE
please support to "go get" for public and private repositories 

### ISSUE THREAD

**Issue by ysaotome** [gitbucket/gitbucket#769]
"go get" is golang command for package download and install.

Same issue with the gitlab
https://github.com/gitlabhq/gitlabhq/pull/7693

Remote import paths
http://golang.org/cmd/go/#hdr-Remote_import_paths

Maybe, I think that it is all right with the addition of ```<meta name="go-import" content="@path git @url (repository)" />``` in [gitbucket/src/main/twirl/gitbucket/core/main.scala.html](https://github.com/takezoe/gitbucket/blob/master/src/main/twirl/gitbucket/core/main.scala.html).

But, even if redirected to the login screen, want to display the repository information before the redirect.

thank you.

**Comment by takezoe** [comment]
@ysaotome Thanks for your request. I added go-import meta tag for public repositories at first. Redirection for private repositories is not implemented yet. It might be raised as an another issue.

**Comment by ysaotome** [comment]
@takezoe Very thank you. But, Regrettable that private repository is not supported. I will consider while using a public repository.

**Comment by binzume** [comment]
Thank you for support to this feature.
However, "go get" command cannot sign-in to the GitBucket　(redirected to the login page), so the meta tag does not detected.
Andalso, can I use "ssh://" url?
