### ISSUE TITLE
Full text search using embedded Elasticsearch

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#792]

**Comment by elion** [comment]
Is there a plan to add this feature to search for a string over all repositories that user has access to?

**Comment by onukura** [comment]
@elion have you tried [gitbucket-fess-plugin](https://github.com/codelibs/gitbucket-fess-plugin) ?

**Comment by takezoe** [comment]
Let's close this issue since gitbucket-fess-plugin is available.
