### ISSUE TITLE
Toggle repository features (Issue and Wiki)

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#80]
In the Github, the repository owner can disable Issue and Wiki.

- [x] Option to turn off Wiki and Issues
- [x] Set URLs of external docs or ITS to link them instead of GitBucket's
- [ ] Issue # linking to the external ITS
- [ ] In forked repository, disable Issues and inherit Wiki configuration

**Comment by msigley** [comment]
I second this. We have an existing issue tracker and it would be nice to be able to link to it in the repo in GitBucket and disable the built in issue functionality.

It would also be nice to be able to integrate the issue # linking in commit and issue comments with our external issue tracker.

**Comment by takezoe** [comment]
In GitBucket 4.2, I would like to add options to turn-off Wiki and Issues. Also it's possible to set URLs of external docs or issue tracking system as below:

![2016-06-10 14 26 07](https://cloud.githubusercontent.com/assets/1094760/15954907/593aedc8-2f17-11e6-8c96-847b7b6ccc6d.png)

**Comment by takezoe** [comment]
@msigley 

> It would also be nice to be able to integrate the issue # linking in commit and issue comments with our external issue tracker.

Good suggestion. I would like to consider to make it.

**Comment by takezoe** [comment]
@msigley I found a problem of linking #issueId to tickets on the external ITS. Pull request is available even if Issues is disabled, so it's impossible to link all #issueId to the external ITS. I can't add this option in GitBucket 4.2.
