### ISSUE TITLE
Provide easy way to develop plug-in

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#822]

**Comment by menangen** [comment]
Intresting...there is a way to create Mercurial plugin for enabling this cvs? :) i very love hg and mercurial merging proces, hg user interface and simplity.

**Comment by menangen** [comment]
Intresting...there is a way to create Mercurial plugin for enabling this cvs? :) i very love hg and mercurial merging proces, hg user interface and simplity.

**Comment by takezoe** [comment]
Merged with #1484
