### ISSUE TITLE
close action does not reference commit

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#839]
would be great to see in the action text on an issue a reference to the commit that created/initiated the action.

For example when closing an issue from a commit message, we have today:
- "McFoggy closed the issue XX minutes ago"

instead we would see something like
- "McFoggy closed the issue XX minutes ago in [45e645646](http://nowhere.com)"

See what github provides as example : https://github.com/McFoggy/cssfx/issues/8

**Comment by kounoike** [comment]
In current version, when closing issue by commit message shows these two lines

![image](https://user-images.githubusercontent.com/6997928/41496176-5564cb78-7174-11e8-9838-10d1a643fd29.png)

@McFoggy @takezoe Can you close this issue?
