### ISSUE TITLE
Exception occurs when confirm to merge pull-request without additional comment.

### ISSUE THREAD

**Issue by Mura-Mi** [gitbucket/gitbucket#842]

**Comment by SIkebe** [comment]
@Mura-Mi @takezoe 
I cannot repro this anymore. If you merge without any comment, you`ll see a warning "Message is required.".
Can we close this?

**Comment by SIkebe** [comment]
Closing this issue for now as there's no further action we can take at this time. When/if you are able to get a repro, we can reopen (or feel free to file a new bug!).
