### ISSUE TITLE
Changes view will freeze the browser for many changes.

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#860]
If the re are many changes present in a commit, the changes view will freeze the browser and in FF is even crashing it.

IMHO it should be limited how many files are collapsed or expanded in the changes view, to avoid such scenarios.

Thank you.

**Comment by haarp** [comment]
This is due to Prettify javascript.

Here it tends to freeze the entire browser for half a minute or more for large files. It was so completely unusable that I had to use Adblock to block the script from running.

**Comment by takezoe** [comment]
This problem was fixed in GitBucket 3.8. It omits large diffs.

**Comment by haarp** [comment]
Can't confirm. Even on small diffs (in large files) it freezes the browser for a long time :(
