### ISSUE TITLE
allow to merge PR from UI "fast forward"

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#898]
Would be great to allow users to choose when accepting a PR if they want to merge with:
- `--no-ff` (which is the default behavior today of gitbucket & github)
- `--ff-only` fast forward only
- `--ff` making fast forward when possible and merge commit otherwise

as see git [merge documentation](http://git-scm.com/docs/git-merge#_options).

PS: We could even think of another possibility which is a rebase.

**Comment by McFoggy** [comment]
To illustrate the diferrent possibilities of the expected feature I have created the attached SVG (inside zip)
- _case 1_: current behavior, just a normal merge
- _case 2_: rebase scenario
- _case 3_: squash + merge, goal is to simplify history but keep a merge commit for information
- _case 4_: squash + rebase, force a pure linear history
- the `ff-only` scenario is not illustrated here
- not sure that last initial proposal is required (`--ff` fast forward if possible otherwise merge) because you are not sure of what will be the state of your graph history

![merge-scenarios](https://cloud.githubusercontent.com/assets/1119660/14134511/1a1c6f7e-f658-11e5-91a1-cfdd4ba60958.png)

[merge-scenarios.zip](https://github.com/gitbucket/gitbucket/files/194984/merge-scenarios.zip)

**Comment by lgathy** [comment]
This would be a very nice and important feature indeed. +1 from me. Any chance it gets implemented in the near future?

**Comment by btlogy** [comment]
My colleagues will like this feature too. They kind of hate to show how erratic they can be, especially on Fridays :-p +1

**Comment by McFoggy** [comment]
@takezoe this starts to become a _differenciator_ feature compared to other platforms.

We are now 2 years after the issue opening and nowadays all other major platforms (github, gitlab, bitbucket, ...) do offer such a possibility.

When people want to keep a clean history then such feature becomes a must.

The real difficulty behind this feature is: _how to handle squashing?_

There are several approaches:
- squash all without interaction: a bit useless as the commit message will be ugly
- squash all but let amend the commit message: the minimum to do in squashing scenarios
- squash + reorder + amend: too complex in my opinion, can be provided later. This can be done externally via git clients.

a step wise approach could be imagined also:
- one delivery without modifying too much the current UI & workflow 
  - providing 'normal merge', 'ff-only' & 'rebase'
- another version later on, in which PR acceptance UI & workflow are modified to allow handling the intermediate step of changing squash commits (just commit message or other features)
