### ISSUE TITLE
Support for controlling the version number of plug-ins.

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#931]
Please add support for controlling the version number of plug-ins.

The main reason for this is to correctly match the version GitBucket has, with the version of the plug-ins themselves.

This should work automatically and not force the users (many of them are not even programmers) to figure it out.

See: gitbucket-plugins/gitbucket-h2-backup-plugin#7

**Comment by kounoike** [comment]
[sbt-gitbucket-plugin](https://github.com/gitbucket/sbt-gitbucket-plugin)-1.3.0 supports embedding GitBucket version number to jar file.
