### ISSUE TITLE
Move repository to organization

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#948]
- [x] gitbucket-gist-plugin repository
- [x] gitbucket-news repository
- [x] gitbucket repository
- [x] Travis configuration
- [x] gitter room
- [x] gitter Japanese room
- [x] URL in documents

**Comment by lefou** [comment]
:+1:

**Comment by aadrian** [comment]
+1

**Comment by FlYnN91** [comment]
+1
