### ISSUE TITLE
Only root user has access to anything

### ISSUE THREAD

**Issue by arcelivez** [gitbucket/gitbucket#959]
Hello,

I've setup gitbucket on my mini server and it looks all really nice, indeed you even have a quite good user management.

But there's one major problem: only the root user has access. Other users don't have access to their groups, web interface, or can not clone anything from their own repositories. That's a little disappointing, I can use this in my case I guess from root user too, but I find this just so wrong, and indeed, it does limit the flexibility if I wanna incorporate more contributors than really just myself.

**Comment by takezoe** [comment]
It's an intended behavior in the current version of GitBucket. You can find existing issues about this topic such as #282 or #347. If you have any opinion, please add comment to these issues.
