### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by nazoking** [gitbucket/gitbucket#962]
Feature request.

https://github.com/blog/2051-protected-branches-and-required-status-checks
https://help.github.com/articles/configuring-protected-branches/
https://help.github.com/articles/enabling-required-status-checks/

 * create `Branches` as repo/settings/branches
   * move default-branch setting to here
   * create `Protected branches` section
     * branch selector.
       * create `Branch protection` as repo/settings/branches/:branchName
       * option `Protect this branch`
       * option `Require status checks to pass before merging`
       * option `Include administrators`
         * administrators is owner of user repository or manager of group repository ( really ? ..)
       * option `Status checks` (multi select, from found in the last week for this repository)
     * `Edit` button on each protected branches.
 * Protected mark(octicon-shield) on Branches page
 * check on pre-receive
   * error if branche is procected branch and
     * force push
     * delete
    * push if new commit-id has not `commit-status` ok on `Status-checkes`.
 * deisable file edit on web.
   * only can create new branch...(gitbucket has not this feature)
 * on pull-request page
   * show commit-status if context is require status checks to pass.
   * deisable merge if new commit-id has not `commit-status` ok on `Status-checkes`.
 * Add API https://developer.github.com/v3/repos/#enabling-and-disabling-branch-protection

**Comment by devalru** [comment]
See "Branch access controll #477" too.
We need protected branches too but a technical user (administrator role) should have the right to push to the branch.

**Comment by takezoe** [comment]
Already merged in 3.11
