### ISSUE TITLE
Update to the latest h2database

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#964]
Please update to the latest h2database version (1.4.190 for now).

The actual used 1.4.180 is more than 1,5 years old.

**Comment by takezoe** [comment]
Previously, upgrading H2 caused backward compatibility problem for some users. So we can't upgrade H2 simply. We have to do it carefully.

**Comment by aadrian** [comment]
> Previously, upgrading H2 caused backward compatibility problem for some users

I remember, but that wasn't version 190. 

Besides, the main problem is the URL: AFAIK the engine can be newer, but the URL needs to have the correct parameters: right now it does not have backward compatible parameters, so using a newer DB will force an upgrade to a newer engine that might fail.

> So we can't upgrade H2 simply. We have to do it carefully.

Of course. What set of tests can we execute to check such a thing?

IMHO it's a pity that GitBucket does not use your other project: MirageSQL in order to have all the statements easily testable and in external SQL files.

**Comment by conradlink** [comment]
+1

I've run into an issue similar to #756 and was unable to run the H2 recovery tool using 1.4.180. I upgraded to 1.4.190 and was able to recover.

**Comment by nazoking** [comment]
https://github.com/gitbucket/gitbucket/commit/dfe3fbc02f25e93bb7849b98e76e81c9e92f785e Bump up H2 to 1.4.190
