### ISSUE TITLE
How to update to newer versions?

### ISSUE THREAD

**Issue by pwFoo** [gitbucket/gitbucket#972]
How update a running gitbucket installation without data loss?
Is all relevant data saved in GITBUCKET_HOME directory?

Just replace the gitbucket.war file? Anything else to consider?

**Comment by takezoe** [comment]
See [Guideline for Issues](https://github.com/gitbucket/gitbucket/blob/master/CONTRIBUTING.md) at first. Here is not support system.
If you have any question about GitBucket, use [gitter](https://gitter.im/gitbucket/gitbucket) instead.

**Comment by McFoggy** [comment]
Have a look at the wiki there's a page on the [backup](https://github.com/gitbucket/gitbucket/wiki/Backup). If you want to do live backups, you will also need the H2 datase plugin, find it at http://gitbucket-plugins.github.io
