### ISSUE TITLE
Subscriber side: additional text required beside "Change password"

### ISSUE THREAD

**Issue by CharlesPooter** [gitbucket/gitbucket#978]
Just in case people think that "change password" relates to the masterkey, could we include a sentence after or under "Change Password" so that it reads: 

(This is NOT your Masterkey: it is the password you use to log in to the site. Your Masterkey cannot be changed once it is set")

**Comment by CharlesPooter** [comment]
Sorry - change that. I've realised that this page might appear on both Exec and Subscriber sides, so it should read:

This is NOT the Masterkey: it is the password you use when you initially log in to the site. The Masterkey (which you use to access the Digital Safe) cannot be changed once it is set.

**Comment by takezoe** [comment]
@CharlesPooter Is this request to GitBucket?
