### ISSUE TITLE
Subscriber side: change text on "contact us" page

### ISSUE THREAD

**Issue by CharlesPooter** [gitbucket/gitbucket#979]
This is the page which wouldn't change when I amended the text. Could you replace the introductory text with the following:

Please use the form below to get in touch with us if you have any queries or comments. You can also e-mail us at support@safeinoneplace. Either way, we will get back to you within 24 hours. Alternatively, if you would prefer to speak with someone directly, fill in the form and leave a number and one of the team will call you within one working day.

**Comment by takezoe** [comment]
@CharlesPooter Is this request to GitBucket?
