### ISSUE TITLE
Exec side: additional text beside "Change password" on "My details" page

### ISSUE THREAD

**Issue by CharlesPooter** [gitbucket/gitbucket#980]
As per the Subscriber side, just in case people think that "change password" relates to the Masterkey, could we include a sentence after or under "Change Password" so that it reads:

This is NOT the Masterkey: it is the password you use when you initially log in to the site. The Masterkey (which you use to access the Digital Safe) cannot be changed once it is set.

**Comment by takezoe** [comment]
@CharlesPooter Is this request to GitBucket?

**Comment by CharlesPooter** [comment]
No - it isn't. My mistake (I'm a bit of a novice). Same goes for the other three you alerted me to. Thanks very much for alerting me to it. All the best.
