### ISSUE TITLE
Exec side: change background colour of "Letters" tile

### ISSUE THREAD

**Issue by CharlesPooter** [gitbucket/gitbucket#981]
I'd had feedback on the need to shift this top left (thanks for having done so). For me, it would also help if it had a slightly coloured background so that it would stand out once I returned to the Digital Safe page - otherwise I wouldn't be entirely sure where it was (since it looks like a page of tiles, which is what I saw before). Would it be possible to give this some pinkish/reddish/you decide because you're the designer tone so that it stands out?

**Comment by takezoe** [comment]
@CharlesPooter Is this request to GitBucket?
