### ISSUE TITLE
Typo error in System Settings

### ISSUE THREAD

**Issue by jimtremblay** [gitbucket/gitbucket#986]
With version 3.8, I see a typo in System Settings -> Communication:

![image](https://cloud.githubusercontent.com/assets/7810954/11099341/c2bbbee4-8878-11e5-9bbd-9fa151a930da.png)

Thanks
Jim

**Comment by bfritz** [comment]
Looks like this was fixed in 2b2a1179.

**Comment by jimtremblay** [comment]
Ok, good. Then, it will certainly be fixed in next version.
