### ISSUE TITLE
Unable to completely delete group

### ISSUE THREAD

**Issue by jimtremblay** [gitbucket/gitbucket#988]
As admin, if I click on group name from Group Management, I see a Edit Group button and have access to deleting group. If I delete the group, all the users are removed from the group, but the group is still visible from Group Management and I can't completely delete the group, only disable it.

I'm using GitBucket 3.8

Thanks
Jim

**Comment by takezoe** [comment]
@jimtremblay Users and groups can't be deleted completely if once created. It's an intended specification.

**Comment by jimtremblay** [comment]
Then why a delete button is needed if I can't delete user? Only a disable button should be available if it is what you want.

I think the admin of the site should have complete control over the settings., including completely deleting users and groups.

Why this intended behavior?

Jim

**Comment by takezoe** [comment]
@jimtremblay Some tables (e.g. `ISSUES`) has foreign key to `ACCOUNT` table. So the record in `ACCOUNT` can't be deleted physically. Yes, it might be design problem. But it can't fix easily.

**Comment by jimtremblay** [comment]
@takezoe Ok, thank you for the clarification. It is clearer.

Jim

**Comment by bviktor** [comment]
Then please, at least make it possible to undelete a group!

**Comment by skironDotNet** [comment]
"Some tables (e.g. ISSUES) have foreign key to ACCOUNT table. So records in ACCOUNT can't be deleted physically. Yes, it might be a design problem. But it can't be fixed easily"
Thats why is better not use DB constraints FK-PK, rather keep relations in the business layer. I would like to be able to delete the user, especially then all repos has been deleted. If a group has no users, and user has no repos, why both can't be deleted? where they refer to? History? then delete the history or if to leave the history, set the user id and group id to 0, and let the history look like "A deleted user added a comment to deleted repo". The repo deleted has been created in deleted group. Hmm are we going back to deleting the history :)
