### ISSUE TITLE
Wrong link in email

### ISSUE THREAD

**Issue by jimtremblay** [gitbucket/gitbucket#996]
The link "View it on GitBucket" point to the internal address instead of my exposed external address. Example: I have setup GitBucket on port 8080, prefix /git and a SSL reverse proxy with Apache from subdir /git to http://localhost:8080/git. When an issue is open, the link point to http://localhost:8080/git/<user>/<repo>/issues/<number> instead of https://<external address>/git/<user>/<repo>/issues/<number>.

Is there a workaround?

Thanks
Jim

Edit: It affects clone URL too and even if I start gitbucket with option --https=true, I have a HTTP clone URL instead of HTTPS. I'm using GitBucket 3.8

**Comment by jimtremblay** [comment]
It affects clone URL too and even if I start gitbucket with option --https=true, I have a HTTP clone URL instead of HTTPS.

Jim

**Comment by McFoggy** [comment]
Did you setup correctly the base URL in the settings page?

**Comment by jimtremblay** [comment]
:-) My fault, I have completely forget to setup the base URL.

Thanks for your help
Jim
